// world_leftover.cpp -- M3 UI stage, step U0: every rewrite in hook/krn_leftover.cpp (generated by
// tools/gen_leftovers.py) and hook/krn_leftover_hand.cpp against its original, outside the game.
//
//   build (x86 tools, from the repo root):
//     cl /nologo /O2 /arch:IA32 /fp:precise /MT /W3 /EHsc /std:c++17 /FC test\world_leftover.cpp
//        /Fo<dir>\ /Fe<dir>\world_leftover.exe /link /BASE:0x10000000 /DYNAMICBASE:NO /FIXED /MACHINE:X86
//   run:   world_leftover.exe [rounds] [seed]        (VP_TRACE=1: one line per function)
//
// Loads out\race_v10.exe at 0x400000 the way test/fuzz.cpp does and includes both rewrite files, with PORT_FN
// redefined to list each function: its v1.0 address, the rewrite, its calling convention, stack arguments and return
// width (from the rewrite's own type), and its footprint. Then, for EVERY listed function, `rounds` times (default 8):
// the exe's writable sections (.data with its .bss, and .idata) and a 64 KB arena are set up -- half the rounds as the
// image was loaded (the .bss zero, as at start-up), half POISONED (every byte of .data/.bss random, so a store that
// writes what was already there, or a store left out, still shows) -- and random arguments are chosen (ecx a pointer
// into the arena, edx and the stack arguments random words). Snapshot; the original runs, from a raw call thunk that
// sets ecx / edx / the stack exactly and records eax / edx, the bytes the callee popped, and ebx / esi / edi / ebp
// (preset to sentinels); the results are kept, the snapshot restored, and the rewrite runs the same way. Compared:
// every byte of .data/.bss/.idata and the arena, the return value (at the rewrite's return width), the bytes popped,
// the callee-saved registers, a fault in either, and the stubs' call logs. A pure footprint must leave everything as
// it was (checked on the original's pass).
//
// The x87 runs at 24 or 53 bits (alternating rounds). Real game code runs wherever a rewrite calls it: the $E's
// constructors (Xlator, RandomAIDriver, the AI driver tables and buckets, SkillInfo2, TVCamera, P3DBase, World) and
// paired $E, Damper::Setup and GetDampingRate. Stubbed (a jump to a logger): operator delete, LogPanic, GrafDraw,
// gxSetCanvas, GraphDrawAxes, GraphDrawLinePlot, gxText, sprintf (its format and raw argument dwords are logged; the
// text is made with this program's own vsprintf, for gxText's log), and the destructors the deleting destructors call
// (each logs its address and `this`), and the game's CRT fatal paths.
//
// Poisoned rounds keep sane what the functions read as an index or a string: RandomAIDriver's registration counts
// (the eight AIDriverTable counts at 0x51d918 + 0x44 k, an index into their 16 slots: 0..15), the default driver name
// SkillInfo2 copies (0x4ebf38) and QuarterCarControl::Draw's sprintf formats (0x4ede9c..0x4edf10), left as loaded, and
// __adjust_fdiv (0x5024b8) 0, as the CRT leaves it on any CPU without the Pentium FDIV bug.
//
// Extra rounds (x250) for the functions whose arguments matter: dsounderr2str (every case value, its neighbours,
// random codes), QuarterCarControl::Draw (random rigs: settings, masses and rates, sometimes NaN / infinite / zero /
// negative), the deleting destructors (random flags).
//
// Built with /DVP_LEFTOVER_FIXES, the rewrites have their fix on (docs/PORTING.md, "Fixes"): every function is still
// compared as above (the rigs' values print in under 80 bytes, where the fix changes nothing), and a directed test
// first runs QuarterCarControl::Draw, the rewrite alone, on rigs whose lines overran the original's 80 bytes (see
// directed_fix_tests). Without it (VP_FAITHFUL) the rewrites must match the originals bit for bit.
#define _CRT_SECURE_NO_WARNINGS
#include <windows.h>
#include <float.h>
#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <tuple>
#include <type_traits>
#include <utility>
#if defined(__GNUC__) && !defined(__clang__)
#include "vp_seh.h"                           // vp_try: the GCC stand-in for __try / __except
#endif

#ifndef VP_LEFTOVER_FIXES
#define VP_FAITHFUL                 // the rewrites exactly as the originals (docs/PORTING.md, "Fixes")
#endif
#include "../hook/port.h"

// ---- the registry: PORT_FN lists each function -------------------------------------------------------------------
struct LoEntry {
    uint32_t v10;
    const char* name;
    void* fn;
    int fast;                                   // __fastcall (a __thiscall rewrite): the first two words are ecx, edx
    int nstack;                                 // stack argument dwords
    int ret;                                    // return width in bytes (0: void)
    void (*fp)(Footprint&, const uint32_t*);    // the footprint, from the argument words (ecx, edx first if fast)
};
static LoEntry g_fns[4096];
static int g_nfns;
struct LoReg { LoReg(const LoEntry& e) { if (g_nfns < 4096) g_fns[g_nfns++] = e; } };
template <typename T> static T from_word(uint32_t w) { T t; memcpy(&t, &w, sizeof(T)); return t; }
template <typename R> static constexpr int ret_width() { if constexpr (std::is_void_v<R>) return 0; else return (int)sizeof(R); }
template <typename F> struct Sig;
template <typename R, typename... A> struct Sig<R(__cdecl*)(A...)> {
    enum { fast = 0, nstack = sizeof...(A) };
    static constexpr int ret = ret_width<R>();
    template <void (*FP)(Footprint&, A...), size_t... I> static void fpi(Footprint& f, const uint32_t* w, std::index_sequence<I...>) {
        FP(f, from_word<A>(w[I])...);
        (void)w;
    }
    template <void (*FP)(Footprint&, A...)> static void fp(Footprint& f, const uint32_t* w) { fpi<FP>(f, w, std::index_sequence_for<A...>()); }
};
template <typename R, typename... A> struct Sig<R(__fastcall*)(A...)> {
    static_assert(sizeof...(A) >= 2, "a __thiscall rewrite takes (self, edx, ...)");
    enum { fast = 1, nstack = sizeof...(A) - 2 };
    static constexpr int ret = ret_width<R>();
    template <void (*FP)(Footprint&, A...), size_t... I> static void fpi(Footprint& f, const uint32_t* w, std::index_sequence<I...>) {
        FP(f, from_word<A>(w[I])...);
    }
    template <void (*FP)(Footprint&, A...)> static void fp(Footprint& f, const uint32_t* w) { fpi<FP>(f, w, std::index_sequence_for<A...>()); }
};
#undef PORT_FN_BUILDS
#define PORT_FN_BUILDS(V10, NAME, NEW, FP, PRO, PROLEN)                                                              \
    static LoReg VP_CAT(reg_, NEW)({V10, NAME, (void*)&NEW, Sig<decltype(&NEW)>::fast, Sig<decltype(&NEW)>::nstack, \
                                    Sig<decltype(&NEW)>::ret, &Sig<decltype(&NEW)>::fp<&FP>});

void Footprint::add(void* p, uint32_t bytes, const char* what) { if (n < MAX) r[n++] = {p, bytes, what}; }
void Footprint::object(void* obj, const char* what) { printf("footprint: object() not expected (%s)\n", what); add(obj, 4, what); }
void Footprint::stack_ptr(void* p, const char* what) { add(p, 4, what); }

#include "../hook/krn_leftover.cpp"
#include "../hook/krn_leftover_hand.cpp"

// ---- random numbers --------------------------------------------------------------------------------------------------
static uint32_t g_rng = 0x2545f491u;
static uint32_t rnd() { g_rng ^= g_rng << 13; g_rng ^= g_rng >> 17; g_rng ^= g_rng << 5; return g_rng; }
static float bitsf(uint32_t u) { float f; memcpy(&f, &u, 4); return f; }
static float uni() { return (float)(rnd() & 0xffffff) / 16777216.0f; }
static float range(float a, float b) { return a + (b - a) * uni(); }
static bool chance(int pct) { return (int)(rnd() % 100) < pct; }
// NaN, infinities, zero, negative, denormal -- but nothing huge: the original QuarterCarControl::Draw prints its values
// into an 80-byte buffer, and a 30-digit number overflows it, which would take the harness's own stack with it (the
// rewrite's fix is tested on its own: directed_fix_tests)
static float wildf() {
    switch (rnd() % 7) {
    case 0: return bitsf(0x7fc00000u);
    case 1: return (rnd() & 1) ? INFINITY : -INFINITY;
    case 2: return 0.0f;
    case 3: return -range(0.0f, 1000.0f);
    case 4: return bitsf(rnd() & 0x807fffff);          // a denormal
    default: return range(-1e4f, 1e4f);
    }
}
static void setf(void* p, float f) { memcpy(p, &f, 4); }

// ---- the original, loaded at 0x400000 ----------------------------------------------------------------------------------
static bool load_race_exe(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) { printf("can't open %s\n", path); return false; }
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t* file = (uint8_t*)malloc(n);
    fread(file, 1, n, f);
    fclose(f);
    IMAGE_NT_HEADERS* nt = (IMAGE_NT_HEADERS*)(file + ((IMAGE_DOS_HEADER*)file)->e_lfanew);
    if (nt->FileHeader.TimeDateStamp != 0x362de68c) { printf("%s isn't the v1.0 race.exe\n", path); return false; }
    uint8_t* base = (uint8_t*)VirtualAlloc((void*)0x400000, nt->OptionalHeader.SizeOfImage, MEM_COMMIT, PAGE_EXECUTE_READWRITE);
    if (base != (uint8_t*)0x400000) { printf("0x400000 isn't reserved for race.exe in this process\n"); return false; }
    memcpy(base, file, nt->OptionalHeader.SizeOfHeaders);
    IMAGE_SECTION_HEADER* sec = IMAGE_FIRST_SECTION(nt);
    for (int i = 0; i < nt->FileHeader.NumberOfSections; i++)
        memcpy(base + sec[i].VirtualAddress, file + sec[i].PointerToRawData,
               sec[i].SizeOfRawData < sec[i].Misc.VirtualSize || !sec[i].Misc.VirtualSize ? sec[i].SizeOfRawData
                                                                                         : sec[i].Misc.VirtualSize);
    free(file);
    return true;
}
static int relaunch() {
    SetEnvironmentVariableA("VP_WORLD_CHILD", "1");
    STARTUPINFOA si = {sizeof si};
    si.dwFlags = STARTF_USESTDHANDLES;                  // (the child writes where this process does: a pipe too)
    si.hStdInput = GetStdHandle(STD_INPUT_HANDLE);
    si.hStdOutput = GetStdHandle(STD_OUTPUT_HANDLE);
    si.hStdError = GetStdHandle(STD_ERROR_HANDLE);
    PROCESS_INFORMATION pi;
    if (!CreateProcessA(0, GetCommandLineA(), 0, 0, TRUE, CREATE_SUSPENDED, 0, 0, &si, &pi)) { printf("can't start the test process\n"); return 2; }
    if (!VirtualAllocEx(pi.hProcess, (void*)0x400000, 0x300000, MEM_RESERVE, PAGE_EXECUTE_READWRITE))
        printf("couldn't reserve 0x400000 in the test process (%lu)\n", GetLastError());
    ResumeThread(pi.hThread);
    WaitForSingleObject(pi.hProcess, INFINITE);
    DWORD code = 2;
    GetExitCodeProcess(pi.hProcess, &code);
    return (int)code;
}
static void patch_jmp(uint32_t at, void* to) {
    uint8_t* p = (uint8_t*)at;
    p[0] = 0xe9;
    int32_t rel = (int32_t)((uintptr_t)to - (at + 5));
    memcpy(p + 1, &rel, 4);
}

// ---- memory: the writable sections and the arena -------------------------------------------------------------------------
static uint8_t* const DATA = (uint8_t*)0x004e1000;      // .data and its .bss
enum { DATA_BYTES = 0xf5f2c };
static uint8_t* const IDATA = (uint8_t*)0x005d7000;     // .idata (writable)
enum { IDATA_BYTES = 0x136a };
enum { ARENA_BYTES = 0x10000 };
static uint8_t* g_arena;
struct Mem { uint8_t* data; uint8_t* idata; uint8_t* arena; };
static Mem g_pristine, g_snap, g_after;
static Mem mem_alloc() { return {(uint8_t*)malloc(DATA_BYTES), (uint8_t*)malloc(IDATA_BYTES), (uint8_t*)malloc(ARENA_BYTES)}; }
static void mem_save(Mem& m) { memcpy(m.data, DATA, DATA_BYTES); memcpy(m.idata, IDATA, IDATA_BYTES); memcpy(m.arena, g_arena, ARENA_BYTES); }
static void mem_load(const Mem& m) { memcpy(DATA, m.data, DATA_BYTES); memcpy(IDATA, m.idata, IDATA_BYTES); memcpy(g_arena, m.arena, ARENA_BYTES); }
// the first differing byte between m and the live memory, as an address (0: none)
static uint32_t mem_diff(const Mem& m) {
    if (memcmp(m.data, DATA, DATA_BYTES))
        for (uint32_t i = 0; i < DATA_BYTES; i++) if (m.data[i] != DATA[i]) return 0x004e1000 + i;
    if (memcmp(m.idata, IDATA, IDATA_BYTES))
        for (uint32_t i = 0; i < IDATA_BYTES; i++) if (m.idata[i] != IDATA[i]) return 0x005d7000 + i;
    if (memcmp(m.arena, g_arena, ARENA_BYTES))
        for (uint32_t i = 0; i < ARENA_BYTES; i++) if (m.arena[i] != g_arena[i]) return (uint32_t)(uintptr_t)(g_arena + i);
    return 0;
}

// ---- the stubs' call log -----------------------------------------------------------------------------------------------
enum { LOG_MAX = 4096 };
struct CallLog { uint32_t n; uint32_t w[LOG_MAX]; };
static CallLog g_log, g_log_orig;
static void log_word(uint32_t w) { if (g_log.n < LOG_MAX) g_log.w[g_log.n] = w; g_log.n++; }
static void log_str(const char* s) {                   // the whole string (the stubs' strings are the harness's own)
    uint32_t w = 0, i = 0;
    for (; s[i]; i++) { w = w << 8 | (uint8_t)s[i]; if ((i & 3) == 3) { log_word(w); w = 0; } }
    log_word(w); log_word(i);
}
static void __cdecl stub_delete(void* p) { log_word('DEL '); log_word((uint32_t)(uintptr_t)p); }
static void __cdecl stub_panic(const char* fmt, ...) { log_word('PANC'); log_word((uint32_t)(uintptr_t)fmt); }
static void __cdecl stub_graf_draw(int g) { log_word('GRAF'); log_word((uint32_t)g); }
static void* __cdecl stub_set_canvas(void* c) { log_word('SCNV'); log_word((uint32_t)(uintptr_t)c); return (void*)0x0badca55; }
static void __cdecl stub_axes(const uint32_t* g, int a, int b, uint32_t color) {
    log_word('AXES');
    for (int i = 0; i < 9; i++) log_word(g[i]);
    log_word((uint32_t)a); log_word((uint32_t)b); log_word(color);
}
static float g_plot_grip, g_plot_at;             // with g_plot_poke: what the plot "finds" (graph_fn's best grip / where)
static bool g_plot_poke;
static void __cdecl stub_line_plot(const uint32_t* g, uint32_t fn, void* data, uint32_t color) {
    if (g_plot_poke) { setf((uint8_t*)data + 0x406c, g_plot_grip); setf((uint8_t*)data + 0x4070, g_plot_at); }
    log_word('PLOT');
    for (int i = 0; i < 9; i++) log_word(g[i]);
    log_word(fn); log_word((uint32_t)(uintptr_t)data); log_word(color);
}
static uint32_t g_text_longest;                  // the longest line gxText was given since it was last zeroed
static void __cdecl stub_text(int x, int y, const char* s, uint32_t color) {
    if (strlen(s) > g_text_longest) g_text_longest = (uint32_t)strlen(s);
    log_word('TEXT'); log_word((uint32_t)x); log_word((uint32_t)y); log_word(color); log_str(s);
}
static uint32_t g_sprf_longest;                  // the longest text sprintf made since it was last zeroed
static int __cdecl stub_sprintf(char* buf, const char* fmt, ...) {
    int nconv = 0;                                   // the Draw formats: %f conversions only, a double each
    for (const char* p = fmt; *p; p++)
        if (*p == '%') { if (p[1] == '%') p++; else nconv++; }
    va_list ap;
    va_start(ap, fmt);
    const uint32_t* w = (const uint32_t*)ap;
    log_word('SPRF'); log_word((uint32_t)(uintptr_t)fmt);
    for (int i = 0; i < 2 * nconv; i++) log_word(w[i]);
    int r = vsprintf(buf, fmt, ap);
    va_end(ap);
    if (r > (int)g_sprf_longest) g_sprf_longest = (uint32_t)r;
    return r;
}
template <uint32_t A> static void __fastcall stub_dtor(void* self, int) { log_word('DTOR'); log_word(A); log_word((uint32_t)(uintptr_t)self); }
static void __cdecl stub_crt_fatal(int code) { printf("the game's CRT reached a fatal path (%d): ending the test\n", code); fflush(stdout); ExitProcess(3); }
static int __cdecl stub_crt_msgbox(const char* text, const char* caption, unsigned) {
    printf("the game's CRT would show a message box: %s / %s\n", caption ? caption : "", text ? text : "");
    fflush(stdout);
    ExitProcess(3);
}

// ---- the raw call ---------------------------------------------------------------------------------------------------------
static uint32_t g_c_fn, g_c_ecx, g_c_edx, g_c_n, g_c_args[16];
static uint32_t g_r_eax, g_r_edx, g_r_ebx, g_r_esi, g_r_edi, g_r_ebp, g_r_esp, g_c_top, g_save_esp;
#if defined(__GNUC__) && !defined(__clang__)
__attribute__((naked)) static void raw_call() {
    __asm__ volatile(
        "push ebx\n\t"
        "push esi\n\t"
        "push edi\n\t"
        "push ebp\n\t"
        "mov dword ptr [%P[save_esp]], esp\n\t"
        "mov ecx, dword ptr [%P[c_n]]\n"
        "1:\n\t"
        "test ecx, ecx\n\t"
        "jz 2f\n\t"
        "dec ecx\n\t"
        "push dword ptr [%P[c_args] + ecx * 4]\n\t"
        "jmp 1b\n"
        "2:\n\t"
        "mov dword ptr [%P[c_top]], esp\n\t"
        "mov ebx, 0x0b0b0b0b\n\t"
        "mov esi, 0x05050505\n\t"
        "mov edi, 0x0d0d0d0d\n\t"
        "mov ebp, 0x0e0e0e0e\n\t"
        "mov ecx, dword ptr [%P[c_ecx]]\n\t"
        "mov edx, dword ptr [%P[c_edx]]\n\t"
        "call dword ptr [%P[c_fn]]\n\t"
        "mov dword ptr [%P[r_eax]], eax\n\t"
        "mov dword ptr [%P[r_edx]], edx\n\t"
        "mov dword ptr [%P[r_ebx]], ebx\n\t"
        "mov dword ptr [%P[r_esi]], esi\n\t"
        "mov dword ptr [%P[r_edi]], edi\n\t"
        "mov dword ptr [%P[r_ebp]], ebp\n\t"
        "mov dword ptr [%P[r_esp]], esp\n\t"
        "mov esp, dword ptr [%P[save_esp]]\n\t"
        "pop ebp\n\t"
        "pop edi\n\t"
        "pop esi\n\t"
        "pop ebx\n\t"
        "ret"
        :: [save_esp] "i"(&g_save_esp), [c_n] "i"(&g_c_n), [c_args] "i"(g_c_args), [c_top] "i"(&g_c_top), [c_ecx] "i"(&g_c_ecx),
           [c_edx] "i"(&g_c_edx), [c_fn] "i"(&g_c_fn), [r_eax] "i"(&g_r_eax), [r_edx] "i"(&g_r_edx), [r_ebx] "i"(&g_r_ebx),
           [r_esi] "i"(&g_r_esi), [r_edi] "i"(&g_r_edi), [r_ebp] "i"(&g_r_ebp), [r_esp] "i"(&g_r_esp));
}
#else
__declspec(naked) static void raw_call() {
    __asm {
        push ebx
        push esi
        push edi
        push ebp
        mov g_save_esp, esp
        mov ecx, g_c_n
    pushloop:
        test ecx, ecx
        jz pushed
        dec ecx
        push dword ptr g_c_args[ecx * 4]
        jmp pushloop
    pushed:
        mov g_c_top, esp
        mov ebx, 0x0b0b0b0b
        mov esi, 0x05050505
        mov edi, 0x0d0d0d0d
        mov ebp, 0x0e0e0e0e
        mov ecx, g_c_ecx
        mov edx, g_c_edx
        call dword ptr g_c_fn
        mov g_r_eax, eax
        mov g_r_edx, edx
        mov g_r_ebx, ebx
        mov g_r_esi, esi
        mov g_r_edi, edi
        mov g_r_ebp, ebp
        mov g_r_esp, esp
        mov esp, g_save_esp
        pop ebp
        pop edi
        pop esi
        pop ebx
        ret
    }
}
#endif
struct Result { int fault; uint32_t code, eip, ret, pops, regs[4]; };
static uint32_t g_fault_code, g_fault_eip;
static int fault_filter(EXCEPTION_POINTERS* e) {
    g_fault_eip = (uint32_t)e->ContextRecord->Eip;
    g_fault_code = e->ExceptionRecord->ExceptionCode;
    return EXCEPTION_EXECUTE_HANDLER;
}
static unsigned g_pc;
static Result run(const LoEntry& f, bool rewrite, const uint32_t* words) {
    Result r = {};
    g_log.n = 0;
    g_c_fn = rewrite ? (uint32_t)(uintptr_t)f.fn : f.v10;
    const uint32_t* stack = words;
    if (f.fast) { g_c_ecx = words[0]; g_c_edx = words[1]; stack = words + 2; }
    else { g_c_ecx = 0x00c0ffee; g_c_edx = 0x00d00d1e; }
    g_c_n = (uint32_t)f.nstack;
    for (int i = 0; i < f.nstack; i++) g_c_args[i] = stack[i];
    unsigned cw;
#if defined(__GNUC__) && !defined(__clang__)
    __asm__ volatile("fninit" ::: VP_X87_CLOBBERS);
    _controlfp_s(&cw, _MCW_EM, _MCW_EM);
    _controlfp_s(&cw, g_pc, _MCW_PC);
    if (vp_try([&] { raw_call(); }, fault_filter)) { r.fault = 1; r.code = g_fault_code; r.eip = g_fault_eip; }
    __asm__ volatile("fninit" ::: VP_X87_CLOBBERS);
#else
    __asm fninit
    _controlfp_s(&cw, _MCW_EM, _MCW_EM);
    _controlfp_s(&cw, g_pc, _MCW_PC);
    __try {
        raw_call();
    } __except (fault_filter(GetExceptionInformation())) { r.fault = 1; r.code = g_fault_code; r.eip = g_fault_eip; }
    __asm fninit
#endif
    _controlfp_s(&cw, _MCW_EM, _MCW_EM);
    _controlfp_s(&cw, _PC_53, _MCW_PC);
    if (!r.fault) {
        const uint32_t mask = f.ret == 0 ? 0 : f.ret == 1 ? 0xffu : f.ret == 2 ? 0xffffu : 0xffffffffu;
        r.ret = g_r_eax & mask;
        r.pops = g_r_esp - g_c_top;
        r.regs[0] = g_r_ebx; r.regs[1] = g_r_esi; r.regs[2] = g_r_edi; r.regs[3] = g_r_ebp;
    }
    return r;
}

// ---- per-function set-up ----------------------------------------------------------------------------------------------
// what the deleting destructors call (stubbed: see the top)
static void patch_dtors() {
#define D(a) patch_jmp(a, (void*)&stub_dtor<a>);
    D(0x004211a0) D(0x00421e90) D(0x00422390) D(0x00422490) D(0x00425fa0) D(0x0042dfc0) D(0x0042eea0) D(0x004331d0)
    D(0x00436920) D(0x0043e960) D(0x0043f570) D(0x00442e30) D(0x00444540) D(0x0041bac0) D(0x00469850)
#undef D
}
static const uint32_t k_dserr[] = {0x80004001u, 0x80004005u, 0x80040110u, 0x8007000eu, 0x80070057u, 0x8878000au, 0x8878001eu,
                                   0x88780032u, 0x88780046u, 0x88780064u, 0x88780078u, 0x88780082u, 0x88780096u, 0x887800a0u,
                                   0x887800aau, 0u, 0x88780000u, 0x887800abu, 0x88780014u, 0x7fffffffu, 0x80000000u};
enum { F_DSERR = 0x004756b0, F_QCC_DRAW = 0x00447620 };
static bool is_deleting_dtor(const LoEntry& f) { return strstr(f.name, "deleting destructor") != 0; }
static bool heavy(const LoEntry& f) { return f.v10 == F_DSERR || f.v10 == F_QCC_DRAW || is_deleting_dtor(f); }

static void poison() {
    uint32_t* d = (uint32_t*)DATA;
    for (uint32_t i = 0; i < DATA_BYTES / 4; i++) d[i] = rnd();
    for (int k = 0; k < 8; k++) *(uint32_t*)(0x0051d918 + 0x44 * k) = rnd() % 16;   // RandomAIDriver's counts
    *(uint32_t*)0x005024b8 = 0;       // __adjust_fdiv: no FDIV-bug Pentium (docs/PORTING.md 5: a plain division)
    // strings the functions read: SkillInfo2's default name, QuarterCarControl::Draw's four formats
    static const uint32_t keep[][2] = {{0x004ebf38, 0x004ebf60}, {0x004ede9c, 0x004edf10}};
    for (auto& k : keep) memcpy(DATA + (k[0] - 0x004e1000), g_pristine.data + (k[0] - 0x004e1000), k[1] - k[0]);
}
static void random_arena() {
    uint32_t* a = (uint32_t*)g_arena;
    for (uint32_t i = 0; i < ARENA_BYTES / 4; i++) a[i] = rnd();
}
// a QuarterCarControl at the arena's object, with its damper
static void random_rig(uint8_t* q) {
    auto f = [&](uint32_t off, float lo, float hi) { setf(q + off, chance(8) ? wildf() : range(lo, hi)); };
    *(int32_t*)(q + 4) = (int32_t)(rnd() % 600); *(int32_t*)(q + 8) = (int32_t)(rnd() % 400);
    *(int32_t*)(q + 0xc) = (int32_t)(rnd() % 400); *(int32_t*)(q + 0x10) = (int32_t)(rnd() % 300);
    f(0x18, 100, 800); f(0x1c, 10, 100); f(0x24, 1e5f, 5e5f);
    f(0x4060, 50, 800); f(0x4064, 1, 50); f(0x4068, 1, 50);
    f(0x406c, 0, 1); f(0x4070, 0, 200); f(0x4074, 0, 2);
    uint8_t* damper = g_arena + 0xc000;
    for (int i = 0; i < 4; i++) setf(damper + 4 * i, chance(8) ? wildf() : range(-5000, 5000));
    *(uint8_t**)(q + 0x28) = chance(80) ? damper : q + 0x4078;
}

#ifdef VP_LEFTOVER_FIXES
// ---- the fix: QuarterCarControl::Draw on values whose lines overran the original's 80 bytes ---------------------------
// Only the rewrite runs: the original would overrun this program's stack. Each rig makes at least one line longer than
// 79 characters -- Best Grip / Best Contact from floats near FLT_MAX (the plot "finds" them, as graph_fn would), the
// damping ratios from denormal masses and rates under huge damper rates (a ratio near 1e82) -- and the rewrite must
// return normally (4 bytes popped, ebx / esi / edi / ebp kept) and draw every line whole: gxText gets each text as
// sprintf made it, the longest over 79 characters.
static int directed_fix_tests() {
    const LoEntry* f = 0;
    for (int i = 0; i < g_nfns; i++) if (g_fns[i].v10 == F_QCC_DRAW) f = &g_fns[i];
    if (!f) { printf("  fix test: QuarterCarControl::Draw isn't listed\n"); return 1; }
    int bad = 0, n = 0;
    uint32_t longest = 0;
    for (int t = 0; t < 400; t++) {
        mem_load(g_pristine);
        random_arena();
        uint8_t* q = g_arena + 0x100;
        random_rig(q);
        const float big = bitsf(0x7f000000u | (rnd() & 0x7fffff)) * ((rnd() & 1) ? 1.0f : -1.0f);   // 1.7e38 .. 3.4e38
        // the damper: base and slope each a quarter of FLT_MAX-ish and positive, so a rate (their sum) stays finite
        const float rate = fabsf(big) * 0.25f;
        uint8_t* damper = g_arena + 0xc000;
        switch (t % 3) {
        case 0:                                         // Best Grip / Best Contact
            g_plot_grip = big; g_plot_at = -big;
            setf(q + 0x4074, big);
            break;
        case 1:                                         // the damping ratios
            setf(q + 0x18, bitsf(1 + rnd() % 0x100)); setf(q + 0x1c, bitsf(1 + rnd() % 0x100));
            setf(q + 0x4060, bitsf(1 + rnd() % 0x100)); setf(q + 0x24, bitsf(1 + rnd() % 0x100));
            for (int i = 0; i < 4; i++) setf(damper + 4 * i, rate);
            *(uint8_t**)(q + 0x28) = damper;
            g_plot_grip = range(0, 1); g_plot_at = range(0, 200);
            break;
        default:                                        // all of them
            g_plot_grip = big; g_plot_at = big;
            setf(q + 0x4074, -big);
            setf(q + 0x18, bitsf(1)); setf(q + 0x1c, bitsf(1)); setf(q + 0x4060, bitsf(1)); setf(q + 0x24, bitsf(1));
            for (int i = 0; i < 4; i++) setf(damper + 4 * i, rate);
            *(uint8_t**)(q + 0x28) = damper;
        }
        uint32_t words[3] = {(uint32_t)(uintptr_t)q, rnd(), rnd()};
        g_pc = (t >> 1) & 1 ? _PC_24 : _PC_53;
        g_plot_poke = true;
        g_text_longest = g_sprf_longest = 0;
        const Result r = run(*f, true, words);
        g_plot_poke = false;
        const bool ok = !r.fault && r.pops == 4 && r.regs[0] == 0x0b0b0b0b && r.regs[1] == 0x05050505 &&
                        r.regs[2] == 0x0d0d0d0d && r.regs[3] == 0x0e0e0e0e && g_sprf_longest >= 0x50 &&
                        g_text_longest == g_sprf_longest;
        if (!ok) {
            printf("  fix test: QuarterCarControl::Draw, rig %d (kind %d): fault %d (%08x at %08x), popped %u, ebx esi edi ebp "
                   "%08x %08x %08x %08x, longest text %u (drawn %u)\n", t, t % 3, r.fault, r.code, r.eip, r.pops, r.regs[0],
                   r.regs[1], r.regs[2], r.regs[3], g_sprf_longest, g_text_longest);
            if (++bad >= 5) break;
        }
        if (g_sprf_longest > longest) longest = g_sprf_longest;
        n++;
    }
    mem_load(g_pristine);
    printf("directed fix tests: %s -- QuarterCarControl::Draw: %d rigs with lines past 79 characters (the longest %u), "
           "drawn whole, no overrun\n", bad ? "FAILED" : "all passed", n, longest);
    return bad;
}
#endif

// ---- main ---------------------------------------------------------------------------------------------------------------
int main(int argc, char** argv) {
    SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX | SEM_NOOPENFILEERRORBOX);
    if (!GetEnvironmentVariableA("VP_WORLD_CHILD", 0, 0)) return relaunch();
    setvbuf(stdout, 0, _IONBF, 0);
    const int rounds = argc > 1 ? atoi(argv[1]) : 8;
    if (argc > 2) g_rng = ((uint32_t)strtoul(argv[2], 0, 0) * 2654435761u) | 1;
    const bool trace = GetEnvironmentVariableA("VP_TRACE", 0, 0) != 0;
    char exe[MAX_PATH];
    strcpy(exe, __FILE__);
    char* s = strstr(exe, "\\test\\world_leftover.cpp");
    if (s) strcpy(s, "\\out\\race_v10.exe");
    if (!load_race_exe(exe)) return 2;
    SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX | SEM_NOOPENFILEERRORBOX);
    patch_jmp(0x004cf730, (void*)&stub_crt_fatal);         // _amsg_exit
    patch_jmp(0x004d45b0, (void*)&stub_crt_fatal);         // _NMSG_WRITE
    patch_jmp(0x004d4570, (void*)&stub_crt_fatal);         // _FF_MSGBANNER
    patch_jmp(0x004d5c10, (void*)&stub_crt_fatal);         // _fptrap
    patch_jmp(0x004d6850, (void*)&stub_crt_msgbox);        // __crtMessageBoxA
    patch_jmp(0x00414390, (void*)&stub_delete);            // operator delete
    patch_jmp(0x004112b0, (void*)&stub_panic);             // LogPanic
    patch_jmp(0x0046dc70, (void*)&stub_graf_draw);         // GrafDraw
    patch_jmp(0x0044fe30, (void*)&stub_set_canvas);        // gxSetCanvas
    patch_jmp(0x004d9420, (void*)&stub_axes);              // GraphDrawAxes
    patch_jmp(0x004d9290, (void*)&stub_line_plot);         // GraphDrawLinePlot
    patch_jmp(0x00453bd0, (void*)&stub_text);              // gxText
    patch_jmp(0x004cf0a0, (void*)&stub_sprintf);           // sprintf
    patch_dtors();
    g_arena = (uint8_t*)VirtualAlloc(0, ARENA_BYTES, MEM_COMMIT, PAGE_READWRITE);
    g_pristine = mem_alloc(); g_snap = mem_alloc(); g_after = mem_alloc();
    mem_save(g_pristine);

    // every listed address once, and each one a function the generator or the hand file wrote
    int dup = 0;
    for (int i = 0; i < g_nfns; i++)
        for (int j = i + 1; j < g_nfns; j++)
            if (g_fns[i].v10 == g_fns[j].v10 || !strcmp(g_fns[i].name, g_fns[j].name)) {
                printf("  listed twice: %08x %s / %08x %s\n", g_fns[i].v10, g_fns[i].name, g_fns[j].v10, g_fns[j].name);
                dup++;
            }

#ifdef VP_LEFTOVER_FIXES
    const int fix_bad = directed_fix_tests();
#else
    const int fix_bad = 0;
#endif

    static Footprint fp;
    long long checks = 0, poisoned_checks = 0, log_words = 0;
    int differ = 0, fp_bad = 0, faults = 0, pure_n = 0, replay_n = 0, changed_fns = 0, still_fns = 0;
    int bad_fns = 0;
    for (int fi = 0; fi < g_nfns; fi++) {
        const LoEntry& f = g_fns[fi];
        const int n = heavy(f) ? rounds * 250 : rounds;
        bool fn_bad = false, fn_changed = false;
        for (int rd = 0; rd < n && !fn_bad; rd++) {
            const bool poisoned = rd & 1;
            g_pc = (rd >> 1) & 1 ? _PC_24 : _PC_53;
            mem_load(g_pristine);
            if (poisoned) poison();
            random_arena();
            uint32_t words[18];
            for (int i = 0; i < 18; i++) words[i] = rnd();
            uint8_t* obj = g_arena + 0x100;
            if (f.fast) words[0] = (uint32_t)(uintptr_t)obj;
            if (f.v10 == F_DSERR) words[0] = (rnd() & 3) ? k_dserr[rnd() % (sizeof k_dserr / 4)] : rnd();
            if (f.v10 == F_QCC_DRAW) random_rig(obj);
            if (is_deleting_dtor(f) && (rnd() & 1)) words[2] &= ~1u;
            fp.n = 0; fp.replay_only = 0; fp.pure = false;
            f.fp(fp, words);
            mem_save(g_snap);
            const Result ro = run(f, false, words);
            const bool changed = mem_diff(g_snap) != 0;
            fn_changed |= changed;
            // a pure function changes nothing; a listed footprint covers every change (checked on the original's pass)
            if (!fp.replay_only && changed) {
                bool bad = fp.pure;
                if (!bad) {
                    for (uint32_t a = 0; a < DATA_BYTES && !bad; a++)
                        if (g_snap.data[a] != DATA[a]) {
                            bool in = false;
                            for (int k = 0; k < fp.n; k++) in |= DATA + a >= (uint8_t*)fp.r[k].p && DATA + a < (uint8_t*)fp.r[k].p + fp.r[k].n;
                            bad = !in;
                        }
                }
                if (bad) { printf("  FOOTPRINT %08x %s: the original changed %08x outside it\n", f.v10, f.name, mem_diff(g_snap)); fp_bad++; fn_bad = true; }
            }
            mem_save(g_after);
            g_log_orig = g_log;
            mem_load(g_snap);
            const Result rn = run(f, true, words);
            checks++;
            poisoned_checks += poisoned;
            log_words += g_log_orig.n;
            if (ro.fault || rn.fault) faults++;
            bool same = ro.fault == rn.fault && ro.code == rn.code && ro.ret == rn.ret && ro.pops == rn.pops &&
                        !memcmp(ro.regs, rn.regs, sizeof ro.regs);
            const uint32_t where = mem_diff(g_after);
            same &= where == 0;
            same &= g_log.n == g_log_orig.n && !memcmp(g_log.w, g_log_orig.w, 4 * (g_log.n < LOG_MAX ? g_log.n : LOG_MAX));
            if (!same) {
                printf("  MISMATCH %08x %s (round %d, %s, pc %s)\n", f.v10, f.name, rd, poisoned ? "poisoned" : "as loaded",
                       g_pc == _PC_24 ? "24" : "53");
                printf("    fault %d/%d (%08x at %08x / %08x at %08x), return %08x / %08x, popped %u / %u, ebx esi edi ebp %08x %08x %08x %08x / %08x %08x %08x %08x\n",
                       ro.fault, rn.fault, ro.code, ro.eip, rn.code, rn.eip, ro.ret, rn.ret, ro.pops, rn.pops, ro.regs[0], ro.regs[1],
                       ro.regs[2], ro.regs[3], rn.regs[0], rn.regs[1], rn.regs[2], rn.regs[3]);
                if (where) printf("    memory first differs at %08x\n", where);
                if (g_log.n != g_log_orig.n) printf("    the stub logs differ: %u / %u words\n", g_log_orig.n, g_log.n);
                else
                    for (uint32_t i = 0; i < g_log.n && i < LOG_MAX; i++)
                        if (g_log.w[i] != g_log_orig.w[i]) { printf("    the stub logs differ at word %u: %08x / %08x\n", i, g_log_orig.w[i], g_log.w[i]); break; }
                differ++;
                fn_bad = true;
            }
            if (rd == 0) { pure_n += fp.pure; replay_n += fp.replay_only != 0; }
        }
        bad_fns += fn_bad;
        (fn_changed ? changed_fns : still_fns)++;
        if (trace) printf("%08x %-48s %s%s\n", f.v10, f.name, fn_bad ? "BAD" : "ok", fn_changed ? "" : " (never changed memory)");
        if (differ >= 30) { printf("stopping after 30 differences\n"); break; }
    }
    mem_load(g_pristine);
    printf("%d functions (%d pure, %d replay_only, %d others), %d listed twice; %lld checks (%lld on poisoned .data), "
           "%lld logged words compared: %d differ, %d footprint violations, %d checks faulted (in both, the same way, unless counted above); "
           "%d functions bad\n", g_nfns, pure_n, replay_n, g_nfns - pure_n - replay_n, dup, checks, poisoned_checks, log_words, differ,
           fp_bad, faults, bad_fns);
    printf("%d functions changed memory in some round, %d never did (bare rets, stubs, jumps to rcfunc_is_internal or to a bare ret)\n",
           changed_fns, still_fns);
    return differ || fp_bad || dup || fix_bad ? 1 : 0;
}
