// generated by tools/gen_com_base.py from the Windows SDK's ddraw.h, d3d.h -- do not edit
#pragma once
#include "dx5.h"

void com_unsupported(const char* method);   // logs the first call to each

struct Base_IDirectDraw : IDirectDraw {
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, LPVOID * ppvObj) override { *ppvObj = 0; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return 1; }
    ULONG STDMETHODCALLTYPE Release() override { return 1; }
    HRESULT STDMETHODCALLTYPE Compact() override { com_unsupported("IDirectDraw::Compact"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateClipper(DWORD, LPDIRECTDRAWCLIPPER FAR*, IUnknown FAR *) override { com_unsupported("IDirectDraw::CreateClipper"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreatePalette(DWORD, LPPALETTEENTRY, LPDIRECTDRAWPALETTE FAR*, IUnknown FAR *) override { com_unsupported("IDirectDraw::CreatePalette"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateSurface(LPDDSURFACEDESC, LPDIRECTDRAWSURFACE FAR *, IUnknown FAR *) override { com_unsupported("IDirectDraw::CreateSurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DuplicateSurface(LPDIRECTDRAWSURFACE, LPDIRECTDRAWSURFACE FAR *) override { com_unsupported("IDirectDraw::DuplicateSurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumDisplayModes(DWORD, LPDDSURFACEDESC, LPVOID, LPDDENUMMODESCALLBACK) override { com_unsupported("IDirectDraw::EnumDisplayModes"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumSurfaces(DWORD, LPDDSURFACEDESC, LPVOID,LPDDENUMSURFACESCALLBACK) override { com_unsupported("IDirectDraw::EnumSurfaces"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE FlipToGDISurface() override { com_unsupported("IDirectDraw::FlipToGDISurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetCaps(LPDDCAPS, LPDDCAPS) override { com_unsupported("IDirectDraw::GetCaps"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetDisplayMode(LPDDSURFACEDESC) override { com_unsupported("IDirectDraw::GetDisplayMode"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetFourCCCodes(LPDWORD, LPDWORD) override { com_unsupported("IDirectDraw::GetFourCCCodes"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetGDISurface(LPDIRECTDRAWSURFACE FAR *) override { com_unsupported("IDirectDraw::GetGDISurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetMonitorFrequency(LPDWORD) override { com_unsupported("IDirectDraw::GetMonitorFrequency"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetScanLine(LPDWORD) override { com_unsupported("IDirectDraw::GetScanLine"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetVerticalBlankStatus(LPBOOL) override { com_unsupported("IDirectDraw::GetVerticalBlankStatus"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Initialize(GUID FAR *) override { com_unsupported("IDirectDraw::Initialize"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE RestoreDisplayMode() override { com_unsupported("IDirectDraw::RestoreDisplayMode"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetCooperativeLevel(HWND, DWORD) override { com_unsupported("IDirectDraw::SetCooperativeLevel"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetDisplayMode(DWORD, DWORD,DWORD) override { com_unsupported("IDirectDraw::SetDisplayMode"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE WaitForVerticalBlank(DWORD, HANDLE) override { com_unsupported("IDirectDraw::WaitForVerticalBlank"); return E_NOTIMPL; }
};

struct Base_IDirectDraw2 : IDirectDraw2 {
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, LPVOID * ppvObj) override { *ppvObj = 0; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return 1; }
    ULONG STDMETHODCALLTYPE Release() override { return 1; }
    HRESULT STDMETHODCALLTYPE Compact() override { com_unsupported("IDirectDraw2::Compact"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateClipper(DWORD, LPDIRECTDRAWCLIPPER FAR*, IUnknown FAR *) override { com_unsupported("IDirectDraw2::CreateClipper"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreatePalette(DWORD, LPPALETTEENTRY, LPDIRECTDRAWPALETTE FAR*, IUnknown FAR *) override { com_unsupported("IDirectDraw2::CreatePalette"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateSurface(LPDDSURFACEDESC, LPDIRECTDRAWSURFACE FAR *, IUnknown FAR *) override { com_unsupported("IDirectDraw2::CreateSurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DuplicateSurface(LPDIRECTDRAWSURFACE, LPDIRECTDRAWSURFACE FAR *) override { com_unsupported("IDirectDraw2::DuplicateSurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumDisplayModes(DWORD, LPDDSURFACEDESC, LPVOID, LPDDENUMMODESCALLBACK) override { com_unsupported("IDirectDraw2::EnumDisplayModes"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumSurfaces(DWORD, LPDDSURFACEDESC, LPVOID,LPDDENUMSURFACESCALLBACK) override { com_unsupported("IDirectDraw2::EnumSurfaces"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE FlipToGDISurface() override { com_unsupported("IDirectDraw2::FlipToGDISurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetCaps(LPDDCAPS, LPDDCAPS) override { com_unsupported("IDirectDraw2::GetCaps"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetDisplayMode(LPDDSURFACEDESC) override { com_unsupported("IDirectDraw2::GetDisplayMode"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetFourCCCodes(LPDWORD, LPDWORD) override { com_unsupported("IDirectDraw2::GetFourCCCodes"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetGDISurface(LPDIRECTDRAWSURFACE FAR *) override { com_unsupported("IDirectDraw2::GetGDISurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetMonitorFrequency(LPDWORD) override { com_unsupported("IDirectDraw2::GetMonitorFrequency"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetScanLine(LPDWORD) override { com_unsupported("IDirectDraw2::GetScanLine"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetVerticalBlankStatus(LPBOOL) override { com_unsupported("IDirectDraw2::GetVerticalBlankStatus"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Initialize(GUID FAR *) override { com_unsupported("IDirectDraw2::Initialize"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE RestoreDisplayMode() override { com_unsupported("IDirectDraw2::RestoreDisplayMode"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetCooperativeLevel(HWND, DWORD) override { com_unsupported("IDirectDraw2::SetCooperativeLevel"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetDisplayMode(DWORD, DWORD,DWORD, DWORD, DWORD) override { com_unsupported("IDirectDraw2::SetDisplayMode"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE WaitForVerticalBlank(DWORD, HANDLE) override { com_unsupported("IDirectDraw2::WaitForVerticalBlank"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetAvailableVidMem(LPDDSCAPS, LPDWORD, LPDWORD) override { com_unsupported("IDirectDraw2::GetAvailableVidMem"); return E_NOTIMPL; }
};

struct Base_IDirectDrawSurface3 : IDirectDrawSurface3 {
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, LPVOID * ppvObj) override { *ppvObj = 0; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return 1; }
    ULONG STDMETHODCALLTYPE Release() override { return 1; }
    HRESULT STDMETHODCALLTYPE AddAttachedSurface(LPDIRECTDRAWSURFACE3) override { com_unsupported("IDirectDrawSurface3::AddAttachedSurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE AddOverlayDirtyRect(LPRECT) override { com_unsupported("IDirectDrawSurface3::AddOverlayDirtyRect"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Blt(LPRECT,LPDIRECTDRAWSURFACE3, LPRECT,DWORD, LPDDBLTFX) override { com_unsupported("IDirectDrawSurface3::Blt"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE BltBatch(LPDDBLTBATCH, DWORD, DWORD) override { com_unsupported("IDirectDrawSurface3::BltBatch"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE BltFast(DWORD,DWORD,LPDIRECTDRAWSURFACE3, LPRECT,DWORD) override { com_unsupported("IDirectDrawSurface3::BltFast"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DeleteAttachedSurface(DWORD,LPDIRECTDRAWSURFACE3) override { com_unsupported("IDirectDrawSurface3::DeleteAttachedSurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumAttachedSurfaces(LPVOID,LPDDENUMSURFACESCALLBACK) override { com_unsupported("IDirectDrawSurface3::EnumAttachedSurfaces"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumOverlayZOrders(DWORD,LPVOID,LPDDENUMSURFACESCALLBACK) override { com_unsupported("IDirectDrawSurface3::EnumOverlayZOrders"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Flip(LPDIRECTDRAWSURFACE3, DWORD) override { com_unsupported("IDirectDrawSurface3::Flip"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetAttachedSurface(LPDDSCAPS, LPDIRECTDRAWSURFACE3 FAR *) override { com_unsupported("IDirectDrawSurface3::GetAttachedSurface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetBltStatus(DWORD) override { com_unsupported("IDirectDrawSurface3::GetBltStatus"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetCaps(LPDDSCAPS) override { com_unsupported("IDirectDrawSurface3::GetCaps"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetClipper(LPDIRECTDRAWCLIPPER FAR*) override { com_unsupported("IDirectDrawSurface3::GetClipper"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetColorKey(DWORD, LPDDCOLORKEY) override { com_unsupported("IDirectDrawSurface3::GetColorKey"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetDC(HDC FAR *) override { com_unsupported("IDirectDrawSurface3::GetDC"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetFlipStatus(DWORD) override { com_unsupported("IDirectDrawSurface3::GetFlipStatus"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetOverlayPosition(LPLONG, LPLONG) override { com_unsupported("IDirectDrawSurface3::GetOverlayPosition"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetPalette(LPDIRECTDRAWPALETTE FAR*) override { com_unsupported("IDirectDrawSurface3::GetPalette"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetPixelFormat(LPDDPIXELFORMAT) override { com_unsupported("IDirectDrawSurface3::GetPixelFormat"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetSurfaceDesc(LPDDSURFACEDESC) override { com_unsupported("IDirectDrawSurface3::GetSurfaceDesc"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Initialize(LPDIRECTDRAW, LPDDSURFACEDESC) override { com_unsupported("IDirectDrawSurface3::Initialize"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE IsLost() override { com_unsupported("IDirectDrawSurface3::IsLost"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Lock(LPRECT,LPDDSURFACEDESC,DWORD,HANDLE) override { com_unsupported("IDirectDrawSurface3::Lock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE ReleaseDC(HDC) override { com_unsupported("IDirectDrawSurface3::ReleaseDC"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Restore() override { com_unsupported("IDirectDrawSurface3::Restore"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetClipper(LPDIRECTDRAWCLIPPER) override { com_unsupported("IDirectDrawSurface3::SetClipper"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetColorKey(DWORD, LPDDCOLORKEY) override { com_unsupported("IDirectDrawSurface3::SetColorKey"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetOverlayPosition(LONG, LONG) override { com_unsupported("IDirectDrawSurface3::SetOverlayPosition"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetPalette(LPDIRECTDRAWPALETTE) override { com_unsupported("IDirectDrawSurface3::SetPalette"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Unlock(LPVOID) override { com_unsupported("IDirectDrawSurface3::Unlock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE UpdateOverlay(LPRECT, LPDIRECTDRAWSURFACE3,LPRECT,DWORD, LPDDOVERLAYFX) override { com_unsupported("IDirectDrawSurface3::UpdateOverlay"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE UpdateOverlayDisplay(DWORD) override { com_unsupported("IDirectDrawSurface3::UpdateOverlayDisplay"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE UpdateOverlayZOrder(DWORD, LPDIRECTDRAWSURFACE3) override { com_unsupported("IDirectDrawSurface3::UpdateOverlayZOrder"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetDDInterface(LPVOID FAR *) override { com_unsupported("IDirectDrawSurface3::GetDDInterface"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE PageLock(DWORD) override { com_unsupported("IDirectDrawSurface3::PageLock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE PageUnlock(DWORD) override { com_unsupported("IDirectDrawSurface3::PageUnlock"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetSurfaceDesc(LPDDSURFACEDESC, DWORD) override { com_unsupported("IDirectDrawSurface3::SetSurfaceDesc"); return E_NOTIMPL; }
};

struct Base_IDirect3D2 : IDirect3D2 {
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, LPVOID * ppvObj) override { *ppvObj = 0; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return 1; }
    ULONG STDMETHODCALLTYPE Release() override { return 1; }
    HRESULT STDMETHODCALLTYPE EnumDevices(LPD3DENUMDEVICESCALLBACK,LPVOID) override { com_unsupported("IDirect3D2::EnumDevices"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateLight(LPDIRECT3DLIGHT*,IUnknown*) override { com_unsupported("IDirect3D2::CreateLight"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateMaterial(LPDIRECT3DMATERIAL2*,IUnknown*) override { com_unsupported("IDirect3D2::CreateMaterial"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateViewport(LPDIRECT3DVIEWPORT2*,IUnknown*) override { com_unsupported("IDirect3D2::CreateViewport"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE FindDevice(LPD3DFINDDEVICESEARCH,LPD3DFINDDEVICERESULT) override { com_unsupported("IDirect3D2::FindDevice"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE CreateDevice(REFCLSID,LPDIRECTDRAWSURFACE,LPDIRECT3DDEVICE2*) override { com_unsupported("IDirect3D2::CreateDevice"); return E_NOTIMPL; }
};

struct Base_IDirect3DDevice2 : IDirect3DDevice2 {
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, LPVOID * ppvObj) override { *ppvObj = 0; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return 1; }
    ULONG STDMETHODCALLTYPE Release() override { return 1; }
    HRESULT STDMETHODCALLTYPE GetCaps(LPD3DDEVICEDESC,LPD3DDEVICEDESC) override { com_unsupported("IDirect3DDevice2::GetCaps"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SwapTextureHandles(LPDIRECT3DTEXTURE2,LPDIRECT3DTEXTURE2) override { com_unsupported("IDirect3DDevice2::SwapTextureHandles"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetStats(LPD3DSTATS) override { com_unsupported("IDirect3DDevice2::GetStats"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE AddViewport(LPDIRECT3DVIEWPORT2) override { com_unsupported("IDirect3DDevice2::AddViewport"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DeleteViewport(LPDIRECT3DVIEWPORT2) override { com_unsupported("IDirect3DDevice2::DeleteViewport"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE NextViewport(LPDIRECT3DVIEWPORT2,LPDIRECT3DVIEWPORT2*,DWORD) override { com_unsupported("IDirect3DDevice2::NextViewport"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EnumTextureFormats(LPD3DENUMTEXTUREFORMATSCALLBACK,LPVOID) override { com_unsupported("IDirect3DDevice2::EnumTextureFormats"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE BeginScene() override { com_unsupported("IDirect3DDevice2::BeginScene"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE EndScene() override { com_unsupported("IDirect3DDevice2::EndScene"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetDirect3D(LPDIRECT3D2*) override { com_unsupported("IDirect3DDevice2::GetDirect3D"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetCurrentViewport(LPDIRECT3DVIEWPORT2) override { com_unsupported("IDirect3DDevice2::SetCurrentViewport"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetCurrentViewport(LPDIRECT3DVIEWPORT2 *) override { com_unsupported("IDirect3DDevice2::GetCurrentViewport"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetRenderTarget(LPDIRECTDRAWSURFACE,DWORD) override { com_unsupported("IDirect3DDevice2::SetRenderTarget"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetRenderTarget(LPDIRECTDRAWSURFACE *) override { com_unsupported("IDirect3DDevice2::GetRenderTarget"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Begin(D3DPRIMITIVETYPE,D3DVERTEXTYPE,DWORD) override { com_unsupported("IDirect3DDevice2::Begin"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE BeginIndexed(D3DPRIMITIVETYPE,D3DVERTEXTYPE,LPVOID,DWORD,DWORD) override { com_unsupported("IDirect3DDevice2::BeginIndexed"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Vertex(LPVOID) override { com_unsupported("IDirect3DDevice2::Vertex"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Index(WORD) override { com_unsupported("IDirect3DDevice2::Index"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE End(DWORD) override { com_unsupported("IDirect3DDevice2::End"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetRenderState(D3DRENDERSTATETYPE,LPDWORD) override { com_unsupported("IDirect3DDevice2::GetRenderState"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetRenderState(D3DRENDERSTATETYPE,DWORD) override { com_unsupported("IDirect3DDevice2::SetRenderState"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetLightState(D3DLIGHTSTATETYPE,LPDWORD) override { com_unsupported("IDirect3DDevice2::GetLightState"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetLightState(D3DLIGHTSTATETYPE,DWORD) override { com_unsupported("IDirect3DDevice2::SetLightState"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetTransform(D3DTRANSFORMSTATETYPE,LPD3DMATRIX) override { com_unsupported("IDirect3DDevice2::SetTransform"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetTransform(D3DTRANSFORMSTATETYPE,LPD3DMATRIX) override { com_unsupported("IDirect3DDevice2::GetTransform"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE MultiplyTransform(D3DTRANSFORMSTATETYPE,LPD3DMATRIX) override { com_unsupported("IDirect3DDevice2::MultiplyTransform"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DrawPrimitive(D3DPRIMITIVETYPE,D3DVERTEXTYPE,LPVOID,DWORD,DWORD) override { com_unsupported("IDirect3DDevice2::DrawPrimitive"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DrawIndexedPrimitive(D3DPRIMITIVETYPE,D3DVERTEXTYPE,LPVOID,DWORD,LPWORD,DWORD,DWORD) override { com_unsupported("IDirect3DDevice2::DrawIndexedPrimitive"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetClipStatus(LPD3DCLIPSTATUS) override { com_unsupported("IDirect3DDevice2::SetClipStatus"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetClipStatus(LPD3DCLIPSTATUS) override { com_unsupported("IDirect3DDevice2::GetClipStatus"); return E_NOTIMPL; }
};

struct Base_IDirect3DViewport2 : IDirect3DViewport2 {
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, LPVOID * ppvObj) override { *ppvObj = 0; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return 1; }
    ULONG STDMETHODCALLTYPE Release() override { return 1; }
    HRESULT STDMETHODCALLTYPE Initialize(LPDIRECT3D) override { com_unsupported("IDirect3DViewport2::Initialize"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetViewport(LPD3DVIEWPORT) override { com_unsupported("IDirect3DViewport2::GetViewport"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetViewport(LPD3DVIEWPORT) override { com_unsupported("IDirect3DViewport2::SetViewport"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE TransformVertices(DWORD,LPD3DTRANSFORMDATA,DWORD,LPDWORD) override { com_unsupported("IDirect3DViewport2::TransformVertices"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE LightElements(DWORD,LPD3DLIGHTDATA) override { com_unsupported("IDirect3DViewport2::LightElements"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetBackground(D3DMATERIALHANDLE) override { com_unsupported("IDirect3DViewport2::SetBackground"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetBackground(LPD3DMATERIALHANDLE,LPBOOL) override { com_unsupported("IDirect3DViewport2::GetBackground"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetBackgroundDepth(LPDIRECTDRAWSURFACE) override { com_unsupported("IDirect3DViewport2::SetBackgroundDepth"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetBackgroundDepth(LPDIRECTDRAWSURFACE*,LPBOOL) override { com_unsupported("IDirect3DViewport2::GetBackgroundDepth"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Clear(DWORD,LPD3DRECT,DWORD) override { com_unsupported("IDirect3DViewport2::Clear"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE AddLight(LPDIRECT3DLIGHT) override { com_unsupported("IDirect3DViewport2::AddLight"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE DeleteLight(LPDIRECT3DLIGHT) override { com_unsupported("IDirect3DViewport2::DeleteLight"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE NextLight(LPDIRECT3DLIGHT,LPDIRECT3DLIGHT*,DWORD) override { com_unsupported("IDirect3DViewport2::NextLight"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetViewport2(LPD3DVIEWPORT2) override { com_unsupported("IDirect3DViewport2::GetViewport2"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE SetViewport2(LPD3DVIEWPORT2) override { com_unsupported("IDirect3DViewport2::SetViewport2"); return E_NOTIMPL; }
};

struct Base_IDirect3DMaterial2 : IDirect3DMaterial2 {
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, LPVOID * ppvObj) override { *ppvObj = 0; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return 1; }
    ULONG STDMETHODCALLTYPE Release() override { return 1; }
    HRESULT STDMETHODCALLTYPE SetMaterial(LPD3DMATERIAL) override { com_unsupported("IDirect3DMaterial2::SetMaterial"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetMaterial(LPD3DMATERIAL) override { com_unsupported("IDirect3DMaterial2::GetMaterial"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE GetHandle(LPDIRECT3DDEVICE2,LPD3DMATERIALHANDLE) override { com_unsupported("IDirect3DMaterial2::GetHandle"); return E_NOTIMPL; }
};

struct Base_IDirect3DTexture2 : IDirect3DTexture2 {
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, LPVOID * ppvObj) override { *ppvObj = 0; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return 1; }
    ULONG STDMETHODCALLTYPE Release() override { return 1; }
    HRESULT STDMETHODCALLTYPE GetHandle(LPDIRECT3DDEVICE2,LPD3DTEXTUREHANDLE) override { com_unsupported("IDirect3DTexture2::GetHandle"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE PaletteChanged(DWORD,DWORD) override { com_unsupported("IDirect3DTexture2::PaletteChanged"); return E_NOTIMPL; }
    HRESULT STDMETHODCALLTYPE Load(LPDIRECT3DTEXTURE2) override { com_unsupported("IDirect3DTexture2::Load"); return E_NOTIMPL; }
};

