// net_leftover.cpp -- generated by tools/gen_leftovers.py --lib multi -- don't edit
//
// Multiplayer stage N1: the $E static initialisers of all sixteen object files of the
// multiplayer library (`multi`, N2's client.obj, server.obj, multi.obj and ded.obj included), and
// the stubs and deleting destructors of dataport.obj, hostent.obj, datamod.obj, delqueue.obj,
// nettypes.obj, session.obj, client.obj, server.obj, multi.obj and ded.obj,
// rewritten from their exact v1.0 instruction bytes (tools/gen_leftovers.py says how each shape reads). The rest of the
// library is written by hand (hook/net_*.cpp); test/world_net_core.cpp checks every one against its original. Faithful (docs/PORTING.md):
// stores through volatile at the original's width, in its order; calls to the game by their v1.0 address (a
// __thiscall as __fastcall with an unused edx), so what runs there -- the original or its hooked rewrite -- is what
// the original would have called.
//
// Counts by shape: $E ret 36, $E jmp 256, $E stores 222, $E constructor 2, ret 12, ret_al 1, ret_this 1, dtor_call 8, dtor_inline 2; 540 in all
//
// The $E static initialisers run once, from the CRT's _initterm: replay_only. A tail jump (`jmp T`) stays a call to T
// by address. The stubs read and write nothing (pure); the deleting destructors free memory (replay_only).
#include <stdint.h>
#include "port.h"

// file-local, so a harness can include it beside krn_leftover.cpp
namespace {
typedef int LoEdx;                                  // the unused edx of a __thiscall received as __fastcall
#define LO_G8(a) (*(volatile uint8_t*)(uintptr_t)(a))
#define LO_G32(a) (*(volatile uint32_t*)(uintptr_t)(a))
#define LO_FN(T, a) ((T)(uintptr_t)(a))
typedef void(__cdecl* LoVoid_t)();
typedef void(__cdecl* LoPtr_t)(void*);
typedef void*(__fastcall* LoCtor0_t)(void*, LoEdx);
typedef void*(__fastcall* LoCtor1_t)(void*, LoEdx, uint32_t);
typedef void*(__fastcall* LoCtor2_t)(void*, LoEdx, uint32_t, uint32_t);

static void fp_lo_static_init(Footprint& f) { f.replay_only = "a static initialiser (runs once, from the CRT's _initterm)"; }


// ---- line.obj --------------------------------------------------------------------------------------------------------
static void __cdecl E2_line_lo() {
    LO_FN(LoVoid_t, 0x004a00d0)();    // jmp: $E1
}
PORT_FN(0x004a00c0, "$E2(line.obj)", E2_line_lo, fp_lo_static_init)
static void __cdecl E1_line_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004a00d0, "$E1(line.obj)", E1_line_lo, fp_lo_static_init)
static void __cdecl E7_line_lo() {}    // ret
PORT_FN(0x004a11d0, "$E7(line.obj)", E7_line_lo, fp_lo_static_init)
static void __cdecl E6_line_lo() {}    // ret
PORT_FN(0x004a11e0, "$E6(line.obj)", E6_line_lo, fp_lo_static_init)
static void __cdecl E19_line_lo() {}    // ret
PORT_FN(0x004a1f00, "$E19(line.obj)", E19_line_lo, fp_lo_static_init)
static void __cdecl E18_line_lo() {}    // ret
PORT_FN(0x004a1f10, "$E18(line.obj)", E18_line_lo, fp_lo_static_init)
static void __cdecl E16_line_lo() {}    // ret
PORT_FN(0x004a1f20, "$E16(line.obj)", E16_line_lo, fp_lo_static_init)
static void __cdecl E15_line_lo() {}    // ret
PORT_FN(0x004a1f30, "$E15(line.obj)", E15_line_lo, fp_lo_static_init)
static void __cdecl E14_line_lo() {}    // ret
PORT_FN(0x004a1f40, "$E14(line.obj)", E14_line_lo, fp_lo_static_init)
static void __cdecl E13_line_lo() {}    // ret
PORT_FN(0x004a1f50, "$E13(line.obj)", E13_line_lo, fp_lo_static_init)
static void __cdecl E12_line_lo() {}    // ret
PORT_FN(0x004a1f60, "$E12(line.obj)", E12_line_lo, fp_lo_static_init)
static void __cdecl E11_line_lo() {}    // ret
PORT_FN(0x004a1f70, "$E11(line.obj)", E11_line_lo, fp_lo_static_init)
static void __cdecl E10_line_lo() {}    // ret
PORT_FN(0x004a1f80, "$E10(line.obj)", E10_line_lo, fp_lo_static_init)
static void __cdecl E9_line_lo() {}    // ret
PORT_FN(0x004a1f90, "$E9(line.obj)", E9_line_lo, fp_lo_static_init)

// ---- multi.obj -------------------------------------------------------------------------------------------------------
static void __cdecl E2_multi_lo() {
    LO_FN(LoVoid_t, 0x004a2090)();    // jmp: $E1
}
PORT_FN(0x004a2080, "$E2(multi.obj)", E2_multi_lo, fp_lo_static_init)
static void __cdecl E1_multi_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004a2090, "$E1(multi.obj)", E1_multi_lo, fp_lo_static_init)
static void __cdecl E6_multi_lo() {
    LO_FN(LoVoid_t, 0x004a20b0)();    // jmp: $E5
}
PORT_FN(0x004a20a0, "$E6(multi.obj)", E6_multi_lo, fp_lo_static_init)
static void __cdecl E5_multi_lo() {
    LO_G32(0x0057d1d4) = 0x00000000u;
}
PORT_FN(0x004a20b0, "$E5(multi.obj)", E5_multi_lo, fp_lo_static_init)
static void __cdecl E9_multi_lo() {
    LO_FN(LoVoid_t, 0x004a20d0)();    // jmp: $E8
}
PORT_FN(0x004a20c0, "$E9(multi.obj)", E9_multi_lo, fp_lo_static_init)
static void __cdecl E8_multi_lo() {
    LO_G32(0x0057d220) = 0x001f001fu;
}
PORT_FN(0x004a20d0, "$E8(multi.obj)", E8_multi_lo, fp_lo_static_init)
static void __cdecl E12_multi_lo() {
    LO_FN(LoVoid_t, 0x004a20f0)();    // jmp: $E11
}
PORT_FN(0x004a20e0, "$E12(multi.obj)", E12_multi_lo, fp_lo_static_init)
static void __cdecl E11_multi_lo() {
    LO_G32(0x0057d1e4) = 0x03e001e0u;
}
PORT_FN(0x004a20f0, "$E11(multi.obj)", E11_multi_lo, fp_lo_static_init)
static void __cdecl E15_multi_lo() {
    LO_FN(LoVoid_t, 0x004a2110)();    // jmp: $E14
}
PORT_FN(0x004a2100, "$E15(multi.obj)", E15_multi_lo, fp_lo_static_init)
static void __cdecl E14_multi_lo() {
    LO_G32(0x0057d238) = 0x03ef01efu;
}
PORT_FN(0x004a2110, "$E14(multi.obj)", E14_multi_lo, fp_lo_static_init)
static void __cdecl E18_multi_lo() {
    LO_FN(LoVoid_t, 0x004a2130)();    // jmp: $E17
}
PORT_FN(0x004a2120, "$E18(multi.obj)", E18_multi_lo, fp_lo_static_init)
static void __cdecl E17_multi_lo() {
    LO_G32(0x0057d254) = 0x78003c00u;
}
PORT_FN(0x004a2130, "$E17(multi.obj)", E17_multi_lo, fp_lo_static_init)
static void __cdecl E21_multi_lo() {
    LO_FN(LoVoid_t, 0x004a2150)();    // jmp: $E20
}
PORT_FN(0x004a2140, "$E21(multi.obj)", E21_multi_lo, fp_lo_static_init)
static void __cdecl E20_multi_lo() {
    LO_G32(0x0057d21c) = 0x780f3c0fu;
}
PORT_FN(0x004a2150, "$E20(multi.obj)", E20_multi_lo, fp_lo_static_init)
static void __cdecl E24_multi_lo() {
    LO_FN(LoVoid_t, 0x004a2170)();    // jmp: $E23
}
PORT_FN(0x004a2160, "$E24(multi.obj)", E24_multi_lo, fp_lo_static_init)
static void __cdecl E23_multi_lo() {
    LO_G32(0x0057d248) = 0x7be03de0u;
}
PORT_FN(0x004a2170, "$E23(multi.obj)", E23_multi_lo, fp_lo_static_init)
static void __cdecl E27_multi_lo() {
    LO_FN(LoVoid_t, 0x004a2190)();    // jmp: $E26
}
PORT_FN(0x004a2180, "$E27(multi.obj)", E27_multi_lo, fp_lo_static_init)
static void __cdecl E26_multi_lo() {
    LO_G32(0x0057d20c) = 0x7bef3defu;
}
PORT_FN(0x004a2190, "$E26(multi.obj)", E26_multi_lo, fp_lo_static_init)
static void __cdecl E30_multi_lo() {
    LO_FN(LoVoid_t, 0x004a21b0)();    // jmp: $E29
}
PORT_FN(0x004a21a0, "$E30(multi.obj)", E30_multi_lo, fp_lo_static_init)
static void __cdecl E29_multi_lo() {
    LO_G32(0x0057d244) = 0x42082108u;
}
PORT_FN(0x004a21b0, "$E29(multi.obj)", E29_multi_lo, fp_lo_static_init)
static void __cdecl E33_multi_lo() {
    LO_FN(LoVoid_t, 0x004a21d0)();    // jmp: $E32
}
PORT_FN(0x004a21c0, "$E33(multi.obj)", E33_multi_lo, fp_lo_static_init)
static void __cdecl E32_multi_lo() {
    LO_G32(0x0057d1cc) = 0x001f001fu;
}
PORT_FN(0x004a21d0, "$E32(multi.obj)", E32_multi_lo, fp_lo_static_init)
static void __cdecl E36_multi_lo() {
    LO_FN(LoVoid_t, 0x004a21f0)();    // jmp: $E35
}
PORT_FN(0x004a21e0, "$E36(multi.obj)", E36_multi_lo, fp_lo_static_init)
static void __cdecl E35_multi_lo() {
    LO_G32(0x0057d250) = 0x07e003e0u;
}
PORT_FN(0x004a21f0, "$E35(multi.obj)", E35_multi_lo, fp_lo_static_init)
static void __cdecl E39_multi_lo() {
    LO_FN(LoVoid_t, 0x004a2210)();    // jmp: $E38
}
PORT_FN(0x004a2200, "$E39(multi.obj)", E39_multi_lo, fp_lo_static_init)
static void __cdecl E38_multi_lo() {
    LO_G32(0x0057d1e0) = 0x07ff03ffu;
}
PORT_FN(0x004a2210, "$E38(multi.obj)", E38_multi_lo, fp_lo_static_init)
static void __cdecl E42_multi_lo() {
    LO_FN(LoVoid_t, 0x004a2230)();    // jmp: $E41
}
PORT_FN(0x004a2220, "$E42(multi.obj)", E42_multi_lo, fp_lo_static_init)
static void __cdecl E41_multi_lo() {
    LO_G32(0x0057d1dc) = 0xf8007c00u;
}
PORT_FN(0x004a2230, "$E41(multi.obj)", E41_multi_lo, fp_lo_static_init)
static void __cdecl E45_multi_lo() {
    LO_FN(LoVoid_t, 0x004a2250)();    // jmp: $E44
}
PORT_FN(0x004a2240, "$E45(multi.obj)", E45_multi_lo, fp_lo_static_init)
static void __cdecl E44_multi_lo() {
    LO_G32(0x0057d260) = 0xf81f7c1fu;
}
PORT_FN(0x004a2250, "$E44(multi.obj)", E44_multi_lo, fp_lo_static_init)
static void __cdecl E48_multi_lo() {
    LO_FN(LoVoid_t, 0x004a2270)();    // jmp: $E47
}
PORT_FN(0x004a2260, "$E48(multi.obj)", E48_multi_lo, fp_lo_static_init)
static void __cdecl E47_multi_lo() {
    LO_G32(0x0057d23c) = 0xffe07fe0u;
}
PORT_FN(0x004a2270, "$E47(multi.obj)", E47_multi_lo, fp_lo_static_init)
static void __cdecl E51_multi_lo() {
    LO_FN(LoVoid_t, 0x004a2290)();    // jmp: $E50
}
PORT_FN(0x004a2280, "$E51(multi.obj)", E51_multi_lo, fp_lo_static_init)
static void __cdecl E50_multi_lo() {
    LO_G32(0x0057d1f8) = 0xffff7fffu;
}
PORT_FN(0x004a2290, "$E50(multi.obj)", E50_multi_lo, fp_lo_static_init)
static void __cdecl E56_multi_lo() {
    LO_FN(LoVoid_t, 0x004a22b0)();    // jmp: $E55
}
PORT_FN(0x004a22a0, "$E56(multi.obj)", E56_multi_lo, fp_lo_static_init)
static void __cdecl E55_multi_lo() {
    LO_G8(0x0057d1d8) = 0x0f;
}
PORT_FN(0x004a22b0, "$E55(multi.obj)", E55_multi_lo, fp_lo_static_init)
static void __cdecl E60_multi_lo() {
    LO_FN(LoVoid_t, 0x004a23f0)();    // jmp: $E59
}
PORT_FN(0x004a23e0, "$E60(multi.obj)", E60_multi_lo, fp_lo_static_init)
static void __cdecl E59_multi_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x0057d200u, 0, 0x004fb494u);    // Xlator::Xlator
}
PORT_FN(0x004a23f0, "$E59(multi.obj)", E59_multi_lo, fp_lo_static_init)
static void __cdecl E63_multi_lo() {
    LO_FN(LoVoid_t, 0x004a2410)();    // jmp: $E62
}
PORT_FN(0x004a2400, "$E63(multi.obj)", E63_multi_lo, fp_lo_static_init)
static void __cdecl E62_multi_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x0057d1e8u, 0, 0x004fb4acu);    // Xlator::Xlator
}
PORT_FN(0x004a2410, "$E62(multi.obj)", E62_multi_lo, fp_lo_static_init)
// void __cdecl MultiPostRace(void)
static void __cdecl MultiPostRace_lo() {}
static void fp_MultiPostRace_lo(Footprint& f) { f.pure = true; }
PORT_FN(0x004a2830, "MultiPostRace", MultiPostRace_lo, fp_MultiPostRace_lo)
// void __cdecl wait_for_key(void)
static void __cdecl wait_for_key_lo() {}
static void fp_wait_for_key_lo(Footprint& f) { f.pure = true; }
PORT_FN(0x004a2a50, "wait_for_key", wait_for_key_lo, fp_wait_for_key_lo)
static void __cdecl E67_multi_lo() {}    // ret
PORT_FN(0x004a2a60, "$E67(multi.obj)", E67_multi_lo, fp_lo_static_init)
static void __cdecl E66_multi_lo() {}    // ret
PORT_FN(0x004a2a70, "$E66(multi.obj)", E66_multi_lo, fp_lo_static_init)

// ---- ded.obj ---------------------------------------------------------------------------------------------------------
static void __cdecl E2_ded_lo() {
    LO_FN(LoVoid_t, 0x004a2f40)();    // jmp: $E1
}
PORT_FN(0x004a2f30, "$E2(ded.obj)", E2_ded_lo, fp_lo_static_init)
static void __cdecl E1_ded_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004a2f40, "$E1(ded.obj)", E1_ded_lo, fp_lo_static_init)
static void __cdecl E6_ded_lo() {
    LO_FN(LoVoid_t, 0x004a2f60)();    // jmp: $E5
}
PORT_FN(0x004a2f50, "$E6(ded.obj)", E6_ded_lo, fp_lo_static_init)
static void __cdecl E5_ded_lo() {
    LO_G32(0x0057d268) = 0x00000000u;
}
PORT_FN(0x004a2f60, "$E5(ded.obj)", E5_ded_lo, fp_lo_static_init)
static void __cdecl E9_ded_lo() {
    LO_FN(LoVoid_t, 0x004a2f80)();    // jmp: $E8
}
PORT_FN(0x004a2f70, "$E9(ded.obj)", E9_ded_lo, fp_lo_static_init)
static void __cdecl E8_ded_lo() {
    LO_G32(0x0057d288) = 0x001f001fu;
}
PORT_FN(0x004a2f80, "$E8(ded.obj)", E8_ded_lo, fp_lo_static_init)
static void __cdecl E12_ded_lo() {
    LO_FN(LoVoid_t, 0x004a2fa0)();    // jmp: $E11
}
PORT_FN(0x004a2f90, "$E12(ded.obj)", E12_ded_lo, fp_lo_static_init)
static void __cdecl E11_ded_lo() {
    LO_G32(0x0057d278) = 0x03e001e0u;
}
PORT_FN(0x004a2fa0, "$E11(ded.obj)", E11_ded_lo, fp_lo_static_init)
static void __cdecl E15_ded_lo() {
    LO_FN(LoVoid_t, 0x004a2fc0)();    // jmp: $E14
}
PORT_FN(0x004a2fb0, "$E15(ded.obj)", E15_ded_lo, fp_lo_static_init)
static void __cdecl E14_ded_lo() {
    LO_G32(0x0057d28c) = 0x03ef01efu;
}
PORT_FN(0x004a2fc0, "$E14(ded.obj)", E14_ded_lo, fp_lo_static_init)
static void __cdecl E18_ded_lo() {
    LO_FN(LoVoid_t, 0x004a2fe0)();    // jmp: $E17
}
PORT_FN(0x004a2fd0, "$E18(ded.obj)", E18_ded_lo, fp_lo_static_init)
static void __cdecl E17_ded_lo() {
    LO_G32(0x0057d2a8) = 0x78003c00u;
}
PORT_FN(0x004a2fe0, "$E17(ded.obj)", E17_ded_lo, fp_lo_static_init)
static void __cdecl E21_ded_lo() {
    LO_FN(LoVoid_t, 0x004a3000)();    // jmp: $E20
}
PORT_FN(0x004a2ff0, "$E21(ded.obj)", E21_ded_lo, fp_lo_static_init)
static void __cdecl E20_ded_lo() {
    LO_G32(0x0057d284) = 0x780f3c0fu;
}
PORT_FN(0x004a3000, "$E20(ded.obj)", E20_ded_lo, fp_lo_static_init)
static void __cdecl E24_ded_lo() {
    LO_FN(LoVoid_t, 0x004a3020)();    // jmp: $E23
}
PORT_FN(0x004a3010, "$E24(ded.obj)", E24_ded_lo, fp_lo_static_init)
static void __cdecl E23_ded_lo() {
    LO_G32(0x0057d298) = 0x7be03de0u;
}
PORT_FN(0x004a3020, "$E23(ded.obj)", E23_ded_lo, fp_lo_static_init)
static void __cdecl E27_ded_lo() {
    LO_FN(LoVoid_t, 0x004a3040)();    // jmp: $E26
}
PORT_FN(0x004a3030, "$E27(ded.obj)", E27_ded_lo, fp_lo_static_init)
static void __cdecl E26_ded_lo() {
    LO_G32(0x0057d280) = 0x7bef3defu;
}
PORT_FN(0x004a3040, "$E26(ded.obj)", E26_ded_lo, fp_lo_static_init)
static void __cdecl E30_ded_lo() {
    LO_FN(LoVoid_t, 0x004a3060)();    // jmp: $E29
}
PORT_FN(0x004a3050, "$E30(ded.obj)", E30_ded_lo, fp_lo_static_init)
static void __cdecl E29_ded_lo() {
    LO_G32(0x0057d294) = 0x42082108u;
}
PORT_FN(0x004a3060, "$E29(ded.obj)", E29_ded_lo, fp_lo_static_init)
static void __cdecl E33_ded_lo() {
    LO_FN(LoVoid_t, 0x004a3080)();    // jmp: $E32
}
PORT_FN(0x004a3070, "$E33(ded.obj)", E33_ded_lo, fp_lo_static_init)
static void __cdecl E32_ded_lo() {
    LO_G32(0x0057d264) = 0x001f001fu;
}
PORT_FN(0x004a3080, "$E32(ded.obj)", E32_ded_lo, fp_lo_static_init)
static void __cdecl E36_ded_lo() {
    LO_FN(LoVoid_t, 0x004a30a0)();    // jmp: $E35
}
PORT_FN(0x004a3090, "$E36(ded.obj)", E36_ded_lo, fp_lo_static_init)
static void __cdecl E35_ded_lo() {
    LO_G32(0x0057d2a4) = 0x07e003e0u;
}
PORT_FN(0x004a30a0, "$E35(ded.obj)", E35_ded_lo, fp_lo_static_init)
static void __cdecl E39_ded_lo() {
    LO_FN(LoVoid_t, 0x004a30c0)();    // jmp: $E38
}
PORT_FN(0x004a30b0, "$E39(ded.obj)", E39_ded_lo, fp_lo_static_init)
static void __cdecl E38_ded_lo() {
    LO_G32(0x0057d274) = 0x07ff03ffu;
}
PORT_FN(0x004a30c0, "$E38(ded.obj)", E38_ded_lo, fp_lo_static_init)
static void __cdecl E42_ded_lo() {
    LO_FN(LoVoid_t, 0x004a30e0)();    // jmp: $E41
}
PORT_FN(0x004a30d0, "$E42(ded.obj)", E42_ded_lo, fp_lo_static_init)
static void __cdecl E41_ded_lo() {
    LO_G32(0x0057d270) = 0xf8007c00u;
}
PORT_FN(0x004a30e0, "$E41(ded.obj)", E41_ded_lo, fp_lo_static_init)
static void __cdecl E45_ded_lo() {
    LO_FN(LoVoid_t, 0x004a3100)();    // jmp: $E44
}
PORT_FN(0x004a30f0, "$E45(ded.obj)", E45_ded_lo, fp_lo_static_init)
static void __cdecl E44_ded_lo() {
    LO_G32(0x0057d2b0) = 0xf81f7c1fu;
}
PORT_FN(0x004a3100, "$E44(ded.obj)", E44_ded_lo, fp_lo_static_init)
static void __cdecl E48_ded_lo() {
    LO_FN(LoVoid_t, 0x004a3120)();    // jmp: $E47
}
PORT_FN(0x004a3110, "$E48(ded.obj)", E48_ded_lo, fp_lo_static_init)
static void __cdecl E47_ded_lo() {
    LO_G32(0x0057d290) = 0xffe07fe0u;
}
PORT_FN(0x004a3120, "$E47(ded.obj)", E47_ded_lo, fp_lo_static_init)
static void __cdecl E51_ded_lo() {
    LO_FN(LoVoid_t, 0x004a3140)();    // jmp: $E50
}
PORT_FN(0x004a3130, "$E51(ded.obj)", E51_ded_lo, fp_lo_static_init)
static void __cdecl E50_ded_lo() {
    LO_G32(0x0057d27c) = 0xffff7fffu;
}
PORT_FN(0x004a3140, "$E50(ded.obj)", E50_ded_lo, fp_lo_static_init)
static void __cdecl E56_ded_lo() {
    LO_FN(LoVoid_t, 0x004a3160)();    // jmp: $E55
}
PORT_FN(0x004a3150, "$E56(ded.obj)", E56_ded_lo, fp_lo_static_init)
static void __cdecl E55_ded_lo() {
    LO_G8(0x0057d26c) = 0x0f;
}
PORT_FN(0x004a3160, "$E55(ded.obj)", E55_ded_lo, fp_lo_static_init)
// void __cdecl spin(void)
static void __cdecl spin_lo() {}
static void fp_spin_lo(Footprint& f) { f.pure = true; }
PORT_FN(0x004a3d20, "spin", spin_lo, fp_spin_lo)

// ---- crc.obj ---------------------------------------------------------------------------------------------------------
static void __cdecl E2_crc_lo() {
    LO_FN(LoVoid_t, 0x004a3d60)();    // jmp: $E1
}
PORT_FN(0x004a3d50, "$E2(crc.obj)", E2_crc_lo, fp_lo_static_init)
static void __cdecl E1_crc_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004a3d60, "$E1(crc.obj)", E1_crc_lo, fp_lo_static_init)

// ---- delqueue.obj ----------------------------------------------------------------------------------------------------
static void __cdecl E2_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3dd0)();    // jmp: $E1
}
PORT_FN(0x004a3dc0, "$E2(delqueue.obj)", E2_delqueue_lo, fp_lo_static_init)
static void __cdecl E1_delqueue_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004a3dd0, "$E1(delqueue.obj)", E1_delqueue_lo, fp_lo_static_init)
static void __cdecl E6_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3df0)();    // jmp: $E5
}
PORT_FN(0x004a3de0, "$E6(delqueue.obj)", E6_delqueue_lo, fp_lo_static_init)
static void __cdecl E5_delqueue_lo() {
    LO_G32(0x0057d2b8) = 0x00000000u;
}
PORT_FN(0x004a3df0, "$E5(delqueue.obj)", E5_delqueue_lo, fp_lo_static_init)
static void __cdecl E9_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3e10)();    // jmp: $E8
}
PORT_FN(0x004a3e00, "$E9(delqueue.obj)", E9_delqueue_lo, fp_lo_static_init)
static void __cdecl E8_delqueue_lo() {
    LO_G32(0x0057d2d8) = 0x001f001fu;
}
PORT_FN(0x004a3e10, "$E8(delqueue.obj)", E8_delqueue_lo, fp_lo_static_init)
static void __cdecl E12_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3e30)();    // jmp: $E11
}
PORT_FN(0x004a3e20, "$E12(delqueue.obj)", E12_delqueue_lo, fp_lo_static_init)
static void __cdecl E11_delqueue_lo() {
    LO_G32(0x0057d2c8) = 0x03e001e0u;
}
PORT_FN(0x004a3e30, "$E11(delqueue.obj)", E11_delqueue_lo, fp_lo_static_init)
static void __cdecl E15_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3e50)();    // jmp: $E14
}
PORT_FN(0x004a3e40, "$E15(delqueue.obj)", E15_delqueue_lo, fp_lo_static_init)
static void __cdecl E14_delqueue_lo() {
    LO_G32(0x0057d2dc) = 0x03ef01efu;
}
PORT_FN(0x004a3e50, "$E14(delqueue.obj)", E14_delqueue_lo, fp_lo_static_init)
static void __cdecl E18_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3e70)();    // jmp: $E17
}
PORT_FN(0x004a3e60, "$E18(delqueue.obj)", E18_delqueue_lo, fp_lo_static_init)
static void __cdecl E17_delqueue_lo() {
    LO_G32(0x0057d2f4) = 0x78003c00u;
}
PORT_FN(0x004a3e70, "$E17(delqueue.obj)", E17_delqueue_lo, fp_lo_static_init)
static void __cdecl E21_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3e90)();    // jmp: $E20
}
PORT_FN(0x004a3e80, "$E21(delqueue.obj)", E21_delqueue_lo, fp_lo_static_init)
static void __cdecl E20_delqueue_lo() {
    LO_G32(0x0057d2d4) = 0x780f3c0fu;
}
PORT_FN(0x004a3e90, "$E20(delqueue.obj)", E20_delqueue_lo, fp_lo_static_init)
static void __cdecl E24_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3eb0)();    // jmp: $E23
}
PORT_FN(0x004a3ea0, "$E24(delqueue.obj)", E24_delqueue_lo, fp_lo_static_init)
static void __cdecl E23_delqueue_lo() {
    LO_G32(0x0057d2e8) = 0x7be03de0u;
}
PORT_FN(0x004a3eb0, "$E23(delqueue.obj)", E23_delqueue_lo, fp_lo_static_init)
static void __cdecl E27_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3ed0)();    // jmp: $E26
}
PORT_FN(0x004a3ec0, "$E27(delqueue.obj)", E27_delqueue_lo, fp_lo_static_init)
static void __cdecl E26_delqueue_lo() {
    LO_G32(0x0057d2d0) = 0x7bef3defu;
}
PORT_FN(0x004a3ed0, "$E26(delqueue.obj)", E26_delqueue_lo, fp_lo_static_init)
static void __cdecl E30_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3ef0)();    // jmp: $E29
}
PORT_FN(0x004a3ee0, "$E30(delqueue.obj)", E30_delqueue_lo, fp_lo_static_init)
static void __cdecl E29_delqueue_lo() {
    LO_G32(0x0057d2e4) = 0x42082108u;
}
PORT_FN(0x004a3ef0, "$E29(delqueue.obj)", E29_delqueue_lo, fp_lo_static_init)
static void __cdecl E33_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3f10)();    // jmp: $E32
}
PORT_FN(0x004a3f00, "$E33(delqueue.obj)", E33_delqueue_lo, fp_lo_static_init)
static void __cdecl E32_delqueue_lo() {
    LO_G32(0x0057d2b4) = 0x001f001fu;
}
PORT_FN(0x004a3f10, "$E32(delqueue.obj)", E32_delqueue_lo, fp_lo_static_init)
static void __cdecl E36_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3f30)();    // jmp: $E35
}
PORT_FN(0x004a3f20, "$E36(delqueue.obj)", E36_delqueue_lo, fp_lo_static_init)
static void __cdecl E35_delqueue_lo() {
    LO_G32(0x0057d2f0) = 0x07e003e0u;
}
PORT_FN(0x004a3f30, "$E35(delqueue.obj)", E35_delqueue_lo, fp_lo_static_init)
static void __cdecl E39_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3f50)();    // jmp: $E38
}
PORT_FN(0x004a3f40, "$E39(delqueue.obj)", E39_delqueue_lo, fp_lo_static_init)
static void __cdecl E38_delqueue_lo() {
    LO_G32(0x0057d2c4) = 0x07ff03ffu;
}
PORT_FN(0x004a3f50, "$E38(delqueue.obj)", E38_delqueue_lo, fp_lo_static_init)
static void __cdecl E42_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3f70)();    // jmp: $E41
}
PORT_FN(0x004a3f60, "$E42(delqueue.obj)", E42_delqueue_lo, fp_lo_static_init)
static void __cdecl E41_delqueue_lo() {
    LO_G32(0x0057d2c0) = 0xf8007c00u;
}
PORT_FN(0x004a3f70, "$E41(delqueue.obj)", E41_delqueue_lo, fp_lo_static_init)
static void __cdecl E45_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3f90)();    // jmp: $E44
}
PORT_FN(0x004a3f80, "$E45(delqueue.obj)", E45_delqueue_lo, fp_lo_static_init)
static void __cdecl E44_delqueue_lo() {
    LO_G32(0x0057d2f8) = 0xf81f7c1fu;
}
PORT_FN(0x004a3f90, "$E44(delqueue.obj)", E44_delqueue_lo, fp_lo_static_init)
static void __cdecl E48_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3fb0)();    // jmp: $E47
}
PORT_FN(0x004a3fa0, "$E48(delqueue.obj)", E48_delqueue_lo, fp_lo_static_init)
static void __cdecl E47_delqueue_lo() {
    LO_G32(0x0057d2e0) = 0xffe07fe0u;
}
PORT_FN(0x004a3fb0, "$E47(delqueue.obj)", E47_delqueue_lo, fp_lo_static_init)
static void __cdecl E51_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3fd0)();    // jmp: $E50
}
PORT_FN(0x004a3fc0, "$E51(delqueue.obj)", E51_delqueue_lo, fp_lo_static_init)
static void __cdecl E50_delqueue_lo() {
    LO_G32(0x0057d2cc) = 0xffff7fffu;
}
PORT_FN(0x004a3fd0, "$E50(delqueue.obj)", E50_delqueue_lo, fp_lo_static_init)
static void __cdecl E56_delqueue_lo() {
    LO_FN(LoVoid_t, 0x004a3ff0)();    // jmp: $E55
}
PORT_FN(0x004a3fe0, "$E56(delqueue.obj)", E56_delqueue_lo, fp_lo_static_init)
static void __cdecl E55_delqueue_lo() {
    LO_G8(0x0057d2bc) = 0x0f;
}
PORT_FN(0x004a3ff0, "$E55(delqueue.obj)", E55_delqueue_lo, fp_lo_static_init)
// void __cdecl advance_latency_idx(void)
static void __cdecl advance_latency_idx_lo() {}
static void fp_advance_latency_idx_lo(Footprint& f) { f.pure = true; }
PORT_FN(0x004a4120, "advance_latency_idx", advance_latency_idx_lo, fp_advance_latency_idx_lo)

// ---- nettypes.obj ----------------------------------------------------------------------------------------------------
static void __cdecl E2_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a41d0)();    // jmp: $E1
}
PORT_FN(0x004a41c0, "$E2(nettypes.obj)", E2_nettypes_lo, fp_lo_static_init)
static void __cdecl E1_nettypes_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004a41d0, "$E1(nettypes.obj)", E1_nettypes_lo, fp_lo_static_init)
static void __cdecl E6_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a41f0)();    // jmp: $E5
}
PORT_FN(0x004a41e0, "$E6(nettypes.obj)", E6_nettypes_lo, fp_lo_static_init)
static void __cdecl E5_nettypes_lo() {
    LO_G32(0x0057d300) = 0x00000000u;
}
PORT_FN(0x004a41f0, "$E5(nettypes.obj)", E5_nettypes_lo, fp_lo_static_init)
static void __cdecl E9_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a4210)();    // jmp: $E8
}
PORT_FN(0x004a4200, "$E9(nettypes.obj)", E9_nettypes_lo, fp_lo_static_init)
static void __cdecl E8_nettypes_lo() {
    LO_G32(0x0057d320) = 0x001f001fu;
}
PORT_FN(0x004a4210, "$E8(nettypes.obj)", E8_nettypes_lo, fp_lo_static_init)
static void __cdecl E12_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a4230)();    // jmp: $E11
}
PORT_FN(0x004a4220, "$E12(nettypes.obj)", E12_nettypes_lo, fp_lo_static_init)
static void __cdecl E11_nettypes_lo() {
    LO_G32(0x0057d310) = 0x03e001e0u;
}
PORT_FN(0x004a4230, "$E11(nettypes.obj)", E11_nettypes_lo, fp_lo_static_init)
static void __cdecl E15_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a4250)();    // jmp: $E14
}
PORT_FN(0x004a4240, "$E15(nettypes.obj)", E15_nettypes_lo, fp_lo_static_init)
static void __cdecl E14_nettypes_lo() {
    LO_G32(0x0057d324) = 0x03ef01efu;
}
PORT_FN(0x004a4250, "$E14(nettypes.obj)", E14_nettypes_lo, fp_lo_static_init)
static void __cdecl E18_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a4270)();    // jmp: $E17
}
PORT_FN(0x004a4260, "$E18(nettypes.obj)", E18_nettypes_lo, fp_lo_static_init)
static void __cdecl E17_nettypes_lo() {
    LO_G32(0x0057d33c) = 0x78003c00u;
}
PORT_FN(0x004a4270, "$E17(nettypes.obj)", E17_nettypes_lo, fp_lo_static_init)
static void __cdecl E21_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a4290)();    // jmp: $E20
}
PORT_FN(0x004a4280, "$E21(nettypes.obj)", E21_nettypes_lo, fp_lo_static_init)
static void __cdecl E20_nettypes_lo() {
    LO_G32(0x0057d31c) = 0x780f3c0fu;
}
PORT_FN(0x004a4290, "$E20(nettypes.obj)", E20_nettypes_lo, fp_lo_static_init)
static void __cdecl E24_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a42b0)();    // jmp: $E23
}
PORT_FN(0x004a42a0, "$E24(nettypes.obj)", E24_nettypes_lo, fp_lo_static_init)
static void __cdecl E23_nettypes_lo() {
    LO_G32(0x0057d330) = 0x7be03de0u;
}
PORT_FN(0x004a42b0, "$E23(nettypes.obj)", E23_nettypes_lo, fp_lo_static_init)
static void __cdecl E27_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a42d0)();    // jmp: $E26
}
PORT_FN(0x004a42c0, "$E27(nettypes.obj)", E27_nettypes_lo, fp_lo_static_init)
static void __cdecl E26_nettypes_lo() {
    LO_G32(0x0057d318) = 0x7bef3defu;
}
PORT_FN(0x004a42d0, "$E26(nettypes.obj)", E26_nettypes_lo, fp_lo_static_init)
static void __cdecl E30_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a42f0)();    // jmp: $E29
}
PORT_FN(0x004a42e0, "$E30(nettypes.obj)", E30_nettypes_lo, fp_lo_static_init)
static void __cdecl E29_nettypes_lo() {
    LO_G32(0x0057d32c) = 0x42082108u;
}
PORT_FN(0x004a42f0, "$E29(nettypes.obj)", E29_nettypes_lo, fp_lo_static_init)
static void __cdecl E33_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a4310)();    // jmp: $E32
}
PORT_FN(0x004a4300, "$E33(nettypes.obj)", E33_nettypes_lo, fp_lo_static_init)
static void __cdecl E32_nettypes_lo() {
    LO_G32(0x0057d2fc) = 0x001f001fu;
}
PORT_FN(0x004a4310, "$E32(nettypes.obj)", E32_nettypes_lo, fp_lo_static_init)
static void __cdecl E36_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a4330)();    // jmp: $E35
}
PORT_FN(0x004a4320, "$E36(nettypes.obj)", E36_nettypes_lo, fp_lo_static_init)
static void __cdecl E35_nettypes_lo() {
    LO_G32(0x0057d338) = 0x07e003e0u;
}
PORT_FN(0x004a4330, "$E35(nettypes.obj)", E35_nettypes_lo, fp_lo_static_init)
static void __cdecl E39_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a4350)();    // jmp: $E38
}
PORT_FN(0x004a4340, "$E39(nettypes.obj)", E39_nettypes_lo, fp_lo_static_init)
static void __cdecl E38_nettypes_lo() {
    LO_G32(0x0057d30c) = 0x07ff03ffu;
}
PORT_FN(0x004a4350, "$E38(nettypes.obj)", E38_nettypes_lo, fp_lo_static_init)
static void __cdecl E42_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a4370)();    // jmp: $E41
}
PORT_FN(0x004a4360, "$E42(nettypes.obj)", E42_nettypes_lo, fp_lo_static_init)
static void __cdecl E41_nettypes_lo() {
    LO_G32(0x0057d308) = 0xf8007c00u;
}
PORT_FN(0x004a4370, "$E41(nettypes.obj)", E41_nettypes_lo, fp_lo_static_init)
static void __cdecl E45_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a4390)();    // jmp: $E44
}
PORT_FN(0x004a4380, "$E45(nettypes.obj)", E45_nettypes_lo, fp_lo_static_init)
static void __cdecl E44_nettypes_lo() {
    LO_G32(0x0057d340) = 0xf81f7c1fu;
}
PORT_FN(0x004a4390, "$E44(nettypes.obj)", E44_nettypes_lo, fp_lo_static_init)
static void __cdecl E48_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a43b0)();    // jmp: $E47
}
PORT_FN(0x004a43a0, "$E48(nettypes.obj)", E48_nettypes_lo, fp_lo_static_init)
static void __cdecl E47_nettypes_lo() {
    LO_G32(0x0057d328) = 0xffe07fe0u;
}
PORT_FN(0x004a43b0, "$E47(nettypes.obj)", E47_nettypes_lo, fp_lo_static_init)
static void __cdecl E51_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a43d0)();    // jmp: $E50
}
PORT_FN(0x004a43c0, "$E51(nettypes.obj)", E51_nettypes_lo, fp_lo_static_init)
static void __cdecl E50_nettypes_lo() {
    LO_G32(0x0057d314) = 0xffff7fffu;
}
PORT_FN(0x004a43d0, "$E50(nettypes.obj)", E50_nettypes_lo, fp_lo_static_init)
static void __cdecl E56_nettypes_lo() {
    LO_FN(LoVoid_t, 0x004a43f0)();    // jmp: $E55
}
PORT_FN(0x004a43e0, "$E56(nettypes.obj)", E56_nettypes_lo, fp_lo_static_init)
static void __cdecl E55_nettypes_lo() {
    LO_G8(0x0057d304) = 0x0f;
}
PORT_FN(0x004a43f0, "$E55(nettypes.obj)", E55_nettypes_lo, fp_lo_static_init)

// ---- session.obj -----------------------------------------------------------------------------------------------------
static void __cdecl E2_session_lo() {
    LO_FN(LoVoid_t, 0x004a4af0)();    // jmp: $E1
}
PORT_FN(0x004a4ae0, "$E2(session.obj)", E2_session_lo, fp_lo_static_init)
static void __cdecl E1_session_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004a4af0, "$E1(session.obj)", E1_session_lo, fp_lo_static_init)
static void __cdecl E6_session_lo() {
    LO_FN(LoVoid_t, 0x004a4b10)();    // jmp: $E5
}
PORT_FN(0x004a4b00, "$E6(session.obj)", E6_session_lo, fp_lo_static_init)
static void __cdecl E5_session_lo() {
    LO_G32(0x0057d35c) = 0x00000000u;
}
PORT_FN(0x004a4b10, "$E5(session.obj)", E5_session_lo, fp_lo_static_init)
static void __cdecl E9_session_lo() {
    LO_FN(LoVoid_t, 0x004a4b30)();    // jmp: $E8
}
PORT_FN(0x004a4b20, "$E9(session.obj)", E9_session_lo, fp_lo_static_init)
static void __cdecl E8_session_lo() {
    LO_G32(0x0057d3a8) = 0x001f001fu;
}
PORT_FN(0x004a4b30, "$E8(session.obj)", E8_session_lo, fp_lo_static_init)
static void __cdecl E12_session_lo() {
    LO_FN(LoVoid_t, 0x004a4b50)();    // jmp: $E11
}
PORT_FN(0x004a4b40, "$E12(session.obj)", E12_session_lo, fp_lo_static_init)
static void __cdecl E11_session_lo() {
    LO_G32(0x0057d37c) = 0x03e001e0u;
}
PORT_FN(0x004a4b50, "$E11(session.obj)", E11_session_lo, fp_lo_static_init)
static void __cdecl E15_session_lo() {
    LO_FN(LoVoid_t, 0x004a4b70)();    // jmp: $E14
}
PORT_FN(0x004a4b60, "$E15(session.obj)", E15_session_lo, fp_lo_static_init)
static void __cdecl E14_session_lo() {
    LO_G32(0x0057d3fc) = 0x03ef01efu;
}
PORT_FN(0x004a4b70, "$E14(session.obj)", E14_session_lo, fp_lo_static_init)
static void __cdecl E18_session_lo() {
    LO_FN(LoVoid_t, 0x004a4b90)();    // jmp: $E17
}
PORT_FN(0x004a4b80, "$E18(session.obj)", E18_session_lo, fp_lo_static_init)
static void __cdecl E17_session_lo() {
    LO_G32(0x0057d43c) = 0x78003c00u;
}
PORT_FN(0x004a4b90, "$E17(session.obj)", E17_session_lo, fp_lo_static_init)
static void __cdecl E21_session_lo() {
    LO_FN(LoVoid_t, 0x004a4bb0)();    // jmp: $E20
}
PORT_FN(0x004a4ba0, "$E21(session.obj)", E21_session_lo, fp_lo_static_init)
static void __cdecl E20_session_lo() {
    LO_G32(0x0057d3a4) = 0x780f3c0fu;
}
PORT_FN(0x004a4bb0, "$E20(session.obj)", E20_session_lo, fp_lo_static_init)
static void __cdecl E24_session_lo() {
    LO_FN(LoVoid_t, 0x004a4bd0)();    // jmp: $E23
}
PORT_FN(0x004a4bc0, "$E24(session.obj)", E24_session_lo, fp_lo_static_init)
static void __cdecl E23_session_lo() {
    LO_G32(0x0057d430) = 0x7be03de0u;
}
PORT_FN(0x004a4bd0, "$E23(session.obj)", E23_session_lo, fp_lo_static_init)
static void __cdecl E27_session_lo() {
    LO_FN(LoVoid_t, 0x004a4bf0)();    // jmp: $E26
}
PORT_FN(0x004a4be0, "$E27(session.obj)", E27_session_lo, fp_lo_static_init)
static void __cdecl E26_session_lo() {
    LO_G32(0x0057d3a0) = 0x7bef3defu;
}
PORT_FN(0x004a4bf0, "$E26(session.obj)", E26_session_lo, fp_lo_static_init)
static void __cdecl E30_session_lo() {
    LO_FN(LoVoid_t, 0x004a4c10)();    // jmp: $E29
}
PORT_FN(0x004a4c00, "$E30(session.obj)", E30_session_lo, fp_lo_static_init)
static void __cdecl E29_session_lo() {
    LO_G32(0x0057d42c) = 0x42082108u;
}
PORT_FN(0x004a4c10, "$E29(session.obj)", E29_session_lo, fp_lo_static_init)
static void __cdecl E33_session_lo() {
    LO_FN(LoVoid_t, 0x004a4c30)();    // jmp: $E32
}
PORT_FN(0x004a4c20, "$E33(session.obj)", E33_session_lo, fp_lo_static_init)
static void __cdecl E32_session_lo() {
    LO_G32(0x0057d348) = 0x001f001fu;
}
PORT_FN(0x004a4c30, "$E32(session.obj)", E32_session_lo, fp_lo_static_init)
static void __cdecl E36_session_lo() {
    LO_FN(LoVoid_t, 0x004a4c50)();    // jmp: $E35
}
PORT_FN(0x004a4c40, "$E36(session.obj)", E36_session_lo, fp_lo_static_init)
static void __cdecl E35_session_lo() {
    LO_G32(0x0057d438) = 0x07e003e0u;
}
PORT_FN(0x004a4c50, "$E35(session.obj)", E35_session_lo, fp_lo_static_init)
static void __cdecl E39_session_lo() {
    LO_FN(LoVoid_t, 0x004a4c70)();    // jmp: $E38
}
PORT_FN(0x004a4c60, "$E39(session.obj)", E39_session_lo, fp_lo_static_init)
static void __cdecl E38_session_lo() {
    LO_G32(0x0057d378) = 0x07ff03ffu;
}
PORT_FN(0x004a4c70, "$E38(session.obj)", E38_session_lo, fp_lo_static_init)
static void __cdecl E42_session_lo() {
    LO_FN(LoVoid_t, 0x004a4c90)();    // jmp: $E41
}
PORT_FN(0x004a4c80, "$E42(session.obj)", E42_session_lo, fp_lo_static_init)
static void __cdecl E41_session_lo() {
    LO_G32(0x0057d374) = 0xf8007c00u;
}
PORT_FN(0x004a4c90, "$E41(session.obj)", E41_session_lo, fp_lo_static_init)
static void __cdecl E45_session_lo() {
    LO_FN(LoVoid_t, 0x004a4cb0)();    // jmp: $E44
}
PORT_FN(0x004a4ca0, "$E45(session.obj)", E45_session_lo, fp_lo_static_init)
static void __cdecl E44_session_lo() {
    LO_G32(0x0057d440) = 0xf81f7c1fu;
}
PORT_FN(0x004a4cb0, "$E44(session.obj)", E44_session_lo, fp_lo_static_init)
static void __cdecl E48_session_lo() {
    LO_FN(LoVoid_t, 0x004a4cd0)();    // jmp: $E47
}
PORT_FN(0x004a4cc0, "$E48(session.obj)", E48_session_lo, fp_lo_static_init)
static void __cdecl E47_session_lo() {
    LO_G32(0x0057d40c) = 0xffe07fe0u;
}
PORT_FN(0x004a4cd0, "$E47(session.obj)", E47_session_lo, fp_lo_static_init)
static void __cdecl E51_session_lo() {
    LO_FN(LoVoid_t, 0x004a4cf0)();    // jmp: $E50
}
PORT_FN(0x004a4ce0, "$E51(session.obj)", E51_session_lo, fp_lo_static_init)
static void __cdecl E50_session_lo() {
    LO_G32(0x0057d39c) = 0xffff7fffu;
}
PORT_FN(0x004a4cf0, "$E50(session.obj)", E50_session_lo, fp_lo_static_init)
static void __cdecl E56_session_lo() {
    LO_FN(LoVoid_t, 0x004a4d10)();    // jmp: $E55
}
PORT_FN(0x004a4d00, "$E56(session.obj)", E56_session_lo, fp_lo_static_init)
static void __cdecl E55_session_lo() {
    LO_G8(0x0057d360) = 0x0f;
}
PORT_FN(0x004a4d10, "$E55(session.obj)", E55_session_lo, fp_lo_static_init)
// void __cdecl ASSERT_MSG(int,char const *,...)
static void __cdecl ASSERT_MSG_lo(int32_t, void*) {}
static void fp_ASSERT_MSG_lo(Footprint& f, int32_t, void*) { f.pure = true; }
PORT_FN(0x004a5050, "ASSERT_MSG(session.obj)", ASSERT_MSG_lo, fp_ASSERT_MSG_lo)
static void __cdecl E65_session_lo() {}    // ret
PORT_FN(0x004a5500, "$E65(session.obj)", E65_session_lo, fp_lo_static_init)
static void __cdecl E64_session_lo() {}    // ret
PORT_FN(0x004a5510, "$E64(session.obj)", E64_session_lo, fp_lo_static_init)
static void __cdecl E63_session_lo() {}    // ret
PORT_FN(0x004a5520, "$E63(session.obj)", E63_session_lo, fp_lo_static_init)
static void __cdecl E62_session_lo() {}    // ret
PORT_FN(0x004a5530, "$E62(session.obj)", E62_session_lo, fp_lo_static_init)
static void __cdecl E61_session_lo() {}    // ret
PORT_FN(0x004a5540, "$E61(session.obj)", E61_session_lo, fp_lo_static_init)
static void __cdecl E60_session_lo() {}    // ret
PORT_FN(0x004a5550, "$E60(session.obj)", E60_session_lo, fp_lo_static_init)
static void __cdecl E73_session_lo() {}    // ret
PORT_FN(0x004a7920, "$E73(session.obj)", E73_session_lo, fp_lo_static_init)
static void __cdecl E72_session_lo() {}    // ret
PORT_FN(0x004a7930, "$E72(session.obj)", E72_session_lo, fp_lo_static_init)
static void __cdecl E71_session_lo() {}    // ret
PORT_FN(0x004a7940, "$E71(session.obj)", E71_session_lo, fp_lo_static_init)
static void __cdecl E70_session_lo() {}    // ret
PORT_FN(0x004a7950, "$E70(session.obj)", E70_session_lo, fp_lo_static_init)
static void __cdecl E69_session_lo() {}    // ret
PORT_FN(0x004a7960, "$E69(session.obj)", E69_session_lo, fp_lo_static_init)
static void __cdecl E68_session_lo() {}    // ret
PORT_FN(0x004a7970, "$E68(session.obj)", E68_session_lo, fp_lo_static_init)
static void __cdecl E67_session_lo() {}    // ret
PORT_FN(0x004a7980, "$E67(session.obj)", E67_session_lo, fp_lo_static_init)
// public: virtual void * __thiscall Pool<struct SessionData>::`vector deleting destructor'(unsigned int)
static void* __fastcall Pool_SessionData_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0041bac0)(self, 0);    // PoolBase::~PoolBase
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_Pool_SessionData_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x004a7990, "Pool<SessionData>::vector deleting destructor", Pool_SessionData_vector_deleting_destructor_lo, fp_Pool_SessionData_vector_deleting_destructor_lo)

// ---- client.obj ------------------------------------------------------------------------------------------------------
static void __cdecl E2_client_lo() {
    LO_FN(LoVoid_t, 0x004a79c0)();    // jmp: $E1
}
PORT_FN(0x004a79b0, "$E2(client.obj)", E2_client_lo, fp_lo_static_init)
static void __cdecl E1_client_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004a79c0, "$E1(client.obj)", E1_client_lo, fp_lo_static_init)
static void __cdecl E6_client_lo() {
    LO_FN(LoVoid_t, 0x004a79e0)();    // jmp: $E5
}
PORT_FN(0x004a79d0, "$E6(client.obj)", E6_client_lo, fp_lo_static_init)
static void __cdecl E5_client_lo() {
    LO_G32(0x0057d484) = 0x00000000u;
}
PORT_FN(0x004a79e0, "$E5(client.obj)", E5_client_lo, fp_lo_static_init)
static void __cdecl E9_client_lo() {
    LO_FN(LoVoid_t, 0x004a7a00)();    // jmp: $E8
}
PORT_FN(0x004a79f0, "$E9(client.obj)", E9_client_lo, fp_lo_static_init)
static void __cdecl E8_client_lo() {
    LO_G32(0x0057d4a4) = 0x001f001fu;
}
PORT_FN(0x004a7a00, "$E8(client.obj)", E8_client_lo, fp_lo_static_init)
static void __cdecl E12_client_lo() {
    LO_FN(LoVoid_t, 0x004a7a20)();    // jmp: $E11
}
PORT_FN(0x004a7a10, "$E12(client.obj)", E12_client_lo, fp_lo_static_init)
static void __cdecl E11_client_lo() {
    LO_G32(0x0057d494) = 0x03e001e0u;
}
PORT_FN(0x004a7a20, "$E11(client.obj)", E11_client_lo, fp_lo_static_init)
static void __cdecl E15_client_lo() {
    LO_FN(LoVoid_t, 0x004a7a40)();    // jmp: $E14
}
PORT_FN(0x004a7a30, "$E15(client.obj)", E15_client_lo, fp_lo_static_init)
static void __cdecl E14_client_lo() {
    LO_G32(0x0057d4b4) = 0x03ef01efu;
}
PORT_FN(0x004a7a40, "$E14(client.obj)", E14_client_lo, fp_lo_static_init)
static void __cdecl E18_client_lo() {
    LO_FN(LoVoid_t, 0x004a7a60)();    // jmp: $E17
}
PORT_FN(0x004a7a50, "$E18(client.obj)", E18_client_lo, fp_lo_static_init)
static void __cdecl E17_client_lo() {
    LO_G32(0x0057d4ec) = 0x78003c00u;
}
PORT_FN(0x004a7a60, "$E17(client.obj)", E17_client_lo, fp_lo_static_init)
static void __cdecl E21_client_lo() {
    LO_FN(LoVoid_t, 0x004a7a80)();    // jmp: $E20
}
PORT_FN(0x004a7a70, "$E21(client.obj)", E21_client_lo, fp_lo_static_init)
static void __cdecl E20_client_lo() {
    LO_G32(0x0057d4a0) = 0x780f3c0fu;
}
PORT_FN(0x004a7a80, "$E20(client.obj)", E20_client_lo, fp_lo_static_init)
static void __cdecl E24_client_lo() {
    LO_FN(LoVoid_t, 0x004a7aa0)();    // jmp: $E23
}
PORT_FN(0x004a7a90, "$E24(client.obj)", E24_client_lo, fp_lo_static_init)
static void __cdecl E23_client_lo() {
    LO_G32(0x0057d4e0) = 0x7be03de0u;
}
PORT_FN(0x004a7aa0, "$E23(client.obj)", E23_client_lo, fp_lo_static_init)
static void __cdecl E27_client_lo() {
    LO_FN(LoVoid_t, 0x004a7ac0)();    // jmp: $E26
}
PORT_FN(0x004a7ab0, "$E27(client.obj)", E27_client_lo, fp_lo_static_init)
static void __cdecl E26_client_lo() {
    LO_G32(0x0057d49c) = 0x7bef3defu;
}
PORT_FN(0x004a7ac0, "$E26(client.obj)", E26_client_lo, fp_lo_static_init)
static void __cdecl E30_client_lo() {
    LO_FN(LoVoid_t, 0x004a7ae0)();    // jmp: $E29
}
PORT_FN(0x004a7ad0, "$E30(client.obj)", E30_client_lo, fp_lo_static_init)
static void __cdecl E29_client_lo() {
    LO_G32(0x0057d4dc) = 0x42082108u;
}
PORT_FN(0x004a7ae0, "$E29(client.obj)", E29_client_lo, fp_lo_static_init)
static void __cdecl E33_client_lo() {
    LO_FN(LoVoid_t, 0x004a7b00)();    // jmp: $E32
}
PORT_FN(0x004a7af0, "$E33(client.obj)", E33_client_lo, fp_lo_static_init)
static void __cdecl E32_client_lo() {
    LO_G32(0x0057d464) = 0x001f001fu;
}
PORT_FN(0x004a7b00, "$E32(client.obj)", E32_client_lo, fp_lo_static_init)
static void __cdecl E36_client_lo() {
    LO_FN(LoVoid_t, 0x004a7b20)();    // jmp: $E35
}
PORT_FN(0x004a7b10, "$E36(client.obj)", E36_client_lo, fp_lo_static_init)
static void __cdecl E35_client_lo() {
    LO_G32(0x0057d4e8) = 0x07e003e0u;
}
PORT_FN(0x004a7b20, "$E35(client.obj)", E35_client_lo, fp_lo_static_init)
static void __cdecl E39_client_lo() {
    LO_FN(LoVoid_t, 0x004a7b40)();    // jmp: $E38
}
PORT_FN(0x004a7b30, "$E39(client.obj)", E39_client_lo, fp_lo_static_init)
static void __cdecl E38_client_lo() {
    LO_G32(0x0057d490) = 0x07ff03ffu;
}
PORT_FN(0x004a7b40, "$E38(client.obj)", E38_client_lo, fp_lo_static_init)
static void __cdecl E42_client_lo() {
    LO_FN(LoVoid_t, 0x004a7b60)();    // jmp: $E41
}
PORT_FN(0x004a7b50, "$E42(client.obj)", E42_client_lo, fp_lo_static_init)
static void __cdecl E41_client_lo() {
    LO_G32(0x0057d48c) = 0xf8007c00u;
}
PORT_FN(0x004a7b60, "$E41(client.obj)", E41_client_lo, fp_lo_static_init)
static void __cdecl E45_client_lo() {
    LO_FN(LoVoid_t, 0x004a7b80)();    // jmp: $E44
}
PORT_FN(0x004a7b70, "$E45(client.obj)", E45_client_lo, fp_lo_static_init)
static void __cdecl E44_client_lo() {
    LO_G32(0x0057d50c) = 0xf81f7c1fu;
}
PORT_FN(0x004a7b80, "$E44(client.obj)", E44_client_lo, fp_lo_static_init)
static void __cdecl E48_client_lo() {
    LO_FN(LoVoid_t, 0x004a7ba0)();    // jmp: $E47
}
PORT_FN(0x004a7b90, "$E48(client.obj)", E48_client_lo, fp_lo_static_init)
static void __cdecl E47_client_lo() {
    LO_G32(0x0057d4d4) = 0xffe07fe0u;
}
PORT_FN(0x004a7ba0, "$E47(client.obj)", E47_client_lo, fp_lo_static_init)
static void __cdecl E51_client_lo() {
    LO_FN(LoVoid_t, 0x004a7bc0)();    // jmp: $E50
}
PORT_FN(0x004a7bb0, "$E51(client.obj)", E51_client_lo, fp_lo_static_init)
static void __cdecl E50_client_lo() {
    LO_G32(0x0057d498) = 0xffff7fffu;
}
PORT_FN(0x004a7bc0, "$E50(client.obj)", E50_client_lo, fp_lo_static_init)
static void __cdecl E56_client_lo() {
    LO_FN(LoVoid_t, 0x004a7be0)();    // jmp: $E55
}
PORT_FN(0x004a7bd0, "$E56(client.obj)", E56_client_lo, fp_lo_static_init)
static void __cdecl E55_client_lo() {
    LO_G8(0x0057d488) = 0x0f;
}
PORT_FN(0x004a7be0, "$E55(client.obj)", E55_client_lo, fp_lo_static_init)
static void __cdecl E64_client_lo() {}    // ret
PORT_FN(0x004a7e20, "$E64(client.obj)", E64_client_lo, fp_lo_static_init)
static void __cdecl E63_client_lo() {}    // ret
PORT_FN(0x004a7e30, "$E63(client.obj)", E63_client_lo, fp_lo_static_init)
static void __cdecl E62_client_lo() {}    // ret
PORT_FN(0x004a7e40, "$E62(client.obj)", E62_client_lo, fp_lo_static_init)
static void __cdecl E61_client_lo() {}    // ret
PORT_FN(0x004a7e50, "$E61(client.obj)", E61_client_lo, fp_lo_static_init)
static void __cdecl E60_client_lo() {}    // ret
PORT_FN(0x004a7e60, "$E60(client.obj)", E60_client_lo, fp_lo_static_init)
// void __cdecl ASSERT_MSG(int,char const *,...)
static void __cdecl ASSERT_MSG_client_lo(int32_t, void*) {}
static void fp_ASSERT_MSG_client_lo(Footprint& f, int32_t, void*) { f.pure = true; }
PORT_FN(0x004a8060, "ASSERT_MSG(client.obj)", ASSERT_MSG_client_lo, fp_ASSERT_MSG_client_lo)
// private: void __thiscall RaceClient::transPGS_HELLO_PGS_RUNNING(void)
static void __fastcall RaceClient_transPGS_HELLO_PGS_RUNNING_lo(void* self, LoEdx) {}
static void fp_RaceClient_transPGS_HELLO_PGS_RUNNING_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x004aa0f0, "RaceClient::transPGS_HELLO_PGS_RUNNING", RaceClient_transPGS_HELLO_PGS_RUNNING_lo, fp_RaceClient_transPGS_HELLO_PGS_RUNNING_lo)
static void __cdecl E71_client_lo() {}    // ret
PORT_FN(0x004aa4b0, "$E71(client.obj)", E71_client_lo, fp_lo_static_init)
static void __cdecl E70_client_lo() {}    // ret
PORT_FN(0x004aa4c0, "$E70(client.obj)", E70_client_lo, fp_lo_static_init)
static void __cdecl E69_client_lo() {}    // ret
PORT_FN(0x004aa4d0, "$E69(client.obj)", E69_client_lo, fp_lo_static_init)
static void __cdecl E68_client_lo() {}    // ret
PORT_FN(0x004aa4e0, "$E68(client.obj)", E68_client_lo, fp_lo_static_init)
// public: virtual void * __thiscall IRaceClient::`scalar deleting destructor'(unsigned int)
static void* __fastcall IRaceClient_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_G32((uint8_t*)self + 0x0) = 0x004df5c0u;    // the inlined destructor
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_IRaceClient_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x004aa600, "IRaceClient::scalar deleting destructor", IRaceClient_scalar_deleting_destructor_lo, fp_IRaceClient_scalar_deleting_destructor_lo)
// public: virtual void * __thiscall Pool<struct ChatLine>::`scalar deleting destructor'(unsigned int)
static void* __fastcall Pool_ChatLine_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0041bac0)(self, 0);    // PoolBase::~PoolBase
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_Pool_ChatLine_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x004aa660, "Pool<ChatLine>::scalar deleting destructor", Pool_ChatLine_scalar_deleting_destructor_lo, fp_Pool_ChatLine_scalar_deleting_destructor_lo)
// public: virtual void * __thiscall RaceClient::`scalar deleting destructor'(unsigned int)
static void* __fastcall RaceClient_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x004a7fb0)(self, 0);    // RaceClient::~RaceClient
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_RaceClient_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x004aa680, "RaceClient::scalar deleting destructor", RaceClient_scalar_deleting_destructor_lo, fp_RaceClient_scalar_deleting_destructor_lo)

// ---- server.obj ------------------------------------------------------------------------------------------------------
static void __cdecl E2_server_lo() {
    LO_FN(LoVoid_t, 0x004aa6b0)();    // jmp: $E1
}
PORT_FN(0x004aa6a0, "$E2(server.obj)", E2_server_lo, fp_lo_static_init)
static void __cdecl E1_server_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004aa6b0, "$E1(server.obj)", E1_server_lo, fp_lo_static_init)
static void __cdecl E6_server_lo() {
    LO_FN(LoVoid_t, 0x004aa6d0)();    // jmp: $E5
}
PORT_FN(0x004aa6c0, "$E6(server.obj)", E6_server_lo, fp_lo_static_init)
static void __cdecl E5_server_lo() {
    LO_G32(0x0057d520) = 0x00000000u;
}
PORT_FN(0x004aa6d0, "$E5(server.obj)", E5_server_lo, fp_lo_static_init)
static void __cdecl E9_server_lo() {
    LO_FN(LoVoid_t, 0x004aa6f0)();    // jmp: $E8
}
PORT_FN(0x004aa6e0, "$E9(server.obj)", E9_server_lo, fp_lo_static_init)
static void __cdecl E8_server_lo() {
    LO_G32(0x0057d540) = 0x001f001fu;
}
PORT_FN(0x004aa6f0, "$E8(server.obj)", E8_server_lo, fp_lo_static_init)
static void __cdecl E12_server_lo() {
    LO_FN(LoVoid_t, 0x004aa710)();    // jmp: $E11
}
PORT_FN(0x004aa700, "$E12(server.obj)", E12_server_lo, fp_lo_static_init)
static void __cdecl E11_server_lo() {
    LO_G32(0x0057d530) = 0x03e001e0u;
}
PORT_FN(0x004aa710, "$E11(server.obj)", E11_server_lo, fp_lo_static_init)
static void __cdecl E15_server_lo() {
    LO_FN(LoVoid_t, 0x004aa730)();    // jmp: $E14
}
PORT_FN(0x004aa720, "$E15(server.obj)", E15_server_lo, fp_lo_static_init)
static void __cdecl E14_server_lo() {
    LO_G32(0x0057d544) = 0x03ef01efu;
}
PORT_FN(0x004aa730, "$E14(server.obj)", E14_server_lo, fp_lo_static_init)
static void __cdecl E18_server_lo() {
    LO_FN(LoVoid_t, 0x004aa750)();    // jmp: $E17
}
PORT_FN(0x004aa740, "$E18(server.obj)", E18_server_lo, fp_lo_static_init)
static void __cdecl E17_server_lo() {
    LO_G32(0x0057d55c) = 0x78003c00u;
}
PORT_FN(0x004aa750, "$E17(server.obj)", E17_server_lo, fp_lo_static_init)
static void __cdecl E21_server_lo() {
    LO_FN(LoVoid_t, 0x004aa770)();    // jmp: $E20
}
PORT_FN(0x004aa760, "$E21(server.obj)", E21_server_lo, fp_lo_static_init)
static void __cdecl E20_server_lo() {
    LO_G32(0x0057d53c) = 0x780f3c0fu;
}
PORT_FN(0x004aa770, "$E20(server.obj)", E20_server_lo, fp_lo_static_init)
static void __cdecl E24_server_lo() {
    LO_FN(LoVoid_t, 0x004aa790)();    // jmp: $E23
}
PORT_FN(0x004aa780, "$E24(server.obj)", E24_server_lo, fp_lo_static_init)
static void __cdecl E23_server_lo() {
    LO_G32(0x0057d550) = 0x7be03de0u;
}
PORT_FN(0x004aa790, "$E23(server.obj)", E23_server_lo, fp_lo_static_init)
static void __cdecl E27_server_lo() {
    LO_FN(LoVoid_t, 0x004aa7b0)();    // jmp: $E26
}
PORT_FN(0x004aa7a0, "$E27(server.obj)", E27_server_lo, fp_lo_static_init)
static void __cdecl E26_server_lo() {
    LO_G32(0x0057d538) = 0x7bef3defu;
}
PORT_FN(0x004aa7b0, "$E26(server.obj)", E26_server_lo, fp_lo_static_init)
static void __cdecl E30_server_lo() {
    LO_FN(LoVoid_t, 0x004aa7d0)();    // jmp: $E29
}
PORT_FN(0x004aa7c0, "$E30(server.obj)", E30_server_lo, fp_lo_static_init)
static void __cdecl E29_server_lo() {
    LO_G32(0x0057d54c) = 0x42082108u;
}
PORT_FN(0x004aa7d0, "$E29(server.obj)", E29_server_lo, fp_lo_static_init)
static void __cdecl E33_server_lo() {
    LO_FN(LoVoid_t, 0x004aa7f0)();    // jmp: $E32
}
PORT_FN(0x004aa7e0, "$E33(server.obj)", E33_server_lo, fp_lo_static_init)
static void __cdecl E32_server_lo() {
    LO_G32(0x0057d51c) = 0x001f001fu;
}
PORT_FN(0x004aa7f0, "$E32(server.obj)", E32_server_lo, fp_lo_static_init)
static void __cdecl E36_server_lo() {
    LO_FN(LoVoid_t, 0x004aa810)();    // jmp: $E35
}
PORT_FN(0x004aa800, "$E36(server.obj)", E36_server_lo, fp_lo_static_init)
static void __cdecl E35_server_lo() {
    LO_G32(0x0057d558) = 0x07e003e0u;
}
PORT_FN(0x004aa810, "$E35(server.obj)", E35_server_lo, fp_lo_static_init)
static void __cdecl E39_server_lo() {
    LO_FN(LoVoid_t, 0x004aa830)();    // jmp: $E38
}
PORT_FN(0x004aa820, "$E39(server.obj)", E39_server_lo, fp_lo_static_init)
static void __cdecl E38_server_lo() {
    LO_G32(0x0057d52c) = 0x07ff03ffu;
}
PORT_FN(0x004aa830, "$E38(server.obj)", E38_server_lo, fp_lo_static_init)
static void __cdecl E42_server_lo() {
    LO_FN(LoVoid_t, 0x004aa850)();    // jmp: $E41
}
PORT_FN(0x004aa840, "$E42(server.obj)", E42_server_lo, fp_lo_static_init)
static void __cdecl E41_server_lo() {
    LO_G32(0x0057d528) = 0xf8007c00u;
}
PORT_FN(0x004aa850, "$E41(server.obj)", E41_server_lo, fp_lo_static_init)
static void __cdecl E45_server_lo() {
    LO_FN(LoVoid_t, 0x004aa870)();    // jmp: $E44
}
PORT_FN(0x004aa860, "$E45(server.obj)", E45_server_lo, fp_lo_static_init)
static void __cdecl E44_server_lo() {
    LO_G32(0x0057d560) = 0xf81f7c1fu;
}
PORT_FN(0x004aa870, "$E44(server.obj)", E44_server_lo, fp_lo_static_init)
static void __cdecl E48_server_lo() {
    LO_FN(LoVoid_t, 0x004aa890)();    // jmp: $E47
}
PORT_FN(0x004aa880, "$E48(server.obj)", E48_server_lo, fp_lo_static_init)
static void __cdecl E47_server_lo() {
    LO_G32(0x0057d548) = 0xffe07fe0u;
}
PORT_FN(0x004aa890, "$E47(server.obj)", E47_server_lo, fp_lo_static_init)
static void __cdecl E51_server_lo() {
    LO_FN(LoVoid_t, 0x004aa8b0)();    // jmp: $E50
}
PORT_FN(0x004aa8a0, "$E51(server.obj)", E51_server_lo, fp_lo_static_init)
static void __cdecl E50_server_lo() {
    LO_G32(0x0057d534) = 0xffff7fffu;
}
PORT_FN(0x004aa8b0, "$E50(server.obj)", E50_server_lo, fp_lo_static_init)
static void __cdecl E56_server_lo() {
    LO_FN(LoVoid_t, 0x004aa8d0)();    // jmp: $E55
}
PORT_FN(0x004aa8c0, "$E56(server.obj)", E56_server_lo, fp_lo_static_init)
static void __cdecl E55_server_lo() {
    LO_G8(0x0057d524) = 0x0f;
}
PORT_FN(0x004aa8d0, "$E55(server.obj)", E55_server_lo, fp_lo_static_init)
static void __cdecl E60_server_lo() {
    LO_FN(LoVoid_t, 0x004aa8f0)();    // jmp: $E59
}
PORT_FN(0x004aa8e0, "$E60(server.obj)", E60_server_lo, fp_lo_static_init)
static void __cdecl E59_server_lo() {
    LO_G8(0x004fd819) = 0x1f;
    LO_G8(0x004fd81a) = 0x20;
    const uint8_t v1 = LO_G8(0x004df354);
    LO_G8(0x004fd818) = v1;
    LO_G8(0x004fd81e) = 0x08;
    LO_G8(0x004fd820) = 0x08;
    LO_G8(0x004fd81b) = 0x50;
    LO_G8(0x004fd81c) = 0x04;
    LO_G8(0x004fd822) = 0x04;
    LO_G8(0x004fd81d) = 0x28;
    LO_G8(0x004fd823) = 0x08;
    LO_G8(0x004fd825) = 0x08;
    LO_G8(0x004fd81f) = 0x19;
    LO_G8(0x004fd821) = 0x09;
    LO_G8(0x004fd828) = 0x08;
    LO_G8(0x004fd829) = 0x08;
    LO_G8(0x004fd824) = 0x40;
    LO_G8(0x004fd826) = 0x38;
    LO_G8(0x004fd82e) = 0x04;
    LO_G8(0x004fd82a) = 0xde;
    LO_G8(0x004fd82d) = 0xde;
    LO_G8(0x004fd827) = 0x0c;
    LO_G8(0x004fd82b) = 0x24;
    LO_G8(0x004fd82c) = 0x05;
    LO_G8(0x004fd833) = 0x04;
    LO_G8(0x004fd82f) = 0x02;
    LO_G8(0x004fd830) = 0x02;
    LO_G8(0x004fd834) = 0x08;
    LO_G8(0x004fd831) = 0x34;
    LO_G8(0x004fd832) = 0x34;
    LO_G8(0x004fd835) = 0x05;
    LO_G8(0x004fd836) = 0x05;
}
PORT_FN(0x004aa8f0, "$E59(server.obj)", E59_server_lo, fp_lo_static_init)
// void __cdecl ASSERT_MSG(int,char const *,...)
static void __cdecl ASSERT_MSG_server_lo(int32_t, void*) {}
static void fp_ASSERT_MSG_server_lo(Footprint& f, int32_t, void*) { f.pure = true; }
PORT_FN(0x004aadd0, "ASSERT_MSG(server.obj)", ASSERT_MSG_server_lo, fp_ASSERT_MSG_server_lo)
// private: void __thiscall RaceServer::checkRS_RACE(void)
static void __fastcall RaceServer_checkRS_RACE_lo(void* self, LoEdx) {}
static void fp_RaceServer_checkRS_RACE_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x004ac9d0, "RaceServer::checkRS_RACE", RaceServer_checkRS_RACE_lo, fp_RaceServer_checkRS_RACE_lo)
// public: virtual void * __thiscall IRaceServer::`vector deleting destructor'(unsigned int)
static void* __fastcall IRaceServer_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_G32((uint8_t*)self + 0x0) = 0x004df6e0u;    // the inlined destructor
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_IRaceServer_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x004ad100, "IRaceServer::vector deleting destructor", IRaceServer_vector_deleting_destructor_lo, fp_IRaceServer_vector_deleting_destructor_lo)
// public: virtual void * __thiscall RaceServer::`scalar deleting destructor'(unsigned int)
static void* __fastcall RaceServer_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x004aac30)(self, 0);    // RaceServer::~RaceServer
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_RaceServer_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x004ad1e0, "RaceServer::scalar deleting destructor", RaceServer_scalar_deleting_destructor_lo, fp_RaceServer_scalar_deleting_destructor_lo)
// public: __thiscall ServerNetCarInfo::ServerNetCarInfo(void)
static void* __fastcall ServerNetCarInfo_ServerNetCarInfo_lo(void* self, LoEdx) {
    return self;
}
static void fp_ServerNetCarInfo_ServerNetCarInfo_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x004ad200, "ServerNetCarInfo::ServerNetCarInfo", ServerNetCarInfo_ServerNetCarInfo_lo, fp_ServerNetCarInfo_ServerNetCarInfo_lo)

// ---- socket.obj ------------------------------------------------------------------------------------------------------
static void __cdecl E2_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad220)();    // jmp: $E1
}
PORT_FN(0x004ad210, "$E2(socket.obj)", E2_socket_lo, fp_lo_static_init)
static void __cdecl E1_socket_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004ad220, "$E1(socket.obj)", E1_socket_lo, fp_lo_static_init)
static void __cdecl E6_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad240)();    // jmp: $E5
}
PORT_FN(0x004ad230, "$E6(socket.obj)", E6_socket_lo, fp_lo_static_init)
static void __cdecl E5_socket_lo() {
    LO_G32(0x0057d580) = 0x00000000u;
}
PORT_FN(0x004ad240, "$E5(socket.obj)", E5_socket_lo, fp_lo_static_init)
static void __cdecl E9_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad260)();    // jmp: $E8
}
PORT_FN(0x004ad250, "$E9(socket.obj)", E9_socket_lo, fp_lo_static_init)
static void __cdecl E8_socket_lo() {
    LO_G32(0x0057d5b4) = 0x001f001fu;
}
PORT_FN(0x004ad260, "$E8(socket.obj)", E8_socket_lo, fp_lo_static_init)
static void __cdecl E12_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad280)();    // jmp: $E11
}
PORT_FN(0x004ad270, "$E12(socket.obj)", E12_socket_lo, fp_lo_static_init)
static void __cdecl E11_socket_lo() {
    LO_G32(0x0057d590) = 0x03e001e0u;
}
PORT_FN(0x004ad280, "$E11(socket.obj)", E11_socket_lo, fp_lo_static_init)
static void __cdecl E15_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad2a0)();    // jmp: $E14
}
PORT_FN(0x004ad290, "$E15(socket.obj)", E15_socket_lo, fp_lo_static_init)
static void __cdecl E14_socket_lo() {
    LO_G32(0x0057d5b8) = 0x03ef01efu;
}
PORT_FN(0x004ad2a0, "$E14(socket.obj)", E14_socket_lo, fp_lo_static_init)
static void __cdecl E18_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad2c0)();    // jmp: $E17
}
PORT_FN(0x004ad2b0, "$E18(socket.obj)", E18_socket_lo, fp_lo_static_init)
static void __cdecl E17_socket_lo() {
    LO_G32(0x0057d5d4) = 0x78003c00u;
}
PORT_FN(0x004ad2c0, "$E17(socket.obj)", E17_socket_lo, fp_lo_static_init)
static void __cdecl E21_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad2e0)();    // jmp: $E20
}
PORT_FN(0x004ad2d0, "$E21(socket.obj)", E21_socket_lo, fp_lo_static_init)
static void __cdecl E20_socket_lo() {
    LO_G32(0x0057d5b0) = 0x780f3c0fu;
}
PORT_FN(0x004ad2e0, "$E20(socket.obj)", E20_socket_lo, fp_lo_static_init)
static void __cdecl E24_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad300)();    // jmp: $E23
}
PORT_FN(0x004ad2f0, "$E24(socket.obj)", E24_socket_lo, fp_lo_static_init)
static void __cdecl E23_socket_lo() {
    LO_G32(0x0057d5c8) = 0x7be03de0u;
}
PORT_FN(0x004ad300, "$E23(socket.obj)", E23_socket_lo, fp_lo_static_init)
static void __cdecl E27_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad320)();    // jmp: $E26
}
PORT_FN(0x004ad310, "$E27(socket.obj)", E27_socket_lo, fp_lo_static_init)
static void __cdecl E26_socket_lo() {
    LO_G32(0x0057d5ac) = 0x7bef3defu;
}
PORT_FN(0x004ad320, "$E26(socket.obj)", E26_socket_lo, fp_lo_static_init)
static void __cdecl E30_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad340)();    // jmp: $E29
}
PORT_FN(0x004ad330, "$E30(socket.obj)", E30_socket_lo, fp_lo_static_init)
static void __cdecl E29_socket_lo() {
    LO_G32(0x0057d5c4) = 0x42082108u;
}
PORT_FN(0x004ad340, "$E29(socket.obj)", E29_socket_lo, fp_lo_static_init)
static void __cdecl E33_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad360)();    // jmp: $E32
}
PORT_FN(0x004ad350, "$E33(socket.obj)", E33_socket_lo, fp_lo_static_init)
static void __cdecl E32_socket_lo() {
    LO_G32(0x0057d56c) = 0x001f001fu;
}
PORT_FN(0x004ad360, "$E32(socket.obj)", E32_socket_lo, fp_lo_static_init)
static void __cdecl E36_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad380)();    // jmp: $E35
}
PORT_FN(0x004ad370, "$E36(socket.obj)", E36_socket_lo, fp_lo_static_init)
static void __cdecl E35_socket_lo() {
    LO_G32(0x0057d5d0) = 0x07e003e0u;
}
PORT_FN(0x004ad380, "$E35(socket.obj)", E35_socket_lo, fp_lo_static_init)
static void __cdecl E39_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad3a0)();    // jmp: $E38
}
PORT_FN(0x004ad390, "$E39(socket.obj)", E39_socket_lo, fp_lo_static_init)
static void __cdecl E38_socket_lo() {
    LO_G32(0x0057d58c) = 0x07ff03ffu;
}
PORT_FN(0x004ad3a0, "$E38(socket.obj)", E38_socket_lo, fp_lo_static_init)
static void __cdecl E42_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad3c0)();    // jmp: $E41
}
PORT_FN(0x004ad3b0, "$E42(socket.obj)", E42_socket_lo, fp_lo_static_init)
static void __cdecl E41_socket_lo() {
    LO_G32(0x0057d588) = 0xf8007c00u;
}
PORT_FN(0x004ad3c0, "$E41(socket.obj)", E41_socket_lo, fp_lo_static_init)
static void __cdecl E45_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad3e0)();    // jmp: $E44
}
PORT_FN(0x004ad3d0, "$E45(socket.obj)", E45_socket_lo, fp_lo_static_init)
static void __cdecl E44_socket_lo() {
    LO_G32(0x0057d5d8) = 0xf81f7c1fu;
}
PORT_FN(0x004ad3e0, "$E44(socket.obj)", E44_socket_lo, fp_lo_static_init)
static void __cdecl E48_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad400)();    // jmp: $E47
}
PORT_FN(0x004ad3f0, "$E48(socket.obj)", E48_socket_lo, fp_lo_static_init)
static void __cdecl E47_socket_lo() {
    LO_G32(0x0057d5bc) = 0xffe07fe0u;
}
PORT_FN(0x004ad400, "$E47(socket.obj)", E47_socket_lo, fp_lo_static_init)
static void __cdecl E51_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad420)();    // jmp: $E50
}
PORT_FN(0x004ad410, "$E51(socket.obj)", E51_socket_lo, fp_lo_static_init)
static void __cdecl E50_socket_lo() {
    LO_G32(0x0057d598) = 0xffff7fffu;
}
PORT_FN(0x004ad420, "$E50(socket.obj)", E50_socket_lo, fp_lo_static_init)
static void __cdecl E56_socket_lo() {
    LO_FN(LoVoid_t, 0x004ad440)();    // jmp: $E55
}
PORT_FN(0x004ad430, "$E56(socket.obj)", E56_socket_lo, fp_lo_static_init)
static void __cdecl E55_socket_lo() {
    LO_G8(0x0057d584) = 0x0f;
}
PORT_FN(0x004ad440, "$E55(socket.obj)", E55_socket_lo, fp_lo_static_init)

// ---- linechek.obj ----------------------------------------------------------------------------------------------------
static void __cdecl E2_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae780)();    // jmp: $E1
}
PORT_FN(0x004ae770, "$E2(linechek.obj)", E2_linechek_lo, fp_lo_static_init)
static void __cdecl E1_linechek_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004ae780, "$E1(linechek.obj)", E1_linechek_lo, fp_lo_static_init)
static void __cdecl E6_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae7a0)();    // jmp: $E5
}
PORT_FN(0x004ae790, "$E6(linechek.obj)", E6_linechek_lo, fp_lo_static_init)
static void __cdecl E5_linechek_lo() {
    LO_G32(0x0057d5e0) = 0x00000000u;
}
PORT_FN(0x004ae7a0, "$E5(linechek.obj)", E5_linechek_lo, fp_lo_static_init)
static void __cdecl E9_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae7c0)();    // jmp: $E8
}
PORT_FN(0x004ae7b0, "$E9(linechek.obj)", E9_linechek_lo, fp_lo_static_init)
static void __cdecl E8_linechek_lo() {
    LO_G32(0x0057d600) = 0x001f001fu;
}
PORT_FN(0x004ae7c0, "$E8(linechek.obj)", E8_linechek_lo, fp_lo_static_init)
static void __cdecl E12_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae7e0)();    // jmp: $E11
}
PORT_FN(0x004ae7d0, "$E12(linechek.obj)", E12_linechek_lo, fp_lo_static_init)
static void __cdecl E11_linechek_lo() {
    LO_G32(0x0057d5f0) = 0x03e001e0u;
}
PORT_FN(0x004ae7e0, "$E11(linechek.obj)", E11_linechek_lo, fp_lo_static_init)
static void __cdecl E15_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae800)();    // jmp: $E14
}
PORT_FN(0x004ae7f0, "$E15(linechek.obj)", E15_linechek_lo, fp_lo_static_init)
static void __cdecl E14_linechek_lo() {
    LO_G32(0x0057d604) = 0x03ef01efu;
}
PORT_FN(0x004ae800, "$E14(linechek.obj)", E14_linechek_lo, fp_lo_static_init)
static void __cdecl E18_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae820)();    // jmp: $E17
}
PORT_FN(0x004ae810, "$E18(linechek.obj)", E18_linechek_lo, fp_lo_static_init)
static void __cdecl E17_linechek_lo() {
    LO_G32(0x0057d61c) = 0x78003c00u;
}
PORT_FN(0x004ae820, "$E17(linechek.obj)", E17_linechek_lo, fp_lo_static_init)
static void __cdecl E21_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae840)();    // jmp: $E20
}
PORT_FN(0x004ae830, "$E21(linechek.obj)", E21_linechek_lo, fp_lo_static_init)
static void __cdecl E20_linechek_lo() {
    LO_G32(0x0057d5fc) = 0x780f3c0fu;
}
PORT_FN(0x004ae840, "$E20(linechek.obj)", E20_linechek_lo, fp_lo_static_init)
static void __cdecl E24_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae860)();    // jmp: $E23
}
PORT_FN(0x004ae850, "$E24(linechek.obj)", E24_linechek_lo, fp_lo_static_init)
static void __cdecl E23_linechek_lo() {
    LO_G32(0x0057d610) = 0x7be03de0u;
}
PORT_FN(0x004ae860, "$E23(linechek.obj)", E23_linechek_lo, fp_lo_static_init)
static void __cdecl E27_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae880)();    // jmp: $E26
}
PORT_FN(0x004ae870, "$E27(linechek.obj)", E27_linechek_lo, fp_lo_static_init)
static void __cdecl E26_linechek_lo() {
    LO_G32(0x0057d5f8) = 0x7bef3defu;
}
PORT_FN(0x004ae880, "$E26(linechek.obj)", E26_linechek_lo, fp_lo_static_init)
static void __cdecl E30_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae8a0)();    // jmp: $E29
}
PORT_FN(0x004ae890, "$E30(linechek.obj)", E30_linechek_lo, fp_lo_static_init)
static void __cdecl E29_linechek_lo() {
    LO_G32(0x0057d60c) = 0x42082108u;
}
PORT_FN(0x004ae8a0, "$E29(linechek.obj)", E29_linechek_lo, fp_lo_static_init)
static void __cdecl E33_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae8c0)();    // jmp: $E32
}
PORT_FN(0x004ae8b0, "$E33(linechek.obj)", E33_linechek_lo, fp_lo_static_init)
static void __cdecl E32_linechek_lo() {
    LO_G32(0x0057d5dc) = 0x001f001fu;
}
PORT_FN(0x004ae8c0, "$E32(linechek.obj)", E32_linechek_lo, fp_lo_static_init)
static void __cdecl E36_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae8e0)();    // jmp: $E35
}
PORT_FN(0x004ae8d0, "$E36(linechek.obj)", E36_linechek_lo, fp_lo_static_init)
static void __cdecl E35_linechek_lo() {
    LO_G32(0x0057d618) = 0x07e003e0u;
}
PORT_FN(0x004ae8e0, "$E35(linechek.obj)", E35_linechek_lo, fp_lo_static_init)
static void __cdecl E39_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae900)();    // jmp: $E38
}
PORT_FN(0x004ae8f0, "$E39(linechek.obj)", E39_linechek_lo, fp_lo_static_init)
static void __cdecl E38_linechek_lo() {
    LO_G32(0x0057d5ec) = 0x07ff03ffu;
}
PORT_FN(0x004ae900, "$E38(linechek.obj)", E38_linechek_lo, fp_lo_static_init)
static void __cdecl E42_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae920)();    // jmp: $E41
}
PORT_FN(0x004ae910, "$E42(linechek.obj)", E42_linechek_lo, fp_lo_static_init)
static void __cdecl E41_linechek_lo() {
    LO_G32(0x0057d5e8) = 0xf8007c00u;
}
PORT_FN(0x004ae920, "$E41(linechek.obj)", E41_linechek_lo, fp_lo_static_init)
static void __cdecl E45_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae940)();    // jmp: $E44
}
PORT_FN(0x004ae930, "$E45(linechek.obj)", E45_linechek_lo, fp_lo_static_init)
static void __cdecl E44_linechek_lo() {
    LO_G32(0x0057d620) = 0xf81f7c1fu;
}
PORT_FN(0x004ae940, "$E44(linechek.obj)", E44_linechek_lo, fp_lo_static_init)
static void __cdecl E48_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae960)();    // jmp: $E47
}
PORT_FN(0x004ae950, "$E48(linechek.obj)", E48_linechek_lo, fp_lo_static_init)
static void __cdecl E47_linechek_lo() {
    LO_G32(0x0057d608) = 0xffe07fe0u;
}
PORT_FN(0x004ae960, "$E47(linechek.obj)", E47_linechek_lo, fp_lo_static_init)
static void __cdecl E51_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae980)();    // jmp: $E50
}
PORT_FN(0x004ae970, "$E51(linechek.obj)", E51_linechek_lo, fp_lo_static_init)
static void __cdecl E50_linechek_lo() {
    LO_G32(0x0057d5f4) = 0xffff7fffu;
}
PORT_FN(0x004ae980, "$E50(linechek.obj)", E50_linechek_lo, fp_lo_static_init)
static void __cdecl E54_linechek_lo() {
    LO_FN(LoVoid_t, 0x004ae9a0)();    // jmp: $E53
}
PORT_FN(0x004ae990, "$E54(linechek.obj)", E54_linechek_lo, fp_lo_static_init)
static void __cdecl E53_linechek_lo() {
    LO_G8(0x0057d5e4) = 0x0f;
}
PORT_FN(0x004ae9a0, "$E53(linechek.obj)", E53_linechek_lo, fp_lo_static_init)

// ---- tapidbg.obj -----------------------------------------------------------------------------------------------------
static void __cdecl E2_tapidbg_lo() {
    LO_FN(LoVoid_t, 0x004aeca0)();    // jmp: $E1
}
PORT_FN(0x004aec90, "$E2(tapidbg.obj)", E2_tapidbg_lo, fp_lo_static_init)
static void __cdecl E1_tapidbg_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004aeca0, "$E1(tapidbg.obj)", E1_tapidbg_lo, fp_lo_static_init)

// ---- dataport.obj ----------------------------------------------------------------------------------------------------
static void __cdecl E2_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aed30)();    // jmp: $E1
}
PORT_FN(0x004aed20, "$E2(dataport.obj)", E2_dataport_lo, fp_lo_static_init)
static void __cdecl E1_dataport_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004aed30, "$E1(dataport.obj)", E1_dataport_lo, fp_lo_static_init)
static void __cdecl E6_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aed50)();    // jmp: $E5
}
PORT_FN(0x004aed40, "$E6(dataport.obj)", E6_dataport_lo, fp_lo_static_init)
static void __cdecl E5_dataport_lo() {
    LO_G32(0x0057d628) = 0x00000000u;
}
PORT_FN(0x004aed50, "$E5(dataport.obj)", E5_dataport_lo, fp_lo_static_init)
static void __cdecl E9_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aed70)();    // jmp: $E8
}
PORT_FN(0x004aed60, "$E9(dataport.obj)", E9_dataport_lo, fp_lo_static_init)
static void __cdecl E8_dataport_lo() {
    LO_G32(0x0057d648) = 0x001f001fu;
}
PORT_FN(0x004aed70, "$E8(dataport.obj)", E8_dataport_lo, fp_lo_static_init)
static void __cdecl E12_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aed90)();    // jmp: $E11
}
PORT_FN(0x004aed80, "$E12(dataport.obj)", E12_dataport_lo, fp_lo_static_init)
static void __cdecl E11_dataport_lo() {
    LO_G32(0x0057d638) = 0x03e001e0u;
}
PORT_FN(0x004aed90, "$E11(dataport.obj)", E11_dataport_lo, fp_lo_static_init)
static void __cdecl E15_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aedb0)();    // jmp: $E14
}
PORT_FN(0x004aeda0, "$E15(dataport.obj)", E15_dataport_lo, fp_lo_static_init)
static void __cdecl E14_dataport_lo() {
    LO_G32(0x0057d64c) = 0x03ef01efu;
}
PORT_FN(0x004aedb0, "$E14(dataport.obj)", E14_dataport_lo, fp_lo_static_init)
static void __cdecl E18_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aedd0)();    // jmp: $E17
}
PORT_FN(0x004aedc0, "$E18(dataport.obj)", E18_dataport_lo, fp_lo_static_init)
static void __cdecl E17_dataport_lo() {
    LO_G32(0x0057d664) = 0x78003c00u;
}
PORT_FN(0x004aedd0, "$E17(dataport.obj)", E17_dataport_lo, fp_lo_static_init)
static void __cdecl E21_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aedf0)();    // jmp: $E20
}
PORT_FN(0x004aede0, "$E21(dataport.obj)", E21_dataport_lo, fp_lo_static_init)
static void __cdecl E20_dataport_lo() {
    LO_G32(0x0057d644) = 0x780f3c0fu;
}
PORT_FN(0x004aedf0, "$E20(dataport.obj)", E20_dataport_lo, fp_lo_static_init)
static void __cdecl E24_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aee10)();    // jmp: $E23
}
PORT_FN(0x004aee00, "$E24(dataport.obj)", E24_dataport_lo, fp_lo_static_init)
static void __cdecl E23_dataport_lo() {
    LO_G32(0x0057d658) = 0x7be03de0u;
}
PORT_FN(0x004aee10, "$E23(dataport.obj)", E23_dataport_lo, fp_lo_static_init)
static void __cdecl E27_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aee30)();    // jmp: $E26
}
PORT_FN(0x004aee20, "$E27(dataport.obj)", E27_dataport_lo, fp_lo_static_init)
static void __cdecl E26_dataport_lo() {
    LO_G32(0x0057d640) = 0x7bef3defu;
}
PORT_FN(0x004aee30, "$E26(dataport.obj)", E26_dataport_lo, fp_lo_static_init)
static void __cdecl E30_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aee50)();    // jmp: $E29
}
PORT_FN(0x004aee40, "$E30(dataport.obj)", E30_dataport_lo, fp_lo_static_init)
static void __cdecl E29_dataport_lo() {
    LO_G32(0x0057d654) = 0x42082108u;
}
PORT_FN(0x004aee50, "$E29(dataport.obj)", E29_dataport_lo, fp_lo_static_init)
static void __cdecl E33_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aee70)();    // jmp: $E32
}
PORT_FN(0x004aee60, "$E33(dataport.obj)", E33_dataport_lo, fp_lo_static_init)
static void __cdecl E32_dataport_lo() {
    LO_G32(0x0057d624) = 0x001f001fu;
}
PORT_FN(0x004aee70, "$E32(dataport.obj)", E32_dataport_lo, fp_lo_static_init)
static void __cdecl E36_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aee90)();    // jmp: $E35
}
PORT_FN(0x004aee80, "$E36(dataport.obj)", E36_dataport_lo, fp_lo_static_init)
static void __cdecl E35_dataport_lo() {
    LO_G32(0x0057d660) = 0x07e003e0u;
}
PORT_FN(0x004aee90, "$E35(dataport.obj)", E35_dataport_lo, fp_lo_static_init)
static void __cdecl E39_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aeeb0)();    // jmp: $E38
}
PORT_FN(0x004aeea0, "$E39(dataport.obj)", E39_dataport_lo, fp_lo_static_init)
static void __cdecl E38_dataport_lo() {
    LO_G32(0x0057d634) = 0x07ff03ffu;
}
PORT_FN(0x004aeeb0, "$E38(dataport.obj)", E38_dataport_lo, fp_lo_static_init)
static void __cdecl E42_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aeed0)();    // jmp: $E41
}
PORT_FN(0x004aeec0, "$E42(dataport.obj)", E42_dataport_lo, fp_lo_static_init)
static void __cdecl E41_dataport_lo() {
    LO_G32(0x0057d630) = 0xf8007c00u;
}
PORT_FN(0x004aeed0, "$E41(dataport.obj)", E41_dataport_lo, fp_lo_static_init)
static void __cdecl E45_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aeef0)();    // jmp: $E44
}
PORT_FN(0x004aeee0, "$E45(dataport.obj)", E45_dataport_lo, fp_lo_static_init)
static void __cdecl E44_dataport_lo() {
    LO_G32(0x0057d668) = 0xf81f7c1fu;
}
PORT_FN(0x004aeef0, "$E44(dataport.obj)", E44_dataport_lo, fp_lo_static_init)
static void __cdecl E48_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aef10)();    // jmp: $E47
}
PORT_FN(0x004aef00, "$E48(dataport.obj)", E48_dataport_lo, fp_lo_static_init)
static void __cdecl E47_dataport_lo() {
    LO_G32(0x0057d650) = 0xffe07fe0u;
}
PORT_FN(0x004aef10, "$E47(dataport.obj)", E47_dataport_lo, fp_lo_static_init)
static void __cdecl E51_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aef30)();    // jmp: $E50
}
PORT_FN(0x004aef20, "$E51(dataport.obj)", E51_dataport_lo, fp_lo_static_init)
static void __cdecl E50_dataport_lo() {
    LO_G32(0x0057d63c) = 0xffff7fffu;
}
PORT_FN(0x004aef30, "$E50(dataport.obj)", E50_dataport_lo, fp_lo_static_init)
static void __cdecl E56_dataport_lo() {
    LO_FN(LoVoid_t, 0x004aef50)();    // jmp: $E55
}
PORT_FN(0x004aef40, "$E56(dataport.obj)", E56_dataport_lo, fp_lo_static_init)
static void __cdecl E55_dataport_lo() {
    LO_G8(0x0057d62c) = 0x0f;
}
PORT_FN(0x004aef50, "$E55(dataport.obj)", E55_dataport_lo, fp_lo_static_init)
// public: virtual unsigned char __thiscall DataPort::Ok(void)
static uint8_t __fastcall DataPort_Ok_lo(void* self, LoEdx) {
    return 0x01;
}
static void fp_DataPort_Ok_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x004aef80, "DataPort::Ok", DataPort_Ok_lo, fp_DataPort_Ok_lo)
// public: virtual void __thiscall DataPort::Tick(void)
static void __fastcall DataPort_Tick_lo(void* self, LoEdx) {}
static void fp_DataPort_Tick_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x004af120, "DataPort::Tick", DataPort_Tick_lo, fp_DataPort_Tick_lo)
// public: virtual void * __thiscall DataPort::`vector deleting destructor'(unsigned int)
static void* __fastcall DataPort_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x004aef90)(self, 0);    // DataPort::~DataPort
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_DataPort_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x004af510, "DataPort::vector deleting destructor", DataPort_vector_deleting_destructor_lo, fp_DataPort_vector_deleting_destructor_lo)
// public: virtual void * __thiscall Pool<struct ReliablePendingPacket>::`vector deleting destructor'(unsigned int)
static void* __fastcall Pool_ReliablePendingPacket_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0041bac0)(self, 0);    // PoolBase::~PoolBase
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_Pool_ReliablePendingPacket_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x004af530, "Pool<ReliablePendingPacket>::vector deleting destructor", Pool_ReliablePendingPacket_vector_deleting_destructor_lo, fp_Pool_ReliablePendingPacket_vector_deleting_destructor_lo)
// public: virtual void * __thiscall Pool<struct ReliableDataPort::node>::`scalar deleting destructor'(unsigned int)
static void* __fastcall Pool_ReliableDataPort_node_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0041bac0)(self, 0);    // PoolBase::~PoolBase
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_Pool_ReliableDataPort_node_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x004af550, "Pool<ReliableDataPort::node>::scalar deleting destructor", Pool_ReliableDataPort_node_scalar_deleting_destructor_lo, fp_Pool_ReliableDataPort_node_scalar_deleting_destructor_lo)
// public: virtual void * __thiscall ReliableDataPort::`vector deleting destructor'(unsigned int)
static void* __fastcall ReliableDataPort_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x004af1c0)(self, 0);    // ReliableDataPort::~ReliableDataPort
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_ReliableDataPort_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x004af570, "ReliableDataPort::vector deleting destructor", ReliableDataPort_vector_deleting_destructor_lo, fp_ReliableDataPort_vector_deleting_destructor_lo)

// ---- linepkt.obj -----------------------------------------------------------------------------------------------------
static void __cdecl E2_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af5a0)();    // jmp: $E1
}
PORT_FN(0x004af590, "$E2(linepkt.obj)", E2_linepkt_lo, fp_lo_static_init)
static void __cdecl E1_linepkt_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004af5a0, "$E1(linepkt.obj)", E1_linepkt_lo, fp_lo_static_init)
static void __cdecl E6_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af5c0)();    // jmp: $E5
}
PORT_FN(0x004af5b0, "$E6(linepkt.obj)", E6_linepkt_lo, fp_lo_static_init)
static void __cdecl E5_linepkt_lo() {
    LO_G32(0x0057d670) = 0x00000000u;
}
PORT_FN(0x004af5c0, "$E5(linepkt.obj)", E5_linepkt_lo, fp_lo_static_init)
static void __cdecl E9_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af5e0)();    // jmp: $E8
}
PORT_FN(0x004af5d0, "$E9(linepkt.obj)", E9_linepkt_lo, fp_lo_static_init)
static void __cdecl E8_linepkt_lo() {
    LO_G32(0x0057d690) = 0x001f001fu;
}
PORT_FN(0x004af5e0, "$E8(linepkt.obj)", E8_linepkt_lo, fp_lo_static_init)
static void __cdecl E12_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af600)();    // jmp: $E11
}
PORT_FN(0x004af5f0, "$E12(linepkt.obj)", E12_linepkt_lo, fp_lo_static_init)
static void __cdecl E11_linepkt_lo() {
    LO_G32(0x0057d680) = 0x03e001e0u;
}
PORT_FN(0x004af600, "$E11(linepkt.obj)", E11_linepkt_lo, fp_lo_static_init)
static void __cdecl E15_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af620)();    // jmp: $E14
}
PORT_FN(0x004af610, "$E15(linepkt.obj)", E15_linepkt_lo, fp_lo_static_init)
static void __cdecl E14_linepkt_lo() {
    LO_G32(0x0057d694) = 0x03ef01efu;
}
PORT_FN(0x004af620, "$E14(linepkt.obj)", E14_linepkt_lo, fp_lo_static_init)
static void __cdecl E18_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af640)();    // jmp: $E17
}
PORT_FN(0x004af630, "$E18(linepkt.obj)", E18_linepkt_lo, fp_lo_static_init)
static void __cdecl E17_linepkt_lo() {
    LO_G32(0x0057d6ac) = 0x78003c00u;
}
PORT_FN(0x004af640, "$E17(linepkt.obj)", E17_linepkt_lo, fp_lo_static_init)
static void __cdecl E21_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af660)();    // jmp: $E20
}
PORT_FN(0x004af650, "$E21(linepkt.obj)", E21_linepkt_lo, fp_lo_static_init)
static void __cdecl E20_linepkt_lo() {
    LO_G32(0x0057d68c) = 0x780f3c0fu;
}
PORT_FN(0x004af660, "$E20(linepkt.obj)", E20_linepkt_lo, fp_lo_static_init)
static void __cdecl E24_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af680)();    // jmp: $E23
}
PORT_FN(0x004af670, "$E24(linepkt.obj)", E24_linepkt_lo, fp_lo_static_init)
static void __cdecl E23_linepkt_lo() {
    LO_G32(0x0057d6a0) = 0x7be03de0u;
}
PORT_FN(0x004af680, "$E23(linepkt.obj)", E23_linepkt_lo, fp_lo_static_init)
static void __cdecl E27_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af6a0)();    // jmp: $E26
}
PORT_FN(0x004af690, "$E27(linepkt.obj)", E27_linepkt_lo, fp_lo_static_init)
static void __cdecl E26_linepkt_lo() {
    LO_G32(0x0057d688) = 0x7bef3defu;
}
PORT_FN(0x004af6a0, "$E26(linepkt.obj)", E26_linepkt_lo, fp_lo_static_init)
static void __cdecl E30_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af6c0)();    // jmp: $E29
}
PORT_FN(0x004af6b0, "$E30(linepkt.obj)", E30_linepkt_lo, fp_lo_static_init)
static void __cdecl E29_linepkt_lo() {
    LO_G32(0x0057d69c) = 0x42082108u;
}
PORT_FN(0x004af6c0, "$E29(linepkt.obj)", E29_linepkt_lo, fp_lo_static_init)
static void __cdecl E33_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af6e0)();    // jmp: $E32
}
PORT_FN(0x004af6d0, "$E33(linepkt.obj)", E33_linepkt_lo, fp_lo_static_init)
static void __cdecl E32_linepkt_lo() {
    LO_G32(0x0057d66c) = 0x001f001fu;
}
PORT_FN(0x004af6e0, "$E32(linepkt.obj)", E32_linepkt_lo, fp_lo_static_init)
static void __cdecl E36_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af700)();    // jmp: $E35
}
PORT_FN(0x004af6f0, "$E36(linepkt.obj)", E36_linepkt_lo, fp_lo_static_init)
static void __cdecl E35_linepkt_lo() {
    LO_G32(0x0057d6a8) = 0x07e003e0u;
}
PORT_FN(0x004af700, "$E35(linepkt.obj)", E35_linepkt_lo, fp_lo_static_init)
static void __cdecl E39_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af720)();    // jmp: $E38
}
PORT_FN(0x004af710, "$E39(linepkt.obj)", E39_linepkt_lo, fp_lo_static_init)
static void __cdecl E38_linepkt_lo() {
    LO_G32(0x0057d67c) = 0x07ff03ffu;
}
PORT_FN(0x004af720, "$E38(linepkt.obj)", E38_linepkt_lo, fp_lo_static_init)
static void __cdecl E42_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af740)();    // jmp: $E41
}
PORT_FN(0x004af730, "$E42(linepkt.obj)", E42_linepkt_lo, fp_lo_static_init)
static void __cdecl E41_linepkt_lo() {
    LO_G32(0x0057d678) = 0xf8007c00u;
}
PORT_FN(0x004af740, "$E41(linepkt.obj)", E41_linepkt_lo, fp_lo_static_init)
static void __cdecl E45_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af760)();    // jmp: $E44
}
PORT_FN(0x004af750, "$E45(linepkt.obj)", E45_linepkt_lo, fp_lo_static_init)
static void __cdecl E44_linepkt_lo() {
    LO_G32(0x0057d6b0) = 0xf81f7c1fu;
}
PORT_FN(0x004af760, "$E44(linepkt.obj)", E44_linepkt_lo, fp_lo_static_init)
static void __cdecl E48_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af780)();    // jmp: $E47
}
PORT_FN(0x004af770, "$E48(linepkt.obj)", E48_linepkt_lo, fp_lo_static_init)
static void __cdecl E47_linepkt_lo() {
    LO_G32(0x0057d698) = 0xffe07fe0u;
}
PORT_FN(0x004af780, "$E47(linepkt.obj)", E47_linepkt_lo, fp_lo_static_init)
static void __cdecl E51_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af7a0)();    // jmp: $E50
}
PORT_FN(0x004af790, "$E51(linepkt.obj)", E51_linepkt_lo, fp_lo_static_init)
static void __cdecl E50_linepkt_lo() {
    LO_G32(0x0057d684) = 0xffff7fffu;
}
PORT_FN(0x004af7a0, "$E50(linepkt.obj)", E50_linepkt_lo, fp_lo_static_init)
static void __cdecl E54_linepkt_lo() {
    LO_FN(LoVoid_t, 0x004af7c0)();    // jmp: $E53
}
PORT_FN(0x004af7b0, "$E54(linepkt.obj)", E54_linepkt_lo, fp_lo_static_init)
static void __cdecl E53_linepkt_lo() {
    LO_G8(0x0057d674) = 0x0f;
}
PORT_FN(0x004af7c0, "$E53(linepkt.obj)", E53_linepkt_lo, fp_lo_static_init)

// ---- datamod.obj -----------------------------------------------------------------------------------------------------
static void __cdecl E2_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afa40)();    // jmp: $E1
}
PORT_FN(0x004afa30, "$E2(datamod.obj)", E2_datamod_lo, fp_lo_static_init)
static void __cdecl E1_datamod_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004afa40, "$E1(datamod.obj)", E1_datamod_lo, fp_lo_static_init)
static void __cdecl E6_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afa60)();    // jmp: $E5
}
PORT_FN(0x004afa50, "$E6(datamod.obj)", E6_datamod_lo, fp_lo_static_init)
static void __cdecl E5_datamod_lo() {
    LO_G32(0x0057d6b8) = 0x00000000u;
}
PORT_FN(0x004afa60, "$E5(datamod.obj)", E5_datamod_lo, fp_lo_static_init)
static void __cdecl E9_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afa80)();    // jmp: $E8
}
PORT_FN(0x004afa70, "$E9(datamod.obj)", E9_datamod_lo, fp_lo_static_init)
static void __cdecl E8_datamod_lo() {
    LO_G32(0x0057d6d8) = 0x001f001fu;
}
PORT_FN(0x004afa80, "$E8(datamod.obj)", E8_datamod_lo, fp_lo_static_init)
static void __cdecl E12_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afaa0)();    // jmp: $E11
}
PORT_FN(0x004afa90, "$E12(datamod.obj)", E12_datamod_lo, fp_lo_static_init)
static void __cdecl E11_datamod_lo() {
    LO_G32(0x0057d6c8) = 0x03e001e0u;
}
PORT_FN(0x004afaa0, "$E11(datamod.obj)", E11_datamod_lo, fp_lo_static_init)
static void __cdecl E15_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afac0)();    // jmp: $E14
}
PORT_FN(0x004afab0, "$E15(datamod.obj)", E15_datamod_lo, fp_lo_static_init)
static void __cdecl E14_datamod_lo() {
    LO_G32(0x0057d6dc) = 0x03ef01efu;
}
PORT_FN(0x004afac0, "$E14(datamod.obj)", E14_datamod_lo, fp_lo_static_init)
static void __cdecl E18_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afae0)();    // jmp: $E17
}
PORT_FN(0x004afad0, "$E18(datamod.obj)", E18_datamod_lo, fp_lo_static_init)
static void __cdecl E17_datamod_lo() {
    LO_G32(0x0057d6f4) = 0x78003c00u;
}
PORT_FN(0x004afae0, "$E17(datamod.obj)", E17_datamod_lo, fp_lo_static_init)
static void __cdecl E21_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afb00)();    // jmp: $E20
}
PORT_FN(0x004afaf0, "$E21(datamod.obj)", E21_datamod_lo, fp_lo_static_init)
static void __cdecl E20_datamod_lo() {
    LO_G32(0x0057d6d4) = 0x780f3c0fu;
}
PORT_FN(0x004afb00, "$E20(datamod.obj)", E20_datamod_lo, fp_lo_static_init)
static void __cdecl E24_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afb20)();    // jmp: $E23
}
PORT_FN(0x004afb10, "$E24(datamod.obj)", E24_datamod_lo, fp_lo_static_init)
static void __cdecl E23_datamod_lo() {
    LO_G32(0x0057d6e8) = 0x7be03de0u;
}
PORT_FN(0x004afb20, "$E23(datamod.obj)", E23_datamod_lo, fp_lo_static_init)
static void __cdecl E27_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afb40)();    // jmp: $E26
}
PORT_FN(0x004afb30, "$E27(datamod.obj)", E27_datamod_lo, fp_lo_static_init)
static void __cdecl E26_datamod_lo() {
    LO_G32(0x0057d6d0) = 0x7bef3defu;
}
PORT_FN(0x004afb40, "$E26(datamod.obj)", E26_datamod_lo, fp_lo_static_init)
static void __cdecl E30_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afb60)();    // jmp: $E29
}
PORT_FN(0x004afb50, "$E30(datamod.obj)", E30_datamod_lo, fp_lo_static_init)
static void __cdecl E29_datamod_lo() {
    LO_G32(0x0057d6e4) = 0x42082108u;
}
PORT_FN(0x004afb60, "$E29(datamod.obj)", E29_datamod_lo, fp_lo_static_init)
static void __cdecl E33_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afb80)();    // jmp: $E32
}
PORT_FN(0x004afb70, "$E33(datamod.obj)", E33_datamod_lo, fp_lo_static_init)
static void __cdecl E32_datamod_lo() {
    LO_G32(0x0057d6b4) = 0x001f001fu;
}
PORT_FN(0x004afb80, "$E32(datamod.obj)", E32_datamod_lo, fp_lo_static_init)
static void __cdecl E36_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afba0)();    // jmp: $E35
}
PORT_FN(0x004afb90, "$E36(datamod.obj)", E36_datamod_lo, fp_lo_static_init)
static void __cdecl E35_datamod_lo() {
    LO_G32(0x0057d6f0) = 0x07e003e0u;
}
PORT_FN(0x004afba0, "$E35(datamod.obj)", E35_datamod_lo, fp_lo_static_init)
static void __cdecl E39_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afbc0)();    // jmp: $E38
}
PORT_FN(0x004afbb0, "$E39(datamod.obj)", E39_datamod_lo, fp_lo_static_init)
static void __cdecl E38_datamod_lo() {
    LO_G32(0x0057d6c4) = 0x07ff03ffu;
}
PORT_FN(0x004afbc0, "$E38(datamod.obj)", E38_datamod_lo, fp_lo_static_init)
static void __cdecl E42_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afbe0)();    // jmp: $E41
}
PORT_FN(0x004afbd0, "$E42(datamod.obj)", E42_datamod_lo, fp_lo_static_init)
static void __cdecl E41_datamod_lo() {
    LO_G32(0x0057d6c0) = 0xf8007c00u;
}
PORT_FN(0x004afbe0, "$E41(datamod.obj)", E41_datamod_lo, fp_lo_static_init)
static void __cdecl E45_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afc00)();    // jmp: $E44
}
PORT_FN(0x004afbf0, "$E45(datamod.obj)", E45_datamod_lo, fp_lo_static_init)
static void __cdecl E44_datamod_lo() {
    LO_G32(0x0057d6f8) = 0xf81f7c1fu;
}
PORT_FN(0x004afc00, "$E44(datamod.obj)", E44_datamod_lo, fp_lo_static_init)
static void __cdecl E48_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afc20)();    // jmp: $E47
}
PORT_FN(0x004afc10, "$E48(datamod.obj)", E48_datamod_lo, fp_lo_static_init)
static void __cdecl E47_datamod_lo() {
    LO_G32(0x0057d6e0) = 0xffe07fe0u;
}
PORT_FN(0x004afc20, "$E47(datamod.obj)", E47_datamod_lo, fp_lo_static_init)
static void __cdecl E51_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afc40)();    // jmp: $E50
}
PORT_FN(0x004afc30, "$E51(datamod.obj)", E51_datamod_lo, fp_lo_static_init)
static void __cdecl E50_datamod_lo() {
    LO_G32(0x0057d6cc) = 0xffff7fffu;
}
PORT_FN(0x004afc40, "$E50(datamod.obj)", E50_datamod_lo, fp_lo_static_init)
static void __cdecl E56_datamod_lo() {
    LO_FN(LoVoid_t, 0x004afc60)();    // jmp: $E55
}
PORT_FN(0x004afc50, "$E56(datamod.obj)", E56_datamod_lo, fp_lo_static_init)
static void __cdecl E55_datamod_lo() {
    LO_G8(0x0057d6bc) = 0x0f;
}
PORT_FN(0x004afc60, "$E55(datamod.obj)", E55_datamod_lo, fp_lo_static_init)

// ---- hostent.obj -----------------------------------------------------------------------------------------------------
static void __cdecl E2_hostent_lo() {
    LO_FN(LoVoid_t, 0x004afdb0)();    // jmp: $E1
}
PORT_FN(0x004afda0, "$E2(hostent.obj)", E2_hostent_lo, fp_lo_static_init)
static void __cdecl E1_hostent_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004afdb0, "$E1(hostent.obj)", E1_hostent_lo, fp_lo_static_init)
static void __cdecl E6_hostent_lo() {
    LO_FN(LoVoid_t, 0x004afdd0)();    // jmp: $E5
}
PORT_FN(0x004afdc0, "$E6(hostent.obj)", E6_hostent_lo, fp_lo_static_init)
static void __cdecl E5_hostent_lo() {
    LO_G32(0x0057d704) = 0x00000000u;
}
PORT_FN(0x004afdd0, "$E5(hostent.obj)", E5_hostent_lo, fp_lo_static_init)
static void __cdecl E9_hostent_lo() {
    LO_FN(LoVoid_t, 0x004afdf0)();    // jmp: $E8
}
PORT_FN(0x004afde0, "$E9(hostent.obj)", E9_hostent_lo, fp_lo_static_init)
static void __cdecl E8_hostent_lo() {
    LO_G32(0x0057d72c) = 0x001f001fu;
}
PORT_FN(0x004afdf0, "$E8(hostent.obj)", E8_hostent_lo, fp_lo_static_init)
static void __cdecl E12_hostent_lo() {
    LO_FN(LoVoid_t, 0x004afe10)();    // jmp: $E11
}
PORT_FN(0x004afe00, "$E12(hostent.obj)", E12_hostent_lo, fp_lo_static_init)
static void __cdecl E11_hostent_lo() {
    LO_G32(0x0057d714) = 0x03e001e0u;
}
PORT_FN(0x004afe10, "$E11(hostent.obj)", E11_hostent_lo, fp_lo_static_init)
static void __cdecl E15_hostent_lo() {
    LO_FN(LoVoid_t, 0x004afe30)();    // jmp: $E14
}
PORT_FN(0x004afe20, "$E15(hostent.obj)", E15_hostent_lo, fp_lo_static_init)
static void __cdecl E14_hostent_lo() {
    LO_G32(0x0057d730) = 0x03ef01efu;
}
PORT_FN(0x004afe30, "$E14(hostent.obj)", E14_hostent_lo, fp_lo_static_init)
static void __cdecl E18_hostent_lo() {
    LO_FN(LoVoid_t, 0x004afe50)();    // jmp: $E17
}
PORT_FN(0x004afe40, "$E18(hostent.obj)", E18_hostent_lo, fp_lo_static_init)
static void __cdecl E17_hostent_lo() {
    LO_G32(0x0057d748) = 0x78003c00u;
}
PORT_FN(0x004afe50, "$E17(hostent.obj)", E17_hostent_lo, fp_lo_static_init)
static void __cdecl E21_hostent_lo() {
    LO_FN(LoVoid_t, 0x004afe70)();    // jmp: $E20
}
PORT_FN(0x004afe60, "$E21(hostent.obj)", E21_hostent_lo, fp_lo_static_init)
static void __cdecl E20_hostent_lo() {
    LO_G32(0x0057d728) = 0x780f3c0fu;
}
PORT_FN(0x004afe70, "$E20(hostent.obj)", E20_hostent_lo, fp_lo_static_init)
static void __cdecl E24_hostent_lo() {
    LO_FN(LoVoid_t, 0x004afe90)();    // jmp: $E23
}
PORT_FN(0x004afe80, "$E24(hostent.obj)", E24_hostent_lo, fp_lo_static_init)
static void __cdecl E23_hostent_lo() {
    LO_G32(0x0057d73c) = 0x7be03de0u;
}
PORT_FN(0x004afe90, "$E23(hostent.obj)", E23_hostent_lo, fp_lo_static_init)
static void __cdecl E27_hostent_lo() {
    LO_FN(LoVoid_t, 0x004afeb0)();    // jmp: $E26
}
PORT_FN(0x004afea0, "$E27(hostent.obj)", E27_hostent_lo, fp_lo_static_init)
static void __cdecl E26_hostent_lo() {
    LO_G32(0x0057d724) = 0x7bef3defu;
}
PORT_FN(0x004afeb0, "$E26(hostent.obj)", E26_hostent_lo, fp_lo_static_init)
static void __cdecl E30_hostent_lo() {
    LO_FN(LoVoid_t, 0x004afed0)();    // jmp: $E29
}
PORT_FN(0x004afec0, "$E30(hostent.obj)", E30_hostent_lo, fp_lo_static_init)
static void __cdecl E29_hostent_lo() {
    LO_G32(0x0057d738) = 0x42082108u;
}
PORT_FN(0x004afed0, "$E29(hostent.obj)", E29_hostent_lo, fp_lo_static_init)
static void __cdecl E33_hostent_lo() {
    LO_FN(LoVoid_t, 0x004afef0)();    // jmp: $E32
}
PORT_FN(0x004afee0, "$E33(hostent.obj)", E33_hostent_lo, fp_lo_static_init)
static void __cdecl E32_hostent_lo() {
    LO_G32(0x0057d700) = 0x001f001fu;
}
PORT_FN(0x004afef0, "$E32(hostent.obj)", E32_hostent_lo, fp_lo_static_init)
static void __cdecl E36_hostent_lo() {
    LO_FN(LoVoid_t, 0x004aff10)();    // jmp: $E35
}
PORT_FN(0x004aff00, "$E36(hostent.obj)", E36_hostent_lo, fp_lo_static_init)
static void __cdecl E35_hostent_lo() {
    LO_G32(0x0057d744) = 0x07e003e0u;
}
PORT_FN(0x004aff10, "$E35(hostent.obj)", E35_hostent_lo, fp_lo_static_init)
static void __cdecl E39_hostent_lo() {
    LO_FN(LoVoid_t, 0x004aff30)();    // jmp: $E38
}
PORT_FN(0x004aff20, "$E39(hostent.obj)", E39_hostent_lo, fp_lo_static_init)
static void __cdecl E38_hostent_lo() {
    LO_G32(0x0057d710) = 0x07ff03ffu;
}
PORT_FN(0x004aff30, "$E38(hostent.obj)", E38_hostent_lo, fp_lo_static_init)
static void __cdecl E42_hostent_lo() {
    LO_FN(LoVoid_t, 0x004aff50)();    // jmp: $E41
}
PORT_FN(0x004aff40, "$E42(hostent.obj)", E42_hostent_lo, fp_lo_static_init)
static void __cdecl E41_hostent_lo() {
    LO_G32(0x0057d70c) = 0xf8007c00u;
}
PORT_FN(0x004aff50, "$E41(hostent.obj)", E41_hostent_lo, fp_lo_static_init)
static void __cdecl E45_hostent_lo() {
    LO_FN(LoVoid_t, 0x004aff70)();    // jmp: $E44
}
PORT_FN(0x004aff60, "$E45(hostent.obj)", E45_hostent_lo, fp_lo_static_init)
static void __cdecl E44_hostent_lo() {
    LO_G32(0x0057d74c) = 0xf81f7c1fu;
}
PORT_FN(0x004aff70, "$E44(hostent.obj)", E44_hostent_lo, fp_lo_static_init)
static void __cdecl E48_hostent_lo() {
    LO_FN(LoVoid_t, 0x004aff90)();    // jmp: $E47
}
PORT_FN(0x004aff80, "$E48(hostent.obj)", E48_hostent_lo, fp_lo_static_init)
static void __cdecl E47_hostent_lo() {
    LO_G32(0x0057d734) = 0xffe07fe0u;
}
PORT_FN(0x004aff90, "$E47(hostent.obj)", E47_hostent_lo, fp_lo_static_init)
static void __cdecl E51_hostent_lo() {
    LO_FN(LoVoid_t, 0x004affb0)();    // jmp: $E50
}
PORT_FN(0x004affa0, "$E51(hostent.obj)", E51_hostent_lo, fp_lo_static_init)
static void __cdecl E50_hostent_lo() {
    LO_G32(0x0057d720) = 0xffff7fffu;
}
PORT_FN(0x004affb0, "$E50(hostent.obj)", E50_hostent_lo, fp_lo_static_init)
static void __cdecl E56_hostent_lo() {
    LO_FN(LoVoid_t, 0x004affd0)();    // jmp: $E55
}
PORT_FN(0x004affc0, "$E56(hostent.obj)", E56_hostent_lo, fp_lo_static_init)
static void __cdecl E55_hostent_lo() {
    LO_G8(0x0057d708) = 0x0f;
}
PORT_FN(0x004affd0, "$E55(hostent.obj)", E55_hostent_lo, fp_lo_static_init)
// void __cdecl ASSERT_MSG(int,char const *,...)
static void __cdecl ASSERT_MSG_hostent_lo(int32_t, void*) {}
static void fp_ASSERT_MSG_hostent_lo(Footprint& f, int32_t, void*) { f.pure = true; }
PORT_FN(0x004b0190, "ASSERT_MSG(hostent.obj)", ASSERT_MSG_hostent_lo, fp_ASSERT_MSG_hostent_lo)
// void __cdecl FOOD(char const *,...)
static void __cdecl FOOD_lo(void*) {}
static void fp_FOOD_lo(Footprint& f, void*) { f.pure = true; }
PORT_FN(0x004b0800, "FOOD", FOOD_lo, fp_FOOD_lo)

}  // namespace
