// root_leftover.cpp -- generated by tools/gen_leftovers.py --lib root -- don't edit
//
// M3 UI stage, step U3: the $E static initialisers of all fourteen root object files (library
// `root`, game.obj's included), and the stubs of dash.obj, gxdash.obj, countdwn.obj, escape.obj,
// splash.obj and hack.obj,
// rewritten from their exact v1.0 instruction bytes (tools/gen_leftovers.py says how each shape reads). The rest of the
// library is written by hand (hook/root_*.cpp); test/world_root_hud.cpp checks every one against its original. Faithful (docs/PORTING.md):
// stores through volatile at the original's width, in its order; calls to the game by their v1.0 address (a
// __thiscall as __fastcall with an unused edx), so what runs there -- the original or its hooked rewrite -- is what
// the original would have called.
//
// Counts by shape: $E ret 91, $E jmp 260, $E jmp (constructor) 1, $E stores 182, $E constructor 49, ret 5; 588 in all
//
// The $E static initialisers run once, from the CRT's _initterm: replay_only. A tail jump (`jmp T`) stays a call to T
// by address. The stubs read and write nothing (pure); the deleting destructors free memory (replay_only).
#include <stdint.h>
#include "port.h"

// file-local, so a harness can include it beside krn_leftover.cpp
namespace {
typedef int LoEdx;                                  // the unused edx of a __thiscall received as __fastcall
#define LO_G8(a) (*(volatile uint8_t*)(uintptr_t)(a))
#define LO_G32(a) (*(volatile uint32_t*)(uintptr_t)(a))
#define LO_FN(T, a) ((T)(uintptr_t)(a))
typedef void(__cdecl* LoVoid_t)();
typedef void(__cdecl* LoPtr_t)(void*);
typedef void*(__fastcall* LoCtor0_t)(void*, LoEdx);
typedef void*(__fastcall* LoCtor1_t)(void*, LoEdx, uint32_t);
typedef void*(__fastcall* LoCtor2_t)(void*, LoEdx, uint32_t, uint32_t);

static void fp_lo_static_init(Footprint& f) { f.replay_only = "a static initialiser (runs once, from the CRT's _initterm)"; }


// ---- main.obj --------------------------------------------------------------------------------------------------------
static void __cdecl E2_main_lo() {
    LO_FN(LoVoid_t, 0x00401010)();    // jmp: $E1
}
PORT_FN(0x00401000, "$E2(main.obj)", E2_main_lo, fp_lo_static_init)
static void __cdecl E1_main_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x00401010, "$E1(main.obj)", E1_main_lo, fp_lo_static_init)
static void __cdecl E6_main_lo() {
    LO_FN(LoVoid_t, 0x00401030)();    // jmp: $E5
}
PORT_FN(0x00401020, "$E6(main.obj)", E6_main_lo, fp_lo_static_init)
static void __cdecl E5_main_lo() {
    LO_G32(0x00503fe4) = 0x00000000u;
}
PORT_FN(0x00401030, "$E5(main.obj)", E5_main_lo, fp_lo_static_init)
static void __cdecl E9_main_lo() {
    LO_FN(LoVoid_t, 0x00401050)();    // jmp: $E8
}
PORT_FN(0x00401040, "$E9(main.obj)", E9_main_lo, fp_lo_static_init)
static void __cdecl E8_main_lo() {
    LO_G32(0x00504030) = 0x001f001fu;
}
PORT_FN(0x00401050, "$E8(main.obj)", E8_main_lo, fp_lo_static_init)
static void __cdecl E12_main_lo() {
    LO_FN(LoVoid_t, 0x00401070)();    // jmp: $E11
}
PORT_FN(0x00401060, "$E12(main.obj)", E12_main_lo, fp_lo_static_init)
static void __cdecl E11_main_lo() {
    LO_G32(0x00503ff4) = 0x03e001e0u;
}
PORT_FN(0x00401070, "$E11(main.obj)", E11_main_lo, fp_lo_static_init)
static void __cdecl E15_main_lo() {
    LO_FN(LoVoid_t, 0x00401090)();    // jmp: $E14
}
PORT_FN(0x00401080, "$E15(main.obj)", E15_main_lo, fp_lo_static_init)
static void __cdecl E14_main_lo() {
    LO_G32(0x00504090) = 0x03ef01efu;
}
PORT_FN(0x00401090, "$E14(main.obj)", E14_main_lo, fp_lo_static_init)
static void __cdecl E18_main_lo() {
    LO_FN(LoVoid_t, 0x004010b0)();    // jmp: $E17
}
PORT_FN(0x004010a0, "$E18(main.obj)", E18_main_lo, fp_lo_static_init)
static void __cdecl E17_main_lo() {
    LO_G32(0x005040b0) = 0x78003c00u;
}
PORT_FN(0x004010b0, "$E17(main.obj)", E17_main_lo, fp_lo_static_init)
static void __cdecl E21_main_lo() {
    LO_FN(LoVoid_t, 0x004010d0)();    // jmp: $E20
}
PORT_FN(0x004010c0, "$E21(main.obj)", E21_main_lo, fp_lo_static_init)
static void __cdecl E20_main_lo() {
    LO_G32(0x0050402c) = 0x780f3c0fu;
}
PORT_FN(0x004010d0, "$E20(main.obj)", E20_main_lo, fp_lo_static_init)
static void __cdecl E24_main_lo() {
    LO_FN(LoVoid_t, 0x004010f0)();    // jmp: $E23
}
PORT_FN(0x004010e0, "$E24(main.obj)", E24_main_lo, fp_lo_static_init)
static void __cdecl E23_main_lo() {
    LO_G32(0x005040a4) = 0x7be03de0u;
}
PORT_FN(0x004010f0, "$E23(main.obj)", E23_main_lo, fp_lo_static_init)
static void __cdecl E27_main_lo() {
    LO_FN(LoVoid_t, 0x00401110)();    // jmp: $E26
}
PORT_FN(0x00401100, "$E27(main.obj)", E27_main_lo, fp_lo_static_init)
static void __cdecl E26_main_lo() {
    LO_G32(0x00504028) = 0x7bef3defu;
}
PORT_FN(0x00401110, "$E26(main.obj)", E26_main_lo, fp_lo_static_init)
static void __cdecl E30_main_lo() {
    LO_FN(LoVoid_t, 0x00401130)();    // jmp: $E29
}
PORT_FN(0x00401120, "$E30(main.obj)", E30_main_lo, fp_lo_static_init)
static void __cdecl E29_main_lo() {
    LO_G32(0x005040a0) = 0x42082108u;
}
PORT_FN(0x00401130, "$E29(main.obj)", E29_main_lo, fp_lo_static_init)
static void __cdecl E33_main_lo() {
    LO_FN(LoVoid_t, 0x00401150)();    // jmp: $E32
}
PORT_FN(0x00401140, "$E33(main.obj)", E33_main_lo, fp_lo_static_init)
static void __cdecl E32_main_lo() {
    LO_G32(0x00503fd0) = 0x001f001fu;
}
PORT_FN(0x00401150, "$E32(main.obj)", E32_main_lo, fp_lo_static_init)
static void __cdecl E36_main_lo() {
    LO_FN(LoVoid_t, 0x00401170)();    // jmp: $E35
}
PORT_FN(0x00401160, "$E36(main.obj)", E36_main_lo, fp_lo_static_init)
static void __cdecl E35_main_lo() {
    LO_G32(0x005040ac) = 0x07e003e0u;
}
PORT_FN(0x00401170, "$E35(main.obj)", E35_main_lo, fp_lo_static_init)
static void __cdecl E39_main_lo() {
    LO_FN(LoVoid_t, 0x00401190)();    // jmp: $E38
}
PORT_FN(0x00401180, "$E39(main.obj)", E39_main_lo, fp_lo_static_init)
static void __cdecl E38_main_lo() {
    LO_G32(0x00503ff0) = 0x07ff03ffu;
}
PORT_FN(0x00401190, "$E38(main.obj)", E38_main_lo, fp_lo_static_init)
static void __cdecl E42_main_lo() {
    LO_FN(LoVoid_t, 0x004011b0)();    // jmp: $E41
}
PORT_FN(0x004011a0, "$E42(main.obj)", E42_main_lo, fp_lo_static_init)
static void __cdecl E41_main_lo() {
    LO_G32(0x00503fec) = 0xf8007c00u;
}
PORT_FN(0x004011b0, "$E41(main.obj)", E41_main_lo, fp_lo_static_init)
static void __cdecl E45_main_lo() {
    LO_FN(LoVoid_t, 0x004011d0)();    // jmp: $E44
}
PORT_FN(0x004011c0, "$E45(main.obj)", E45_main_lo, fp_lo_static_init)
static void __cdecl E44_main_lo() {
    LO_G32(0x005040b4) = 0xf81f7c1fu;
}
PORT_FN(0x004011d0, "$E44(main.obj)", E44_main_lo, fp_lo_static_init)
static void __cdecl E48_main_lo() {
    LO_FN(LoVoid_t, 0x004011f0)();    // jmp: $E47
}
PORT_FN(0x004011e0, "$E48(main.obj)", E48_main_lo, fp_lo_static_init)
static void __cdecl E47_main_lo() {
    LO_G32(0x00504098) = 0xffe07fe0u;
}
PORT_FN(0x004011f0, "$E47(main.obj)", E47_main_lo, fp_lo_static_init)
static void __cdecl E51_main_lo() {
    LO_FN(LoVoid_t, 0x00401210)();    // jmp: $E50
}
PORT_FN(0x00401200, "$E51(main.obj)", E51_main_lo, fp_lo_static_init)
static void __cdecl E50_main_lo() {
    LO_G32(0x00504024) = 0xffff7fffu;
}
PORT_FN(0x00401210, "$E50(main.obj)", E50_main_lo, fp_lo_static_init)
static void __cdecl E56_main_lo() {
    LO_FN(LoVoid_t, 0x00401230)();    // jmp: $E55
}
PORT_FN(0x00401220, "$E56(main.obj)", E56_main_lo, fp_lo_static_init)
static void __cdecl E55_main_lo() {
    LO_G8(0x00503fe8) = 0x0f;
}
PORT_FN(0x00401230, "$E55(main.obj)", E55_main_lo, fp_lo_static_init)
static void __cdecl E60_main_lo() {
    LO_FN(LoVoid_t, 0x00401250)();    // jmp: $E59
}
PORT_FN(0x00401240, "$E60(main.obj)", E60_main_lo, fp_lo_static_init)
static void __cdecl E59_main_lo() {}    // ret
PORT_FN(0x00401250, "$E59(main.obj)", E59_main_lo, fp_lo_static_init)
static void __cdecl E63_main_lo() {
    LO_FN(LoVoid_t, 0x00401270)();    // jmp: $E62
}
PORT_FN(0x00401260, "$E63(main.obj)", E63_main_lo, fp_lo_static_init)
static void __cdecl E62_main_lo() {
    const uint32_t v1 = LO_G32(0x004e3764);
    LO_G32(0x00504004) = v1;
}
PORT_FN(0x00401270, "$E62(main.obj)", E62_main_lo, fp_lo_static_init)
static void __cdecl E67_main_lo() {}    // ret
PORT_FN(0x00401d30, "$E67(main.obj)", E67_main_lo, fp_lo_static_init)
static void __cdecl E66_main_lo() {}    // ret
PORT_FN(0x00401d40, "$E66(main.obj)", E66_main_lo, fp_lo_static_init)
static void __cdecl E72_main_lo() {}    // ret
PORT_FN(0x00402bf0, "$E72(main.obj)", E72_main_lo, fp_lo_static_init)
static void __cdecl E71_main_lo() {}    // ret
PORT_FN(0x00402c00, "$E71(main.obj)", E71_main_lo, fp_lo_static_init)
static void __cdecl E70_main_lo() {}    // ret
PORT_FN(0x00402c10, "$E70(main.obj)", E70_main_lo, fp_lo_static_init)
static void __cdecl E69_main_lo() {}    // ret
PORT_FN(0x00402c20, "$E69(main.obj)", E69_main_lo, fp_lo_static_init)

// ---- dash.obj --------------------------------------------------------------------------------------------------------
static void __cdecl E2_dash_lo() {
    LO_FN(LoVoid_t, 0x00403250)();    // jmp: $E1
}
PORT_FN(0x00403240, "$E2(dash.obj)", E2_dash_lo, fp_lo_static_init)
static void __cdecl E1_dash_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x00403250, "$E1(dash.obj)", E1_dash_lo, fp_lo_static_init)
static void __cdecl E6_dash_lo() {
    LO_FN(LoVoid_t, 0x00403270)();    // jmp: $E5
}
PORT_FN(0x00403260, "$E6(dash.obj)", E6_dash_lo, fp_lo_static_init)
static void __cdecl E5_dash_lo() {
    LO_G32(0x005040fc) = 0x00000000u;
}
PORT_FN(0x00403270, "$E5(dash.obj)", E5_dash_lo, fp_lo_static_init)
static void __cdecl E9_dash_lo() {
    LO_FN(LoVoid_t, 0x00403290)();    // jmp: $E8
}
PORT_FN(0x00403280, "$E9(dash.obj)", E9_dash_lo, fp_lo_static_init)
static void __cdecl E8_dash_lo() {
    LO_G32(0x005041ec) = 0x001f001fu;
}
PORT_FN(0x00403290, "$E8(dash.obj)", E8_dash_lo, fp_lo_static_init)
static void __cdecl E12_dash_lo() {
    LO_FN(LoVoid_t, 0x004032b0)();    // jmp: $E11
}
PORT_FN(0x004032a0, "$E12(dash.obj)", E12_dash_lo, fp_lo_static_init)
static void __cdecl E11_dash_lo() {
    LO_G32(0x00504124) = 0x03e001e0u;
}
PORT_FN(0x004032b0, "$E11(dash.obj)", E11_dash_lo, fp_lo_static_init)
static void __cdecl E15_dash_lo() {
    LO_FN(LoVoid_t, 0x004032d0)();    // jmp: $E14
}
PORT_FN(0x004032c0, "$E15(dash.obj)", E15_dash_lo, fp_lo_static_init)
static void __cdecl E14_dash_lo() {
    LO_G32(0x00504214) = 0x03ef01efu;
}
PORT_FN(0x004032d0, "$E14(dash.obj)", E14_dash_lo, fp_lo_static_init)
static void __cdecl E18_dash_lo() {
    LO_FN(LoVoid_t, 0x004032f0)();    // jmp: $E17
}
PORT_FN(0x004032e0, "$E18(dash.obj)", E18_dash_lo, fp_lo_static_init)
static void __cdecl E17_dash_lo() {
    LO_G32(0x005042dc) = 0x78003c00u;
}
PORT_FN(0x004032f0, "$E17(dash.obj)", E17_dash_lo, fp_lo_static_init)
static void __cdecl E21_dash_lo() {
    LO_FN(LoVoid_t, 0x00403310)();    // jmp: $E20
}
PORT_FN(0x00403300, "$E21(dash.obj)", E21_dash_lo, fp_lo_static_init)
static void __cdecl E20_dash_lo() {
    LO_G32(0x005041d4) = 0x780f3c0fu;
}
PORT_FN(0x00403310, "$E20(dash.obj)", E20_dash_lo, fp_lo_static_init)
static void __cdecl E24_dash_lo() {
    LO_FN(LoVoid_t, 0x00403330)();    // jmp: $E23
}
PORT_FN(0x00403320, "$E24(dash.obj)", E24_dash_lo, fp_lo_static_init)
static void __cdecl E23_dash_lo() {
    LO_G32(0x005042cc) = 0x7be03de0u;
}
PORT_FN(0x00403330, "$E23(dash.obj)", E23_dash_lo, fp_lo_static_init)
static void __cdecl E27_dash_lo() {
    LO_FN(LoVoid_t, 0x00403350)();    // jmp: $E26
}
PORT_FN(0x00403340, "$E27(dash.obj)", E27_dash_lo, fp_lo_static_init)
static void __cdecl E26_dash_lo() {
    LO_G32(0x005041bc) = 0x7bef3defu;
}
PORT_FN(0x00403350, "$E26(dash.obj)", E26_dash_lo, fp_lo_static_init)
static void __cdecl E30_dash_lo() {
    LO_FN(LoVoid_t, 0x00403370)();    // jmp: $E29
}
PORT_FN(0x00403360, "$E30(dash.obj)", E30_dash_lo, fp_lo_static_init)
static void __cdecl E29_dash_lo() {
    LO_G32(0x005042c4) = 0x42082108u;
}
PORT_FN(0x00403370, "$E29(dash.obj)", E29_dash_lo, fp_lo_static_init)
static void __cdecl E33_dash_lo() {
    LO_FN(LoVoid_t, 0x00403390)();    // jmp: $E32
}
PORT_FN(0x00403380, "$E33(dash.obj)", E33_dash_lo, fp_lo_static_init)
static void __cdecl E32_dash_lo() {
    LO_G32(0x005040c0) = 0x001f001fu;
}
PORT_FN(0x00403390, "$E32(dash.obj)", E32_dash_lo, fp_lo_static_init)
static void __cdecl E36_dash_lo() {
    LO_FN(LoVoid_t, 0x004033b0)();    // jmp: $E35
}
PORT_FN(0x004033a0, "$E36(dash.obj)", E36_dash_lo, fp_lo_static_init)
static void __cdecl E35_dash_lo() {
    LO_G32(0x005042d8) = 0x07e003e0u;
}
PORT_FN(0x004033b0, "$E35(dash.obj)", E35_dash_lo, fp_lo_static_init)
static void __cdecl E39_dash_lo() {
    LO_FN(LoVoid_t, 0x004033d0)();    // jmp: $E38
}
PORT_FN(0x004033c0, "$E39(dash.obj)", E39_dash_lo, fp_lo_static_init)
static void __cdecl E38_dash_lo() {
    LO_G32(0x00504120) = 0x07ff03ffu;
}
PORT_FN(0x004033d0, "$E38(dash.obj)", E38_dash_lo, fp_lo_static_init)
static void __cdecl E42_dash_lo() {
    LO_FN(LoVoid_t, 0x004033f0)();    // jmp: $E41
}
PORT_FN(0x004033e0, "$E42(dash.obj)", E42_dash_lo, fp_lo_static_init)
static void __cdecl E41_dash_lo() {
    LO_G32(0x0050411c) = 0xf8007c00u;
}
PORT_FN(0x004033f0, "$E41(dash.obj)", E41_dash_lo, fp_lo_static_init)
static void __cdecl E45_dash_lo() {
    LO_FN(LoVoid_t, 0x00403410)();    // jmp: $E44
}
PORT_FN(0x00403400, "$E45(dash.obj)", E45_dash_lo, fp_lo_static_init)
static void __cdecl E44_dash_lo() {
    LO_G32(0x005042f0) = 0xf81f7c1fu;
}
PORT_FN(0x00403410, "$E44(dash.obj)", E44_dash_lo, fp_lo_static_init)
static void __cdecl E48_dash_lo() {
    LO_FN(LoVoid_t, 0x00403430)();    // jmp: $E47
}
PORT_FN(0x00403420, "$E48(dash.obj)", E48_dash_lo, fp_lo_static_init)
static void __cdecl E47_dash_lo() {
    LO_G32(0x0050427c) = 0xffe07fe0u;
}
PORT_FN(0x00403430, "$E47(dash.obj)", E47_dash_lo, fp_lo_static_init)
static void __cdecl E51_dash_lo() {
    LO_FN(LoVoid_t, 0x00403450)();    // jmp: $E50
}
PORT_FN(0x00403440, "$E51(dash.obj)", E51_dash_lo, fp_lo_static_init)
static void __cdecl E50_dash_lo() {
    LO_G32(0x005041a8) = 0xffff7fffu;
}
PORT_FN(0x00403450, "$E50(dash.obj)", E50_dash_lo, fp_lo_static_init)
static void __cdecl E65_dash_lo() {}    // ret
PORT_FN(0x00404790, "$E65(dash.obj)", E65_dash_lo, fp_lo_static_init)
static void __cdecl E63_dash_lo() {}    // ret
PORT_FN(0x004047a0, "$E63(dash.obj)", E63_dash_lo, fp_lo_static_init)
static void __cdecl E62_dash_lo() {}    // ret
PORT_FN(0x004047b0, "$E62(dash.obj)", E62_dash_lo, fp_lo_static_init)
static void __cdecl E61_dash_lo() {}    // ret
PORT_FN(0x004047c0, "$E61(dash.obj)", E61_dash_lo, fp_lo_static_init)
static void __cdecl E60_dash_lo() {}    // ret
PORT_FN(0x004047d0, "$E60(dash.obj)", E60_dash_lo, fp_lo_static_init)
static void __cdecl E59_dash_lo() {}    // ret
PORT_FN(0x004047e0, "$E59(dash.obj)", E59_dash_lo, fp_lo_static_init)
static void __cdecl E58_dash_lo() {}    // ret
PORT_FN(0x004047f0, "$E58(dash.obj)", E58_dash_lo, fp_lo_static_init)
static void __cdecl E57_dash_lo() {}    // ret
PORT_FN(0x00404800, "$E57(dash.obj)", E57_dash_lo, fp_lo_static_init)
static void __cdecl E56_dash_lo() {}    // ret
PORT_FN(0x00404810, "$E56(dash.obj)", E56_dash_lo, fp_lo_static_init)
static void __cdecl E67_dash_lo() {
    LO_FN(LoVoid_t, 0x00404a30)();    // jmp: $E66
}
PORT_FN(0x00404a20, "$E67(dash.obj)", E67_dash_lo, fp_lo_static_init)
static void __cdecl E66_dash_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005042a8u, 0, 0x004e3d38u);    // Xlator::Xlator
}
PORT_FN(0x00404a30, "$E66(dash.obj)", E66_dash_lo, fp_lo_static_init)
static void __cdecl E70_dash_lo() {
    LO_FN(LoVoid_t, 0x00404a50)();    // jmp: $E69
}
PORT_FN(0x00404a40, "$E70(dash.obj)", E70_dash_lo, fp_lo_static_init)
static void __cdecl E69_dash_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504110u, 0, 0x004e3d54u);    // Xlator::Xlator
}
PORT_FN(0x00404a50, "$E69(dash.obj)", E69_dash_lo, fp_lo_static_init)
static void __cdecl E73_dash_lo() {
    LO_FN(LoVoid_t, 0x00404a70)();    // jmp: $E72
}
PORT_FN(0x00404a60, "$E73(dash.obj)", E73_dash_lo, fp_lo_static_init)
static void __cdecl E72_dash_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504240u, 0, 0x004e3d70u);    // Xlator::Xlator
}
PORT_FN(0x00404a70, "$E72(dash.obj)", E72_dash_lo, fp_lo_static_init)
// void __cdecl draw_fps(void)
static void __cdecl draw_fps_lo() {}
static void fp_draw_fps_lo(Footprint& f) { f.pure = true; }
PORT_FN(0x004054a0, "draw_fps", draw_fps_lo, fp_draw_fps_lo)
static void __cdecl E85_dash_lo() {}    // ret
PORT_FN(0x004054b0, "$E85(dash.obj)", E85_dash_lo, fp_lo_static_init)
static void __cdecl E84_dash_lo() {}    // ret
PORT_FN(0x004054c0, "$E84(dash.obj)", E84_dash_lo, fp_lo_static_init)
static void __cdecl E82_dash_lo() {}    // ret
PORT_FN(0x004054d0, "$E82(dash.obj)", E82_dash_lo, fp_lo_static_init)
static void __cdecl E81_dash_lo() {}    // ret
PORT_FN(0x004054e0, "$E81(dash.obj)", E81_dash_lo, fp_lo_static_init)
static void __cdecl E80_dash_lo() {}    // ret
PORT_FN(0x004054f0, "$E80(dash.obj)", E80_dash_lo, fp_lo_static_init)
static void __cdecl E79_dash_lo() {}    // ret
PORT_FN(0x00405500, "$E79(dash.obj)", E79_dash_lo, fp_lo_static_init)
static void __cdecl E78_dash_lo() {}    // ret
PORT_FN(0x00405510, "$E78(dash.obj)", E78_dash_lo, fp_lo_static_init)
static void __cdecl E77_dash_lo() {}    // ret
PORT_FN(0x00405520, "$E77(dash.obj)", E77_dash_lo, fp_lo_static_init)
static void __cdecl E76_dash_lo() {}    // ret
PORT_FN(0x00405530, "$E76(dash.obj)", E76_dash_lo, fp_lo_static_init)

// ---- race.obj --------------------------------------------------------------------------------------------------------
static void __cdecl E2_race_lo() {
    LO_FN(LoVoid_t, 0x00405870)();    // jmp: $E1
}
PORT_FN(0x00405860, "$E2(race.obj)", E2_race_lo, fp_lo_static_init)
static void __cdecl E1_race_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x00405870, "$E1(race.obj)", E1_race_lo, fp_lo_static_init)
static void __cdecl E6_race_lo() {
    LO_FN(LoVoid_t, 0x00405890)();    // jmp: $E5
}
PORT_FN(0x00405880, "$E6(race.obj)", E6_race_lo, fp_lo_static_init)
static void __cdecl E5_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504528u, 0, 0x004e4140u);    // Xlator::Xlator
}
PORT_FN(0x00405890, "$E5(race.obj)", E5_race_lo, fp_lo_static_init)
static void __cdecl E9_race_lo() {
    LO_FN(LoVoid_t, 0x004058b0)();    // jmp: $E8
}
PORT_FN(0x004058a0, "$E9(race.obj)", E9_race_lo, fp_lo_static_init)
static void __cdecl E8_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504468u, 0, 0x004e4154u);    // Xlator::Xlator
}
PORT_FN(0x004058b0, "$E8(race.obj)", E8_race_lo, fp_lo_static_init)
static void __cdecl E12_race_lo() {
    LO_FN(LoVoid_t, 0x004058d0)();    // jmp: $E11
}
PORT_FN(0x004058c0, "$E12(race.obj)", E12_race_lo, fp_lo_static_init)
static void __cdecl E11_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504538u, 0, 0x004e4168u);    // Xlator::Xlator
}
PORT_FN(0x004058d0, "$E11(race.obj)", E11_race_lo, fp_lo_static_init)
static void __cdecl E15_race_lo() {
    LO_FN(LoVoid_t, 0x004058f0)();    // jmp: $E14
}
PORT_FN(0x004058e0, "$E15(race.obj)", E15_race_lo, fp_lo_static_init)
static void __cdecl E14_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504408u, 0, 0x004e417cu);    // Xlator::Xlator
}
PORT_FN(0x004058f0, "$E14(race.obj)", E14_race_lo, fp_lo_static_init)
static void __cdecl E18_race_lo() {
    LO_FN(LoVoid_t, 0x00405910)();    // jmp: $E17
}
PORT_FN(0x00405900, "$E18(race.obj)", E18_race_lo, fp_lo_static_init)
static void __cdecl E17_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504558u, 0, 0x004e4190u);    // Xlator::Xlator
}
PORT_FN(0x00405910, "$E17(race.obj)", E17_race_lo, fp_lo_static_init)
static void __cdecl E21_race_lo() {
    LO_FN(LoVoid_t, 0x00405930)();    // jmp: $E20
}
PORT_FN(0x00405920, "$E21(race.obj)", E21_race_lo, fp_lo_static_init)
static void __cdecl E20_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005043b8u, 0, 0x004e41a8u);    // Xlator::Xlator
}
PORT_FN(0x00405930, "$E20(race.obj)", E20_race_lo, fp_lo_static_init)
static void __cdecl E24_race_lo() {
    LO_FN(LoVoid_t, 0x00405950)();    // jmp: $E23
}
PORT_FN(0x00405940, "$E24(race.obj)", E24_race_lo, fp_lo_static_init)
static void __cdecl E23_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005045b8u, 0, 0x004e41bcu);    // Xlator::Xlator
}
PORT_FN(0x00405950, "$E23(race.obj)", E23_race_lo, fp_lo_static_init)
static void __cdecl E27_race_lo() {
    LO_FN(LoVoid_t, 0x00405970)();    // jmp: $E26
}
PORT_FN(0x00405960, "$E27(race.obj)", E27_race_lo, fp_lo_static_init)
static void __cdecl E26_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005043a8u, 0, 0x004e41d4u);    // Xlator::Xlator
}
PORT_FN(0x00405970, "$E26(race.obj)", E26_race_lo, fp_lo_static_init)
static void __cdecl E30_race_lo() {
    LO_FN(LoVoid_t, 0x00405990)();    // jmp: $E29
}
PORT_FN(0x00405980, "$E30(race.obj)", E30_race_lo, fp_lo_static_init)
static void __cdecl E29_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005044c8u, 0, 0x004e41ecu);    // Xlator::Xlator
}
PORT_FN(0x00405990, "$E29(race.obj)", E29_race_lo, fp_lo_static_init)
static void __cdecl E33_race_lo() {
    LO_FN(LoVoid_t, 0x004059b0)();    // jmp: $E32
}
PORT_FN(0x004059a0, "$E33(race.obj)", E33_race_lo, fp_lo_static_init)
static void __cdecl E32_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504488u, 0, 0x004e4204u);    // Xlator::Xlator
}
PORT_FN(0x004059b0, "$E32(race.obj)", E32_race_lo, fp_lo_static_init)
static void __cdecl E36_race_lo() {
    LO_FN(LoVoid_t, 0x004059d0)();    // jmp: $E35
}
PORT_FN(0x004059c0, "$E36(race.obj)", E36_race_lo, fp_lo_static_init)
static void __cdecl E35_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504458u, 0, 0x004e4218u);    // Xlator::Xlator
}
PORT_FN(0x004059d0, "$E35(race.obj)", E35_race_lo, fp_lo_static_init)
static void __cdecl E39_race_lo() {
    LO_FN(LoVoid_t, 0x004059f0)();    // jmp: $E38
}
PORT_FN(0x004059e0, "$E39(race.obj)", E39_race_lo, fp_lo_static_init)
static void __cdecl E38_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005045f8u, 0, 0x004e422cu);    // Xlator::Xlator
}
PORT_FN(0x004059f0, "$E38(race.obj)", E38_race_lo, fp_lo_static_init)
static void __cdecl E42_race_lo() {
    LO_FN(LoVoid_t, 0x00405a10)();    // jmp: $E41
}
PORT_FN(0x00405a00, "$E42(race.obj)", E42_race_lo, fp_lo_static_init)
static void __cdecl E41_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005045a8u, 0, 0x004e423cu);    // Xlator::Xlator
}
PORT_FN(0x00405a10, "$E41(race.obj)", E41_race_lo, fp_lo_static_init)
static void __cdecl E45_race_lo() {
    LO_FN(LoVoid_t, 0x00405a30)();    // jmp: $E44
}
PORT_FN(0x00405a20, "$E45(race.obj)", E45_race_lo, fp_lo_static_init)
static void __cdecl E44_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504478u, 0, 0x004e4258u);    // Xlator::Xlator
}
PORT_FN(0x00405a30, "$E44(race.obj)", E44_race_lo, fp_lo_static_init)
static void __cdecl E48_race_lo() {
    LO_FN(LoVoid_t, 0x00405a50)();    // jmp: $E47
}
PORT_FN(0x00405a40, "$E48(race.obj)", E48_race_lo, fp_lo_static_init)
static void __cdecl E47_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504310u, 0, 0x004e427cu);    // Xlator::Xlator
}
PORT_FN(0x00405a50, "$E47(race.obj)", E47_race_lo, fp_lo_static_init)
static void __cdecl E51_race_lo() {
    LO_FN(LoVoid_t, 0x00405a70)();    // jmp: $E50
}
PORT_FN(0x00405a60, "$E51(race.obj)", E51_race_lo, fp_lo_static_init)
static void __cdecl E50_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504498u, 0, 0x004e429cu);    // Xlator::Xlator
}
PORT_FN(0x00405a70, "$E50(race.obj)", E50_race_lo, fp_lo_static_init)
static void __cdecl E54_race_lo() {
    LO_FN(LoVoid_t, 0x00405a90)();    // jmp: $E53
}
PORT_FN(0x00405a80, "$E54(race.obj)", E54_race_lo, fp_lo_static_init)
static void __cdecl E53_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005044a8u, 0, 0x004e42b8u);    // Xlator::Xlator
}
PORT_FN(0x00405a90, "$E53(race.obj)", E53_race_lo, fp_lo_static_init)
static void __cdecl E57_race_lo() {
    LO_FN(LoVoid_t, 0x00405ab0)();    // jmp: $E56
}
PORT_FN(0x00405aa0, "$E57(race.obj)", E57_race_lo, fp_lo_static_init)
static void __cdecl E56_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504358u, 0, 0x004e42d4u);    // Xlator::Xlator
}
PORT_FN(0x00405ab0, "$E56(race.obj)", E56_race_lo, fp_lo_static_init)
static void __cdecl E60_race_lo() {
    LO_FN(LoVoid_t, 0x00405ad0)();    // jmp: $E59
}
PORT_FN(0x00405ac0, "$E60(race.obj)", E60_race_lo, fp_lo_static_init)
static void __cdecl E59_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504398u, 0, 0x004e42f0u);    // Xlator::Xlator
}
PORT_FN(0x00405ad0, "$E59(race.obj)", E59_race_lo, fp_lo_static_init)
static void __cdecl E63_race_lo() {
    LO_FN(LoVoid_t, 0x00405af0)();    // jmp: $E62
}
PORT_FN(0x00405ae0, "$E63(race.obj)", E63_race_lo, fp_lo_static_init)
static void __cdecl E62_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005044d8u, 0, 0x004e430cu);    // Xlator::Xlator
}
PORT_FN(0x00405af0, "$E62(race.obj)", E62_race_lo, fp_lo_static_init)
static void __cdecl E66_race_lo() {
    LO_FN(LoVoid_t, 0x00405b10)();    // jmp: $E65
}
PORT_FN(0x00405b00, "$E66(race.obj)", E66_race_lo, fp_lo_static_init)
static void __cdecl E65_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005044e8u, 0, 0x004e432cu);    // Xlator::Xlator
}
PORT_FN(0x00405b10, "$E65(race.obj)", E65_race_lo, fp_lo_static_init)
static void __cdecl E69_race_lo() {
    LO_FN(LoVoid_t, 0x00405b30)();    // jmp: $E68
}
PORT_FN(0x00405b20, "$E69(race.obj)", E69_race_lo, fp_lo_static_init)
static void __cdecl E68_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504518u, 0, 0x004e4348u);    // Xlator::Xlator
}
PORT_FN(0x00405b30, "$E68(race.obj)", E68_race_lo, fp_lo_static_init)
static void __cdecl E72_race_lo() {
    LO_FN(LoVoid_t, 0x00405b50)();    // jmp: $E71
}
PORT_FN(0x00405b40, "$E72(race.obj)", E72_race_lo, fp_lo_static_init)
static void __cdecl E71_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005045d8u, 0, 0x004e4364u);    // Xlator::Xlator
}
PORT_FN(0x00405b50, "$E71(race.obj)", E71_race_lo, fp_lo_static_init)
static void __cdecl E75_race_lo() {
    LO_FN(LoVoid_t, 0x00405b70)();    // jmp: $E74
}
PORT_FN(0x00405b60, "$E75(race.obj)", E75_race_lo, fp_lo_static_init)
static void __cdecl E74_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504608u, 0, 0x004e437cu);    // Xlator::Xlator
}
PORT_FN(0x00405b70, "$E74(race.obj)", E74_race_lo, fp_lo_static_init)
static void __cdecl E78_race_lo() {
    LO_FN(LoVoid_t, 0x00405b90)();    // jmp: $E77
}
PORT_FN(0x00405b80, "$E78(race.obj)", E78_race_lo, fp_lo_static_init)
static void __cdecl E77_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005043e8u, 0, 0x004e439cu);    // Xlator::Xlator
}
PORT_FN(0x00405b90, "$E77(race.obj)", E77_race_lo, fp_lo_static_init)
static void __cdecl E81_race_lo() {
    LO_FN(LoVoid_t, 0x00405bb0)();    // jmp: $E80
}
PORT_FN(0x00405ba0, "$E81(race.obj)", E81_race_lo, fp_lo_static_init)
static void __cdecl E80_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504348u, 0, 0x004e43b8u);    // Xlator::Xlator
}
PORT_FN(0x00405bb0, "$E80(race.obj)", E80_race_lo, fp_lo_static_init)
static void __cdecl E84_race_lo() {
    LO_FN(LoVoid_t, 0x00405bd0)();    // jmp: $E83
}
PORT_FN(0x00405bc0, "$E84(race.obj)", E84_race_lo, fp_lo_static_init)
static void __cdecl E83_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005044b8u, 0, 0x004e43d4u);    // Xlator::Xlator
}
PORT_FN(0x00405bd0, "$E83(race.obj)", E83_race_lo, fp_lo_static_init)
static void __cdecl E87_race_lo() {
    LO_FN(LoVoid_t, 0x00405bf0)();    // jmp: $E86
}
PORT_FN(0x00405be0, "$E87(race.obj)", E87_race_lo, fp_lo_static_init)
static void __cdecl E86_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005045c8u, 0, 0x004e43f0u);    // Xlator::Xlator
}
PORT_FN(0x00405bf0, "$E86(race.obj)", E86_race_lo, fp_lo_static_init)
static void __cdecl E90_race_lo() {
    LO_FN(LoVoid_t, 0x00405c10)();    // jmp: $E89
}
PORT_FN(0x00405c00, "$E90(race.obj)", E90_race_lo, fp_lo_static_init)
static void __cdecl E89_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504578u, 0, 0x004e4410u);    // Xlator::Xlator
}
PORT_FN(0x00405c10, "$E89(race.obj)", E89_race_lo, fp_lo_static_init)
static void __cdecl E93_race_lo() {
    LO_FN(LoVoid_t, 0x00405c30)();    // jmp: $E92
}
PORT_FN(0x00405c20, "$E93(race.obj)", E93_race_lo, fp_lo_static_init)
static void __cdecl E92_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005043f8u, 0, 0x004e442cu);    // Xlator::Xlator
}
PORT_FN(0x00405c30, "$E92(race.obj)", E92_race_lo, fp_lo_static_init)
static void __cdecl E96_race_lo() {
    LO_FN(LoVoid_t, 0x00405c50)();    // jmp: $E95
}
PORT_FN(0x00405c40, "$E96(race.obj)", E96_race_lo, fp_lo_static_init)
static void __cdecl E95_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504588u, 0, 0x004e4448u);    // Xlator::Xlator
}
PORT_FN(0x00405c50, "$E95(race.obj)", E95_race_lo, fp_lo_static_init)
static void __cdecl E99_race_lo() {
    LO_FN(LoVoid_t, 0x00405c70)();    // jmp: $E98
}
PORT_FN(0x00405c60, "$E99(race.obj)", E99_race_lo, fp_lo_static_init)
static void __cdecl E98_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504618u, 0, 0x004e4464u);    // Xlator::Xlator
}
PORT_FN(0x00405c70, "$E98(race.obj)", E98_race_lo, fp_lo_static_init)
static void __cdecl E102_race_lo() {
    LO_FN(LoVoid_t, 0x00405c90)();    // jmp: $E101
}
PORT_FN(0x00405c80, "$E102(race.obj)", E102_race_lo, fp_lo_static_init)
static void __cdecl E101_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504418u, 0, 0x004e4480u);    // Xlator::Xlator
}
PORT_FN(0x00405c90, "$E101(race.obj)", E101_race_lo, fp_lo_static_init)
static void __cdecl E105_race_lo() {
    LO_FN(LoVoid_t, 0x00405cb0)();    // jmp: $E104
}
PORT_FN(0x00405ca0, "$E105(race.obj)", E105_race_lo, fp_lo_static_init)
static void __cdecl E104_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504568u, 0, 0x004e44a4u);    // Xlator::Xlator
}
PORT_FN(0x00405cb0, "$E104(race.obj)", E104_race_lo, fp_lo_static_init)
static void __cdecl E108_race_lo() {
    LO_FN(LoVoid_t, 0x00405cd0)();    // jmp: $E107
}
PORT_FN(0x00405cc0, "$E108(race.obj)", E108_race_lo, fp_lo_static_init)
static void __cdecl E107_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504428u, 0, 0x004e44c8u);    // Xlator::Xlator
}
PORT_FN(0x00405cd0, "$E107(race.obj)", E107_race_lo, fp_lo_static_init)
static void __cdecl E111_race_lo() {
    LO_FN(LoVoid_t, 0x00405cf0)();    // jmp: $E110
}
PORT_FN(0x00405ce0, "$E111(race.obj)", E111_race_lo, fp_lo_static_init)
static void __cdecl E110_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005043c8u, 0, 0x004e44e8u);    // Xlator::Xlator
}
PORT_FN(0x00405cf0, "$E110(race.obj)", E110_race_lo, fp_lo_static_init)
static void __cdecl E114_race_lo() {
    LO_FN(LoVoid_t, 0x00405d10)();    // jmp: $E113
}
PORT_FN(0x00405d00, "$E114(race.obj)", E114_race_lo, fp_lo_static_init)
static void __cdecl E113_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504598u, 0, 0x004e4504u);    // Xlator::Xlator
}
PORT_FN(0x00405d10, "$E113(race.obj)", E113_race_lo, fp_lo_static_init)
static void __cdecl E117_race_lo() {
    LO_FN(LoVoid_t, 0x00405d30)();    // jmp: $E116
}
PORT_FN(0x00405d20, "$E117(race.obj)", E117_race_lo, fp_lo_static_init)
static void __cdecl E116_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504640u, 0, 0x004e4524u);    // Xlator::Xlator
}
PORT_FN(0x00405d30, "$E116(race.obj)", E116_race_lo, fp_lo_static_init)
static void __cdecl E120_race_lo() {
    LO_FN(LoVoid_t, 0x00405d50)();    // jmp: $E119
}
PORT_FN(0x00405d40, "$E120(race.obj)", E120_race_lo, fp_lo_static_init)
static void __cdecl E119_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504630u, 0, 0x004e4548u);    // Xlator::Xlator
}
PORT_FN(0x00405d50, "$E119(race.obj)", E119_race_lo, fp_lo_static_init)
static void __cdecl E123_race_lo() {
    LO_FN(LoVoid_t, 0x00405d70)();    // jmp: $E122
}
PORT_FN(0x00405d60, "$E123(race.obj)", E123_race_lo, fp_lo_static_init)
static void __cdecl E122_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504508u, 0, 0x004e4570u);    // Xlator::Xlator
}
PORT_FN(0x00405d70, "$E122(race.obj)", E122_race_lo, fp_lo_static_init)
static void __cdecl E126_race_lo() {
    LO_FN(LoVoid_t, 0x00405d90)();    // jmp: $E125
}
PORT_FN(0x00405d80, "$E126(race.obj)", E126_race_lo, fp_lo_static_init)
static void __cdecl E125_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504548u, 0, 0x004e4590u);    // Xlator::Xlator
}
PORT_FN(0x00405d90, "$E125(race.obj)", E125_race_lo, fp_lo_static_init)
static void __cdecl E129_race_lo() {
    LO_FN(LoVoid_t, 0x00405db0)();    // jmp: $E128
}
PORT_FN(0x00405da0, "$E129(race.obj)", E129_race_lo, fp_lo_static_init)
static void __cdecl E128_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005043d8u, 0, 0x004e45b0u);    // Xlator::Xlator
}
PORT_FN(0x00405db0, "$E128(race.obj)", E128_race_lo, fp_lo_static_init)
static void __cdecl E132_race_lo() {
    LO_FN(LoVoid_t, 0x00405dd0)();    // jmp: $E131
}
PORT_FN(0x00405dc0, "$E132(race.obj)", E132_race_lo, fp_lo_static_init)
static void __cdecl E131_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504388u, 0, 0x004e45ccu);    // Xlator::Xlator
}
PORT_FN(0x00405dd0, "$E131(race.obj)", E131_race_lo, fp_lo_static_init)
static void __cdecl E135_race_lo() {
    LO_FN(LoVoid_t, 0x00405df0)();    // jmp: $E134
}
PORT_FN(0x00405de0, "$E135(race.obj)", E135_race_lo, fp_lo_static_init)
static void __cdecl E134_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005044f8u, 0, 0x004e45ecu);    // Xlator::Xlator
}
PORT_FN(0x00405df0, "$E134(race.obj)", E134_race_lo, fp_lo_static_init)
static void __cdecl E138_race_lo() {
    LO_FN(LoVoid_t, 0x00405e10)();    // jmp: $E137
}
PORT_FN(0x00405e00, "$E138(race.obj)", E138_race_lo, fp_lo_static_init)
static void __cdecl E137_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00504650u, 0, 0x004e460cu);    // Xlator::Xlator
}
PORT_FN(0x00405e10, "$E137(race.obj)", E137_race_lo, fp_lo_static_init)
static void __cdecl E141_race_lo() {
    LO_FN(LoVoid_t, 0x00405e30)();    // jmp: $E140
}
PORT_FN(0x00405e20, "$E141(race.obj)", E141_race_lo, fp_lo_static_init)
static void __cdecl E140_race_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x005045e8u, 0, 0x004e462cu);    // Xlator::Xlator
}
PORT_FN(0x00405e30, "$E140(race.obj)", E140_race_lo, fp_lo_static_init)

// ---- replay.obj ------------------------------------------------------------------------------------------------------
static void __cdecl E2_replay_lo() {
    LO_FN(LoVoid_t, 0x00406990)();    // jmp: $E1
}
PORT_FN(0x00406980, "$E2(replay.obj)", E2_replay_lo, fp_lo_static_init)
static void __cdecl E1_replay_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x00406990, "$E1(replay.obj)", E1_replay_lo, fp_lo_static_init)
static void __cdecl E6_replay_lo() {
    LO_FN(LoVoid_t, 0x004069b0)();    // jmp: $E5
}
PORT_FN(0x004069a0, "$E6(replay.obj)", E6_replay_lo, fp_lo_static_init)
static void __cdecl E5_replay_lo() {
    LO_G32(0x00504694) = 0x00000000u;
}
PORT_FN(0x004069b0, "$E5(replay.obj)", E5_replay_lo, fp_lo_static_init)
static void __cdecl E9_replay_lo() {
    LO_FN(LoVoid_t, 0x004069d0)();    // jmp: $E8
}
PORT_FN(0x004069c0, "$E9(replay.obj)", E9_replay_lo, fp_lo_static_init)
static void __cdecl E8_replay_lo() {
    LO_G32(0x00505574) = 0x001f001fu;
}
PORT_FN(0x004069d0, "$E8(replay.obj)", E8_replay_lo, fp_lo_static_init)
static void __cdecl E12_replay_lo() {
    LO_FN(LoVoid_t, 0x004069f0)();    // jmp: $E11
}
PORT_FN(0x004069e0, "$E12(replay.obj)", E12_replay_lo, fp_lo_static_init)
static void __cdecl E11_replay_lo() {
    LO_G32(0x00505398) = 0x03e001e0u;
}
PORT_FN(0x004069f0, "$E11(replay.obj)", E11_replay_lo, fp_lo_static_init)
static void __cdecl E15_replay_lo() {
    LO_FN(LoVoid_t, 0x00406a10)();    // jmp: $E14
}
PORT_FN(0x00406a00, "$E15(replay.obj)", E15_replay_lo, fp_lo_static_init)
static void __cdecl E14_replay_lo() {
    LO_G32(0x00505668) = 0x03ef01efu;
}
PORT_FN(0x00406a10, "$E14(replay.obj)", E14_replay_lo, fp_lo_static_init)
static void __cdecl E18_replay_lo() {
    LO_FN(LoVoid_t, 0x00406a30)();    // jmp: $E17
}
PORT_FN(0x00406a20, "$E18(replay.obj)", E18_replay_lo, fp_lo_static_init)
static void __cdecl E17_replay_lo() {
    LO_G32(0x0050580c) = 0x78003c00u;
}
PORT_FN(0x00406a30, "$E17(replay.obj)", E17_replay_lo, fp_lo_static_init)
static void __cdecl E21_replay_lo() {
    LO_FN(LoVoid_t, 0x00406a50)();    // jmp: $E20
}
PORT_FN(0x00406a40, "$E21(replay.obj)", E21_replay_lo, fp_lo_static_init)
static void __cdecl E20_replay_lo() {
    LO_G32(0x0050545c) = 0x780f3c0fu;
}
PORT_FN(0x00406a50, "$E20(replay.obj)", E20_replay_lo, fp_lo_static_init)
static void __cdecl E24_replay_lo() {
    LO_FN(LoVoid_t, 0x00406a70)();    // jmp: $E23
}
PORT_FN(0x00406a60, "$E24(replay.obj)", E24_replay_lo, fp_lo_static_init)
static void __cdecl E23_replay_lo() {
    LO_G32(0x00505800) = 0x7be03de0u;
}
PORT_FN(0x00406a70, "$E23(replay.obj)", E23_replay_lo, fp_lo_static_init)
static void __cdecl E27_replay_lo() {
    LO_FN(LoVoid_t, 0x00406a90)();    // jmp: $E26
}
PORT_FN(0x00406a80, "$E27(replay.obj)", E27_replay_lo, fp_lo_static_init)
static void __cdecl E26_replay_lo() {
    LO_G32(0x0050543c) = 0x7bef3defu;
}
PORT_FN(0x00406a90, "$E26(replay.obj)", E26_replay_lo, fp_lo_static_init)
static void __cdecl E30_replay_lo() {
    LO_FN(LoVoid_t, 0x00406ab0)();    // jmp: $E29
}
PORT_FN(0x00406aa0, "$E30(replay.obj)", E30_replay_lo, fp_lo_static_init)
static void __cdecl E29_replay_lo() {
    LO_G32(0x005057fc) = 0x42082108u;
}
PORT_FN(0x00406ab0, "$E29(replay.obj)", E29_replay_lo, fp_lo_static_init)
static void __cdecl E33_replay_lo() {
    LO_FN(LoVoid_t, 0x00406ad0)();    // jmp: $E32
}
PORT_FN(0x00406ac0, "$E33(replay.obj)", E33_replay_lo, fp_lo_static_init)
static void __cdecl E32_replay_lo() {
    LO_G32(0x0050466c) = 0x001f001fu;
}
PORT_FN(0x00406ad0, "$E32(replay.obj)", E32_replay_lo, fp_lo_static_init)
static void __cdecl E36_replay_lo() {
    LO_FN(LoVoid_t, 0x00406af0)();    // jmp: $E35
}
PORT_FN(0x00406ae0, "$E36(replay.obj)", E36_replay_lo, fp_lo_static_init)
static void __cdecl E35_replay_lo() {
    LO_G32(0x00505808) = 0x07e003e0u;
}
PORT_FN(0x00406af0, "$E35(replay.obj)", E35_replay_lo, fp_lo_static_init)
static void __cdecl E39_replay_lo() {
    LO_FN(LoVoid_t, 0x00406b10)();    // jmp: $E38
}
PORT_FN(0x00406b00, "$E39(replay.obj)", E39_replay_lo, fp_lo_static_init)
static void __cdecl E38_replay_lo() {
    LO_G32(0x00505394) = 0x07ff03ffu;
}
PORT_FN(0x00406b10, "$E38(replay.obj)", E38_replay_lo, fp_lo_static_init)
static void __cdecl E42_replay_lo() {
    LO_FN(LoVoid_t, 0x00406b30)();    // jmp: $E41
}
PORT_FN(0x00406b20, "$E42(replay.obj)", E42_replay_lo, fp_lo_static_init)
static void __cdecl E41_replay_lo() {
    LO_G32(0x00505390) = 0xf8007c00u;
}
PORT_FN(0x00406b30, "$E41(replay.obj)", E41_replay_lo, fp_lo_static_init)
static void __cdecl E45_replay_lo() {
    LO_FN(LoVoid_t, 0x00406b50)();    // jmp: $E44
}
PORT_FN(0x00406b40, "$E45(replay.obj)", E45_replay_lo, fp_lo_static_init)
static void __cdecl E44_replay_lo() {
    LO_G32(0x00505820) = 0xf81f7c1fu;
}
PORT_FN(0x00406b50, "$E44(replay.obj)", E44_replay_lo, fp_lo_static_init)
static void __cdecl E48_replay_lo() {
    LO_FN(LoVoid_t, 0x00406b70)();    // jmp: $E47
}
PORT_FN(0x00406b60, "$E48(replay.obj)", E48_replay_lo, fp_lo_static_init)
static void __cdecl E47_replay_lo() {
    LO_G32(0x005057e4) = 0xffe07fe0u;
}
PORT_FN(0x00406b70, "$E47(replay.obj)", E47_replay_lo, fp_lo_static_init)
static void __cdecl E51_replay_lo() {
    LO_FN(LoVoid_t, 0x00406b90)();    // jmp: $E50
}
PORT_FN(0x00406b80, "$E51(replay.obj)", E51_replay_lo, fp_lo_static_init)
static void __cdecl E50_replay_lo() {
    LO_G32(0x00505420) = 0xffff7fffu;
}
PORT_FN(0x00406b90, "$E50(replay.obj)", E50_replay_lo, fp_lo_static_init)
static void __cdecl E54_replay_lo() {
    LO_FN(LoVoid_t, 0x00406bb0)();    // jmp: $E53
}
PORT_FN(0x00406ba0, "$E54(replay.obj)", E54_replay_lo, fp_lo_static_init)
static void __cdecl E53_replay_lo() {
    LO_FN(LoCtor0_t, 0x00462a90)((void*)0x005046a8u, 0);    // jmp: World::World
}
PORT_FN(0x00406bb0, "$E53(replay.obj)", E53_replay_lo, fp_lo_static_init)
static void __cdecl E61_replay_lo() {}    // ret
PORT_FN(0x004072e0, "$E61(replay.obj)", E61_replay_lo, fp_lo_static_init)
static void __cdecl E60_replay_lo() {}    // ret
PORT_FN(0x004072f0, "$E60(replay.obj)", E60_replay_lo, fp_lo_static_init)
static void __cdecl E59_replay_lo() {}    // ret
PORT_FN(0x00407300, "$E59(replay.obj)", E59_replay_lo, fp_lo_static_init)
static void __cdecl E58_replay_lo() {}    // ret
PORT_FN(0x00407310, "$E58(replay.obj)", E58_replay_lo, fp_lo_static_init)
static void __cdecl E57_replay_lo() {}    // ret
PORT_FN(0x00407320, "$E57(replay.obj)", E57_replay_lo, fp_lo_static_init)
static void __cdecl E63_replay_lo() {}    // ret
PORT_FN(0x004075f0, "$E63(replay.obj)", E63_replay_lo, fp_lo_static_init)
static void __cdecl E66_replay_lo() {}    // ret
PORT_FN(0x004079b0, "$E66(replay.obj)", E66_replay_lo, fp_lo_static_init)
static void __cdecl E65_replay_lo() {}    // ret
PORT_FN(0x004079c0, "$E65(replay.obj)", E65_replay_lo, fp_lo_static_init)
static void __cdecl E73_replay_lo() {}    // ret
PORT_FN(0x00407e70, "$E73(replay.obj)", E73_replay_lo, fp_lo_static_init)
static void __cdecl E72_replay_lo() {}    // ret
PORT_FN(0x00407e80, "$E72(replay.obj)", E72_replay_lo, fp_lo_static_init)
static void __cdecl E71_replay_lo() {}    // ret
PORT_FN(0x00407e90, "$E71(replay.obj)", E71_replay_lo, fp_lo_static_init)
static void __cdecl E70_replay_lo() {}    // ret
PORT_FN(0x00407ea0, "$E70(replay.obj)", E70_replay_lo, fp_lo_static_init)
static void __cdecl E69_replay_lo() {}    // ret
PORT_FN(0x00407eb0, "$E69(replay.obj)", E69_replay_lo, fp_lo_static_init)
static void __cdecl E68_replay_lo() {}    // ret
PORT_FN(0x00407ec0, "$E68(replay.obj)", E68_replay_lo, fp_lo_static_init)
static void __cdecl E78_replay_lo() {}    // ret
PORT_FN(0x004080f0, "$E78(replay.obj)", E78_replay_lo, fp_lo_static_init)
static void __cdecl E77_replay_lo() {}    // ret
PORT_FN(0x00408100, "$E77(replay.obj)", E77_replay_lo, fp_lo_static_init)
static void __cdecl E76_replay_lo() {}    // ret
PORT_FN(0x00408110, "$E76(replay.obj)", E76_replay_lo, fp_lo_static_init)
static void __cdecl E75_replay_lo() {}    // ret
PORT_FN(0x00408120, "$E75(replay.obj)", E75_replay_lo, fp_lo_static_init)
static void __cdecl E87_replay_lo() {}    // ret
PORT_FN(0x00408c00, "$E87(replay.obj)", E87_replay_lo, fp_lo_static_init)
static void __cdecl E86_replay_lo() {}    // ret
PORT_FN(0x00408c10, "$E86(replay.obj)", E86_replay_lo, fp_lo_static_init)
static void __cdecl E85_replay_lo() {}    // ret
PORT_FN(0x00408c20, "$E85(replay.obj)", E85_replay_lo, fp_lo_static_init)
static void __cdecl E84_replay_lo() {}    // ret
PORT_FN(0x00408c30, "$E84(replay.obj)", E84_replay_lo, fp_lo_static_init)
static void __cdecl E83_replay_lo() {}    // ret
PORT_FN(0x00408c40, "$E83(replay.obj)", E83_replay_lo, fp_lo_static_init)
static void __cdecl E82_replay_lo() {}    // ret
PORT_FN(0x00408c50, "$E82(replay.obj)", E82_replay_lo, fp_lo_static_init)
static void __cdecl E81_replay_lo() {}    // ret
PORT_FN(0x00408c60, "$E81(replay.obj)", E81_replay_lo, fp_lo_static_init)
static void __cdecl E80_replay_lo() {}    // ret
PORT_FN(0x00408c70, "$E80(replay.obj)", E80_replay_lo, fp_lo_static_init)
static void __cdecl E92_replay_lo() {}    // ret
PORT_FN(0x00408f50, "$E92(replay.obj)", E92_replay_lo, fp_lo_static_init)
static void __cdecl E91_replay_lo() {}    // ret
PORT_FN(0x00408f60, "$E91(replay.obj)", E91_replay_lo, fp_lo_static_init)
static void __cdecl E90_replay_lo() {}    // ret
PORT_FN(0x00408f70, "$E90(replay.obj)", E90_replay_lo, fp_lo_static_init)
static void __cdecl E89_replay_lo() {}    // ret
PORT_FN(0x00408f80, "$E89(replay.obj)", E89_replay_lo, fp_lo_static_init)

// ---- game.obj --------------------------------------------------------------------------------------------------------
static void __cdecl E2_game_lo() {
    LO_FN(LoVoid_t, 0x0040a1a0)();    // jmp: $E1
}
PORT_FN(0x0040a190, "$E2(game.obj)", E2_game_lo, fp_lo_static_init)
static void __cdecl E1_game_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x0040a1a0, "$E1(game.obj)", E1_game_lo, fp_lo_static_init)
static void __cdecl E6_game_lo() {
    LO_FN(LoVoid_t, 0x0040a1c0)();    // jmp: $E5
}
PORT_FN(0x0040a1b0, "$E6(game.obj)", E6_game_lo, fp_lo_static_init)
static void __cdecl E5_game_lo() {
    LO_G32(0x00505830) = 0x00000000u;
}
PORT_FN(0x0040a1c0, "$E5(game.obj)", E5_game_lo, fp_lo_static_init)
static void __cdecl E9_game_lo() {
    LO_FN(LoVoid_t, 0x0040a1e0)();    // jmp: $E8
}
PORT_FN(0x0040a1d0, "$E9(game.obj)", E9_game_lo, fp_lo_static_init)
static void __cdecl E8_game_lo() {
    LO_G32(0x00505894) = 0x001f001fu;
}
PORT_FN(0x0040a1e0, "$E8(game.obj)", E8_game_lo, fp_lo_static_init)
static void __cdecl E12_game_lo() {
    LO_FN(LoVoid_t, 0x0040a200)();    // jmp: $E11
}
PORT_FN(0x0040a1f0, "$E12(game.obj)", E12_game_lo, fp_lo_static_init)
static void __cdecl E11_game_lo() {
    LO_G32(0x00505840) = 0x03e001e0u;
}
PORT_FN(0x0040a200, "$E11(game.obj)", E11_game_lo, fp_lo_static_init)
static void __cdecl E15_game_lo() {
    LO_FN(LoVoid_t, 0x0040a220)();    // jmp: $E14
}
PORT_FN(0x0040a210, "$E15(game.obj)", E15_game_lo, fp_lo_static_init)
static void __cdecl E14_game_lo() {
    LO_G32(0x00505898) = 0x03ef01efu;
}
PORT_FN(0x0040a220, "$E14(game.obj)", E14_game_lo, fp_lo_static_init)
static void __cdecl E18_game_lo() {
    LO_FN(LoVoid_t, 0x0040a240)();    // jmp: $E17
}
PORT_FN(0x0040a230, "$E18(game.obj)", E18_game_lo, fp_lo_static_init)
static void __cdecl E17_game_lo() {
    LO_G32(0x005058b0) = 0x78003c00u;
}
PORT_FN(0x0040a240, "$E17(game.obj)", E17_game_lo, fp_lo_static_init)
static void __cdecl E21_game_lo() {
    LO_FN(LoVoid_t, 0x0040a260)();    // jmp: $E20
}
PORT_FN(0x0040a250, "$E21(game.obj)", E21_game_lo, fp_lo_static_init)
static void __cdecl E20_game_lo() {
    LO_G32(0x00505890) = 0x780f3c0fu;
}
PORT_FN(0x0040a260, "$E20(game.obj)", E20_game_lo, fp_lo_static_init)
static void __cdecl E24_game_lo() {
    LO_FN(LoVoid_t, 0x0040a280)();    // jmp: $E23
}
PORT_FN(0x0040a270, "$E24(game.obj)", E24_game_lo, fp_lo_static_init)
static void __cdecl E23_game_lo() {
    LO_G32(0x005058a4) = 0x7be03de0u;
}
PORT_FN(0x0040a280, "$E23(game.obj)", E23_game_lo, fp_lo_static_init)
static void __cdecl E27_game_lo() {
    LO_FN(LoVoid_t, 0x0040a2a0)();    // jmp: $E26
}
PORT_FN(0x0040a290, "$E27(game.obj)", E27_game_lo, fp_lo_static_init)
static void __cdecl E26_game_lo() {
    LO_G32(0x0050588c) = 0x7bef3defu;
}
PORT_FN(0x0040a2a0, "$E26(game.obj)", E26_game_lo, fp_lo_static_init)
static void __cdecl E30_game_lo() {
    LO_FN(LoVoid_t, 0x0040a2c0)();    // jmp: $E29
}
PORT_FN(0x0040a2b0, "$E30(game.obj)", E30_game_lo, fp_lo_static_init)
static void __cdecl E29_game_lo() {
    LO_G32(0x005058a0) = 0x42082108u;
}
PORT_FN(0x0040a2c0, "$E29(game.obj)", E29_game_lo, fp_lo_static_init)
static void __cdecl E33_game_lo() {
    LO_FN(LoVoid_t, 0x0040a2e0)();    // jmp: $E32
}
PORT_FN(0x0040a2d0, "$E33(game.obj)", E33_game_lo, fp_lo_static_init)
static void __cdecl E32_game_lo() {
    LO_G32(0x0050582c) = 0x001f001fu;
}
PORT_FN(0x0040a2e0, "$E32(game.obj)", E32_game_lo, fp_lo_static_init)
static void __cdecl E36_game_lo() {
    LO_FN(LoVoid_t, 0x0040a300)();    // jmp: $E35
}
PORT_FN(0x0040a2f0, "$E36(game.obj)", E36_game_lo, fp_lo_static_init)
static void __cdecl E35_game_lo() {
    LO_G32(0x005058ac) = 0x07e003e0u;
}
PORT_FN(0x0040a300, "$E35(game.obj)", E35_game_lo, fp_lo_static_init)
static void __cdecl E39_game_lo() {
    LO_FN(LoVoid_t, 0x0040a320)();    // jmp: $E38
}
PORT_FN(0x0040a310, "$E39(game.obj)", E39_game_lo, fp_lo_static_init)
static void __cdecl E38_game_lo() {
    LO_G32(0x0050583c) = 0x07ff03ffu;
}
PORT_FN(0x0040a320, "$E38(game.obj)", E38_game_lo, fp_lo_static_init)
static void __cdecl E42_game_lo() {
    LO_FN(LoVoid_t, 0x0040a340)();    // jmp: $E41
}
PORT_FN(0x0040a330, "$E42(game.obj)", E42_game_lo, fp_lo_static_init)
static void __cdecl E41_game_lo() {
    LO_G32(0x00505838) = 0xf8007c00u;
}
PORT_FN(0x0040a340, "$E41(game.obj)", E41_game_lo, fp_lo_static_init)
static void __cdecl E45_game_lo() {
    LO_FN(LoVoid_t, 0x0040a360)();    // jmp: $E44
}
PORT_FN(0x0040a350, "$E45(game.obj)", E45_game_lo, fp_lo_static_init)
static void __cdecl E44_game_lo() {
    LO_G32(0x005058b4) = 0xf81f7c1fu;
}
PORT_FN(0x0040a360, "$E44(game.obj)", E44_game_lo, fp_lo_static_init)
static void __cdecl E48_game_lo() {
    LO_FN(LoVoid_t, 0x0040a380)();    // jmp: $E47
}
PORT_FN(0x0040a370, "$E48(game.obj)", E48_game_lo, fp_lo_static_init)
static void __cdecl E47_game_lo() {
    LO_G32(0x0050589c) = 0xffe07fe0u;
}
PORT_FN(0x0040a380, "$E47(game.obj)", E47_game_lo, fp_lo_static_init)
static void __cdecl E51_game_lo() {
    LO_FN(LoVoid_t, 0x0040a3a0)();    // jmp: $E50
}
PORT_FN(0x0040a390, "$E51(game.obj)", E51_game_lo, fp_lo_static_init)
static void __cdecl E50_game_lo() {
    LO_G32(0x00505888) = 0xffff7fffu;
}
PORT_FN(0x0040a3a0, "$E50(game.obj)", E50_game_lo, fp_lo_static_init)
static void __cdecl E54_game_lo() {
    LO_FN(LoVoid_t, 0x0040a3c0)();    // jmp: $E53
}
PORT_FN(0x0040a3b0, "$E54(game.obj)", E54_game_lo, fp_lo_static_init)
static void __cdecl E53_game_lo() {
    LO_G8(0x00505834) = 0x0f;
}
PORT_FN(0x0040a3c0, "$E53(game.obj)", E53_game_lo, fp_lo_static_init)

// ---- countdwn.obj ----------------------------------------------------------------------------------------------------
// void __cdecl CountdownBegin(void)
static void __cdecl CountdownBegin_lo() {}
static void fp_CountdownBegin_lo(Footprint& f) { f.pure = true; }
PORT_FN(0x0040ac90, "CountdownBegin", CountdownBegin_lo, fp_CountdownBegin_lo)
// void __cdecl CountdownDraw(void)
static void __cdecl CountdownDraw_lo() {}
static void fp_CountdownDraw_lo(Footprint& f) { f.pure = true; }
PORT_FN(0x0040aca0, "CountdownDraw", CountdownDraw_lo, fp_CountdownDraw_lo)
// void __cdecl CountdownEnd(void)
static void __cdecl CountdownEnd_lo() {}
static void fp_CountdownEnd_lo(Footprint& f) { f.pure = true; }
PORT_FN(0x0040acb0, "CountdownEnd", CountdownEnd_lo, fp_CountdownEnd_lo)

// ---- postrace.obj ----------------------------------------------------------------------------------------------------
static void __cdecl E2_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040acd0)();    // jmp: $E1
}
PORT_FN(0x0040acc0, "$E2(postrace.obj)", E2_postrace_lo, fp_lo_static_init)
static void __cdecl E1_postrace_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x0040acd0, "$E1(postrace.obj)", E1_postrace_lo, fp_lo_static_init)
static void __cdecl E6_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040acf0)();    // jmp: $E5
}
PORT_FN(0x0040ace0, "$E6(postrace.obj)", E6_postrace_lo, fp_lo_static_init)
static void __cdecl E5_postrace_lo() {
    LO_G32(0x005058bc) = 0x00000000u;
}
PORT_FN(0x0040acf0, "$E5(postrace.obj)", E5_postrace_lo, fp_lo_static_init)
static void __cdecl E9_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040ad10)();    // jmp: $E8
}
PORT_FN(0x0040ad00, "$E9(postrace.obj)", E9_postrace_lo, fp_lo_static_init)
static void __cdecl E8_postrace_lo() {
    LO_G32(0x005058e8) = 0x001f001fu;
}
PORT_FN(0x0040ad10, "$E8(postrace.obj)", E8_postrace_lo, fp_lo_static_init)
static void __cdecl E12_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040ad30)();    // jmp: $E11
}
PORT_FN(0x0040ad20, "$E12(postrace.obj)", E12_postrace_lo, fp_lo_static_init)
static void __cdecl E11_postrace_lo() {
    LO_G32(0x005058d4) = 0x03e001e0u;
}
PORT_FN(0x0040ad30, "$E11(postrace.obj)", E11_postrace_lo, fp_lo_static_init)
static void __cdecl E15_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040ad50)();    // jmp: $E14
}
PORT_FN(0x0040ad40, "$E15(postrace.obj)", E15_postrace_lo, fp_lo_static_init)
static void __cdecl E14_postrace_lo() {
    LO_G32(0x00505930) = 0x03ef01efu;
}
PORT_FN(0x0040ad50, "$E14(postrace.obj)", E14_postrace_lo, fp_lo_static_init)
static void __cdecl E18_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040ad70)();    // jmp: $E17
}
PORT_FN(0x0040ad60, "$E18(postrace.obj)", E18_postrace_lo, fp_lo_static_init)
static void __cdecl E17_postrace_lo() {
    LO_G32(0x00505980) = 0x78003c00u;
}
PORT_FN(0x0040ad70, "$E17(postrace.obj)", E17_postrace_lo, fp_lo_static_init)
static void __cdecl E21_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040ad90)();    // jmp: $E20
}
PORT_FN(0x0040ad80, "$E21(postrace.obj)", E21_postrace_lo, fp_lo_static_init)
static void __cdecl E20_postrace_lo() {
    LO_G32(0x005058e4) = 0x780f3c0fu;
}
PORT_FN(0x0040ad90, "$E20(postrace.obj)", E20_postrace_lo, fp_lo_static_init)
static void __cdecl E24_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040adb0)();    // jmp: $E23
}
PORT_FN(0x0040ada0, "$E24(postrace.obj)", E24_postrace_lo, fp_lo_static_init)
static void __cdecl E23_postrace_lo() {
    LO_G32(0x00505968) = 0x7be03de0u;
}
PORT_FN(0x0040adb0, "$E23(postrace.obj)", E23_postrace_lo, fp_lo_static_init)
static void __cdecl E27_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040add0)();    // jmp: $E26
}
PORT_FN(0x0040adc0, "$E27(postrace.obj)", E27_postrace_lo, fp_lo_static_init)
static void __cdecl E26_postrace_lo() {
    LO_G32(0x005058e0) = 0x7bef3defu;
}
PORT_FN(0x0040add0, "$E26(postrace.obj)", E26_postrace_lo, fp_lo_static_init)
static void __cdecl E30_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040adf0)();    // jmp: $E29
}
PORT_FN(0x0040ade0, "$E30(postrace.obj)", E30_postrace_lo, fp_lo_static_init)
static void __cdecl E29_postrace_lo() {
    LO_G32(0x00505964) = 0x42082108u;
}
PORT_FN(0x0040adf0, "$E29(postrace.obj)", E29_postrace_lo, fp_lo_static_init)
static void __cdecl E33_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040ae10)();    // jmp: $E32
}
PORT_FN(0x0040ae00, "$E33(postrace.obj)", E33_postrace_lo, fp_lo_static_init)
static void __cdecl E32_postrace_lo() {
    LO_G32(0x005058b8) = 0x001f001fu;
}
PORT_FN(0x0040ae10, "$E32(postrace.obj)", E32_postrace_lo, fp_lo_static_init)
static void __cdecl E36_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040ae30)();    // jmp: $E35
}
PORT_FN(0x0040ae20, "$E36(postrace.obj)", E36_postrace_lo, fp_lo_static_init)
static void __cdecl E35_postrace_lo() {
    LO_G32(0x0050597c) = 0x07e003e0u;
}
PORT_FN(0x0040ae30, "$E35(postrace.obj)", E35_postrace_lo, fp_lo_static_init)
static void __cdecl E39_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040ae50)();    // jmp: $E38
}
PORT_FN(0x0040ae40, "$E39(postrace.obj)", E39_postrace_lo, fp_lo_static_init)
static void __cdecl E38_postrace_lo() {
    LO_G32(0x005058d0) = 0x07ff03ffu;
}
PORT_FN(0x0040ae50, "$E38(postrace.obj)", E38_postrace_lo, fp_lo_static_init)
static void __cdecl E42_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040ae70)();    // jmp: $E41
}
PORT_FN(0x0040ae60, "$E42(postrace.obj)", E42_postrace_lo, fp_lo_static_init)
static void __cdecl E41_postrace_lo() {
    LO_G32(0x005058cc) = 0xf8007c00u;
}
PORT_FN(0x0040ae70, "$E41(postrace.obj)", E41_postrace_lo, fp_lo_static_init)
static void __cdecl E45_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040ae90)();    // jmp: $E44
}
PORT_FN(0x0040ae80, "$E45(postrace.obj)", E45_postrace_lo, fp_lo_static_init)
static void __cdecl E44_postrace_lo() {
    LO_G32(0x00505984) = 0xf81f7c1fu;
}
PORT_FN(0x0040ae90, "$E44(postrace.obj)", E44_postrace_lo, fp_lo_static_init)
static void __cdecl E48_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040aeb0)();    // jmp: $E47
}
PORT_FN(0x0040aea0, "$E48(postrace.obj)", E48_postrace_lo, fp_lo_static_init)
static void __cdecl E47_postrace_lo() {
    LO_G32(0x00505944) = 0xffe07fe0u;
}
PORT_FN(0x0040aeb0, "$E47(postrace.obj)", E47_postrace_lo, fp_lo_static_init)
static void __cdecl E51_postrace_lo() {
    LO_FN(LoVoid_t, 0x0040aed0)();    // jmp: $E50
}
PORT_FN(0x0040aec0, "$E51(postrace.obj)", E51_postrace_lo, fp_lo_static_init)
static void __cdecl E50_postrace_lo() {
    LO_G32(0x005058dc) = 0xffff7fffu;
}
PORT_FN(0x0040aed0, "$E50(postrace.obj)", E50_postrace_lo, fp_lo_static_init)
static void __cdecl E68_postrace_lo() {}    // ret
PORT_FN(0x0040b610, "$E68(postrace.obj)", E68_postrace_lo, fp_lo_static_init)
static void __cdecl E67_postrace_lo() {}    // ret
PORT_FN(0x0040b620, "$E67(postrace.obj)", E67_postrace_lo, fp_lo_static_init)
static void __cdecl E66_postrace_lo() {}    // ret
PORT_FN(0x0040b630, "$E66(postrace.obj)", E66_postrace_lo, fp_lo_static_init)
static void __cdecl E65_postrace_lo() {}    // ret
PORT_FN(0x0040b640, "$E65(postrace.obj)", E65_postrace_lo, fp_lo_static_init)
static void __cdecl E64_postrace_lo() {}    // ret
PORT_FN(0x0040b650, "$E64(postrace.obj)", E64_postrace_lo, fp_lo_static_init)
static void __cdecl E76_postrace_lo() {}    // ret
PORT_FN(0x0040bd00, "$E76(postrace.obj)", E76_postrace_lo, fp_lo_static_init)
static void __cdecl E75_postrace_lo() {}    // ret
PORT_FN(0x0040bd10, "$E75(postrace.obj)", E75_postrace_lo, fp_lo_static_init)
static void __cdecl E74_postrace_lo() {}    // ret
PORT_FN(0x0040bd20, "$E74(postrace.obj)", E74_postrace_lo, fp_lo_static_init)
static void __cdecl E73_postrace_lo() {}    // ret
PORT_FN(0x0040bd30, "$E73(postrace.obj)", E73_postrace_lo, fp_lo_static_init)
static void __cdecl E72_postrace_lo() {}    // ret
PORT_FN(0x0040bd40, "$E72(postrace.obj)", E72_postrace_lo, fp_lo_static_init)
static void __cdecl E71_postrace_lo() {}    // ret
PORT_FN(0x0040bd50, "$E71(postrace.obj)", E71_postrace_lo, fp_lo_static_init)
static void __cdecl E70_postrace_lo() {}    // ret
PORT_FN(0x0040bd60, "$E70(postrace.obj)", E70_postrace_lo, fp_lo_static_init)

// ---- escape.obj ------------------------------------------------------------------------------------------------------
static void __cdecl E2_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c310)();    // jmp: $E1
}
PORT_FN(0x0040c300, "$E2(escape.obj)", E2_escape_lo, fp_lo_static_init)
static void __cdecl E1_escape_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x0040c310, "$E1(escape.obj)", E1_escape_lo, fp_lo_static_init)
static void __cdecl E6_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c330)();    // jmp: $E5
}
PORT_FN(0x0040c320, "$E6(escape.obj)", E6_escape_lo, fp_lo_static_init)
static void __cdecl E5_escape_lo() {
    LO_G32(0x005059c4) = 0x00000000u;
}
PORT_FN(0x0040c330, "$E5(escape.obj)", E5_escape_lo, fp_lo_static_init)
static void __cdecl E9_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c350)();    // jmp: $E8
}
PORT_FN(0x0040c340, "$E9(escape.obj)", E9_escape_lo, fp_lo_static_init)
static void __cdecl E8_escape_lo() {
    LO_G32(0x005059e0) = 0x001f001fu;
}
PORT_FN(0x0040c350, "$E8(escape.obj)", E8_escape_lo, fp_lo_static_init)
static void __cdecl E12_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c370)();    // jmp: $E11
}
PORT_FN(0x0040c360, "$E12(escape.obj)", E12_escape_lo, fp_lo_static_init)
static void __cdecl E11_escape_lo() {
    LO_G32(0x005059d0) = 0x03e001e0u;
}
PORT_FN(0x0040c370, "$E11(escape.obj)", E11_escape_lo, fp_lo_static_init)
static void __cdecl E15_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c390)();    // jmp: $E14
}
PORT_FN(0x0040c380, "$E15(escape.obj)", E15_escape_lo, fp_lo_static_init)
static void __cdecl E14_escape_lo() {
    LO_G32(0x005059e4) = 0x03ef01efu;
}
PORT_FN(0x0040c390, "$E14(escape.obj)", E14_escape_lo, fp_lo_static_init)
static void __cdecl E18_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c3b0)();    // jmp: $E17
}
PORT_FN(0x0040c3a0, "$E18(escape.obj)", E18_escape_lo, fp_lo_static_init)
static void __cdecl E17_escape_lo() {
    LO_G32(0x005059fc) = 0x78003c00u;
}
PORT_FN(0x0040c3b0, "$E17(escape.obj)", E17_escape_lo, fp_lo_static_init)
static void __cdecl E21_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c3d0)();    // jmp: $E20
}
PORT_FN(0x0040c3c0, "$E21(escape.obj)", E21_escape_lo, fp_lo_static_init)
static void __cdecl E20_escape_lo() {
    LO_G32(0x005059dc) = 0x780f3c0fu;
}
PORT_FN(0x0040c3d0, "$E20(escape.obj)", E20_escape_lo, fp_lo_static_init)
static void __cdecl E24_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c3f0)();    // jmp: $E23
}
PORT_FN(0x0040c3e0, "$E24(escape.obj)", E24_escape_lo, fp_lo_static_init)
static void __cdecl E23_escape_lo() {
    LO_G32(0x005059f0) = 0x7be03de0u;
}
PORT_FN(0x0040c3f0, "$E23(escape.obj)", E23_escape_lo, fp_lo_static_init)
static void __cdecl E27_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c410)();    // jmp: $E26
}
PORT_FN(0x0040c400, "$E27(escape.obj)", E27_escape_lo, fp_lo_static_init)
static void __cdecl E26_escape_lo() {
    LO_G32(0x005059d8) = 0x7bef3defu;
}
PORT_FN(0x0040c410, "$E26(escape.obj)", E26_escape_lo, fp_lo_static_init)
static void __cdecl E30_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c430)();    // jmp: $E29
}
PORT_FN(0x0040c420, "$E30(escape.obj)", E30_escape_lo, fp_lo_static_init)
static void __cdecl E29_escape_lo() {
    LO_G32(0x005059ec) = 0x42082108u;
}
PORT_FN(0x0040c430, "$E29(escape.obj)", E29_escape_lo, fp_lo_static_init)
static void __cdecl E33_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c450)();    // jmp: $E32
}
PORT_FN(0x0040c440, "$E33(escape.obj)", E33_escape_lo, fp_lo_static_init)
static void __cdecl E32_escape_lo() {
    LO_G32(0x005059b8) = 0x001f001fu;
}
PORT_FN(0x0040c450, "$E32(escape.obj)", E32_escape_lo, fp_lo_static_init)
static void __cdecl E36_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c470)();    // jmp: $E35
}
PORT_FN(0x0040c460, "$E36(escape.obj)", E36_escape_lo, fp_lo_static_init)
static void __cdecl E35_escape_lo() {
    LO_G32(0x005059f8) = 0x07e003e0u;
}
PORT_FN(0x0040c470, "$E35(escape.obj)", E35_escape_lo, fp_lo_static_init)
static void __cdecl E39_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c490)();    // jmp: $E38
}
PORT_FN(0x0040c480, "$E39(escape.obj)", E39_escape_lo, fp_lo_static_init)
static void __cdecl E38_escape_lo() {
    LO_G32(0x005059cc) = 0x07ff03ffu;
}
PORT_FN(0x0040c490, "$E38(escape.obj)", E38_escape_lo, fp_lo_static_init)
static void __cdecl E42_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c4b0)();    // jmp: $E41
}
PORT_FN(0x0040c4a0, "$E42(escape.obj)", E42_escape_lo, fp_lo_static_init)
static void __cdecl E41_escape_lo() {
    LO_G32(0x005059c8) = 0xf8007c00u;
}
PORT_FN(0x0040c4b0, "$E41(escape.obj)", E41_escape_lo, fp_lo_static_init)
static void __cdecl E45_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c4d0)();    // jmp: $E44
}
PORT_FN(0x0040c4c0, "$E45(escape.obj)", E45_escape_lo, fp_lo_static_init)
static void __cdecl E44_escape_lo() {
    LO_G32(0x00505a00) = 0xf81f7c1fu;
}
PORT_FN(0x0040c4d0, "$E44(escape.obj)", E44_escape_lo, fp_lo_static_init)
static void __cdecl E48_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c4f0)();    // jmp: $E47
}
PORT_FN(0x0040c4e0, "$E48(escape.obj)", E48_escape_lo, fp_lo_static_init)
static void __cdecl E47_escape_lo() {
    LO_G32(0x005059e8) = 0xffe07fe0u;
}
PORT_FN(0x0040c4f0, "$E47(escape.obj)", E47_escape_lo, fp_lo_static_init)
static void __cdecl E51_escape_lo() {
    LO_FN(LoVoid_t, 0x0040c510)();    // jmp: $E50
}
PORT_FN(0x0040c500, "$E51(escape.obj)", E51_escape_lo, fp_lo_static_init)
static void __cdecl E50_escape_lo() {
    LO_G32(0x005059d4) = 0xffff7fffu;
}
PORT_FN(0x0040c510, "$E50(escape.obj)", E50_escape_lo, fp_lo_static_init)

// ---- root:splash.obj -------------------------------------------------------------------------------------------------
static void __cdecl E2_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c7d0)();    // jmp: $E1
}
PORT_FN(0x0040c7c0, "$E2(root:splash.obj)", E2_root_splash_lo, fp_lo_static_init)
static void __cdecl E1_root_splash_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x0040c7d0, "$E1(root:splash.obj)", E1_root_splash_lo, fp_lo_static_init)
static void __cdecl E6_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c7f0)();    // jmp: $E5
}
PORT_FN(0x0040c7e0, "$E6(root:splash.obj)", E6_root_splash_lo, fp_lo_static_init)
static void __cdecl E5_root_splash_lo() {
    LO_G32(0x00505a10) = 0x00000000u;
}
PORT_FN(0x0040c7f0, "$E5(root:splash.obj)", E5_root_splash_lo, fp_lo_static_init)
static void __cdecl E9_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c810)();    // jmp: $E8
}
PORT_FN(0x0040c800, "$E9(root:splash.obj)", E9_root_splash_lo, fp_lo_static_init)
static void __cdecl E8_root_splash_lo() {
    LO_G32(0x00505a68) = 0x001f001fu;
}
PORT_FN(0x0040c810, "$E8(root:splash.obj)", E8_root_splash_lo, fp_lo_static_init)
static void __cdecl E12_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c830)();    // jmp: $E11
}
PORT_FN(0x0040c820, "$E12(root:splash.obj)", E12_root_splash_lo, fp_lo_static_init)
static void __cdecl E11_root_splash_lo() {
    LO_G32(0x00505a1c) = 0x03e001e0u;
}
PORT_FN(0x0040c830, "$E11(root:splash.obj)", E11_root_splash_lo, fp_lo_static_init)
static void __cdecl E15_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c850)();    // jmp: $E14
}
PORT_FN(0x0040c840, "$E15(root:splash.obj)", E15_root_splash_lo, fp_lo_static_init)
static void __cdecl E14_root_splash_lo() {
    LO_G32(0x00505a94) = 0x03ef01efu;
}
PORT_FN(0x0040c850, "$E14(root:splash.obj)", E14_root_splash_lo, fp_lo_static_init)
static void __cdecl E18_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c870)();    // jmp: $E17
}
PORT_FN(0x0040c860, "$E18(root:splash.obj)", E18_root_splash_lo, fp_lo_static_init)
static void __cdecl E17_root_splash_lo() {
    LO_G32(0x00505ac4) = 0x78003c00u;
}
PORT_FN(0x0040c870, "$E17(root:splash.obj)", E17_root_splash_lo, fp_lo_static_init)
static void __cdecl E21_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c890)();    // jmp: $E20
}
PORT_FN(0x0040c880, "$E21(root:splash.obj)", E21_root_splash_lo, fp_lo_static_init)
static void __cdecl E20_root_splash_lo() {
    LO_G32(0x00505a64) = 0x780f3c0fu;
}
PORT_FN(0x0040c890, "$E20(root:splash.obj)", E20_root_splash_lo, fp_lo_static_init)
static void __cdecl E24_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c8b0)();    // jmp: $E23
}
PORT_FN(0x0040c8a0, "$E24(root:splash.obj)", E24_root_splash_lo, fp_lo_static_init)
static void __cdecl E23_root_splash_lo() {
    LO_G32(0x00505ab8) = 0x7be03de0u;
}
PORT_FN(0x0040c8b0, "$E23(root:splash.obj)", E23_root_splash_lo, fp_lo_static_init)
static void __cdecl E27_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c8d0)();    // jmp: $E26
}
PORT_FN(0x0040c8c0, "$E27(root:splash.obj)", E27_root_splash_lo, fp_lo_static_init)
static void __cdecl E26_root_splash_lo() {
    LO_G32(0x00505a4c) = 0x7bef3defu;
}
PORT_FN(0x0040c8d0, "$E26(root:splash.obj)", E26_root_splash_lo, fp_lo_static_init)
static void __cdecl E30_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c8f0)();    // jmp: $E29
}
PORT_FN(0x0040c8e0, "$E30(root:splash.obj)", E30_root_splash_lo, fp_lo_static_init)
static void __cdecl E29_root_splash_lo() {
    LO_G32(0x00505ab4) = 0x42082108u;
}
PORT_FN(0x0040c8f0, "$E29(root:splash.obj)", E29_root_splash_lo, fp_lo_static_init)
static void __cdecl E33_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c910)();    // jmp: $E32
}
PORT_FN(0x0040c900, "$E33(root:splash.obj)", E33_root_splash_lo, fp_lo_static_init)
static void __cdecl E32_root_splash_lo() {
    LO_G32(0x00505a08) = 0x001f001fu;
}
PORT_FN(0x0040c910, "$E32(root:splash.obj)", E32_root_splash_lo, fp_lo_static_init)
static void __cdecl E36_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c930)();    // jmp: $E35
}
PORT_FN(0x0040c920, "$E36(root:splash.obj)", E36_root_splash_lo, fp_lo_static_init)
static void __cdecl E35_root_splash_lo() {
    LO_G32(0x00505ac0) = 0x07e003e0u;
}
PORT_FN(0x0040c930, "$E35(root:splash.obj)", E35_root_splash_lo, fp_lo_static_init)
static void __cdecl E39_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c950)();    // jmp: $E38
}
PORT_FN(0x0040c940, "$E39(root:splash.obj)", E39_root_splash_lo, fp_lo_static_init)
static void __cdecl E38_root_splash_lo() {
    LO_G32(0x00505a18) = 0x07ff03ffu;
}
PORT_FN(0x0040c950, "$E38(root:splash.obj)", E38_root_splash_lo, fp_lo_static_init)
static void __cdecl E42_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c970)();    // jmp: $E41
}
PORT_FN(0x0040c960, "$E42(root:splash.obj)", E42_root_splash_lo, fp_lo_static_init)
static void __cdecl E41_root_splash_lo() {
    LO_G32(0x00505a14) = 0xf8007c00u;
}
PORT_FN(0x0040c970, "$E41(root:splash.obj)", E41_root_splash_lo, fp_lo_static_init)
static void __cdecl E45_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c990)();    // jmp: $E44
}
PORT_FN(0x0040c980, "$E45(root:splash.obj)", E45_root_splash_lo, fp_lo_static_init)
static void __cdecl E44_root_splash_lo() {
    LO_G32(0x00505ac8) = 0xf81f7c1fu;
}
PORT_FN(0x0040c990, "$E44(root:splash.obj)", E44_root_splash_lo, fp_lo_static_init)
static void __cdecl E48_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c9b0)();    // jmp: $E47
}
PORT_FN(0x0040c9a0, "$E48(root:splash.obj)", E48_root_splash_lo, fp_lo_static_init)
static void __cdecl E47_root_splash_lo() {
    LO_G32(0x00505aa4) = 0xffe07fe0u;
}
PORT_FN(0x0040c9b0, "$E47(root:splash.obj)", E47_root_splash_lo, fp_lo_static_init)
static void __cdecl E51_root_splash_lo() {
    LO_FN(LoVoid_t, 0x0040c9d0)();    // jmp: $E50
}
PORT_FN(0x0040c9c0, "$E51(root:splash.obj)", E51_root_splash_lo, fp_lo_static_init)
static void __cdecl E50_root_splash_lo() {
    LO_G32(0x00505a48) = 0xffff7fffu;
}
PORT_FN(0x0040c9d0, "$E50(root:splash.obj)", E50_root_splash_lo, fp_lo_static_init)
static void __cdecl E54_root_splash_lo() {}    // ret
PORT_FN(0x0040cc30, "$E54(root:splash.obj)", E54_root_splash_lo, fp_lo_static_init)
static void __cdecl E56_root_splash_lo() {}    // ret
PORT_FN(0x0040cd90, "$E56(root:splash.obj)", E56_root_splash_lo, fp_lo_static_init)
static void __cdecl E58_root_splash_lo() {}    // ret
PORT_FN(0x0040ce10, "$E58(root:splash.obj)", E58_root_splash_lo, fp_lo_static_init)
static void __cdecl E60_root_splash_lo() {}    // ret
PORT_FN(0x0040ce90, "$E60(root:splash.obj)", E60_root_splash_lo, fp_lo_static_init)
static void __cdecl E62_root_splash_lo() {}    // ret
PORT_FN(0x0040cf10, "$E62(root:splash.obj)", E62_root_splash_lo, fp_lo_static_init)
static void __cdecl E64_root_splash_lo() {}    // ret
PORT_FN(0x0040cf90, "$E64(root:splash.obj)", E64_root_splash_lo, fp_lo_static_init)

// ---- hack.obj --------------------------------------------------------------------------------------------------------
static void __cdecl E2_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d140)();    // jmp: $E1
}
PORT_FN(0x0040d130, "$E2(hack.obj)", E2_hack_lo, fp_lo_static_init)
static void __cdecl E1_hack_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x0040d140, "$E1(hack.obj)", E1_hack_lo, fp_lo_static_init)
static void __cdecl E6_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d160)();    // jmp: $E5
}
PORT_FN(0x0040d150, "$E6(hack.obj)", E6_hack_lo, fp_lo_static_init)
static void __cdecl E5_hack_lo() {
    LO_G32(0x00505aec) = 0x00000000u;
}
PORT_FN(0x0040d160, "$E5(hack.obj)", E5_hack_lo, fp_lo_static_init)
static void __cdecl E9_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d180)();    // jmp: $E8
}
PORT_FN(0x0040d170, "$E9(hack.obj)", E9_hack_lo, fp_lo_static_init)
static void __cdecl E8_hack_lo() {
    LO_G32(0x00505b10) = 0x001f001fu;
}
PORT_FN(0x0040d180, "$E8(hack.obj)", E8_hack_lo, fp_lo_static_init)
static void __cdecl E12_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d1a0)();    // jmp: $E11
}
PORT_FN(0x0040d190, "$E12(hack.obj)", E12_hack_lo, fp_lo_static_init)
static void __cdecl E11_hack_lo() {
    LO_G32(0x00505af8) = 0x03e001e0u;
}
PORT_FN(0x0040d1a0, "$E11(hack.obj)", E11_hack_lo, fp_lo_static_init)
static void __cdecl E15_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d1c0)();    // jmp: $E14
}
PORT_FN(0x0040d1b0, "$E15(hack.obj)", E15_hack_lo, fp_lo_static_init)
static void __cdecl E14_hack_lo() {
    LO_G32(0x00505b20) = 0x03ef01efu;
}
PORT_FN(0x0040d1c0, "$E14(hack.obj)", E14_hack_lo, fp_lo_static_init)
static void __cdecl E18_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d1e0)();    // jmp: $E17
}
PORT_FN(0x0040d1d0, "$E18(hack.obj)", E18_hack_lo, fp_lo_static_init)
static void __cdecl E17_hack_lo() {
    LO_G32(0x00505b38) = 0x78003c00u;
}
PORT_FN(0x0040d1e0, "$E17(hack.obj)", E17_hack_lo, fp_lo_static_init)
static void __cdecl E21_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d200)();    // jmp: $E20
}
PORT_FN(0x0040d1f0, "$E21(hack.obj)", E21_hack_lo, fp_lo_static_init)
static void __cdecl E20_hack_lo() {
    LO_G32(0x00505b08) = 0x780f3c0fu;
}
PORT_FN(0x0040d200, "$E20(hack.obj)", E20_hack_lo, fp_lo_static_init)
static void __cdecl E24_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d220)();    // jmp: $E23
}
PORT_FN(0x0040d210, "$E24(hack.obj)", E24_hack_lo, fp_lo_static_init)
static void __cdecl E23_hack_lo() {
    LO_G32(0x00505b2c) = 0x7be03de0u;
}
PORT_FN(0x0040d220, "$E23(hack.obj)", E23_hack_lo, fp_lo_static_init)
static void __cdecl E27_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d240)();    // jmp: $E26
}
PORT_FN(0x0040d230, "$E27(hack.obj)", E27_hack_lo, fp_lo_static_init)
static void __cdecl E26_hack_lo() {
    LO_G32(0x00505b04) = 0x7bef3defu;
}
PORT_FN(0x0040d240, "$E26(hack.obj)", E26_hack_lo, fp_lo_static_init)
static void __cdecl E30_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d260)();    // jmp: $E29
}
PORT_FN(0x0040d250, "$E30(hack.obj)", E30_hack_lo, fp_lo_static_init)
static void __cdecl E29_hack_lo() {
    LO_G32(0x00505b28) = 0x42082108u;
}
PORT_FN(0x0040d260, "$E29(hack.obj)", E29_hack_lo, fp_lo_static_init)
static void __cdecl E33_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d280)();    // jmp: $E32
}
PORT_FN(0x0040d270, "$E33(hack.obj)", E33_hack_lo, fp_lo_static_init)
static void __cdecl E32_hack_lo() {
    LO_G32(0x00505ae4) = 0x001f001fu;
}
PORT_FN(0x0040d280, "$E32(hack.obj)", E32_hack_lo, fp_lo_static_init)
static void __cdecl E36_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d2a0)();    // jmp: $E35
}
PORT_FN(0x0040d290, "$E36(hack.obj)", E36_hack_lo, fp_lo_static_init)
static void __cdecl E35_hack_lo() {
    LO_G32(0x00505b34) = 0x07e003e0u;
}
PORT_FN(0x0040d2a0, "$E35(hack.obj)", E35_hack_lo, fp_lo_static_init)
static void __cdecl E39_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d2c0)();    // jmp: $E38
}
PORT_FN(0x0040d2b0, "$E39(hack.obj)", E39_hack_lo, fp_lo_static_init)
static void __cdecl E38_hack_lo() {
    LO_G32(0x00505af4) = 0x07ff03ffu;
}
PORT_FN(0x0040d2c0, "$E38(hack.obj)", E38_hack_lo, fp_lo_static_init)
static void __cdecl E42_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d2e0)();    // jmp: $E41
}
PORT_FN(0x0040d2d0, "$E42(hack.obj)", E42_hack_lo, fp_lo_static_init)
static void __cdecl E41_hack_lo() {
    LO_G32(0x00505af0) = 0xf8007c00u;
}
PORT_FN(0x0040d2e0, "$E41(hack.obj)", E41_hack_lo, fp_lo_static_init)
static void __cdecl E45_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d300)();    // jmp: $E44
}
PORT_FN(0x0040d2f0, "$E45(hack.obj)", E45_hack_lo, fp_lo_static_init)
static void __cdecl E44_hack_lo() {
    LO_G32(0x00505b3c) = 0xf81f7c1fu;
}
PORT_FN(0x0040d300, "$E44(hack.obj)", E44_hack_lo, fp_lo_static_init)
static void __cdecl E48_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d320)();    // jmp: $E47
}
PORT_FN(0x0040d310, "$E48(hack.obj)", E48_hack_lo, fp_lo_static_init)
static void __cdecl E47_hack_lo() {
    LO_G32(0x00505b24) = 0xffe07fe0u;
}
PORT_FN(0x0040d320, "$E47(hack.obj)", E47_hack_lo, fp_lo_static_init)
static void __cdecl E51_hack_lo() {
    LO_FN(LoVoid_t, 0x0040d340)();    // jmp: $E50
}
PORT_FN(0x0040d330, "$E51(hack.obj)", E51_hack_lo, fp_lo_static_init)
static void __cdecl E50_hack_lo() {
    LO_G32(0x00505b00) = 0xffff7fffu;
}
PORT_FN(0x0040d340, "$E50(hack.obj)", E50_hack_lo, fp_lo_static_init)
// void __cdecl HackEnd(void)
static void __cdecl HackEnd_lo() {}
static void fp_HackEnd_lo(Footprint& f) { f.pure = true; }
PORT_FN(0x0040d4a0, "HackEnd", HackEnd_lo, fp_HackEnd_lo)

// ---- gxdash.obj ------------------------------------------------------------------------------------------------------
static void __cdecl E2_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d5d0)();    // jmp: $E1
}
PORT_FN(0x0040d5c0, "$E2(gxdash.obj)", E2_gxdash_lo, fp_lo_static_init)
static void __cdecl E1_gxdash_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x0040d5d0, "$E1(gxdash.obj)", E1_gxdash_lo, fp_lo_static_init)
static void __cdecl E6_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d5f0)();    // jmp: $E5
}
PORT_FN(0x0040d5e0, "$E6(gxdash.obj)", E6_gxdash_lo, fp_lo_static_init)
static void __cdecl E5_gxdash_lo() {
    LO_G32(0x00505b48) = 0x00000000u;
}
PORT_FN(0x0040d5f0, "$E5(gxdash.obj)", E5_gxdash_lo, fp_lo_static_init)
static void __cdecl E9_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d610)();    // jmp: $E8
}
PORT_FN(0x0040d600, "$E9(gxdash.obj)", E9_gxdash_lo, fp_lo_static_init)
static void __cdecl E8_gxdash_lo() {
    LO_G32(0x00505b64) = 0x001f001fu;
}
PORT_FN(0x0040d610, "$E8(gxdash.obj)", E8_gxdash_lo, fp_lo_static_init)
static void __cdecl E12_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d630)();    // jmp: $E11
}
PORT_FN(0x0040d620, "$E12(gxdash.obj)", E12_gxdash_lo, fp_lo_static_init)
static void __cdecl E11_gxdash_lo() {
    LO_G32(0x00505b54) = 0x03e001e0u;
}
PORT_FN(0x0040d630, "$E11(gxdash.obj)", E11_gxdash_lo, fp_lo_static_init)
static void __cdecl E15_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d650)();    // jmp: $E14
}
PORT_FN(0x0040d640, "$E15(gxdash.obj)", E15_gxdash_lo, fp_lo_static_init)
static void __cdecl E14_gxdash_lo() {
    LO_G32(0x00505b68) = 0x03ef01efu;
}
PORT_FN(0x0040d650, "$E14(gxdash.obj)", E14_gxdash_lo, fp_lo_static_init)
static void __cdecl E18_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d670)();    // jmp: $E17
}
PORT_FN(0x0040d660, "$E18(gxdash.obj)", E18_gxdash_lo, fp_lo_static_init)
static void __cdecl E17_gxdash_lo() {
    LO_G32(0x00505b80) = 0x78003c00u;
}
PORT_FN(0x0040d670, "$E17(gxdash.obj)", E17_gxdash_lo, fp_lo_static_init)
static void __cdecl E21_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d690)();    // jmp: $E20
}
PORT_FN(0x0040d680, "$E21(gxdash.obj)", E21_gxdash_lo, fp_lo_static_init)
static void __cdecl E20_gxdash_lo() {
    LO_G32(0x00505b60) = 0x780f3c0fu;
}
PORT_FN(0x0040d690, "$E20(gxdash.obj)", E20_gxdash_lo, fp_lo_static_init)
static void __cdecl E24_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d6b0)();    // jmp: $E23
}
PORT_FN(0x0040d6a0, "$E24(gxdash.obj)", E24_gxdash_lo, fp_lo_static_init)
static void __cdecl E23_gxdash_lo() {
    LO_G32(0x00505b74) = 0x7be03de0u;
}
PORT_FN(0x0040d6b0, "$E23(gxdash.obj)", E23_gxdash_lo, fp_lo_static_init)
static void __cdecl E27_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d6d0)();    // jmp: $E26
}
PORT_FN(0x0040d6c0, "$E27(gxdash.obj)", E27_gxdash_lo, fp_lo_static_init)
static void __cdecl E26_gxdash_lo() {
    LO_G32(0x00505b5c) = 0x7bef3defu;
}
PORT_FN(0x0040d6d0, "$E26(gxdash.obj)", E26_gxdash_lo, fp_lo_static_init)
static void __cdecl E30_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d6f0)();    // jmp: $E29
}
PORT_FN(0x0040d6e0, "$E30(gxdash.obj)", E30_gxdash_lo, fp_lo_static_init)
static void __cdecl E29_gxdash_lo() {
    LO_G32(0x00505b70) = 0x42082108u;
}
PORT_FN(0x0040d6f0, "$E29(gxdash.obj)", E29_gxdash_lo, fp_lo_static_init)
static void __cdecl E33_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d710)();    // jmp: $E32
}
PORT_FN(0x0040d700, "$E33(gxdash.obj)", E33_gxdash_lo, fp_lo_static_init)
static void __cdecl E32_gxdash_lo() {
    LO_G32(0x00505b44) = 0x001f001fu;
}
PORT_FN(0x0040d710, "$E32(gxdash.obj)", E32_gxdash_lo, fp_lo_static_init)
static void __cdecl E36_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d730)();    // jmp: $E35
}
PORT_FN(0x0040d720, "$E36(gxdash.obj)", E36_gxdash_lo, fp_lo_static_init)
static void __cdecl E35_gxdash_lo() {
    LO_G32(0x00505b7c) = 0x07e003e0u;
}
PORT_FN(0x0040d730, "$E35(gxdash.obj)", E35_gxdash_lo, fp_lo_static_init)
static void __cdecl E39_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d750)();    // jmp: $E38
}
PORT_FN(0x0040d740, "$E39(gxdash.obj)", E39_gxdash_lo, fp_lo_static_init)
static void __cdecl E38_gxdash_lo() {
    LO_G32(0x00505b50) = 0x07ff03ffu;
}
PORT_FN(0x0040d750, "$E38(gxdash.obj)", E38_gxdash_lo, fp_lo_static_init)
static void __cdecl E42_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d770)();    // jmp: $E41
}
PORT_FN(0x0040d760, "$E42(gxdash.obj)", E42_gxdash_lo, fp_lo_static_init)
static void __cdecl E41_gxdash_lo() {
    LO_G32(0x00505b4c) = 0xf8007c00u;
}
PORT_FN(0x0040d770, "$E41(gxdash.obj)", E41_gxdash_lo, fp_lo_static_init)
static void __cdecl E45_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d790)();    // jmp: $E44
}
PORT_FN(0x0040d780, "$E45(gxdash.obj)", E45_gxdash_lo, fp_lo_static_init)
static void __cdecl E44_gxdash_lo() {
    LO_G32(0x00505b84) = 0xf81f7c1fu;
}
PORT_FN(0x0040d790, "$E44(gxdash.obj)", E44_gxdash_lo, fp_lo_static_init)
static void __cdecl E48_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d7b0)();    // jmp: $E47
}
PORT_FN(0x0040d7a0, "$E48(gxdash.obj)", E48_gxdash_lo, fp_lo_static_init)
static void __cdecl E47_gxdash_lo() {
    LO_G32(0x00505b6c) = 0xffe07fe0u;
}
PORT_FN(0x0040d7b0, "$E47(gxdash.obj)", E47_gxdash_lo, fp_lo_static_init)
static void __cdecl E51_gxdash_lo() {
    LO_FN(LoVoid_t, 0x0040d7d0)();    // jmp: $E50
}
PORT_FN(0x0040d7c0, "$E51(gxdash.obj)", E51_gxdash_lo, fp_lo_static_init)
static void __cdecl E50_gxdash_lo() {
    LO_G32(0x00505b58) = 0xffff7fffu;
}
PORT_FN(0x0040d7d0, "$E50(gxdash.obj)", E50_gxdash_lo, fp_lo_static_init)

// ---- ghost.obj -------------------------------------------------------------------------------------------------------
static void __cdecl E2_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040d9f0)();    // jmp: $E1
}
PORT_FN(0x0040d9e0, "$E2(ghost.obj)", E2_ghost_lo, fp_lo_static_init)
static void __cdecl E1_ghost_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x0040d9f0, "$E1(ghost.obj)", E1_ghost_lo, fp_lo_static_init)
static void __cdecl E6_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040da10)();    // jmp: $E5
}
PORT_FN(0x0040da00, "$E6(ghost.obj)", E6_ghost_lo, fp_lo_static_init)
static void __cdecl E5_ghost_lo() {
    LO_G32(0x00505b90) = 0x00000000u;
}
PORT_FN(0x0040da10, "$E5(ghost.obj)", E5_ghost_lo, fp_lo_static_init)
static void __cdecl E9_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040da30)();    // jmp: $E8
}
PORT_FN(0x0040da20, "$E9(ghost.obj)", E9_ghost_lo, fp_lo_static_init)
static void __cdecl E8_ghost_lo() {
    LO_G32(0x00505bb4) = 0x001f001fu;
}
PORT_FN(0x0040da30, "$E8(ghost.obj)", E8_ghost_lo, fp_lo_static_init)
static void __cdecl E12_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040da50)();    // jmp: $E11
}
PORT_FN(0x0040da40, "$E12(ghost.obj)", E12_ghost_lo, fp_lo_static_init)
static void __cdecl E11_ghost_lo() {
    LO_G32(0x00505ba0) = 0x03e001e0u;
}
PORT_FN(0x0040da50, "$E11(ghost.obj)", E11_ghost_lo, fp_lo_static_init)
static void __cdecl E15_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040da70)();    // jmp: $E14
}
PORT_FN(0x0040da60, "$E15(ghost.obj)", E15_ghost_lo, fp_lo_static_init)
static void __cdecl E14_ghost_lo() {
    LO_G32(0x00505bbc) = 0x03ef01efu;
}
PORT_FN(0x0040da70, "$E14(ghost.obj)", E14_ghost_lo, fp_lo_static_init)
static void __cdecl E18_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040da90)();    // jmp: $E17
}
PORT_FN(0x0040da80, "$E18(ghost.obj)", E18_ghost_lo, fp_lo_static_init)
static void __cdecl E17_ghost_lo() {
    LO_G32(0x00505c28) = 0x78003c00u;
}
PORT_FN(0x0040da90, "$E17(ghost.obj)", E17_ghost_lo, fp_lo_static_init)
static void __cdecl E21_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040dab0)();    // jmp: $E20
}
PORT_FN(0x0040daa0, "$E21(ghost.obj)", E21_ghost_lo, fp_lo_static_init)
static void __cdecl E20_ghost_lo() {
    LO_G32(0x00505bb0) = 0x780f3c0fu;
}
PORT_FN(0x0040dab0, "$E20(ghost.obj)", E20_ghost_lo, fp_lo_static_init)
static void __cdecl E24_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040dad0)();    // jmp: $E23
}
PORT_FN(0x0040dac0, "$E24(ghost.obj)", E24_ghost_lo, fp_lo_static_init)
static void __cdecl E23_ghost_lo() {
    LO_G32(0x00505c1c) = 0x7be03de0u;
}
PORT_FN(0x0040dad0, "$E23(ghost.obj)", E23_ghost_lo, fp_lo_static_init)
static void __cdecl E27_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040daf0)();    // jmp: $E26
}
PORT_FN(0x0040dae0, "$E27(ghost.obj)", E27_ghost_lo, fp_lo_static_init)
static void __cdecl E26_ghost_lo() {
    LO_G32(0x00505bac) = 0x7bef3defu;
}
PORT_FN(0x0040daf0, "$E26(ghost.obj)", E26_ghost_lo, fp_lo_static_init)
static void __cdecl E30_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040db10)();    // jmp: $E29
}
PORT_FN(0x0040db00, "$E30(ghost.obj)", E30_ghost_lo, fp_lo_static_init)
static void __cdecl E29_ghost_lo() {
    LO_G32(0x00505c18) = 0x42082108u;
}
PORT_FN(0x0040db10, "$E29(ghost.obj)", E29_ghost_lo, fp_lo_static_init)
static void __cdecl E33_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040db30)();    // jmp: $E32
}
PORT_FN(0x0040db20, "$E33(ghost.obj)", E33_ghost_lo, fp_lo_static_init)
static void __cdecl E32_ghost_lo() {
    LO_G32(0x00505b8c) = 0x001f001fu;
}
PORT_FN(0x0040db30, "$E32(ghost.obj)", E32_ghost_lo, fp_lo_static_init)
static void __cdecl E36_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040db50)();    // jmp: $E35
}
PORT_FN(0x0040db40, "$E36(ghost.obj)", E36_ghost_lo, fp_lo_static_init)
static void __cdecl E35_ghost_lo() {
    LO_G32(0x00505c24) = 0x07e003e0u;
}
PORT_FN(0x0040db50, "$E35(ghost.obj)", E35_ghost_lo, fp_lo_static_init)
static void __cdecl E39_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040db70)();    // jmp: $E38
}
PORT_FN(0x0040db60, "$E39(ghost.obj)", E39_ghost_lo, fp_lo_static_init)
static void __cdecl E38_ghost_lo() {
    LO_G32(0x00505b9c) = 0x07ff03ffu;
}
PORT_FN(0x0040db70, "$E38(ghost.obj)", E38_ghost_lo, fp_lo_static_init)
static void __cdecl E42_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040db90)();    // jmp: $E41
}
PORT_FN(0x0040db80, "$E42(ghost.obj)", E42_ghost_lo, fp_lo_static_init)
static void __cdecl E41_ghost_lo() {
    LO_G32(0x00505b98) = 0xf8007c00u;
}
PORT_FN(0x0040db90, "$E41(ghost.obj)", E41_ghost_lo, fp_lo_static_init)
static void __cdecl E45_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040dbb0)();    // jmp: $E44
}
PORT_FN(0x0040dba0, "$E45(ghost.obj)", E45_ghost_lo, fp_lo_static_init)
static void __cdecl E44_ghost_lo() {
    LO_G32(0x00505c2c) = 0xf81f7c1fu;
}
PORT_FN(0x0040dbb0, "$E44(ghost.obj)", E44_ghost_lo, fp_lo_static_init)
static void __cdecl E48_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040dbd0)();    // jmp: $E47
}
PORT_FN(0x0040dbc0, "$E48(ghost.obj)", E48_ghost_lo, fp_lo_static_init)
static void __cdecl E47_ghost_lo() {
    LO_G32(0x00505c14) = 0xffe07fe0u;
}
PORT_FN(0x0040dbd0, "$E47(ghost.obj)", E47_ghost_lo, fp_lo_static_init)
static void __cdecl E51_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040dbf0)();    // jmp: $E50
}
PORT_FN(0x0040dbe0, "$E51(ghost.obj)", E51_ghost_lo, fp_lo_static_init)
static void __cdecl E50_ghost_lo() {
    LO_G32(0x00505ba8) = 0xffff7fffu;
}
PORT_FN(0x0040dbf0, "$E50(ghost.obj)", E50_ghost_lo, fp_lo_static_init)
static void __cdecl E54_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040dc10)();    // jmp: $E53
}
PORT_FN(0x0040dc00, "$E54(ghost.obj)", E54_ghost_lo, fp_lo_static_init)
static void __cdecl E53_ghost_lo() {
    LO_G8(0x00505b94) = 0x0f;
}
PORT_FN(0x0040dc10, "$E53(ghost.obj)", E53_ghost_lo, fp_lo_static_init)
static void __cdecl E60_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040dc30)();    // jmp: $E59
}
PORT_FN(0x0040dc20, "$E60(ghost.obj)", E60_ghost_lo, fp_lo_static_init)
static void __cdecl E59_ghost_lo() {
    LO_G32(0x00505b88) = 0x00000960u;
}
PORT_FN(0x0040dc30, "$E59(ghost.obj)", E59_ghost_lo, fp_lo_static_init)
static void __cdecl E63_ghost_lo() {
    LO_FN(LoVoid_t, 0x0040dc50)();    // jmp: $E62
}
PORT_FN(0x0040dc40, "$E63(ghost.obj)", E63_ghost_lo, fp_lo_static_init)

// ---- prerace.obj -----------------------------------------------------------------------------------------------------
static void __cdecl E2_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040ef10)();    // jmp: $E1
}
PORT_FN(0x0040ef00, "$E2(prerace.obj)", E2_prerace_lo, fp_lo_static_init)
static void __cdecl E1_prerace_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x0040ef10, "$E1(prerace.obj)", E1_prerace_lo, fp_lo_static_init)
static void __cdecl E6_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040ef30)();    // jmp: $E5
}
PORT_FN(0x0040ef20, "$E6(prerace.obj)", E6_prerace_lo, fp_lo_static_init)
static void __cdecl E5_prerace_lo() {
    LO_G32(0x00505c88) = 0x00000000u;
}
PORT_FN(0x0040ef30, "$E5(prerace.obj)", E5_prerace_lo, fp_lo_static_init)
static void __cdecl E9_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040ef50)();    // jmp: $E8
}
PORT_FN(0x0040ef40, "$E9(prerace.obj)", E9_prerace_lo, fp_lo_static_init)
static void __cdecl E8_prerace_lo() {
    LO_G32(0x00505d78) = 0x001f001fu;
}
PORT_FN(0x0040ef50, "$E8(prerace.obj)", E8_prerace_lo, fp_lo_static_init)
static void __cdecl E12_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040ef70)();    // jmp: $E11
}
PORT_FN(0x0040ef60, "$E12(prerace.obj)", E12_prerace_lo, fp_lo_static_init)
static void __cdecl E11_prerace_lo() {
    LO_G32(0x00505cc4) = 0x03e001e0u;
}
PORT_FN(0x0040ef70, "$E11(prerace.obj)", E11_prerace_lo, fp_lo_static_init)
static void __cdecl E15_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040ef90)();    // jmp: $E14
}
PORT_FN(0x0040ef80, "$E15(prerace.obj)", E15_prerace_lo, fp_lo_static_init)
static void __cdecl E14_prerace_lo() {
    LO_G32(0x00505dec) = 0x03ef01efu;
}
PORT_FN(0x0040ef90, "$E14(prerace.obj)", E14_prerace_lo, fp_lo_static_init)
static void __cdecl E18_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040efb0)();    // jmp: $E17
}
PORT_FN(0x0040efa0, "$E18(prerace.obj)", E18_prerace_lo, fp_lo_static_init)
static void __cdecl E17_prerace_lo() {
    LO_G32(0x00505e50) = 0x78003c00u;
}
PORT_FN(0x0040efb0, "$E17(prerace.obj)", E17_prerace_lo, fp_lo_static_init)
static void __cdecl E21_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040efd0)();    // jmp: $E20
}
PORT_FN(0x0040efc0, "$E21(prerace.obj)", E21_prerace_lo, fp_lo_static_init)
static void __cdecl E20_prerace_lo() {
    LO_G32(0x00505d30) = 0x780f3c0fu;
}
PORT_FN(0x0040efd0, "$E20(prerace.obj)", E20_prerace_lo, fp_lo_static_init)
static void __cdecl E24_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040eff0)();    // jmp: $E23
}
PORT_FN(0x0040efe0, "$E24(prerace.obj)", E24_prerace_lo, fp_lo_static_init)
static void __cdecl E23_prerace_lo() {
    LO_G32(0x00505e34) = 0x7be03de0u;
}
PORT_FN(0x0040eff0, "$E23(prerace.obj)", E23_prerace_lo, fp_lo_static_init)
static void __cdecl E27_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040f010)();    // jmp: $E26
}
PORT_FN(0x0040f000, "$E27(prerace.obj)", E27_prerace_lo, fp_lo_static_init)
static void __cdecl E26_prerace_lo() {
    LO_G32(0x00505d2c) = 0x7bef3defu;
}
PORT_FN(0x0040f010, "$E26(prerace.obj)", E26_prerace_lo, fp_lo_static_init)
static void __cdecl E30_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040f030)();    // jmp: $E29
}
PORT_FN(0x0040f020, "$E30(prerace.obj)", E30_prerace_lo, fp_lo_static_init)
static void __cdecl E29_prerace_lo() {
    LO_G32(0x00505e30) = 0x42082108u;
}
PORT_FN(0x0040f030, "$E29(prerace.obj)", E29_prerace_lo, fp_lo_static_init)
static void __cdecl E33_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040f050)();    // jmp: $E32
}
PORT_FN(0x0040f040, "$E33(prerace.obj)", E33_prerace_lo, fp_lo_static_init)
static void __cdecl E32_prerace_lo() {
    LO_G32(0x00505c30) = 0x001f001fu;
}
PORT_FN(0x0040f050, "$E32(prerace.obj)", E32_prerace_lo, fp_lo_static_init)
static void __cdecl E36_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040f070)();    // jmp: $E35
}
PORT_FN(0x0040f060, "$E36(prerace.obj)", E36_prerace_lo, fp_lo_static_init)
static void __cdecl E35_prerace_lo() {
    LO_G32(0x00505e4c) = 0x07e003e0u;
}
PORT_FN(0x0040f070, "$E35(prerace.obj)", E35_prerace_lo, fp_lo_static_init)
static void __cdecl E39_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040f090)();    // jmp: $E38
}
PORT_FN(0x0040f080, "$E39(prerace.obj)", E39_prerace_lo, fp_lo_static_init)
static void __cdecl E38_prerace_lo() {
    LO_G32(0x00505cc0) = 0x07ff03ffu;
}
PORT_FN(0x0040f090, "$E38(prerace.obj)", E38_prerace_lo, fp_lo_static_init)
static void __cdecl E42_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040f0b0)();    // jmp: $E41
}
PORT_FN(0x0040f0a0, "$E42(prerace.obj)", E42_prerace_lo, fp_lo_static_init)
static void __cdecl E41_prerace_lo() {
    LO_G32(0x00505cbc) = 0xf8007c00u;
}
PORT_FN(0x0040f0b0, "$E41(prerace.obj)", E41_prerace_lo, fp_lo_static_init)
static void __cdecl E45_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040f0d0)();    // jmp: $E44
}
PORT_FN(0x0040f0c0, "$E45(prerace.obj)", E45_prerace_lo, fp_lo_static_init)
static void __cdecl E44_prerace_lo() {
    LO_G32(0x00505e54) = 0xf81f7c1fu;
}
PORT_FN(0x0040f0d0, "$E44(prerace.obj)", E44_prerace_lo, fp_lo_static_init)
static void __cdecl E48_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040f0f0)();    // jmp: $E47
}
PORT_FN(0x0040f0e0, "$E48(prerace.obj)", E48_prerace_lo, fp_lo_static_init)
static void __cdecl E47_prerace_lo() {
    LO_G32(0x00505e2c) = 0xffe07fe0u;
}
PORT_FN(0x0040f0f0, "$E47(prerace.obj)", E47_prerace_lo, fp_lo_static_init)
static void __cdecl E51_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040f110)();    // jmp: $E50
}
PORT_FN(0x0040f100, "$E51(prerace.obj)", E51_prerace_lo, fp_lo_static_init)
static void __cdecl E50_prerace_lo() {
    LO_G32(0x00505d24) = 0xffff7fffu;
}
PORT_FN(0x0040f110, "$E50(prerace.obj)", E50_prerace_lo, fp_lo_static_init)
static void __cdecl E54_prerace_lo() {
    LO_FN(LoVoid_t, 0x0040f130)();    // jmp: $E53
}
PORT_FN(0x0040f120, "$E54(prerace.obj)", E54_prerace_lo, fp_lo_static_init)
static void __cdecl E53_prerace_lo() {
    LO_G8(0x00505c9c) = 0x0f;
}
PORT_FN(0x0040f130, "$E53(prerace.obj)", E53_prerace_lo, fp_lo_static_init)
static void __cdecl E82_prerace_lo() {}    // ret
PORT_FN(0x00410220, "$E82(prerace.obj)", E82_prerace_lo, fp_lo_static_init)
static void __cdecl E81_prerace_lo() {}    // ret
PORT_FN(0x00410230, "$E81(prerace.obj)", E81_prerace_lo, fp_lo_static_init)
static void __cdecl E79_prerace_lo() {}    // ret
PORT_FN(0x00410240, "$E79(prerace.obj)", E79_prerace_lo, fp_lo_static_init)
static void __cdecl E78_prerace_lo() {}    // ret
PORT_FN(0x00410250, "$E78(prerace.obj)", E78_prerace_lo, fp_lo_static_init)
static void __cdecl E77_prerace_lo() {}    // ret
PORT_FN(0x00410260, "$E77(prerace.obj)", E77_prerace_lo, fp_lo_static_init)
static void __cdecl E76_prerace_lo() {}    // ret
PORT_FN(0x00410270, "$E76(prerace.obj)", E76_prerace_lo, fp_lo_static_init)
static void __cdecl E75_prerace_lo() {}    // ret
PORT_FN(0x00410280, "$E75(prerace.obj)", E75_prerace_lo, fp_lo_static_init)
static void __cdecl E74_prerace_lo() {}    // ret
PORT_FN(0x00410290, "$E74(prerace.obj)", E74_prerace_lo, fp_lo_static_init)
static void __cdecl E73_prerace_lo() {}    // ret
PORT_FN(0x004102a0, "$E73(prerace.obj)", E73_prerace_lo, fp_lo_static_init)
static void __cdecl E72_prerace_lo() {}    // ret
PORT_FN(0x004102b0, "$E72(prerace.obj)", E72_prerace_lo, fp_lo_static_init)
static void __cdecl E70_prerace_lo() {}    // ret
PORT_FN(0x004102c0, "$E70(prerace.obj)", E70_prerace_lo, fp_lo_static_init)
static void __cdecl E69_prerace_lo() {}    // ret
PORT_FN(0x004102d0, "$E69(prerace.obj)", E69_prerace_lo, fp_lo_static_init)
static void __cdecl E68_prerace_lo() {}    // ret
PORT_FN(0x004102e0, "$E68(prerace.obj)", E68_prerace_lo, fp_lo_static_init)
static void __cdecl E67_prerace_lo() {}    // ret
PORT_FN(0x004102f0, "$E67(prerace.obj)", E67_prerace_lo, fp_lo_static_init)
static void __cdecl E66_prerace_lo() {}    // ret
PORT_FN(0x00410300, "$E66(prerace.obj)", E66_prerace_lo, fp_lo_static_init)
static void __cdecl E65_prerace_lo() {}    // ret
PORT_FN(0x00410310, "$E65(prerace.obj)", E65_prerace_lo, fp_lo_static_init)
static void __cdecl E64_prerace_lo() {}    // ret
PORT_FN(0x00410320, "$E64(prerace.obj)", E64_prerace_lo, fp_lo_static_init)
static void __cdecl E63_prerace_lo() {}    // ret
PORT_FN(0x00410330, "$E63(prerace.obj)", E63_prerace_lo, fp_lo_static_init)

// ---- version.obj -----------------------------------------------------------------------------------------------------
static void __cdecl E2_version_lo() {
    LO_FN(LoVoid_t, 0x00410ca0)();    // jmp: $E1
}
PORT_FN(0x00410c90, "$E2(version.obj)", E2_version_lo, fp_lo_static_init)
static void __cdecl E1_version_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x00410ca0, "$E1(version.obj)", E1_version_lo, fp_lo_static_init)

}  // namespace
