// ui_leftover.cpp -- generated by tools/gen_leftovers.py --lib ui -- don't edit
//
// M3 UI stage, step U1: the mechanical functions of the widget toolkit (library `ui`: ui.obj,
// _widget.obj, widget.obj, uistyle.obj),
// rewritten from their exact v1.0 instruction bytes (tools/gen_leftovers.py says how each shape reads). The rest of the
// library is written by hand (hook/ui_*.cpp); test/world_ui.cpp checks every one against its original. Faithful (docs/PORTING.md):
// stores through volatile at the original's width, in its order; calls to the game by their v1.0 address (a
// __thiscall as __fastcall with an unused edx), so what runs there -- the original or its hooked rewrite -- is what
// the original would have called.
//
// Counts by shape: $E ret 3, $E jmp 79, $E stores 65, $E constructor 6, ret 6, ret_n 6, ret_al 12, dtor_call 22; 199 in all
//
// The $E static initialisers run once, from the CRT's _initterm: replay_only. A tail jump (`jmp T`) stays a call to T
// by address. The stubs read and write nothing (pure); the deleting destructors free memory (replay_only).
#include <stdint.h>
#include "port.h"

// file-local, so a harness can include it beside krn_leftover.cpp
namespace {
typedef int LoEdx;                                  // the unused edx of a __thiscall received as __fastcall
#define LO_G8(a) (*(volatile uint8_t*)(uintptr_t)(a))
#define LO_G32(a) (*(volatile uint32_t*)(uintptr_t)(a))
#define LO_FN(T, a) ((T)(uintptr_t)(a))
typedef void(__cdecl* LoVoid_t)();
typedef void(__cdecl* LoPtr_t)(void*);
typedef void*(__fastcall* LoCtor0_t)(void*, LoEdx);
typedef void*(__fastcall* LoCtor1_t)(void*, LoEdx, uint32_t);
typedef void*(__fastcall* LoCtor2_t)(void*, LoEdx, uint32_t, uint32_t);

static void fp_lo_static_init(Footprint& f) { f.replay_only = "a static initialiser (runs once, from the CRT's _initterm)"; }


// ---- ui.obj ----------------------------------------------------------------------------------------------------------
static void __cdecl E2_ui_lo() {
    LO_FN(LoVoid_t, 0x004776b0)();    // jmp: $E1
}
PORT_FN(0x004776a0, "$E2(ui.obj)", E2_ui_lo, fp_lo_static_init)
static void __cdecl E1_ui_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x004776b0, "$E1(ui.obj)", E1_ui_lo, fp_lo_static_init)
static void __cdecl E6_ui_lo() {
    LO_FN(LoVoid_t, 0x004776d0)();    // jmp: $E5
}
PORT_FN(0x004776c0, "$E6(ui.obj)", E6_ui_lo, fp_lo_static_init)
static void __cdecl E5_ui_lo() {
    LO_G32(0x00578cf0) = 0x00000000u;
}
PORT_FN(0x004776d0, "$E5(ui.obj)", E5_ui_lo, fp_lo_static_init)
static void __cdecl E9_ui_lo() {
    LO_FN(LoVoid_t, 0x004776f0)();    // jmp: $E8
}
PORT_FN(0x004776e0, "$E9(ui.obj)", E9_ui_lo, fp_lo_static_init)
static void __cdecl E8_ui_lo() {
    LO_G32(0x00578d44) = 0x001f001fu;
}
PORT_FN(0x004776f0, "$E8(ui.obj)", E8_ui_lo, fp_lo_static_init)
static void __cdecl E12_ui_lo() {
    LO_FN(LoVoid_t, 0x00477710)();    // jmp: $E11
}
PORT_FN(0x00477700, "$E12(ui.obj)", E12_ui_lo, fp_lo_static_init)
static void __cdecl E11_ui_lo() {
    LO_G32(0x00578cfc) = 0x03e001e0u;
}
PORT_FN(0x00477710, "$E11(ui.obj)", E11_ui_lo, fp_lo_static_init)
static void __cdecl E15_ui_lo() {
    LO_FN(LoVoid_t, 0x00477730)();    // jmp: $E14
}
PORT_FN(0x00477720, "$E15(ui.obj)", E15_ui_lo, fp_lo_static_init)
static void __cdecl E14_ui_lo() {
    LO_G32(0x00578ea4) = 0x03ef01efu;
}
PORT_FN(0x00477730, "$E14(ui.obj)", E14_ui_lo, fp_lo_static_init)
static void __cdecl E18_ui_lo() {
    LO_FN(LoVoid_t, 0x00477750)();    // jmp: $E17
}
PORT_FN(0x00477740, "$E18(ui.obj)", E18_ui_lo, fp_lo_static_init)
static void __cdecl E17_ui_lo() {
    LO_G32(0x00578eec) = 0x78003c00u;
}
PORT_FN(0x00477750, "$E17(ui.obj)", E17_ui_lo, fp_lo_static_init)
static void __cdecl E21_ui_lo() {
    LO_FN(LoVoid_t, 0x00477770)();    // jmp: $E20
}
PORT_FN(0x00477760, "$E21(ui.obj)", E21_ui_lo, fp_lo_static_init)
static void __cdecl E20_ui_lo() {
    LO_G32(0x00578d40) = 0x780f3c0fu;
}
PORT_FN(0x00477770, "$E20(ui.obj)", E20_ui_lo, fp_lo_static_init)
static void __cdecl E24_ui_lo() {
    LO_FN(LoVoid_t, 0x00477790)();    // jmp: $E23
}
PORT_FN(0x00477780, "$E24(ui.obj)", E24_ui_lo, fp_lo_static_init)
static void __cdecl E23_ui_lo() {
    LO_G32(0x00578ed0) = 0x7be03de0u;
}
PORT_FN(0x00477790, "$E23(ui.obj)", E23_ui_lo, fp_lo_static_init)
static void __cdecl E27_ui_lo() {
    LO_FN(LoVoid_t, 0x004777b0)();    // jmp: $E26
}
PORT_FN(0x004777a0, "$E27(ui.obj)", E27_ui_lo, fp_lo_static_init)
static void __cdecl E26_ui_lo() {
    LO_G32(0x00578d04) = 0x7bef3defu;
}
PORT_FN(0x004777b0, "$E26(ui.obj)", E26_ui_lo, fp_lo_static_init)
static void __cdecl E30_ui_lo() {
    LO_FN(LoVoid_t, 0x004777d0)();    // jmp: $E29
}
PORT_FN(0x004777c0, "$E30(ui.obj)", E30_ui_lo, fp_lo_static_init)
static void __cdecl E29_ui_lo() {
    LO_G32(0x00578ecc) = 0x42082108u;
}
PORT_FN(0x004777d0, "$E29(ui.obj)", E29_ui_lo, fp_lo_static_init)
static void __cdecl E33_ui_lo() {
    LO_FN(LoVoid_t, 0x004777f0)();    // jmp: $E32
}
PORT_FN(0x004777e0, "$E33(ui.obj)", E33_ui_lo, fp_lo_static_init)
static void __cdecl E32_ui_lo() {
    LO_G32(0x00578cdc) = 0x001f001fu;
}
PORT_FN(0x004777f0, "$E32(ui.obj)", E32_ui_lo, fp_lo_static_init)
static void __cdecl E36_ui_lo() {
    LO_FN(LoVoid_t, 0x00477810)();    // jmp: $E35
}
PORT_FN(0x00477800, "$E36(ui.obj)", E36_ui_lo, fp_lo_static_init)
static void __cdecl E35_ui_lo() {
    LO_G32(0x00578ee8) = 0x07e003e0u;
}
PORT_FN(0x00477810, "$E35(ui.obj)", E35_ui_lo, fp_lo_static_init)
static void __cdecl E39_ui_lo() {
    LO_FN(LoVoid_t, 0x00477830)();    // jmp: $E38
}
PORT_FN(0x00477820, "$E39(ui.obj)", E39_ui_lo, fp_lo_static_init)
static void __cdecl E38_ui_lo() {
    LO_G32(0x00578cf8) = 0x07ff03ffu;
}
PORT_FN(0x00477830, "$E38(ui.obj)", E38_ui_lo, fp_lo_static_init)
static void __cdecl E42_ui_lo() {
    LO_FN(LoVoid_t, 0x00477850)();    // jmp: $E41
}
PORT_FN(0x00477840, "$E42(ui.obj)", E42_ui_lo, fp_lo_static_init)
static void __cdecl E41_ui_lo() {
    LO_G32(0x00578cf4) = 0xf8007c00u;
}
PORT_FN(0x00477850, "$E41(ui.obj)", E41_ui_lo, fp_lo_static_init)
static void __cdecl E45_ui_lo() {
    LO_FN(LoVoid_t, 0x00477870)();    // jmp: $E44
}
PORT_FN(0x00477860, "$E45(ui.obj)", E45_ui_lo, fp_lo_static_init)
static void __cdecl E44_ui_lo() {
    LO_G32(0x00578ef0) = 0xf81f7c1fu;
}
PORT_FN(0x00477870, "$E44(ui.obj)", E44_ui_lo, fp_lo_static_init)
static void __cdecl E48_ui_lo() {
    LO_FN(LoVoid_t, 0x00477890)();    // jmp: $E47
}
PORT_FN(0x00477880, "$E48(ui.obj)", E48_ui_lo, fp_lo_static_init)
static void __cdecl E47_ui_lo() {
    LO_G32(0x00578ea8) = 0xffe07fe0u;
}
PORT_FN(0x00477890, "$E47(ui.obj)", E47_ui_lo, fp_lo_static_init)
static void __cdecl E51_ui_lo() {
    LO_FN(LoVoid_t, 0x004778b0)();    // jmp: $E50
}
PORT_FN(0x004778a0, "$E51(ui.obj)", E51_ui_lo, fp_lo_static_init)
static void __cdecl E50_ui_lo() {
    LO_G32(0x00578d00) = 0xffff7fffu;
}
PORT_FN(0x004778b0, "$E50(ui.obj)", E50_ui_lo, fp_lo_static_init)
static void __cdecl E54_ui_lo() {
    LO_FN(LoVoid_t, 0x004778d0)();    // jmp: $E53
}
PORT_FN(0x004778c0, "$E54(ui.obj)", E54_ui_lo, fp_lo_static_init)
static void __cdecl E53_ui_lo() {
    LO_G32(0x00578d08) = 0x00000000u;
}
PORT_FN(0x004778d0, "$E53(ui.obj)", E53_ui_lo, fp_lo_static_init)
static void __cdecl E57_ui_lo() {
    LO_FN(LoVoid_t, 0x004778f0)();    // jmp: $E56
}
PORT_FN(0x004778e0, "$E57(ui.obj)", E57_ui_lo, fp_lo_static_init)
static void __cdecl E56_ui_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00578ec0u, 0, 0x004f665cu);    // Xlator::Xlator
}
PORT_FN(0x004778f0, "$E56(ui.obj)", E56_ui_lo, fp_lo_static_init)
static void __cdecl E60_ui_lo() {
    LO_FN(LoVoid_t, 0x00477910)();    // jmp: $E59
}
PORT_FN(0x00477900, "$E60(ui.obj)", E60_ui_lo, fp_lo_static_init)
static void __cdecl E59_ui_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00578cd0u, 0, 0x004f6664u);    // Xlator::Xlator
}
PORT_FN(0x00477910, "$E59(ui.obj)", E59_ui_lo, fp_lo_static_init)
static void __cdecl E63_ui_lo() {
    LO_FN(LoVoid_t, 0x00477930)();    // jmp: $E62
}
PORT_FN(0x00477920, "$E63(ui.obj)", E63_ui_lo, fp_lo_static_init)
static void __cdecl E62_ui_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00578e98u, 0, 0x004f6670u);    // Xlator::Xlator
}
PORT_FN(0x00477930, "$E62(ui.obj)", E62_ui_lo, fp_lo_static_init)
static void __cdecl E66_ui_lo() {
    LO_FN(LoVoid_t, 0x00477950)();    // jmp: $E65
}
PORT_FN(0x00477940, "$E66(ui.obj)", E66_ui_lo, fp_lo_static_init)
static void __cdecl E65_ui_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00578eb0u, 0, 0x004f6678u);    // Xlator::Xlator
}
PORT_FN(0x00477950, "$E65(ui.obj)", E65_ui_lo, fp_lo_static_init)
static void __cdecl E69_ui_lo() {
    LO_FN(LoVoid_t, 0x00477970)();    // jmp: $E68
}
PORT_FN(0x00477960, "$E69(ui.obj)", E69_ui_lo, fp_lo_static_init)
static void __cdecl E68_ui_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00578d60u, 0, 0x004f6680u);    // Xlator::Xlator
}
PORT_FN(0x00477970, "$E68(ui.obj)", E68_ui_lo, fp_lo_static_init)
static void __cdecl E72_ui_lo() {
    LO_FN(LoVoid_t, 0x00477990)();    // jmp: $E71
}
PORT_FN(0x00477980, "$E72(ui.obj)", E72_ui_lo, fp_lo_static_init)
static void __cdecl E71_ui_lo() {
    LO_FN(LoCtor1_t, 0x0041af80)((void*)0x00578ef8u, 0, 0x004f6688u);    // Xlator::Xlator
}
PORT_FN(0x00477990, "$E71(ui.obj)", E71_ui_lo, fp_lo_static_init)
static void __cdecl E77_ui_lo() {}    // ret
PORT_FN(0x0047b270, "$E77(ui.obj)", E77_ui_lo, fp_lo_static_init)
static void __cdecl E76_ui_lo() {}    // ret
PORT_FN(0x0047b280, "$E76(ui.obj)", E76_ui_lo, fp_lo_static_init)
// public: virtual void __thiscall Widget::Activate(void)
static void __fastcall Widget_Activate_lo(void* self, LoEdx) {}
static void fp_Widget_Activate_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047b470, "Widget::Activate", Widget_Activate_lo, fp_Widget_Activate_lo)
// public: virtual void __thiscall Widget::Deactivate(void)
static void __fastcall Widget_Deactivate_lo(void* self, LoEdx) {}
static void fp_Widget_Deactivate_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047b480, "Widget::Deactivate", Widget_Deactivate_lo, fp_Widget_Deactivate_lo)
// public: virtual void __thiscall Widget::Added(void)
static void __fastcall Widget_Added_lo(void* self, LoEdx) {}
static void fp_Widget_Added_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047b490, "Widget::Added", Widget_Added_lo, fp_Widget_Added_lo)
// public: virtual void __thiscall Widget::Draw3D(void)
static void __fastcall Widget_Draw3D_lo(void* self, LoEdx) {}
static void fp_Widget_Draw3D_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047b4b0, "Widget::Draw3D", Widget_Draw3D_lo, fp_Widget_Draw3D_lo)
// public: virtual void __thiscall Widget::MouseDown(int,int)
static void __fastcall Widget_MouseDown_lo(void* self, LoEdx, int32_t, int32_t) {}
static void fp_Widget_MouseDown_lo(Footprint& f, void*, LoEdx, int32_t, int32_t) { f.pure = true; }
PORT_FN(0x0047b500, "Widget::MouseDown", Widget_MouseDown_lo, fp_Widget_MouseDown_lo)
// public: virtual void __thiscall Widget::MouseUp(int,int)
static void __fastcall Widget_MouseUp_lo(void* self, LoEdx, int32_t, int32_t) {}
static void fp_Widget_MouseUp_lo(Footprint& f, void*, LoEdx, int32_t, int32_t) { f.pure = true; }
PORT_FN(0x0047b510, "Widget::MouseUp", Widget_MouseUp_lo, fp_Widget_MouseUp_lo)
// public: virtual void __thiscall Widget::MouseRDown(int,int)
static void __fastcall Widget_MouseRDown_lo(void* self, LoEdx, int32_t, int32_t) {}
static void fp_Widget_MouseRDown_lo(Footprint& f, void*, LoEdx, int32_t, int32_t) { f.pure = true; }
PORT_FN(0x0047b520, "Widget::MouseRDown", Widget_MouseRDown_lo, fp_Widget_MouseRDown_lo)
// public: virtual void __thiscall Widget::MouseRUp(int,int)
static void __fastcall Widget_MouseRUp_lo(void* self, LoEdx, int32_t, int32_t) {}
static void fp_Widget_MouseRUp_lo(Footprint& f, void*, LoEdx, int32_t, int32_t) { f.pure = true; }
PORT_FN(0x0047b530, "Widget::MouseRUp", Widget_MouseRUp_lo, fp_Widget_MouseRUp_lo)
// public: virtual void __thiscall Widget::MouseMove(int,int)
static void __fastcall Widget_MouseMove_lo(void* self, LoEdx, int32_t, int32_t) {}
static void fp_Widget_MouseMove_lo(Footprint& f, void*, LoEdx, int32_t, int32_t) { f.pure = true; }
PORT_FN(0x0047b540, "Widget::MouseMove", Widget_MouseMove_lo, fp_Widget_MouseMove_lo)
// public: virtual unsigned char __thiscall Widget::IsTabStop(void)
static uint8_t __fastcall Widget_IsTabStop_lo(void* self, LoEdx) {
    return 0;
}
static void fp_Widget_IsTabStop_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047b580, "Widget::IsTabStop", Widget_IsTabStop_lo, fp_Widget_IsTabStop_lo)
// public: virtual void * __thiscall HotKey::`vector deleting destructor'(unsigned int)
static void* __fastcall HotKey_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_HotKey_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047b620, "HotKey::vector deleting destructor", HotKey_vector_deleting_destructor_lo, fp_HotKey_vector_deleting_destructor_lo)
// public: virtual unsigned char __thiscall Button::IsTabStop(void)
static uint8_t __fastcall Button_IsTabStop_lo(void* self, LoEdx) {
    return 0x01;
}
static void fp_Button_IsTabStop_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047b700, "Button::IsTabStop", Button_IsTabStop_lo, fp_Button_IsTabStop_lo)
// public: virtual void * __thiscall MenuButton::`scalar deleting destructor'(unsigned int)
static void* __fastcall MenuButton_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_MenuButton_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047b7a0, "MenuButton::scalar deleting destructor", MenuButton_scalar_deleting_destructor_lo, fp_MenuButton_scalar_deleting_destructor_lo)
// public: virtual void * __thiscall CustomWidget::`vector deleting destructor'(unsigned int)
static void* __fastcall CustomWidget_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_CustomWidget_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047b9c0, "CustomWidget::vector deleting destructor", CustomWidget_vector_deleting_destructor_lo, fp_CustomWidget_vector_deleting_destructor_lo)
// public: virtual void * __thiscall TitleBar::`vector deleting destructor'(unsigned int)
static void* __fastcall TitleBar_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_TitleBar_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047b9f0, "TitleBar::vector deleting destructor", TitleBar_vector_deleting_destructor_lo, fp_TitleBar_vector_deleting_destructor_lo)

// ---- _widget.obj -----------------------------------------------------------------------------------------------------
static void __cdecl E2_widget_lo() {
    LO_FN(LoVoid_t, 0x0047ba20)();    // jmp: $E1
}
PORT_FN(0x0047ba10, "$E2(_widget.obj)", E2_widget_lo, fp_lo_static_init)
static void __cdecl E1_widget_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x0047ba20, "$E1(_widget.obj)", E1_widget_lo, fp_lo_static_init)
static void __cdecl E6_widget_lo() {
    LO_FN(LoVoid_t, 0x0047ba40)();    // jmp: $E5
}
PORT_FN(0x0047ba30, "$E6(_widget.obj)", E6_widget_lo, fp_lo_static_init)
static void __cdecl E5_widget_lo() {
    LO_G32(0x00578f10) = 0x00000000u;
}
PORT_FN(0x0047ba40, "$E5(_widget.obj)", E5_widget_lo, fp_lo_static_init)
static void __cdecl E9_widget_lo() {
    LO_FN(LoVoid_t, 0x0047ba60)();    // jmp: $E8
}
PORT_FN(0x0047ba50, "$E9(_widget.obj)", E9_widget_lo, fp_lo_static_init)
static void __cdecl E8_widget_lo() {
    LO_G32(0x00579048) = 0x001f001fu;
}
PORT_FN(0x0047ba60, "$E8(_widget.obj)", E8_widget_lo, fp_lo_static_init)
static void __cdecl E12_widget_lo() {
    LO_FN(LoVoid_t, 0x0047ba80)();    // jmp: $E11
}
PORT_FN(0x0047ba70, "$E12(_widget.obj)", E12_widget_lo, fp_lo_static_init)
static void __cdecl E11_widget_lo() {
    LO_G32(0x00578f1c) = 0x03e001e0u;
}
PORT_FN(0x0047ba80, "$E11(_widget.obj)", E11_widget_lo, fp_lo_static_init)
static void __cdecl E15_widget_lo() {
    LO_FN(LoVoid_t, 0x0047baa0)();    // jmp: $E14
}
PORT_FN(0x0047ba90, "$E15(_widget.obj)", E15_widget_lo, fp_lo_static_init)
static void __cdecl E14_widget_lo() {
    LO_G32(0x0057905c) = 0x03ef01efu;
}
PORT_FN(0x0047baa0, "$E14(_widget.obj)", E14_widget_lo, fp_lo_static_init)
static void __cdecl E18_widget_lo() {
    LO_FN(LoVoid_t, 0x0047bac0)();    // jmp: $E17
}
PORT_FN(0x0047bab0, "$E18(_widget.obj)", E18_widget_lo, fp_lo_static_init)
static void __cdecl E17_widget_lo() {
    LO_G32(0x00579074) = 0x78003c00u;
}
PORT_FN(0x0047bac0, "$E17(_widget.obj)", E17_widget_lo, fp_lo_static_init)
static void __cdecl E21_widget_lo() {
    LO_FN(LoVoid_t, 0x0047bae0)();    // jmp: $E20
}
PORT_FN(0x0047bad0, "$E21(_widget.obj)", E21_widget_lo, fp_lo_static_init)
static void __cdecl E20_widget_lo() {
    LO_G32(0x00578f44) = 0x780f3c0fu;
}
PORT_FN(0x0047bae0, "$E20(_widget.obj)", E20_widget_lo, fp_lo_static_init)
static void __cdecl E24_widget_lo() {
    LO_FN(LoVoid_t, 0x0047bb00)();    // jmp: $E23
}
PORT_FN(0x0047baf0, "$E24(_widget.obj)", E24_widget_lo, fp_lo_static_init)
static void __cdecl E23_widget_lo() {
    LO_G32(0x00579068) = 0x7be03de0u;
}
PORT_FN(0x0047bb00, "$E23(_widget.obj)", E23_widget_lo, fp_lo_static_init)
static void __cdecl E27_widget_lo() {
    LO_FN(LoVoid_t, 0x0047bb20)();    // jmp: $E26
}
PORT_FN(0x0047bb10, "$E27(_widget.obj)", E27_widget_lo, fp_lo_static_init)
static void __cdecl E26_widget_lo() {
    LO_G32(0x00578f24) = 0x7bef3defu;
}
PORT_FN(0x0047bb20, "$E26(_widget.obj)", E26_widget_lo, fp_lo_static_init)
static void __cdecl E30_widget_lo() {
    LO_FN(LoVoid_t, 0x0047bb40)();    // jmp: $E29
}
PORT_FN(0x0047bb30, "$E30(_widget.obj)", E30_widget_lo, fp_lo_static_init)
static void __cdecl E29_widget_lo() {
    LO_G32(0x00579064) = 0x42082108u;
}
PORT_FN(0x0047bb40, "$E29(_widget.obj)", E29_widget_lo, fp_lo_static_init)
static void __cdecl E33_widget_lo() {
    LO_FN(LoVoid_t, 0x0047bb60)();    // jmp: $E32
}
PORT_FN(0x0047bb50, "$E33(_widget.obj)", E33_widget_lo, fp_lo_static_init)
static void __cdecl E32_widget_lo() {
    LO_G32(0x00578f08) = 0x001f001fu;
}
PORT_FN(0x0047bb60, "$E32(_widget.obj)", E32_widget_lo, fp_lo_static_init)
static void __cdecl E36_widget_lo() {
    LO_FN(LoVoid_t, 0x0047bb80)();    // jmp: $E35
}
PORT_FN(0x0047bb70, "$E36(_widget.obj)", E36_widget_lo, fp_lo_static_init)
static void __cdecl E35_widget_lo() {
    LO_G32(0x00579070) = 0x07e003e0u;
}
PORT_FN(0x0047bb80, "$E35(_widget.obj)", E35_widget_lo, fp_lo_static_init)
static void __cdecl E39_widget_lo() {
    LO_FN(LoVoid_t, 0x0047bba0)();    // jmp: $E38
}
PORT_FN(0x0047bb90, "$E39(_widget.obj)", E39_widget_lo, fp_lo_static_init)
static void __cdecl E38_widget_lo() {
    LO_G32(0x00578f18) = 0x07ff03ffu;
}
PORT_FN(0x0047bba0, "$E38(_widget.obj)", E38_widget_lo, fp_lo_static_init)
static void __cdecl E42_widget_lo() {
    LO_FN(LoVoid_t, 0x0047bbc0)();    // jmp: $E41
}
PORT_FN(0x0047bbb0, "$E42(_widget.obj)", E42_widget_lo, fp_lo_static_init)
static void __cdecl E41_widget_lo() {
    LO_G32(0x00578f14) = 0xf8007c00u;
}
PORT_FN(0x0047bbc0, "$E41(_widget.obj)", E41_widget_lo, fp_lo_static_init)
static void __cdecl E45_widget_lo() {
    LO_FN(LoVoid_t, 0x0047bbe0)();    // jmp: $E44
}
PORT_FN(0x0047bbd0, "$E45(_widget.obj)", E45_widget_lo, fp_lo_static_init)
static void __cdecl E44_widget_lo() {
    LO_G32(0x00579078) = 0xf81f7c1fu;
}
PORT_FN(0x0047bbe0, "$E44(_widget.obj)", E44_widget_lo, fp_lo_static_init)
static void __cdecl E48_widget_lo() {
    LO_FN(LoVoid_t, 0x0047bc00)();    // jmp: $E47
}
PORT_FN(0x0047bbf0, "$E48(_widget.obj)", E48_widget_lo, fp_lo_static_init)
static void __cdecl E47_widget_lo() {
    LO_G32(0x00579060) = 0xffe07fe0u;
}
PORT_FN(0x0047bc00, "$E47(_widget.obj)", E47_widget_lo, fp_lo_static_init)
static void __cdecl E51_widget_lo() {
    LO_FN(LoVoid_t, 0x0047bc20)();    // jmp: $E50
}
PORT_FN(0x0047bc10, "$E51(_widget.obj)", E51_widget_lo, fp_lo_static_init)
static void __cdecl E50_widget_lo() {
    LO_G32(0x00578f20) = 0xffff7fffu;
}
PORT_FN(0x0047bc20, "$E50(_widget.obj)", E50_widget_lo, fp_lo_static_init)
// public: virtual void __thiscall Widget::Draw(struct gxCanvas *)
static void __fastcall Widget_Draw_lo(void* self, LoEdx, void*) {}
static void fp_Widget_Draw_lo(Footprint& f, void*, LoEdx, void*) { f.pure = true; }
PORT_FN(0x0047bd10, "Widget::Draw", Widget_Draw_lo, fp_Widget_Draw_lo)
static void __cdecl E54_widget_lo() {}    // ret
PORT_FN(0x0047dd10, "$E54(_widget.obj)", E54_widget_lo, fp_lo_static_init)
// public: virtual void * __thiscall Widget::`vector deleting destructor'(unsigned int)
static void* __fastcall Widget_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_Widget_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047e890, "Widget::vector deleting destructor", Widget_vector_deleting_destructor_lo, fp_Widget_vector_deleting_destructor_lo)
// public: virtual void * __thiscall StyleWidget::`vector deleting destructor'(unsigned int)
static void* __fastcall StyleWidget_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_StyleWidget_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047e8c0, "StyleWidget::vector deleting destructor", StyleWidget_vector_deleting_destructor_lo, fp_StyleWidget_vector_deleting_destructor_lo)
// public: virtual void * __thiscall Button::`vector deleting destructor'(unsigned int)
static void* __fastcall Button_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_Button_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047e8e0, "Button::vector deleting destructor", Button_vector_deleting_destructor_lo, fp_Button_vector_deleting_destructor_lo)
// public: virtual unsigned char __thiscall BButton::IsTabStop(void)
static uint8_t __fastcall BButton_IsTabStop_lo(void* self, LoEdx) {
    return 0x01;
}
static void fp_BButton_IsTabStop_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047e9b0, "BButton::IsTabStop", BButton_IsTabStop_lo, fp_BButton_IsTabStop_lo)
// public: virtual unsigned char __thiscall CheckBox::IsTabStop(void)
static uint8_t __fastcall CheckBox_IsTabStop_lo(void* self, LoEdx) {
    return 0x01;
}
static void fp_CheckBox_IsTabStop_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047ea70, "CheckBox::IsTabStop", CheckBox_IsTabStop_lo, fp_CheckBox_IsTabStop_lo)
// public: virtual void * __thiscall CheckBox::`scalar deleting destructor'(unsigned int)
static void* __fastcall CheckBox_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_CheckBox_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047eaf0, "CheckBox::scalar deleting destructor", CheckBox_scalar_deleting_destructor_lo, fp_CheckBox_scalar_deleting_destructor_lo)
// public: virtual void * __thiscall StampRoll::`vector deleting destructor'(unsigned int)
static void* __fastcall StampRoll_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047c4e0)(self, 0);    // StampRoll::~StampRoll
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_StampRoll_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047eb10, "StampRoll::vector deleting destructor", StampRoll_vector_deleting_destructor_lo, fp_StampRoll_vector_deleting_destructor_lo)
// public: virtual unsigned char __thiscall RadioButton::IsTabStop(void)
static uint8_t __fastcall RadioButton_IsTabStop_lo(void* self, LoEdx) {
    return 0x01;
}
static void fp_RadioButton_IsTabStop_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047eb40, "RadioButton::IsTabStop", RadioButton_IsTabStop_lo, fp_RadioButton_IsTabStop_lo)
// public: virtual void * __thiscall RadioButton::`vector deleting destructor'(unsigned int)
static void* __fastcall RadioButton_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_RadioButton_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047ebf0, "RadioButton::vector deleting destructor", RadioButton_vector_deleting_destructor_lo, fp_RadioButton_vector_deleting_destructor_lo)
// public: virtual unsigned char __thiscall BRadioButton::IsTabStop(void)
static uint8_t __fastcall BRadioButton_IsTabStop_lo(void* self, LoEdx) {
    return 0x01;
}
static void fp_BRadioButton_IsTabStop_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047ec10, "BRadioButton::IsTabStop", BRadioButton_IsTabStop_lo, fp_BRadioButton_IsTabStop_lo)
// public: virtual unsigned char __thiscall ScrollButtonBase::IsTabStop(void)
static uint8_t __fastcall ScrollButtonBase_IsTabStop_lo(void* self, LoEdx) {
    return 0x01;
}
static void fp_ScrollButtonBase_IsTabStop_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047ec80, "ScrollButtonBase::IsTabStop", ScrollButtonBase_IsTabStop_lo, fp_ScrollButtonBase_IsTabStop_lo)
// public: virtual void * __thiscall ScrollButtonBase::`scalar deleting destructor'(unsigned int)
static void* __fastcall ScrollButtonBase_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_ScrollButtonBase_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047ed20, "ScrollButtonBase::scalar deleting destructor", ScrollButtonBase_scalar_deleting_destructor_lo, fp_ScrollButtonBase_scalar_deleting_destructor_lo)
// public: virtual void * __thiscall ArrowButton::`vector deleting destructor'(unsigned int)
static void* __fastcall ArrowButton_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_ArrowButton_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047ed40, "ArrowButton::vector deleting destructor", ArrowButton_vector_deleting_destructor_lo, fp_ArrowButton_vector_deleting_destructor_lo)
// public: virtual void * __thiscall ScrollButton::`scalar deleting destructor'(unsigned int)
static void* __fastcall ScrollButton_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_ScrollButton_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047ed60, "ScrollButton::scalar deleting destructor", ScrollButton_scalar_deleting_destructor_lo, fp_ScrollButton_scalar_deleting_destructor_lo)
// public: virtual void * __thiscall StaticText::`scalar deleting destructor'(unsigned int)
static void* __fastcall StaticText_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_StaticText_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047ed90, "StaticText::scalar deleting destructor", StaticText_scalar_deleting_destructor_lo, fp_StaticText_scalar_deleting_destructor_lo)
// public: virtual void * __thiscall LineWidget::`scalar deleting destructor'(unsigned int)
static void* __fastcall LineWidget_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_LineWidget_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047edb0, "LineWidget::scalar deleting destructor", LineWidget_scalar_deleting_destructor_lo, fp_LineWidget_scalar_deleting_destructor_lo)
// public: virtual void * __thiscall Numeric::`scalar deleting destructor'(unsigned int)
static void* __fastcall Numeric_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_Numeric_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047ede0, "Numeric::scalar deleting destructor", Numeric_scalar_deleting_destructor_lo, fp_Numeric_scalar_deleting_destructor_lo)
// public: virtual void * __thiscall IntNumeric::`vector deleting destructor'(unsigned int)
static void* __fastcall IntNumeric_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_IntNumeric_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047ee10, "IntNumeric::vector deleting destructor", IntNumeric_vector_deleting_destructor_lo, fp_IntNumeric_vector_deleting_destructor_lo)
// public: virtual void * __thiscall Multi::`vector deleting destructor'(unsigned int)
static void* __fastcall Multi_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_Multi_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047ee40, "Multi::vector deleting destructor", Multi_vector_deleting_destructor_lo, fp_Multi_vector_deleting_destructor_lo)
// public: virtual unsigned char __thiscall ListBox::IsTabStop(void)
static uint8_t __fastcall ListBox_IsTabStop_lo(void* self, LoEdx) {
    return 0x01;
}
static void fp_ListBox_IsTabStop_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047ee60, "ListBox::IsTabStop", ListBox_IsTabStop_lo, fp_ListBox_IsTabStop_lo)
// public: virtual void * __thiscall ListBox::`scalar deleting destructor'(unsigned int)
static void* __fastcall ListBox_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_ListBox_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047eec0, "ListBox::scalar deleting destructor", ListBox_scalar_deleting_destructor_lo, fp_ListBox_scalar_deleting_destructor_lo)
// public: virtual void * __thiscall DropList::`vector deleting destructor'(unsigned int)
static void* __fastcall DropList_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047bc80)(self, 0);    // Widget::~Widget
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_DropList_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047ef30, "DropList::vector deleting destructor", DropList_vector_deleting_destructor_lo, fp_DropList_vector_deleting_destructor_lo)
// public: virtual unsigned char __thiscall Input::IsTabStop(void)
static uint8_t __fastcall Input_IsTabStop_lo(void* self, LoEdx) {
    return 0x01;
}
static void fp_Input_IsTabStop_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047ef50, "Input::IsTabStop", Input_IsTabStop_lo, fp_Input_IsTabStop_lo)
// public: virtual void * __thiscall Input::`vector deleting destructor'(unsigned int)
static void* __fastcall Input_vector_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047d480)(self, 0);    // Input::~Input
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_Input_vector_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047efb0, "Input::vector deleting destructor", Input_vector_deleting_destructor_lo, fp_Input_vector_deleting_destructor_lo)
// public: virtual void * __thiscall CDetect::`scalar deleting destructor'(unsigned int)
static void* __fastcall CDetect_scalar_deleting_destructor_lo(void* self, LoEdx, uint32_t flags) {
    LO_FN(LoCtor0_t, 0x0047d480)(self, 0);    // Input::~Input
    if (flags & 1) LO_FN(LoPtr_t, 0x00414390)(self);    // operator delete
    return self;
}
static void fp_CDetect_scalar_deleting_destructor_lo(Footprint& f, void*, LoEdx, uint32_t) { f.replay_only = "frees the object"; }
PORT_FN(0x0047efe0, "CDetect::scalar deleting destructor", CDetect_scalar_deleting_destructor_lo, fp_CDetect_scalar_deleting_destructor_lo)
// public: virtual unsigned char __thiscall Slider::IsTabStop(void)
static uint8_t __fastcall Slider_IsTabStop_lo(void* self, LoEdx) {
    return 0x01;
}
static void fp_Slider_IsTabStop_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047f000, "Slider::IsTabStop", Slider_IsTabStop_lo, fp_Slider_IsTabStop_lo)
// public: virtual unsigned char __thiscall ScrollBar::IsTabStop(void)
static uint8_t __fastcall ScrollBar_IsTabStop_lo(void* self, LoEdx) {
    return 0x01;
}
static void fp_ScrollBar_IsTabStop_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x0047f0c0, "ScrollBar::IsTabStop", ScrollBar_IsTabStop_lo, fp_ScrollBar_IsTabStop_lo)

// ---- uistyle.obj -----------------------------------------------------------------------------------------------------
static void __cdecl E2_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f120)();    // jmp: $E1
}
PORT_FN(0x0047f110, "$E2(uistyle.obj)", E2_uistyle_lo, fp_lo_static_init)
static void __cdecl E1_uistyle_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x0047f120, "$E1(uistyle.obj)", E1_uistyle_lo, fp_lo_static_init)
static void __cdecl E6_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f140)();    // jmp: $E5
}
PORT_FN(0x0047f130, "$E6(uistyle.obj)", E6_uistyle_lo, fp_lo_static_init)
static void __cdecl E5_uistyle_lo() {
    LO_G32(0x00579084) = 0x00000000u;
}
PORT_FN(0x0047f140, "$E5(uistyle.obj)", E5_uistyle_lo, fp_lo_static_init)
static void __cdecl E9_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f160)();    // jmp: $E8
}
PORT_FN(0x0047f150, "$E9(uistyle.obj)", E9_uistyle_lo, fp_lo_static_init)
static void __cdecl E8_uistyle_lo() {
    LO_G32(0x005790a0) = 0x001f001fu;
}
PORT_FN(0x0047f160, "$E8(uistyle.obj)", E8_uistyle_lo, fp_lo_static_init)
static void __cdecl E12_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f180)();    // jmp: $E11
}
PORT_FN(0x0047f170, "$E12(uistyle.obj)", E12_uistyle_lo, fp_lo_static_init)
static void __cdecl E11_uistyle_lo() {
    LO_G32(0x00579090) = 0x03e001e0u;
}
PORT_FN(0x0047f180, "$E11(uistyle.obj)", E11_uistyle_lo, fp_lo_static_init)
static void __cdecl E15_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f1a0)();    // jmp: $E14
}
PORT_FN(0x0047f190, "$E15(uistyle.obj)", E15_uistyle_lo, fp_lo_static_init)
static void __cdecl E14_uistyle_lo() {
    LO_G32(0x005790d8) = 0x03ef01efu;
}
PORT_FN(0x0047f1a0, "$E14(uistyle.obj)", E14_uistyle_lo, fp_lo_static_init)
static void __cdecl E18_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f1c0)();    // jmp: $E17
}
PORT_FN(0x0047f1b0, "$E18(uistyle.obj)", E18_uistyle_lo, fp_lo_static_init)
static void __cdecl E17_uistyle_lo() {
    LO_G32(0x005796f0) = 0x78003c00u;
}
PORT_FN(0x0047f1c0, "$E17(uistyle.obj)", E17_uistyle_lo, fp_lo_static_init)
static void __cdecl E21_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f1e0)();    // jmp: $E20
}
PORT_FN(0x0047f1d0, "$E21(uistyle.obj)", E21_uistyle_lo, fp_lo_static_init)
static void __cdecl E20_uistyle_lo() {
    LO_G32(0x0057909c) = 0x780f3c0fu;
}
PORT_FN(0x0047f1e0, "$E20(uistyle.obj)", E20_uistyle_lo, fp_lo_static_init)
static void __cdecl E24_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f200)();    // jmp: $E23
}
PORT_FN(0x0047f1f0, "$E24(uistyle.obj)", E24_uistyle_lo, fp_lo_static_init)
static void __cdecl E23_uistyle_lo() {
    LO_G32(0x005796e4) = 0x7be03de0u;
}
PORT_FN(0x0047f200, "$E23(uistyle.obj)", E23_uistyle_lo, fp_lo_static_init)
static void __cdecl E27_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f220)();    // jmp: $E26
}
PORT_FN(0x0047f210, "$E27(uistyle.obj)", E27_uistyle_lo, fp_lo_static_init)
static void __cdecl E26_uistyle_lo() {
    LO_G32(0x00579098) = 0x7bef3defu;
}
PORT_FN(0x0047f220, "$E26(uistyle.obj)", E26_uistyle_lo, fp_lo_static_init)
static void __cdecl E30_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f240)();    // jmp: $E29
}
PORT_FN(0x0047f230, "$E30(uistyle.obj)", E30_uistyle_lo, fp_lo_static_init)
static void __cdecl E29_uistyle_lo() {
    LO_G32(0x005796e0) = 0x42082108u;
}
PORT_FN(0x0047f240, "$E29(uistyle.obj)", E29_uistyle_lo, fp_lo_static_init)
static void __cdecl E33_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f260)();    // jmp: $E32
}
PORT_FN(0x0047f250, "$E33(uistyle.obj)", E33_uistyle_lo, fp_lo_static_init)
static void __cdecl E32_uistyle_lo() {
    LO_G32(0x00579080) = 0x001f001fu;
}
PORT_FN(0x0047f260, "$E32(uistyle.obj)", E32_uistyle_lo, fp_lo_static_init)
static void __cdecl E36_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f280)();    // jmp: $E35
}
PORT_FN(0x0047f270, "$E36(uistyle.obj)", E36_uistyle_lo, fp_lo_static_init)
static void __cdecl E35_uistyle_lo() {
    LO_G32(0x005796ec) = 0x07e003e0u;
}
PORT_FN(0x0047f280, "$E35(uistyle.obj)", E35_uistyle_lo, fp_lo_static_init)
static void __cdecl E39_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f2a0)();    // jmp: $E38
}
PORT_FN(0x0047f290, "$E39(uistyle.obj)", E39_uistyle_lo, fp_lo_static_init)
static void __cdecl E38_uistyle_lo() {
    LO_G32(0x0057908c) = 0x07ff03ffu;
}
PORT_FN(0x0047f2a0, "$E38(uistyle.obj)", E38_uistyle_lo, fp_lo_static_init)
static void __cdecl E42_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f2c0)();    // jmp: $E41
}
PORT_FN(0x0047f2b0, "$E42(uistyle.obj)", E42_uistyle_lo, fp_lo_static_init)
static void __cdecl E41_uistyle_lo() {
    LO_G32(0x00579088) = 0xf8007c00u;
}
PORT_FN(0x0047f2c0, "$E41(uistyle.obj)", E41_uistyle_lo, fp_lo_static_init)
static void __cdecl E45_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f2e0)();    // jmp: $E44
}
PORT_FN(0x0047f2d0, "$E45(uistyle.obj)", E45_uistyle_lo, fp_lo_static_init)
static void __cdecl E44_uistyle_lo() {
    LO_G32(0x005796f4) = 0xf81f7c1fu;
}
PORT_FN(0x0047f2e0, "$E44(uistyle.obj)", E44_uistyle_lo, fp_lo_static_init)
static void __cdecl E48_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f300)();    // jmp: $E47
}
PORT_FN(0x0047f2f0, "$E48(uistyle.obj)", E48_uistyle_lo, fp_lo_static_init)
static void __cdecl E47_uistyle_lo() {
    LO_G32(0x005790dc) = 0xffe07fe0u;
}
PORT_FN(0x0047f300, "$E47(uistyle.obj)", E47_uistyle_lo, fp_lo_static_init)
static void __cdecl E51_uistyle_lo() {
    LO_FN(LoVoid_t, 0x0047f320)();    // jmp: $E50
}
PORT_FN(0x0047f310, "$E51(uistyle.obj)", E51_uistyle_lo, fp_lo_static_init)
static void __cdecl E50_uistyle_lo() {
    LO_G32(0x00579094) = 0xffff7fffu;
}
PORT_FN(0x0047f320, "$E50(uistyle.obj)", E50_uistyle_lo, fp_lo_static_init)
// void __cdecl ASSERT_MSG(int,char const *,...)
static void __cdecl ASSERT_MSG_lo(int32_t, void*) {}
static void fp_ASSERT_MSG_lo(Footprint& f, int32_t, void*) { f.pure = true; }
PORT_FN(0x0047f560, "ASSERT_MSG(uistyle.obj)", ASSERT_MSG_lo, fp_ASSERT_MSG_lo)

// ---- widget.obj ------------------------------------------------------------------------------------------------------
static void __cdecl E2_widget_47fc30_lo() {
    LO_FN(LoVoid_t, 0x0047fc40)();    // jmp: $E1
}
PORT_FN(0x0047fc30, "$E2(widget.obj)", E2_widget_47fc30_lo, fp_lo_static_init)
static void __cdecl E1_widget_47fc40_lo() {
    LO_FN(LoVoid_t, 0x00410cc0)();    // jmp: rcfunc_is_internal (a bare `ret`)
}
PORT_FN(0x0047fc40, "$E1(widget.obj)", E1_widget_47fc40_lo, fp_lo_static_init)
static void __cdecl E6_widget_47fc50_lo() {
    LO_FN(LoVoid_t, 0x0047fc60)();    // jmp: $E5
}
PORT_FN(0x0047fc50, "$E6(widget.obj)", E6_widget_47fc50_lo, fp_lo_static_init)
static void __cdecl E5_widget_47fc60_lo() {
    LO_G32(0x00579704) = 0x00000000u;
}
PORT_FN(0x0047fc60, "$E5(widget.obj)", E5_widget_47fc60_lo, fp_lo_static_init)
static void __cdecl E9_widget_47fc70_lo() {
    LO_FN(LoVoid_t, 0x0047fc80)();    // jmp: $E8
}
PORT_FN(0x0047fc70, "$E9(widget.obj)", E9_widget_47fc70_lo, fp_lo_static_init)
static void __cdecl E8_widget_47fc80_lo() {
    LO_G32(0x00579720) = 0x001f001fu;
}
PORT_FN(0x0047fc80, "$E8(widget.obj)", E8_widget_47fc80_lo, fp_lo_static_init)
static void __cdecl E12_widget_47fc90_lo() {
    LO_FN(LoVoid_t, 0x0047fca0)();    // jmp: $E11
}
PORT_FN(0x0047fc90, "$E12(widget.obj)", E12_widget_47fc90_lo, fp_lo_static_init)
static void __cdecl E11_widget_47fca0_lo() {
    LO_G32(0x00579710) = 0x03e001e0u;
}
PORT_FN(0x0047fca0, "$E11(widget.obj)", E11_widget_47fca0_lo, fp_lo_static_init)
static void __cdecl E15_widget_47fcb0_lo() {
    LO_FN(LoVoid_t, 0x0047fcc0)();    // jmp: $E14
}
PORT_FN(0x0047fcb0, "$E15(widget.obj)", E15_widget_47fcb0_lo, fp_lo_static_init)
static void __cdecl E14_widget_47fcc0_lo() {
    LO_G32(0x0057972c) = 0x03ef01efu;
}
PORT_FN(0x0047fcc0, "$E14(widget.obj)", E14_widget_47fcc0_lo, fp_lo_static_init)
static void __cdecl E18_widget_47fcd0_lo() {
    LO_FN(LoVoid_t, 0x0047fce0)();    // jmp: $E17
}
PORT_FN(0x0047fcd0, "$E18(widget.obj)", E18_widget_47fcd0_lo, fp_lo_static_init)
static void __cdecl E17_widget_47fce0_lo() {
    LO_G32(0x0057978c) = 0x78003c00u;
}
PORT_FN(0x0047fce0, "$E17(widget.obj)", E17_widget_47fce0_lo, fp_lo_static_init)
static void __cdecl E21_widget_47fcf0_lo() {
    LO_FN(LoVoid_t, 0x0047fd00)();    // jmp: $E20
}
PORT_FN(0x0047fcf0, "$E21(widget.obj)", E21_widget_47fcf0_lo, fp_lo_static_init)
static void __cdecl E20_widget_47fd00_lo() {
    LO_G32(0x0057971c) = 0x780f3c0fu;
}
PORT_FN(0x0047fd00, "$E20(widget.obj)", E20_widget_47fd00_lo, fp_lo_static_init)
static void __cdecl E24_widget_47fd10_lo() {
    LO_FN(LoVoid_t, 0x0047fd20)();    // jmp: $E23
}
PORT_FN(0x0047fd10, "$E24(widget.obj)", E24_widget_47fd10_lo, fp_lo_static_init)
static void __cdecl E23_widget_47fd20_lo() {
    LO_G32(0x0057977c) = 0x7be03de0u;
}
PORT_FN(0x0047fd20, "$E23(widget.obj)", E23_widget_47fd20_lo, fp_lo_static_init)
static void __cdecl E27_widget_47fd30_lo() {
    LO_FN(LoVoid_t, 0x0047fd40)();    // jmp: $E26
}
PORT_FN(0x0047fd30, "$E27(widget.obj)", E27_widget_47fd30_lo, fp_lo_static_init)
static void __cdecl E26_widget_47fd40_lo() {
    LO_G32(0x00579718) = 0x7bef3defu;
}
PORT_FN(0x0047fd40, "$E26(widget.obj)", E26_widget_47fd40_lo, fp_lo_static_init)
static void __cdecl E30_widget_47fd50_lo() {
    LO_FN(LoVoid_t, 0x0047fd60)();    // jmp: $E29
}
PORT_FN(0x0047fd50, "$E30(widget.obj)", E30_widget_47fd50_lo, fp_lo_static_init)
static void __cdecl E29_widget_47fd60_lo() {
    LO_G32(0x00579778) = 0x42082108u;
}
PORT_FN(0x0047fd60, "$E29(widget.obj)", E29_widget_47fd60_lo, fp_lo_static_init)
static void __cdecl E33_widget_47fd70_lo() {
    LO_FN(LoVoid_t, 0x0047fd80)();    // jmp: $E32
}
PORT_FN(0x0047fd70, "$E33(widget.obj)", E33_widget_47fd70_lo, fp_lo_static_init)
static void __cdecl E32_widget_47fd80_lo() {
    LO_G32(0x005796f8) = 0x001f001fu;
}
PORT_FN(0x0047fd80, "$E32(widget.obj)", E32_widget_47fd80_lo, fp_lo_static_init)
static void __cdecl E36_widget_47fd90_lo() {
    LO_FN(LoVoid_t, 0x0047fda0)();    // jmp: $E35
}
PORT_FN(0x0047fd90, "$E36(widget.obj)", E36_widget_47fd90_lo, fp_lo_static_init)
static void __cdecl E35_widget_47fda0_lo() {
    LO_G32(0x00579788) = 0x07e003e0u;
}
PORT_FN(0x0047fda0, "$E35(widget.obj)", E35_widget_47fda0_lo, fp_lo_static_init)
static void __cdecl E39_widget_47fdb0_lo() {
    LO_FN(LoVoid_t, 0x0047fdc0)();    // jmp: $E38
}
PORT_FN(0x0047fdb0, "$E39(widget.obj)", E39_widget_47fdb0_lo, fp_lo_static_init)
static void __cdecl E38_widget_47fdc0_lo() {
    LO_G32(0x0057970c) = 0x07ff03ffu;
}
PORT_FN(0x0047fdc0, "$E38(widget.obj)", E38_widget_47fdc0_lo, fp_lo_static_init)
static void __cdecl E42_widget_47fdd0_lo() {
    LO_FN(LoVoid_t, 0x0047fde0)();    // jmp: $E41
}
PORT_FN(0x0047fdd0, "$E42(widget.obj)", E42_widget_47fdd0_lo, fp_lo_static_init)
static void __cdecl E41_widget_47fde0_lo() {
    LO_G32(0x00579708) = 0xf8007c00u;
}
PORT_FN(0x0047fde0, "$E41(widget.obj)", E41_widget_47fde0_lo, fp_lo_static_init)
static void __cdecl E45_widget_47fdf0_lo() {
    LO_FN(LoVoid_t, 0x0047fe00)();    // jmp: $E44
}
PORT_FN(0x0047fdf0, "$E45(widget.obj)", E45_widget_47fdf0_lo, fp_lo_static_init)
static void __cdecl E44_widget_47fe00_lo() {
    LO_G32(0x00579790) = 0xf81f7c1fu;
}
PORT_FN(0x0047fe00, "$E44(widget.obj)", E44_widget_47fe00_lo, fp_lo_static_init)
static void __cdecl E48_widget_47fe10_lo() {
    LO_FN(LoVoid_t, 0x0047fe20)();    // jmp: $E47
}
PORT_FN(0x0047fe10, "$E48(widget.obj)", E48_widget_47fe10_lo, fp_lo_static_init)
static void __cdecl E47_widget_47fe20_lo() {
    LO_G32(0x00579734) = 0xffe07fe0u;
}
PORT_FN(0x0047fe20, "$E47(widget.obj)", E47_widget_47fe20_lo, fp_lo_static_init)
static void __cdecl E51_widget_47fe30_lo() {
    LO_FN(LoVoid_t, 0x0047fe40)();    // jmp: $E50
}
PORT_FN(0x0047fe30, "$E51(widget.obj)", E51_widget_47fe30_lo, fp_lo_static_init)
static void __cdecl E50_widget_47fe40_lo() {
    LO_G32(0x00579714) = 0xffff7fffu;
}
PORT_FN(0x0047fe40, "$E50(widget.obj)", E50_widget_47fe40_lo, fp_lo_static_init)
// public: unsigned char __thiscall WidgetWindow::IsDirty(void)
static uint8_t __fastcall WidgetWindow_IsDirty_lo(void* self, LoEdx) {
    return 0x01;
}
static void fp_WidgetWindow_IsDirty_lo(Footprint& f, void*, LoEdx) { f.pure = true; }
PORT_FN(0x004804a0, "WidgetWindow::IsDirty", WidgetWindow_IsDirty_lo, fp_WidgetWindow_IsDirty_lo)
// void __cdecl ASSERT_MSG(int,char const *,...)
static void __cdecl ASSERT_MSG_widget_lo(int32_t, void*) {}
static void fp_ASSERT_MSG_widget_lo(Footprint& f, int32_t, void*) { f.pure = true; }
PORT_FN(0x00480b60, "ASSERT_MSG(widget.obj)", ASSERT_MSG_widget_lo, fp_ASSERT_MSG_widget_lo)

}  // namespace
