// viperport -- milestone M0's proof of concept.
//
// A proxy DINPUT.dll: race.exe imports one function from it (DirectInputCreateA), and Windows looks
// in the game's own folder before the system one, so a DLL of that name there loads with the game --
// race.exe itself is never modified. The one export forwards to the real DirectInput; on load, the
// DLL replaces a real game function with new C++.
//
// The function is Obstacle::Update (race.exe v1.0, 0x43d2e0): the sleep logic every obstacle ball,
// cube and prism runs each physics tick. The C++ below behaves exactly like the original (see
// docs/reference/file-formats.md, "How an obstacle lives") and counts its calls in viperport.log.
//
// Builds: v1.0 race.exe, and the race.bin builds -- v1.1, and 1.2.4-1.2.6 (one compile, told apart
// only by community hex-edits). Addresses in this file are all v1.0's; the others are translated through
// a per-build table generated by tools/port_sites.py (see "which engine build" below).
//
// Safety: nothing is patched unless the host is a known build (by PE timestamp), and every function
// replaced and every field changed first holds exactly what that build should. Otherwise it logs why
// and stays out of the way.
#define _CRT_SECURE_NO_WARNINGS
#include <windows.h>
#include "vp_os.h"
#include <stdint.h>
#include <stdio.h>
#include <algorithm>
#include <vector>
#include "viperport.h"
#include "port.h"
#include "session.h"
#include "fix_paths.h"
#include "standalone.h"
#ifndef _WIN32
#include <fcntl.h>                                       // (R2b: two_copies' lock files)
#include <stdlib.h>
#include <string.h>
#include <sys/file.h>
#include <unistd.h>
#endif

// ---- the one export, forwarded ---------------------------------------------------------------------
// (Windows only: the dinput.dll route's real DirectInput, for the game's own input code when SDL is off)
#ifdef _WIN32
typedef HRESULT(WINAPI* DirectInputCreateA_t)(HINSTANCE, DWORD, void**, void*);
static HMODULE g_real_dinput;

extern "C" HRESULT WINAPI DirectInputCreateA(HINSTANCE inst, DWORD version, void** out, void* outer) {
    if (!g_real_dinput) {
        char path[MAX_PATH];
        GetSystemDirectoryA(path, MAX_PATH);             // WOW64 redirects this to SysWOW64 for us
        vpos_lstrcatA(path, "\\dinput.dll");
        g_real_dinput = LoadLibraryA(path);
    }
    DirectInputCreateA_t real = g_real_dinput ? (DirectInputCreateA_t)GetProcAddress(g_real_dinput, "DirectInputCreateA") : 0;
    return real ? real(inst, version, out, outer) : E_FAIL;
}
#endif

// ---- logging -------------------------------------------------------------------------------------------
static FILE* g_log;
static HMODULE g_self;
void logf(const char* fmt, ...) {
    if (!g_log) return;
    SYSTEMTIME t; vpos_GetLocalTime(&t);
    fprintf(g_log, "%02d:%02d:%02d.%03d  ", t.wHour, t.wMinute, t.wSecond, t.wMilliseconds);
    va_list ap; va_start(ap, fmt); vfprintf(g_log, fmt, ap); va_end(ap);
    fputc('\n', g_log); fflush(g_log);
}

// ---- [test] two_copies: two copies of the game on one PC ------------------------------------------------
// viperport.ini `[test] two_copies=1` (README, "Testing multiplayer on one PC"). Decided here, when the DLL loads,
// before any game code: two named mutexes are the two copies' slots, held for the life of the process. The first free
// one is this copy: slot 1 is copy 1 -- the game's folders, unchanged --, slot 2 is copy 2, with <race.exe's
// folder>\Config-2\ and log-2\ (fix_paths.h) and its window on the right half (platform.cpp). Holding a slot lets the
// game's single-instance check pass (krn_file.cpp, start_unique_instance). A third start finds both taken and is the
// game's own: the check refuses it as always. Without the key nothing here runs.
static HANDLE g_copy_slot;
static const char* g_copy_note = "";
int vp_copy() { return vp_g_copy; }
const char* vp_copy_suffix() { return vp_g_copy_suffix; }
bool vp_two_copies() { return vp_g_two_copies; }

static void decide_copy(const char* ini) {
    if (!vpos_GetPrivateProfileIntA("test", "two_copies", 0, ini)) return;
#ifdef _WIN32
    // (Windows' own named mutexes and their last error -- not the game's: a Windows-only test feature)
    for (int c = 1; c <= 2; c++) {
        HANDLE h = CreateMutexA(0, FALSE, c == 1 ? "viperport two_copies 1" : "viperport two_copies 2");
        if (!h) continue;
        if (GetLastError() == ERROR_ALREADY_EXISTS) {
            CloseHandle(h);
            continue;
        }
        g_copy_slot = h;
        vp_g_two_copies = true;
        vp_g_copy = c;
        vp_g_copy_suffix = c == 2 ? "-2" : "";
        g_copy_note = c == 2 ? "two_copies: this is copy 2 (Config-2\\, log-2\\, the right half of the screen)"
                             : "two_copies: this is copy 1 (Config\\, log\\, the left half of the screen)";
        return;
    }
    g_copy_note = "two_copies: two copies already run; this start is the game's own (its single-instance check decides)";
#else
    // R2b: the two slots are lock files ($XDG_RUNTIME_DIR, else /tmp: viperport-two_copies-1 / -2), flock'd for the
    // process's life -- the OS lets go when it ends, as Windows closes a mutex handle
    static int held = -1;
    const char* dir = getenv("XDG_RUNTIME_DIR");
    for (int c = 1; c <= 2; c++) {
        char path[600];
        snprintf(path, sizeof path, "%s/viperport-two_copies-%d", dir && *dir && strlen(dir) < 500 ? dir : "/tmp", c);
        const int fd = open(path, O_RDWR | O_CREAT | O_CLOEXEC, 0600);
        if (fd < 0) continue;
        if (flock(fd, LOCK_EX | LOCK_NB) != 0) {
            close(fd);
            continue;
        }
        held = fd;
        vp_g_two_copies = true;
        vp_g_copy = c;
        vp_g_copy_suffix = c == 2 ? "-2" : "";
        g_copy_note = c == 2 ? "two_copies: this is copy 2 (Config-2\\, log-2\\, the right half of the screen)"
                             : "two_copies: this is copy 1 (Config\\, log\\, the left half of the screen)";
        return;
    }
    (void)held;
    g_copy_note = "two_copies: two copies already run; this start is the game's own (its single-instance check decides)";
#endif
}

// the DLL's own log: viperport.log beside the DLL; copy 2's in <race.exe's folder>\log-2\ (made)
static FILE* open_dll_log() {
    char path[MAX_PATH];
    if (vp_g_copy == 2) {
        const DWORD n = vpos_GetModuleFileNameA(NULL, path, MAX_PATH);
        char* slash = n && n < MAX_PATH ? strrchr(path, '\\') : 0;
        if (slash && (size_t)(slash + 1 - path) + 20 < MAX_PATH) {
            vpos_lstrcpyA(slash + 1, "log-2");
            vpos_CreateDirectoryA(path, 0);
            vpos_lstrcatA(path, "\\viperport.log");
            if (FILE* f = fopen(path, "w")) return f;
        }
    }
    vpos_GetModuleFileNameA(g_self, path, MAX_PATH);
    char* slash = strrchr(path, '\\');
    vpos_lstrcpyA(slash ? slash + 1 : path, "viperport.log");
    return fopen(path, "w");
}

// ---- which engine build ------------------------------------------------------------------------------
// Every game address in this file is written as its v1.0 race.exe address. The race.bin builds run the
// same code elsewhere: tools/port_sites.py carries each address this file uses across (matched functions,
// then the same instruction inside them) and checks the target's bytes, into one table per build.
// A(v10) is the address in the running build. A table entry's value is the hash (vp_code_hash) of the four bytes
// that should be there: a patched field's current value, or a function's first four bytes (0: an address only).
struct Xlat { uint32_t v10, here, value; };
static const Xlat k_v11[] = {
#include "sites_v11.inc"
};
static const Xlat k_v12x[] = {
#include "sites_v12x.inc"
};
struct Build { const char* name; uint32_t timestamp; const Xlat* table; int n; };
static const Build k_builds[] = {
    {"v1.0 race.exe", 0x362de68c, 0, 0},                                // the addresses as written
    {"v1.1 race.bin", 0x36acae44, k_v11, sizeof k_v11 / sizeof k_v11[0]},
    {"1.2.4-1.2.6 race.bin", 0x40e074ad, k_v12x, sizeof k_v12x / sizeof k_v12x[0]},
};
static const Build* g_build;
static int g_unresolved;

static const Xlat* xlat(uint32_t v10) {
    for (int i = 0; i < g_build->n; i++)
        if (g_build->table[i].v10 == v10) return &g_build->table[i];
    return 0;
}

bool build_is_v10() { return g_build && !g_build->table; }

// viperport.exe --probe (standalone.h): the DLL loaded only to run the stock check on race.exe's image at 0x400000 --
// DllMain does nothing, and this names the build from the image's own headers, as install() does from GetModuleHandle
static bool g_probe;
bool vp_probe_build() {
    const uint8_t* base = (const uint8_t*)0x400000;
    MEMORY_BASIC_INFORMATION mbi;
    if (!vpos_VirtualQuery(base, &mbi, sizeof mbi) || mbi.State != MEM_COMMIT) return false;
    const IMAGE_NT_HEADERS* nt = (const IMAGE_NT_HEADERS*)(base + ((const IMAGE_DOS_HEADER*)base)->e_lfanew);
    for (const Build& b : k_builds)
        if (nt->FileHeader.TimeDateStamp == b.timestamp) g_build = &b;
    return build_is_v10();
}

bool have(uint32_t v10) { return !g_build->table || xlat(v10) != 0; }

uint32_t A(uint32_t v10) {
    if (!g_build->table) return v10;
    if (const Xlat* x = xlat(v10)) return x->here;
    logf("no address for v1.0 %08x in %s (regenerate its table with tools/port_sites.py)", v10, g_build->name);
    g_unresolved++;
    return 0;
}

// ---- the game's own functions and globals we use, resolved for the build at load ---------------------
typedef float(__cdecl* PhysicsGetTime_t)(void);              // ?PhysicsGetTime@@YAMXZ
typedef void(__fastcall* Method0_t)(void* self, void* edx);   // a __thiscall with no arguments
static PhysicsGetTime_t PhysicsGetTime;
static Method0_t Obstacle_Perturb;                            // ?Perturb@Obstacle@@QAEXXZ
static Method0_t PhobDyno_Update;                             // ?Update@PhobDyno@@UAEXXZ

static volatile LONG g_calls, g_sleeps, g_perturbs;
static void note_peaks();

// Obstacle::Update, rewritten. __fastcall with an unused edx is how a __thiscall is received.
static void __fastcall Obstacle_Update(uint8_t* self, void* /*edx*/) {
    LONG n = InterlockedIncrement(&g_calls);
    if ((n & 255) == 1) note_peaks();
    if (n == 1) logf("first call to the new Obstacle::Update (obstacle at %p)", self);
    const float* v = (const float*)(self + 0x234);            // linear velocity
    // Wake (restart the 1 s timer) while moving faster than 0.5 m/s -- unless fallen below y = -500.
    // The original compares the height's raw bits UNSIGNED against -500.0f (0xc3fa0000), so any
    // positive height passes and only heights at or below -500 fail; reproduced exactly here.
    float speed2 = (v[2] * v[2] + v[1] * v[1]) + v[0] * v[0];
    uint32_t ybits = *(const uint32_t*)(self + 0x60);
    if (speed2 > 0.25f && ybits < 0xc3fa0000u) {
        Obstacle_Perturb(self, 0);
        InterlockedIncrement(&g_perturbs);
    }
    if (!self[0x4ac])                                          // asleep: no physics at all
        return;
    if (*(const float*)(self + 0x4a8) + 1.0f < PhysicsGetTime()) {
        self[0x4ac] = 0;                                       // a second since the last wake: sleep
        float* w = (float*)(self + 0x240);                     // angular velocity
        w[0] = w[1] = w[2] = 0.0f;
        float* lv = (float*)(self + 0x234);
        lv[0] = lv[1] = lv[2] = 0.0f;
        InterlockedIncrement(&g_sleeps);
        return;
    }
    PhobDyno_Update(self, 0);
}

// M3: switched and checked through port.h. It changes its own obstacle (Perturb and PhobDyno::Update
// included), so that's its footprint. v1.1 and 1.2.x square +238h first: the same sum, the terms the
// other way round -- their first bytes come from the build tables.
static void fp_obstacle_update(Footprint& f, uint8_t* self, void*) { f.object(self); }
// push ebx; push esi; fld dword [ecx+23Ch]; fmul dword [ecx+23Ch]
PORT_FN_BUILDS(0x0043d2e0, "Obstacle::Update", Obstacle_Update, fp_obstacle_update, 0x9d684b85, 14)   // (its 14 bytes' hash)

// ---- hooking -------------------------------------------------------------------------------------------
// Does the function at v1.0 address v10 start as it should? v1.0: the prologue given; another build: the
// first four bytes its table recorded. Both as hashes (vp_code_hash): no original code is carried here.
bool code_is(uint32_t v10, uint32_t hash, size_t n) {
    uint32_t at = A(v10);
    if (!at) return false;
    if (!g_build->table) return vp_code_hash((const void*)at, n) == hash;
    return vp_code_hash((const void*)at, 4) == xlat(v10)->value;
}

bool jmp_hook(uint32_t v10, uint32_t hash, size_t n, void* to, const char* what) {
    if (!code_is(v10, hash, n)) {
        logf("NOT hooking %s: its first bytes aren't what %s has there", what, g_build->name);
        return false;
    }
    uint32_t at = A(v10);
    uint8_t* p = (uint8_t*)at;
    DWORD old;
    vpos_VirtualProtect(p, 5, PAGE_EXECUTE_READWRITE, &old);
    p[0] = 0xE9;
    *(int32_t*)(p + 1) = (int32_t)((uint8_t*)to - (p + 5));
    vpos_VirtualProtect(p, 5, old, &old);
    vpos_flush_code(p, 5);
    logf("hooked %s at %08x -> %p", what, at, to);
    return true;
}

// ---- M1: lifting the object limits ---------------------------------------------------------------
// Three fixed lists cap how much a track can hold, and none of them is checked in the release build
// (v1.1 and 1.2.x have the same three; their two world lists hold 1,040):
//   * physics objects: PhysTaskBegin allocates 0x800 bytes = 512 pointers and fills it with every car,
//     checkpoint, obstacle, wobble and static in the track, with no bound. Everything else reaches the
//     array through its pointer and count, so only the allocation's size needs raising.
//   * world objects and graphics objects: static 1,024-entry arrays in .data (0x5512a0, 0x5522d8). Eleven
//     instructions address them; they're repointed at bigger arrays here, along with the two capacity
//     checks and the two 1,024-entry clears in WorldEndCommon.
enum { PHOB_CAP = 8192, WOB_CAP = 8192, GOB_CAP = 8192 };
static void* g_wobs[WOB_CAP + 2];               // index 0 unused: the game pre-increments, first entry at [1]
static void* g_gobs[GOB_CAP + 2];

// A 32-bit operand to change: the instruction's v1.0 address, the operand's offset in it, the v1.0 value
// and the new one. at_least marks a pool size (a push/mov imm32) that is only ever raised: the community
// builds hex-edited several of them to their own sizes, so any size is accepted and a bigger one kept.
struct Field { uint32_t at; uint8_t off; uint32_t old; uint32_t neu; bool at_least; };

static uint32_t field_addr(const Field& f) { return g_build->table ? A(f.at) : f.at + f.off; }
// does the field hold the value it should before patching? v1.0: Field::old; another build: its table's hash of it
static bool field_holds_old(const Field& f, uint32_t at) {
    return g_build->table ? vp_code_hash((const void*)at, 4) == xlat(f.at)->value : *(uint32_t*)at == f.old;
}

static bool patch_fields(Field* f, int n, const char* what) {
    for (int i = 0; i < n; i++) {                                    // all or nothing
        uint32_t at = field_addr(f[i]);
        bool ok = at != 0;
        if (ok && f[i].at_least) {
            uint8_t op = *(uint8_t*)(at - 1);                        // push imm32, or mov reg, imm32
            uint32_t now = *(uint32_t*)at;
            ok = (op == 0x68 || (op >= 0xB8 && op <= 0xBF)) && now > 0 && now < 0x100000;
        } else if (ok) {
            ok = field_holds_old(f[i], at);
        }
        if (!ok) {
            logf("NOT lifting %s: the field for v1.0 %08x isn't what %s has there", what, f[i].at, g_build->name);
            return false;
        }
    }
    for (int i = 0; i < n; i++) {
        uint8_t* p = (uint8_t*)field_addr(f[i]);
        uint32_t neu = f[i].neu;
        if (f[i].at_least && *(uint32_t*)p > neu) neu = *(uint32_t*)p;
        DWORD old;
        vpos_VirtualProtect(p, 4, PAGE_EXECUTE_READWRITE, &old);
        *(uint32_t*)p = neu;
        vpos_VirtualProtect(p, 4, old, &old);
        vpos_flush_code(p, 4);
        port_note_m1((uint32_t)p, 4);                                // (a trampoline over it must copy the new value)
    }
    logf("lifted %s (%d fields)", what, n);
    return true;
}

static void lift_limits() {
    uint32_t wob = (uint32_t)&g_wobs[0], gob = (uint32_t)&g_gobs[0];
    Field phys[] = {
        {0x426893, 1, 0x800, PHOB_CAP * 4, true},             // PhysTaskBegin: push 0x800 -> MemAlloc
    };
    Field world[] = {
        {0x46283a, 3, 0x55129c, wob},                         // WorldAddWob: mov [eax*4 + list-4], esi
        {0x462806, 6, 0x400, WOB_CAP},                        // WorldAddWob: cmp count, 0x400
        {0x461e39, 1, 0x5512a0, wob + 4},                     // WorldEndCommon: mov edi, list
        {0x461e3e, 1, 0x400, WOB_CAP},                        // WorldEndCommon: mov ecx, 0x400 (rep stosd)
        {0x462196, 1, 0x5512a0, wob + 4},                     // WorldUpdate: mov edi, list
        {0x4627f0, 3, 0x5522d4, gob},                         // WorldAddGob: mov [eax*4 + list-4], ecx
        {0x4627ca, 6, 0x400, GOB_CAP},                        // WorldAddGob: cmp count, 0x400
        {0x461e0e, 1, 0x5522d8, gob + 4},                     // WorldEndCommon: mov esi, list (destroy loop)
        {0x461e2b, 1, 0x5522d8, gob + 4},                     // WorldEndCommon: mov edi, list
        {0x461e32, 1, 0x400, GOB_CAP},                        // WorldEndCommon: mov ecx, 0x400 (rep stosd)
        {0x461f5c, 1, 0x5522d8, gob + 4},                     // WorldInitTextures
        {0x4622a2, 1, 0x5522d8, gob + 4},                     // WorldDraw
        {0x4624c7, 1, 0x5522d8, gob + 4},                     // draw_mirror
        {0x462595, 1, 0x5522d8, gob + 4},                     // WorldDraw2D
        {0x463f4d, 1, 0x5522d8, gob + 4},                     // sort_objects: push list (for qsort)
    };
    // Fixed pools behind them: every obstacle loads its own model instance, and each draws through the
    // deferred list. Balls2000 died "out of memory in pool(models)" once the lists above were lifted.
    // Model handles are the pool entries' own pointers (convert_to_mrmodel returns its argument), so
    // nothing indexes these pools by number; the counts can simply grow.
    Field pools[] = {
        {0x455741, 1, 0x990, 16384, true},                    // mr_model_begin: 'models', 2448 x 48 bytes
        {0x455706, 1, 0x1320, 32768, true},                   // mr_model_begin: 'surf info', 4896 x 44 bytes
        {0x457216, 1, 0x400, 8192, true},                     // begin_deferred: 'deferr pool', 1024 x 16 bytes
    };
    patch_fields(pools, sizeof pools / sizeof pools[0], "the model, surface and deferred-draw pools");
    patch_fields(phys, 1, "the physics-object limit, 512 -> 8192");
    patch_fields(world, sizeof world / sizeof world[0], "the world and graphics object lists, 1024 -> 8192");
}

// ---- M1: the texture limit -----------------------------------------------------------------------
// The "~119 textures, then crash" rule. Surfaces drawn late (after the main scene) are bucketed by
// texture number into a 120-entry array at 0x522b40 -- bucket id+1, bucket 0 for untextured -- and
// nothing checks the number: add_deferred_surf writes past the end for texture 119 and up, straight
// into the model list head and the pool pointers that follow. The two drawing loops only visit
// buckets 0..118 (a 3-byte `cmp reg, 0x77`, too small to widen in place). M1 repoints begin_deferred's
// clear at a 1,024-bucket array here, and the three functions -- add_deferred_surf, end_deferred_surfs,
// draw_alpha_deferred_surfs -- are M3's rewrites (gx_model.cpp, PORT_FN_BUILDS on every build, as M1's
// own hooks were): they take the array and its size from begin_deferred's operands, so with M1's they
// use all 1,024 buckets, and a texture number that still wouldn't fit is drawn untextured instead of
// corrupting memory (vp_deferred_bucket_ok, below). Behaviour is otherwise identical: same buckets,
// same order, same two passes (opaque, then alpha). They must stay `new` for the lift: left original
// (or in shadow mode, which runs the original) they are the stock 120-bucket code.
enum { TEX_BUCKETS = 1024 };
static void* g_buckets[TEX_BUCKETS];
static volatile LONG g_tex_overflows, g_peak_tex, g_peak_table;
static int peak_textures();
static struct {                                                   // globals, resolved for the build
    uint32_t phobs, nphobs, collisions, walls, getextents_stub; // collisions
    uint32_t nwobs, ngobs;                                      // the exit log's peaks
} G;

// add_deferred_surf's rewrite asks here whether texture `id` has a bucket among `buckets` (M1's
// lifted count): no -> logged once, and it draws it untextured (bucket 0); yes -> the exit line's peaks
bool vp_deferred_bucket_ok(int id, int buckets) {
    int b = id + 1;
    if (b < 0 || b >= buckets) {
        if (InterlockedIncrement(&g_tex_overflows) == 1) logf("texture %d is past %d buckets: drawn untextured", id, buckets);
        return false;
    }
    if (id > g_peak_tex) {
        g_peak_tex = id;
        LONG used = peak_textures();
        if (used > g_peak_table) g_peak_table = used;
    }
    return true;
}

static void lift_texture_limit() {
    Field fields[] = {
        {0x45723d, 1, 0x522b40, (uint32_t)&g_buckets[0]},    // begin_deferred: mov edi, buckets
        {0x457244, 1, 0x78, TEX_BUCKETS},                     // begin_deferred: mov ecx, 120 (rep stosd)
        {0x45fbea, 1, 200, 1024, true},                       // txBegin: 'sys texture pool', 200 x 40
        {0x45fc25, 1, 0x80, 1024, true},                      // txBegin: 'vid texture pool', 128 x 40
    };
    // verify everything before touching anything
    // (vp_code_hash of v1.0's first bytes: add_deferred_surf's 7 -- push esi; mov ecx, [pool] -- end_deferred_surfs' 8,
    // draw_alpha_deferred_surfs' 6)
    if (!code_is(0x4573d0, 0xc2c6cfb8, 7) || !code_is(0x457290, 0xacf3d005, 8) || !code_is(0x457340, 0x44d71d16, 6)) {
        logf("NOT lifting the texture limit: the deferred-draw functions aren't the code %s should have", g_build->name);
        return;
    }
    patch_fields(fields, sizeof fields / sizeof fields[0], "the texture buckets and texture pools");
    // (the three deferred-draw functions are hooked by port_install: M3's rewrites in gx_model.cpp)
}

// ---- M1: the texture table --------------------------------------------------------------------------
// With the pools and buckets lifted, the next wall is the texture table itself: 250 entries of 40 bytes
// at 0x522fa0, and tc_add panics "out of texture cache entries" when it's full (Tex200, with eight cars'
// textures on top of the track's). 66 instructions in the texture functions address it -- fields at base
// +0x00..+0x24, and loop ends at 0x5256b0 / 0x5256d0 -- listed in texture_table_fields.inc (generated by
// tools/gen_texture_table.py). They're repointed at a 1,000-entry table here, with tc_add's count.
enum { TEX_TABLE = 1000, TEX_ENTRY = 0x28 };
static uint8_t g_tex_table[TEX_TABLE * TEX_ENTRY];

static void relocate_texture_table() {
    struct Ref { uint32_t at; uint8_t off; uint32_t old; int end; };
    static const Ref refs[] = {
#include "texture_table_fields.inc"
    };
    const int n = sizeof refs / sizeof refs[0];
    static Field fields[sizeof refs / sizeof refs[0] + 2];
    uint32_t base = (uint32_t)g_tex_table, end = base + TEX_TABLE * TEX_ENTRY;
    for (int i = 0; i < n; i++)
        fields[i] = {refs[i].at, refs[i].off, refs[i].old,
                     refs[i].end ? end + (refs[i].old - 0x5256b0) : base + (refs[i].old - 0x522fa0)};
    fields[n] = {0x45a60a, 2, 0xfa, TEX_TABLE};                // tc_add: cmp edx, 250 (table full)
    // tc_lookup counts entries as it walks the table and reports "not found" only if the count reached
    // 250. Missing this (first build) made a failed lookup return 1000 -- a garbage entry that tc_add
    // then trusted -- and the front end died in txSelect ("unknown wrap mode").
    fields[n + 1] = {0x45a6db, 2, 0xfa, TEX_TABLE};            // tc_lookup: cmp ebx, 250 (not found)
    patch_fields(fields, n + 2, "the texture table, 250 -> 1000");
}

// ---- M1: the options, language and open-file tables -----------------------------------------------------------------
// opt.obj keeps the options in a 256-item table (0x90 bytes each, 0x55a078) and find_item appends to it with no bound:
// the 257th item overwrote the colour constants and the telemetry after it. locale.obj keeps the languages (*.lng) in
// 8 LangInfos (0x40 bytes each, 0x509438), filled with no bound either: a 9th overwrote the language count. file.obj
// keeps every open file in 32 slots {char name[0x100]; HANDLE handle} at 0x505ea8, and alloc_file panics when they're
// all taken ("increase MAX_FILES") -- each loaded resource set keeps its archive open, so that was also the limit of
// 32 sets at once (fewer: the log and log.cfg hold two).
// Every instruction that addresses one of the tables -- 10, 6 and 20, and file.obj's two loop ends, listed in
// res_table_fields.inc (tools/gen_res_tables.py, which also checks that nothing else runs to a table's end or compares
// with its capacity) -- is repointed at a bigger table here, all or nothing per table. The rewrites (krn_res.cpp,
// krn_file.cpp) read the same operands (m1_operand) and use the new capacity (VP_LIFT_*).
// alloc_file's capacity is `cmp edx, 0x20`, an imm8: it can say at most 0x7f. M1 makes it 0x7f, so alloc_file left
// original (viperport.ini) hands out at most 127 never-used slots and then only reuses free ones below that -- inside
// the 256-slot table, so safe; its rewrite uses all 256. Either way nothing is written past the table.
// v1.0 race.exe only: the race.bin builds keep theirs (they have no rewrites to agree with, and their tables aren't in
// sites_*.inc). Below the old limits nothing changes but where the entries live.
static uint8_t g_opt_table[VP_LIFT_OPTIONS * 0x90];
static struct { uint8_t before[0x40]; uint8_t t[VP_LIFT_LANGUAGES * 0x40]; } g_lang_table;   // (index -1: a blank name)
static uint8_t g_file_table[VP_LIFT_FILES * 0x104];

static void relocate_res_tables() {
    if (!build_is_v10()) {
        logf("NOT lifting the options, language and open-file tables: v1.0 race.exe only");
        return;
    }
    struct Ref { uint32_t at; uint8_t off; uint32_t old; int table; };
    static const Ref refs[] = {
#include "res_table_fields.inc"
    };
    const int n = sizeof refs / sizeof refs[0];
    static Field opt[sizeof refs / sizeof refs[0]], lang[sizeof refs / sizeof refs[0]], files[sizeof refs / sizeof refs[0] + 1];
    int nopt = 0, nlang = 0, nfiles = 0;
    const uint32_t fbase = (uint32_t)g_file_table, fend = fbase + VP_LIFT_FILES * 0x104;
    for (int i = 0; i < n; i++) {
        const Ref& r = refs[i];
        if (r.table == 0) opt[nopt++] = {r.at, r.off, r.old, (uint32_t)g_opt_table + (r.old - 0x55a078)};
        else if (r.table == 1) lang[nlang++] = {r.at, r.off, r.old, (uint32_t)g_lang_table.t + (r.old - 0x509438)};
        else if (r.table == 2) files[nfiles++] = {r.at, r.off, r.old, fbase + (r.old - 0x505ea8)};
        else files[nfiles++] = {r.at, r.off, r.old, fend + (r.old - 0x507f28)};                  // a loop end
    }
    // alloc_file: cmp edx, 0x20 (83 FA 20) -- the dword from its imm8 on (20 7D 0B 8B: the jge after it), 0x20 -> 0x7f
    files[nfiles++] = {0x411650, 2, 0x8b0b7d20, 0x8b0b7d7f};
    patch_fields(opt, nopt, "the options table, 256 -> 4096 items");
    patch_fields(lang, nlang, "the languages, 8 -> 64");
    patch_fields(files, nfiles, "the open-file table, 32 -> 256");
}

// ---- M1: the track graph's facing-model lists ---------------------------------------------------------------------------
// draw_tree queues every camera-facing model node (mode 1) into 512 slots at 0x558968 and every upright one (mode 2) into
// 514 at 0x558160, with no bound: past them it overwrote the dynamic-model table (0x559168) and the other list. Only
// four instructions address the lists (draw_tree's two stores, GrafDraw's two loops); they're repointed at bigger lists
// here, v1.0 only (the race.bin builds keep theirs). The rewrites read the same operands (m1_operand) and stop at
// VP_LIFT_GRAF_FACING (wld_draw.cpp).
static uint8_t* g_graf_facing[VP_LIFT_GRAF_FACING];
static uint8_t* g_graf_upright[VP_LIFT_GRAF_FACING];

static void relocate_graf_lists() {
    if (!build_is_v10()) {
        logf("NOT lifting the graf's facing lists: v1.0 race.exe only");
        return;
    }
    const uint32_t facing = (uint32_t)&g_graf_facing[0], upright = (uint32_t)&g_graf_upright[0];
    Field f[] = {
        {0x46dcb6, 1, 0x558968, facing},                      // GrafDraw: mov ebp, facing list
        {0x46e047, 3, 0x558968, facing},                      // draw_tree: mov [eax*4 + facing list], esi
        {0x46ddca, 1, 0x558160, upright},                     // GrafDraw: mov esi, upright list
        {0x46e063, 3, 0x558160, upright},                     // draw_tree: mov [eax*4 + upright list], esi
    };
    patch_fields(f, sizeof f / sizeof f[0], "the graf's facing lists, 512 / 514 -> 8192");
}

// ---- M1: the sound limits -------------------------------------------------------------------------------------------
// SoundManager's table of every sound is one MemAlloc of 384 pointers (its constructor's push 0x600) and add_sound had
// no bound: the 385th overran the heap. The software mixer keeps each sound's SoftSound in a bag of 256 (SoftMixer::Begin's
// push 0x100) and the 257th panicked "full". Both sizes are raised to VP_LIFT_SOUNDS here, v1.0 only (the race.bin
// builds keep theirs). The rewrites read the same operands (m1_operand) and use them as the capacities (snd_mgr.cpp,
// snd_mix.cpp); past them a new sound is silent.
static void lift_sound_limits() {
    if (!build_is_v10()) {
        logf("NOT lifting the sound limits: v1.0 race.exe only");
        return;
    }
    Field f[] = {
        {0x473ed0, 1, 0x600, VP_LIFT_SOUNDS * 4},              // SoundManager::SoundManager: push 0x600 (the table's size)
        {0x474d78, 1, 0x100, VP_LIFT_SOUNDS},                  // SoftMixer::Begin: push 0x100 (the bag's capacity)
    };
    patch_fields(f, sizeof f / sizeof f[0], "the sounds, 384 (table) / 256 (mixer) -> 1024");
}

static int peak_textures() {                                    // entries in use at the moment
    int used = 0;
    for (int i = 0; i < TEX_TABLE; i++) used += g_tex_table[i * TEX_ENTRY] != 0;
    return used;
}

// ---- M1: collision broad-phase ----------------------------------------------------------------------
// collide_phobs (0x427120) tests every physics object against every later one, every tick: with 2,000
// obstacles that is ~2 million pair tests and the physics ran at a quarter speed. This rewrite keeps the
// original's exact sequence -- per object i: its pair collisions with each later j in ascending order,
// then its wall collision -- but only visits the j whose bounding boxes overlap i's. A pair whose boxes
// don't overlap can't be touching, and the collision routines return without effect when they aren't
// (collide_sphere_sphere: `cmp overlap, 0; jle exit`), so the result is the same, faster.
// Bounds come from each volume's own GetExtents (vtable +0x18); a volume without one (the base class's
// stub, 0x436080) or a tube (whose GetExtents can undershoot) makes its object unbounded, and an unbounded
// object is paired with everything.
typedef char(__fastcall* VBool_t)(void* self, void* edx);
typedef void(__fastcall* VVoid_t)(void* self, void* edx);
typedef void(__fastcall* VCollide_t)(void* self, void* edx, void* other);
typedef void(__fastcall* VExtents_t)(void* self, void* edx, float* mn, float* mx);
typedef void(__cdecl* CollideObject_t)(void* phob);
static CollideObject_t collide_object;
#define VSLOT(o, off) ((*(void***)(o))[(off) / 4])
static inline bool phob_dynamic(void* p) { return ((VBool_t)VSLOT(p, 0x2c))(p, 0) != 0; }   // IsDynamic
static inline bool phob_solid(void* p) { return ((VBool_t)VSLOT(p, 0x30))(p, 0) != 0; }     // IsSolid
static inline int phob_nvol(void* p) { return *(int*)((uint8_t*)p + 0x24); }
static inline void* phob_vol(void* p, int k) {                    // the original's bounds-checked fetch
    return (k < 0 || k >= phob_nvol(p)) ? 0 : ((void**)((uint8_t*)p + 0x14))[k];
}

struct Box { float mn[3], mx[3]; int idx; bool bounded; };
static std::vector<Box> g_boxes;
static std::vector<uint64_t> g_pairs;                             // (i << 32) | j, i < j
static volatile LONG64 g_pair_tests, g_pair_ticks;

static bool phob_box(void* p, Box& b) {
    b.bounded = true;
    for (int k = 0; k < 3; k++) { b.mn[k] = (float)3.0e38f; b.mx[k] = -(float)3.0e38f; }
    for (int k = 0; k < phob_nvol(p); k++) {
        void* v = phob_vol(p, k);
        if (!v || VSLOT(v, 0x18) == (void*)G.getextents_stub) { b.bounded = false; return false; }
        // A tube's GetExtents isn't a bounding box: it takes the minimum from one end cap and the maximum
        // from the other, which for some orientations is smaller than the tube (found porting it in M3).
        // Tubes (tag 'TUBE') are paired with everything, as the original's all-pairs loop does.
        if (*(uint32_t*)((uint8_t*)v + 0x14) == 0x54554245u) { b.bounded = false; return false; }
        float mn[3], mx[3];
        ((VExtents_t)VSLOT(v, 0x18))(v, 0, mn, mx);
        for (int a = 0; a < 3; a++) {
            if (!(mn[a] <= mx[a])) { b.bounded = false; return false; }   // NaN or inverted: trust nothing
            if (mn[a] < b.mn[a]) b.mn[a] = mn[a];
            if (mx[a] > b.mx[a]) b.mx[a] = mx[a];
        }
    }
    const float m = 0.05f;                                         // a hair of slack for rounding
    for (int a = 0; a < 3; a++) { b.mn[a] -= m; b.mx[a] += m; }
    return true;
}

static void build_pairs(void** ph, int n) {
    g_boxes.clear();
    g_pairs.clear();
    std::vector<int> unbounded;
    for (int i = 0; i < n; i++) {
        void* p = ph[i];
        if (!p || phob_nvol(p) == 0) continue;                     // can never take part in a pair
        Box b; b.idx = i;
        if (phob_box(p, b)) g_boxes.push_back(b); else unbounded.push_back(i);
    }
    std::sort(g_boxes.begin(), g_boxes.end(), [](const Box& a, const Box& b) { return a.mn[0] < b.mn[0]; });
    for (size_t a = 0; a < g_boxes.size(); a++) {                  // sort and sweep along x
        const Box& A = g_boxes[a];
        for (size_t c = a + 1; c < g_boxes.size() && g_boxes[c].mn[0] <= A.mx[0]; c++) {
            const Box& C = g_boxes[c];
            if (C.mn[1] > A.mx[1] || C.mx[1] < A.mn[1] || C.mn[2] > A.mx[2] || C.mx[2] < A.mn[2]) continue;
            uint32_t i = (uint32_t)(A.idx < C.idx ? A.idx : C.idx), j = (uint32_t)(A.idx < C.idx ? C.idx : A.idx);
            g_pairs.push_back(((uint64_t)i << 32) | j);
        }
    }
    for (int u : unbounded)                                        // unbounded: paired with everyone
        for (int k = 0; k < n; k++)
            if (k != u && ph[k] && phob_nvol(ph[k]) != 0) {
                bool seen_u = false;                               // two unbounded objects: add the pair once
                for (int w : unbounded) if (w == k) { seen_u = true; break; }
                if (seen_u && k < u) continue;
                uint32_t i = (uint32_t)(u < k ? u : k), j = (uint32_t)(u < k ? k : u);
                g_pairs.push_back(((uint64_t)i << 32) | j);
            }
    std::sort(g_pairs.begin(), g_pairs.end());
}

static void __cdecl collide_phobs(void) {
    void** ph = *(void***)G.phobs;
    int n = *(int*)G.nphobs;
    const bool collisions = *(uint8_t*)G.collisions != 0, walls = *(uint8_t*)G.walls != 0;
    if ((g_pair_ticks & 255) == 0) note_peaks();                   // every track has this, not every one obstacles
    // 1. every dynamic object's volumes move to where their object now is
    for (int i = 0; i < n; i++) {
        void* p = ph[i];
        if (p && phob_dynamic(p))
            for (int k = 0; k < phob_nvol(p); k++) ((VVoid_t)VSLOT(phob_vol(p, k), 0x04))(phob_vol(p, k), 0);
    }
    // 2. pairs (only the ones that can touch), then walls, object by object in the original order
    if (collisions) build_pairs(ph, n); else g_pairs.clear();
    size_t at = 0;
    LONG64 tests = 0;
    for (int i = 0; i < n; i++) {
        size_t from = at;
        while (at < g_pairs.size() && (int)(g_pairs[at] >> 32) == i) at++;
        void* p = ph[i];
        if (!p || !phob_dynamic(p) || phob_nvol(p) == 0) continue;
        if (collisions && phob_solid(p)) {
            for (size_t e = from; e < at; e++) {
                int j = (int)(uint32_t)g_pairs[e];
                void* q = ph[j];
                if (!q || phob_nvol(q) == 0 || !phob_dynamic(q) || !phob_solid(q)) continue;
                for (int kq = 0; kq < phob_nvol(q); kq++) {
                    void* vq = phob_vol(q, kq);
                    for (int kp = 0; kp < phob_nvol(p); kp++) {
                        ((VCollide_t)VSLOT(phob_vol(p, kp), 0x08))(phob_vol(p, kp), 0, vq);
                        tests++;
                    }
                }
            }
        }
        if (walls) collide_object(p);
    }
    g_pair_tests += tests;
    g_pair_ticks++;
}

// M3: switched through port.h. Every object's volumes, impulses and contacts can change, some outside
// the objects themselves, so it isn't shadow-checked: a replay with it on and off compares whole races.
static void fp_collide_phobs(Footprint& f) { f.replay_only = "it can change every physics object"; }
// sub esp,14h; push ebx; push esi; push edi; push ebp; xor esi,esi (the race.bin builds have no profiler
// calls in it, so theirs starts sub esp,10h -- the loops are the same)
PORT_FN_BUILDS(0x00427120, "collide_phobs", collide_phobs, fp_collide_phobs, 0xc6c97d66, 9)   // (its 9 bytes' hash)

// the most of each seen during the session, for the exit line
static volatile LONG g_peak_phobs, g_peak_wobs, g_peak_gobs;
static void note_peaks() {
    LONG p = *(LONG*)G.nphobs, w = *(LONG*)G.nwobs, g = *(LONG*)G.ngobs;
    if (p > g_peak_phobs) g_peak_phobs = p;
    if (w > g_peak_wobs) g_peak_wobs = w;
    if (g > g_peak_gobs) g_peak_gobs = g;
}

static void resolve() {
    PhysicsGetTime = (PhysicsGetTime_t)A(0x0042bc80);
    Obstacle_Perturb = (Method0_t)A(0x0043d3e0);
    PhobDyno_Update = (Method0_t)A(0x00445210);
    // what the deferred-draw rewrites (gx_model.cpp) resolve on first use: every build must have it
    static const uint32_t k_deferred_uses[] = {0x0041bb20, 0x0041bb60, 0x0045dfd0, 0x00458990, 0x00458a90, 0x0045a590,
                                               0x0045c250, 0x00458a60, 0x00457340, 0x00522d80, 0x00522d84, 0x004f2198};
    for (uint32_t a : k_deferred_uses) A(a);
    collide_object = (CollideObject_t)A(0x00427350);
    G.phobs = A(0x00520bb4);
    G.nphobs = A(0x00521090);
    G.collisions = A(0x004ecce4);
    G.walls = A(0x004ecce8);
    G.getextents_stub = A(0x00436080);                           // CollisionVolume::GetExtents, the stub
    G.nwobs = A(0x005522d0);
    G.ngobs = A(0x00553368);
}

// ---- diagnostics: the game's own log, and crashes --------------------------------------------------------
// The game writes its log to c:\log.log and its crash report to c:\except.log, which an ordinary user can't
// create today, so both are lost. Its log is mirrored here (a hook of its own, LogInstallHook), and a vectored
// exception handler notes each fault as it happens: the code, where, and the code addresses on the stack
// (hook\build\dinput.map names the DLL's; out\symbols.csv the game's). First chance: some are handled.
static void __cdecl game_log_hook(const char* msg) { logf("game: %s", msg); }
static volatile long g_faults;
static LONG CALLBACK fault_logger(EXCEPTION_POINTERS* e) {
    const DWORD code = e->ExceptionRecord->ExceptionCode;
    switch (code) {
    case EXCEPTION_ACCESS_VIOLATION: case EXCEPTION_INT_DIVIDE_BY_ZERO: case EXCEPTION_FLT_DIVIDE_BY_ZERO:
    case EXCEPTION_FLT_OVERFLOW: case EXCEPTION_FLT_INVALID_OPERATION: case EXCEPTION_ILLEGAL_INSTRUCTION:
    case EXCEPTION_PRIV_INSTRUCTION: case EXCEPTION_STACK_OVERFLOW: case EXCEPTION_FLT_STACK_CHECK:
        break;
    default:
        return EXCEPTION_CONTINUE_SEARCH;
    }
    if (InterlockedIncrement(&g_faults) > 20) return EXCEPTION_CONTINUE_SEARCH;
    const uintptr_t at = (uintptr_t)e->ExceptionRecord->ExceptionAddress;
    const uintptr_t self = (uintptr_t)g_self;
    char where[48];
    if (at >= 0x400000 && at < 0x600000) vpos_wsprintfA(where, "race.exe %08lx", (unsigned long)at);
    else vpos_wsprintfA(where, "dinput.dll+%05lx", (unsigned long)(at - self));
    char stack[16 * 22] = "";
    const uint32_t* sp = (const uint32_t*)(uintptr_t)e->ContextRecord->Esp;
    int n = 0;
    for (int i = 0; i < 256 && n < 16 && !vpos_IsBadReadPtr(sp + i, 4); i++) {
        const uint32_t v = sp[i];
        char one[24];
        if (v >= 0x401000 && v < 0x4d0000) vpos_wsprintfA(one, " %08lx", (unsigned long)v);
        else if (v >= self + 0x1000 && v < self + 0x400000) vpos_wsprintfA(one, " dll+%05lx", (unsigned long)(v - self));
        else continue;
        vpos_lstrcatA(stack, one);
        n++;
    }
    const ULONG_PTR* info = e->ExceptionRecord->ExceptionInformation;
    logf("FAULT %08lx at %s (thread %lu%s)%s%08lx; code on the stack:%s", code, where, vpos_GetCurrentThreadId(),
         vpos_GetCurrentThreadId() == g_physics_thread_id ? ", physics" : "",
         code == EXCEPTION_ACCESS_VIOLATION ? (info[0] ? ", writing " : ", reading ") : ", ",
         code == EXCEPTION_ACCESS_VIOLATION ? (unsigned long)info[1] : (unsigned long)e->ContextRecord->Eip, stack);
    return EXCEPTION_CONTINUE_SEARCH;
}
// LogBegin clears the hook table, so the hook goes in just after it (detour(0x00410d10), for gen_port_tables.py)
static uint8_t(__cdecl* o_LogBegin)();
static uint8_t __cdecl h_LogBegin() {
    const uint8_t r = o_LogBegin();
    ((void(__cdecl*)(void*))0x00411120)((void*)game_log_hook);                                 // LogInstallHook
    return r;
}
static void install_diagnostics() {
    vpos_AddVectoredExceptionHandler(0, fault_logger);
    if (g_build == &k_builds[0]) *(void**)&o_LogBegin = detour_front(0x00410d10, (void*)h_LogBegin, "LogBegin (the game's log, mirrored)");
}

static void install() {
    uint8_t* base = (uint8_t*)vpos_GetModuleHandleA(NULL);
    IMAGE_NT_HEADERS* nt = (IMAGE_NT_HEADERS*)(base + ((IMAGE_DOS_HEADER*)base)->e_lfanew);
    for (const Build& b : k_builds)
        if (nt->FileHeader.TimeDateStamp == b.timestamp) g_build = &b;
    if ((uintptr_t)base != 0x400000 || !g_build) {
        logf("host isn't a known build (base %p, timestamp %08lx): nothing hooked", base, nt->FileHeader.TimeDateStamp);
        return;
    }
    logf("host is %s", g_build->name);
    resolve();
    if (g_unresolved) {
        logf("NOT installing anything: %d addresses have no translation for %s", g_unresolved, g_build->name);
        return;
    }
    port_check_stock();                         // M3: before M1 patches any code, note non-stock functions
    lift_limits();
    lift_texture_limit();
    relocate_texture_table();
    relocate_res_tables();
    relocate_graf_lists();
    lift_sound_limits();
    char ini[MAX_PATH];                         // viperport.ini, beside this DLL
    vpos_GetModuleFileNameA(g_self, ini, MAX_PATH);
    char* slash = strrchr(ini, '\\');
    vpos_lstrcpyA(slash ? slash + 1 : ini, "viperport.ini");
    port_install(ini);                          // M3: rewritten functions (Obstacle::Update, collide_phobs, ...)
    session_install(ini);                       // M3: the session recorder (before the race recorder, which it drives)
    replay_install(ini);                        // M3: the race recorder and replayer
    gfx_capture_install(ini);                   // [debug] capture=<seconds>: frames for the hi-res 2D work
    platform_install(g_build->name);            // M2: SDL2 window and input, when viperport.ini asks
    install_diagnostics();
}

BOOL WINAPI DllMain(HINSTANCE inst, DWORD reason, LPVOID) {
    if (reason == DLL_PROCESS_ATTACH) {
        g_self = inst;
        DisableThreadLibraryCalls(inst);
        if (GetEnvironmentVariableA(VP_PROBE_ENV, 0, 0)) {  // viperport.exe --probe: no log, no install (vp_probe_build)
            g_probe = true;
            return TRUE;
        }
#ifdef VP_GCC
        vp_os_init(vp_standalone());            // the stand-ins are race.exe's imports: the port's own calls go there too
#endif
        char ini[MAX_PATH];                     // viperport.ini, beside this DLL: [test] two_copies, before the log
        vpos_GetModuleFileNameA(inst, ini, MAX_PATH);
        char* slash = strrchr(ini, '\\');
        vpos_lstrcpyA(slash ? slash + 1 : ini, "viperport.ini");
        decide_copy(ini);
        g_log = open_dll_log();
        logf("viperport loaded (M1: object limits, texture limit + table, options + language + open-file tables; M3: rewritten functions, race recorder)");
        if (*g_copy_note) logf("%s", g_copy_note);
        install();
    } else if (reason == DLL_PROCESS_DETACH) {
        if (g_probe) return TRUE;
        logf("exit: new Obstacle::Update ran %ld times, woke obstacles %ld times, put them to sleep %ld times",
             g_calls, g_perturbs, g_sleeps);
        logf("exit: peak physics objects %ld (stock limit 512), world objects %ld and graphics objects %ld (stock 1024 each)",
             g_peak_phobs, g_peak_wobs, g_peak_gobs);
        logf("exit: highest texture number drawn through the deferred buckets %ld (stock crashes past 118); %ld past %d",
             g_peak_tex, g_tex_overflows, TEX_BUCKETS);
        logf("exit: texture table entries in use at the peak %ld (stock table 250)", g_peak_table);
        if (build_is_v10())
            logf("exit: options items %ld (stock table 256), languages %ld (stock 8), open-file slots ever used %ld (stock 32)",
                 *(volatile LONG*)0x0055a05c, *(volatile LONG*)0x00509638, *(volatile LONG*)0x00505ea0);
        replay_report();
        session_report();
        port_report();
        renderer_report();
        platform_report();
#ifdef VP_GCC
        vp_os_report();
#endif
        if (g_pair_ticks)
            logf("exit: collisions: %.0f volume pair tests per tick on average (stock tests every pair)",
                 (double)g_pair_tests / (double)g_pair_ticks);
        if (g_log) fclose(g_log);
    }
    return TRUE;
}
