// viperport -- milestone M0's proof of concept.
//
// A proxy DINPUT.dll: race.exe imports one function from it (DirectInputCreateA), and Windows looks
// in the game's own folder before the system one, so a DLL of that name there loads with the game --
// race.exe itself is never modified. The one export forwards to the real DirectInput; on load, the
// DLL replaces a real game function with new C++.
//
// The function is Obstacle::Update (race.exe v1.0, 0x43d2e0): the sleep logic every obstacle ball,
// cube and prism runs each physics tick. The C++ below behaves exactly like the original (see
// docs/reference/file-formats.md, "How an obstacle lives") and counts its calls in viperport.log.
//
// Builds: v1.0 race.exe, and the race.bin builds -- v1.1, and 1.2.4-1.2.6 (one compile, told apart
// only by community hex-edits). Addresses in this file are all v1.0's; the others are translated through
// a per-build table generated by tools/port_sites.py (see "which engine build" below).
//
// Safety: nothing is patched unless the host is a known build (by PE timestamp), and every function
// replaced and every field changed first holds exactly what that build should. Otherwise it logs why
// and stays out of the way.
#define _CRT_SECURE_NO_WARNINGS
#include <windows.h>
#include <stdint.h>
#include <stdio.h>
#include <algorithm>
#include <vector>
#include "viperport.h"

// ---- the one export, forwarded ---------------------------------------------------------------------
typedef HRESULT(WINAPI* DirectInputCreateA_t)(HINSTANCE, DWORD, void**, void*);
static HMODULE g_real_dinput;

extern "C" HRESULT WINAPI DirectInputCreateA(HINSTANCE inst, DWORD version, void** out, void* outer) {
    if (!g_real_dinput) {
        char path[MAX_PATH];
        GetSystemDirectoryA(path, MAX_PATH);             // WOW64 redirects this to SysWOW64 for us
        lstrcatA(path, "\\dinput.dll");
        g_real_dinput = LoadLibraryA(path);
    }
    DirectInputCreateA_t real = g_real_dinput ? (DirectInputCreateA_t)GetProcAddress(g_real_dinput, "DirectInputCreateA") : 0;
    return real ? real(inst, version, out, outer) : E_FAIL;
}

// ---- logging -------------------------------------------------------------------------------------------
static FILE* g_log;
void logf(const char* fmt, ...) {
    if (!g_log) return;
    SYSTEMTIME t; GetLocalTime(&t);
    fprintf(g_log, "%02d:%02d:%02d.%03d  ", t.wHour, t.wMinute, t.wSecond, t.wMilliseconds);
    va_list ap; va_start(ap, fmt); vfprintf(g_log, fmt, ap); va_end(ap);
    fputc('\n', g_log); fflush(g_log);
}

// ---- which engine build ------------------------------------------------------------------------------
// Every game address in this file is written as its v1.0 race.exe address. The race.bin builds run the
// same code elsewhere: tools/port_sites.py carries each address this file uses across (matched functions,
// then the same instruction inside them) and checks the target's bytes, into one table per build.
// A(v10) is the address in the running build. A table entry's value is what should be there: a patched
// field's current value, or a function's first four bytes.
struct Xlat { uint32_t v10, here, value; };
static const Xlat k_v11[] = {
#include "sites_v11.inc"
};
static const Xlat k_v12x[] = {
#include "sites_v12x.inc"
};
struct Build { const char* name; uint32_t timestamp; const Xlat* table; int n; };
static const Build k_builds[] = {
    {"v1.0 race.exe", 0x362de68c, 0, 0},                                // the addresses as written
    {"v1.1 race.bin", 0x36acae44, k_v11, sizeof k_v11 / sizeof k_v11[0]},
    {"1.2.4-1.2.6 race.bin", 0x40e074ad, k_v12x, sizeof k_v12x / sizeof k_v12x[0]},
};
static const Build* g_build;
static int g_unresolved;

static const Xlat* xlat(uint32_t v10) {
    for (int i = 0; i < g_build->n; i++)
        if (g_build->table[i].v10 == v10) return &g_build->table[i];
    return 0;
}

bool have(uint32_t v10) { return !g_build->table || xlat(v10) != 0; }

uint32_t A(uint32_t v10) {
    if (!g_build->table) return v10;
    if (const Xlat* x = xlat(v10)) return x->here;
    logf("no address for v1.0 %08x in %s (regenerate its table with tools/port_sites.py)", v10, g_build->name);
    g_unresolved++;
    return 0;
}

// ---- the game's own functions and globals we use, resolved for the build at load ---------------------
typedef float(__cdecl* PhysicsGetTime_t)(void);              // ?PhysicsGetTime@@YAMXZ
typedef void(__fastcall* Method0_t)(void* self, void* edx);   // a __thiscall with no arguments
static PhysicsGetTime_t PhysicsGetTime;
static Method0_t Obstacle_Perturb;                            // ?Perturb@Obstacle@@QAEXXZ
static Method0_t PhobDyno_Update;                             // ?Update@PhobDyno@@UAEXXZ

static volatile LONG g_calls, g_sleeps, g_perturbs;
static void note_peaks();

// Obstacle::Update, rewritten. __fastcall with an unused edx is how a __thiscall is received.
static void __fastcall Obstacle_Update(uint8_t* self, void* /*edx*/) {
    LONG n = InterlockedIncrement(&g_calls);
    if ((n & 255) == 1) note_peaks();
    if (n == 1) logf("first call to the new Obstacle::Update (obstacle at %p)", self);
    const float* v = (const float*)(self + 0x234);            // linear velocity
    // Wake (restart the 1 s timer) while moving faster than 0.5 m/s -- unless fallen below y = -500.
    // The original compares the height's raw bits UNSIGNED against -500.0f (0xc3fa0000), so any
    // positive height passes and only heights at or below -500 fail; reproduced exactly here.
    float speed2 = (v[2] * v[2] + v[1] * v[1]) + v[0] * v[0];
    uint32_t ybits = *(const uint32_t*)(self + 0x60);
    if (speed2 > 0.25f && ybits < 0xc3fa0000u) {
        Obstacle_Perturb(self, 0);
        InterlockedIncrement(&g_perturbs);
    }
    if (!self[0x4ac])                                          // asleep: no physics at all
        return;
    if (*(const float*)(self + 0x4a8) + 1.0f < PhysicsGetTime()) {
        self[0x4ac] = 0;                                       // a second since the last wake: sleep
        float* w = (float*)(self + 0x240);                     // angular velocity
        w[0] = w[1] = w[2] = 0.0f;
        float* lv = (float*)(self + 0x234);
        lv[0] = lv[1] = lv[2] = 0.0f;
        InterlockedIncrement(&g_sleeps);
        return;
    }
    PhobDyno_Update(self, 0);
}

// ---- hooking -------------------------------------------------------------------------------------------
// Does the function at v1.0 address v10 start as it should? v1.0: the prologue given; another build: the
// first four bytes its table recorded.
bool code_is(uint32_t v10, const uint8_t* expect, size_t n) {
    uint32_t at = A(v10);
    if (!at) return false;
    if (!g_build->table) return memcmp((void*)at, expect, n) == 0;
    return memcmp((void*)at, &xlat(v10)->value, 4) == 0;
}

bool jmp_hook(uint32_t v10, const uint8_t* expect, size_t n, void* to, const char* what) {
    if (!code_is(v10, expect, n)) {
        logf("NOT hooking %s: its first bytes aren't what %s has there", what, g_build->name);
        return false;
    }
    uint32_t at = A(v10);
    uint8_t* p = (uint8_t*)at;
    DWORD old;
    VirtualProtect(p, 5, PAGE_EXECUTE_READWRITE, &old);
    p[0] = 0xE9;
    *(int32_t*)(p + 1) = (int32_t)((uint8_t*)to - (p + 5));
    VirtualProtect(p, 5, old, &old);
    FlushInstructionCache(GetCurrentProcess(), p, 5);
    logf("hooked %s at %08x -> %p", what, at, to);
    return true;
}

// ---- M1: lifting the object limits ---------------------------------------------------------------
// Three fixed lists cap how much a track can hold, and none of them is checked in the release build
// (v1.1 and 1.2.x have the same three; their two world lists hold 1,040):
//   * physics objects: PhysTaskBegin allocates 0x800 bytes = 512 pointers and fills it with every car,
//     checkpoint, obstacle, wobble and static in the track, with no bound. Everything else reaches the
//     array through its pointer and count, so only the allocation's size needs raising.
//   * world objects and graphics objects: static 1,024-entry arrays in .data (0x5512a0, 0x5522d8). Eleven
//     instructions address them; they're repointed at bigger arrays here, along with the two capacity
//     checks and the two 1,024-entry clears in WorldEndCommon.
enum { PHOB_CAP = 8192, WOB_CAP = 8192, GOB_CAP = 8192 };
static void* g_wobs[WOB_CAP + 2];               // index 0 unused: the game pre-increments, first entry at [1]
static void* g_gobs[GOB_CAP + 2];

// A 32-bit operand to change: the instruction's v1.0 address, the operand's offset in it, the v1.0 value
// and the new one. at_least marks a pool size (a push/mov imm32) that is only ever raised: the community
// builds hex-edited several of them to their own sizes, so any size is accepted and a bigger one kept.
struct Field { uint32_t at; uint8_t off; uint32_t old; uint32_t neu; bool at_least; };

static uint32_t field_addr(const Field& f) { return g_build->table ? A(f.at) : f.at + f.off; }
static uint32_t field_old(const Field& f) { return g_build->table ? xlat(f.at)->value : f.old; }

static bool patch_fields(Field* f, int n, const char* what) {
    for (int i = 0; i < n; i++) {                                    // all or nothing
        uint32_t at = field_addr(f[i]);
        bool ok = at != 0;
        if (ok && f[i].at_least) {
            uint8_t op = *(uint8_t*)(at - 1);                        // push imm32, or mov reg, imm32
            uint32_t now = *(uint32_t*)at;
            ok = (op == 0x68 || (op >= 0xB8 && op <= 0xBF)) && now > 0 && now < 0x100000;
        } else if (ok) {
            ok = *(uint32_t*)at == field_old(f[i]);
        }
        if (!ok) {
            logf("NOT lifting %s: the field for v1.0 %08x isn't what %s has there", what, f[i].at, g_build->name);
            return false;
        }
    }
    for (int i = 0; i < n; i++) {
        uint8_t* p = (uint8_t*)field_addr(f[i]);
        uint32_t neu = f[i].neu;
        if (f[i].at_least && *(uint32_t*)p > neu) neu = *(uint32_t*)p;
        DWORD old;
        VirtualProtect(p, 4, PAGE_EXECUTE_READWRITE, &old);
        *(uint32_t*)p = neu;
        VirtualProtect(p, 4, old, &old);
        FlushInstructionCache(GetCurrentProcess(), p, 4);
    }
    logf("lifted %s (%d fields)", what, n);
    return true;
}

static void lift_limits() {
    uint32_t wob = (uint32_t)&g_wobs[0], gob = (uint32_t)&g_gobs[0];
    Field phys[] = {
        {0x426893, 1, 0x800, PHOB_CAP * 4, true},             // PhysTaskBegin: push 0x800 -> MemAlloc
    };
    Field world[] = {
        {0x46283a, 3, 0x55129c, wob},                         // WorldAddWob: mov [eax*4 + list-4], esi
        {0x462806, 6, 0x400, WOB_CAP},                        // WorldAddWob: cmp count, 0x400
        {0x461e39, 1, 0x5512a0, wob + 4},                     // WorldEndCommon: mov edi, list
        {0x461e3e, 1, 0x400, WOB_CAP},                        // WorldEndCommon: mov ecx, 0x400 (rep stosd)
        {0x462196, 1, 0x5512a0, wob + 4},                     // WorldUpdate: mov edi, list
        {0x4627f0, 3, 0x5522d4, gob},                         // WorldAddGob: mov [eax*4 + list-4], ecx
        {0x4627ca, 6, 0x400, GOB_CAP},                        // WorldAddGob: cmp count, 0x400
        {0x461e0e, 1, 0x5522d8, gob + 4},                     // WorldEndCommon: mov esi, list (destroy loop)
        {0x461e2b, 1, 0x5522d8, gob + 4},                     // WorldEndCommon: mov edi, list
        {0x461e32, 1, 0x400, GOB_CAP},                        // WorldEndCommon: mov ecx, 0x400 (rep stosd)
        {0x461f5c, 1, 0x5522d8, gob + 4},                     // WorldInitTextures
        {0x4622a2, 1, 0x5522d8, gob + 4},                     // WorldDraw
        {0x4624c7, 1, 0x5522d8, gob + 4},                     // draw_mirror
        {0x462595, 1, 0x5522d8, gob + 4},                     // WorldDraw2D
        {0x463f4d, 1, 0x5522d8, gob + 4},                     // sort_objects: push list (for qsort)
    };
    // Fixed pools behind them: every obstacle loads its own model instance, and each draws through the
    // deferred list. Balls2000 died "out of memory in pool(models)" once the lists above were lifted.
    // Model handles are the pool entries' own pointers (convert_to_mrmodel returns its argument), so
    // nothing indexes these pools by number; the counts can simply grow.
    Field pools[] = {
        {0x455741, 1, 0x990, 16384, true},                    // mr_model_begin: 'models', 2448 x 48 bytes
        {0x455706, 1, 0x1320, 32768, true},                   // mr_model_begin: 'surf info', 4896 x 44 bytes
        {0x457216, 1, 0x400, 8192, true},                     // begin_deferred: 'deferr pool', 1024 x 16 bytes
    };
    patch_fields(pools, sizeof pools / sizeof pools[0], "the model, surface and deferred-draw pools");
    patch_fields(phys, 1, "the physics-object limit, 512 -> 8192");
    patch_fields(world, sizeof world / sizeof world[0], "the world and graphics object lists, 1024 -> 8192");
}

// ---- M1: the texture limit -----------------------------------------------------------------------
// The "~119 textures, then crash" rule. Surfaces drawn late (after the main scene) are bucketed by
// texture number into a 120-entry array at 0x522b40 -- bucket id+1, bucket 0 for untextured -- and
// nothing checks the number: add_deferred_surf writes past the end for texture 119 and up, straight
// into the model list head and the pool pointers that follow. The two drawing loops only visit
// buckets 0..118 (a 3-byte `cmp reg, 0x77`, too small to widen in place), so these three functions
// are rewritten here with a 1,024-bucket array; begin_deferred's clear is repointed at it. A texture
// number that still wouldn't fit is drawn untextured instead of corrupting memory. Behaviour is
// otherwise identical: same buckets, same order, same two passes (opaque, then alpha).
enum { TEX_BUCKETS = 1024 };
struct DeferredEntry { void* surf_info; void* surface; void* model_info; DeferredEntry* next; };
static DeferredEntry* g_buckets[TEX_BUCKETS];
static volatile LONG g_tex_overflows, g_peak_tex, g_peak_table;
static int peak_textures();

typedef void*(__fastcall* PoolAlloc_t)(void* pool, void* edx);
typedef void(__fastcall* PoolFree_t)(void* pool, void* edx, void* p);
typedef void(__cdecl* Void_t)(void);
typedef void(__cdecl* IntArg_t)(int);
typedef unsigned char(__cdecl* HasAlpha_t)(int);
typedef void(__cdecl* PreLit_t)(void* surface, void* vertices, void* lit);
typedef void(__cdecl* DPDraw_t)(const void* verts, int nverts, const uint16_t* idx, int nidx);
static PoolAlloc_t PoolBase_alloc;
static PoolFree_t PoolBase_free;
static Void_t dxStateFlush;
static IntArg_t dxDPBegin;
static Void_t dxDPEnd;
static HasAlpha_t TextureHasAlpha;
static PreLit_t LightSurfacePreLit;
static DPDraw_t dxDPDraw;
static struct {                                                   // globals, resolved for the build
    uint32_t deferred_pool, deferred_flag, prelit_buffer;       // the texture limit
    uint32_t phobs, nphobs, collisions, walls, getextents_stub; // collisions
    uint32_t nwobs, ngobs;                                      // the exit log's peaks
} G;
#define DEFERRED_POOL (*(void**)G.deferred_pool)
#define PRELIT_BUFFER (*(void**)G.prelit_buffer)

static void __cdecl add_deferred_surf(void* model_info, void* surface, void* surf_info) {
    int id = *(int*)((uint8_t*)surf_info + 0x14);
    DeferredEntry* e = (DeferredEntry*)PoolBase_alloc(DEFERRED_POOL, 0);
    e->surf_info = surf_info;
    e->surface = surface;
    e->model_info = model_info;
    int b = id + 1;
    if (b < 0 || b >= TEX_BUCKETS) {
        if (InterlockedIncrement(&g_tex_overflows) == 1) logf("texture %d is past %d buckets: drawn untextured", id, TEX_BUCKETS);
        b = 0;
    } else if (id > g_peak_tex) {
        g_peak_tex = id;
        LONG used = peak_textures();
        if (used > g_peak_table) g_peak_table = used;
    }
    e->next = g_buckets[b];
    g_buckets[b] = e;
}

static void draw_bucket(int b) {
    dxDPBegin(b - 1);
    for (DeferredEntry* e = g_buckets[b]; e;) {
        LightSurfacePreLit(e->surface, *(void**)((uint8_t*)e->model_info + 4), PRELIT_BUFFER);
        uint8_t* si = (uint8_t*)e->surf_info;
        dxDPDraw(*(void**)(si + 0x20), *(int*)(si + 0x24), *(uint16_t**)(si + 0x18), *(int*)(si + 0x1c));
        DeferredEntry* next = e->next;
        PoolBase_free(DEFERRED_POOL, 0, e);
        e = next;
    }
    dxDPEnd();
    g_buckets[b] = 0;
}

static void __cdecl draw_alpha_deferred_surfs(void) {           // everything still queued
    dxStateFlush();
    for (int b = 0; b < TEX_BUCKETS; b++)
        if (g_buckets[b]) draw_bucket(b);
}

static void __cdecl end_deferred_surfs(void) {                  // opaque buckets first, then the rest
    *(uint8_t*)G.deferred_flag = 0;                              // a BYTE (mov byte ptr [522d84h], bl)
    dxStateFlush();
    for (int b = 0; b < TEX_BUCKETS; b++)
        if (g_buckets[b] && !TextureHasAlpha(b - 1)) draw_bucket(b);
    draw_alpha_deferred_surfs();
}

static void lift_texture_limit() {
    static const uint8_t add_pro[] = {0x56, 0x8B, 0x0D, 0x80, 0x2D, 0x52, 0x00};
    static const uint8_t end_pro[] = {0x53, 0x56, 0x57, 0x33, 0xDB, 0x55, 0x88, 0x1D};
    static const uint8_t alpha_pro[] = {0x53, 0x56, 0x57, 0x55, 0x33, 0xFF};
    Field fields[] = {
        {0x45723d, 1, 0x522b40, (uint32_t)&g_buckets[0]},    // begin_deferred: mov edi, buckets
        {0x457244, 1, 0x78, TEX_BUCKETS},                     // begin_deferred: mov ecx, 120 (rep stosd)
        {0x45fbea, 1, 200, 1024, true},                       // txBegin: 'sys texture pool', 200 x 40
        {0x45fc25, 1, 0x80, 1024, true},                      // txBegin: 'vid texture pool', 128 x 40
    };
    // verify everything before touching anything
    if (!code_is(0x4573d0, add_pro, sizeof add_pro) || !code_is(0x457290, end_pro, sizeof end_pro) ||
        !code_is(0x457340, alpha_pro, sizeof alpha_pro)) {
        logf("NOT lifting the texture limit: the deferred-draw functions aren't the code %s should have", g_build->name);
        return;
    }
    if (!patch_fields(fields, sizeof fields / sizeof fields[0], "the texture buckets and texture pools"))
        return;
    jmp_hook(0x4573d0, add_pro, sizeof add_pro, (void*)add_deferred_surf, "add_deferred_surf");
    jmp_hook(0x457290, end_pro, sizeof end_pro, (void*)end_deferred_surfs, "end_deferred_surfs");
    jmp_hook(0x457340, alpha_pro, sizeof alpha_pro, (void*)draw_alpha_deferred_surfs, "draw_alpha_deferred_surfs");
}

// ---- M1: the texture table --------------------------------------------------------------------------
// With the pools and buckets lifted, the next wall is the texture table itself: 250 entries of 40 bytes
// at 0x522fa0, and tc_add panics "out of texture cache entries" when it's full (Tex200, with eight cars'
// textures on top of the track's). 66 instructions in the texture functions address it -- fields at base
// +0x00..+0x24, and loop ends at 0x5256b0 / 0x5256d0 -- listed in texture_table_fields.inc (generated by
// tools/gen_texture_table.py). They're repointed at a 1,000-entry table here, with tc_add's count.
enum { TEX_TABLE = 1000, TEX_ENTRY = 0x28 };
static uint8_t g_tex_table[TEX_TABLE * TEX_ENTRY];

static void relocate_texture_table() {
    struct Ref { uint32_t at; uint8_t off; uint32_t old; int end; };
    static const Ref refs[] = {
#include "texture_table_fields.inc"
    };
    const int n = sizeof refs / sizeof refs[0];
    static Field fields[sizeof refs / sizeof refs[0] + 2];
    uint32_t base = (uint32_t)g_tex_table, end = base + TEX_TABLE * TEX_ENTRY;
    for (int i = 0; i < n; i++)
        fields[i] = {refs[i].at, refs[i].off, refs[i].old,
                     refs[i].end ? end + (refs[i].old - 0x5256b0) : base + (refs[i].old - 0x522fa0)};
    fields[n] = {0x45a60a, 2, 0xfa, TEX_TABLE};                // tc_add: cmp edx, 250 (table full)
    // tc_lookup counts entries as it walks the table and reports "not found" only if the count reached
    // 250. Missing this (first build) made a failed lookup return 1000 -- a garbage entry that tc_add
    // then trusted -- and the front end died in txSelect ("unknown wrap mode").
    fields[n + 1] = {0x45a6db, 2, 0xfa, TEX_TABLE};            // tc_lookup: cmp ebx, 250 (not found)
    patch_fields(fields, n + 2, "the texture table, 250 -> 1000");
}

static int peak_textures() {                                    // entries in use at the moment
    int used = 0;
    for (int i = 0; i < TEX_TABLE; i++) used += g_tex_table[i * TEX_ENTRY] != 0;
    return used;
}

// ---- M1: collision broad-phase ----------------------------------------------------------------------
// collide_phobs (0x427120) tests every physics object against every later one, every tick: with 2,000
// obstacles that is ~2 million pair tests and the physics ran at a quarter speed. This rewrite keeps the
// original's exact sequence -- per object i: its pair collisions with each later j in ascending order,
// then its wall collision -- but only visits the j whose bounding boxes overlap i's. A pair whose boxes
// don't overlap can't be touching, and the collision routines return without effect when they aren't
// (collide_sphere_sphere: `cmp overlap, 0; jle exit`), so the result is the same, faster.
// Bounds come from each volume's own GetExtents (vtable +0x18); a volume without one (the base class's
// stub, 0x436080) makes its object unbounded, and an unbounded object is paired with everything.
typedef char(__fastcall* VBool_t)(void* self, void* edx);
typedef void(__fastcall* VVoid_t)(void* self, void* edx);
typedef void(__fastcall* VCollide_t)(void* self, void* edx, void* other);
typedef void(__fastcall* VExtents_t)(void* self, void* edx, float* mn, float* mx);
typedef void(__cdecl* CollideObject_t)(void* phob);
static CollideObject_t collide_object;
#define VSLOT(o, off) ((*(void***)(o))[(off) / 4])
static inline bool phob_dynamic(void* p) { return ((VBool_t)VSLOT(p, 0x2c))(p, 0) != 0; }   // IsDynamic
static inline bool phob_solid(void* p) { return ((VBool_t)VSLOT(p, 0x30))(p, 0) != 0; }     // IsSolid
static inline int phob_nvol(void* p) { return *(int*)((uint8_t*)p + 0x24); }
static inline void* phob_vol(void* p, int k) {                    // the original's bounds-checked fetch
    return (k < 0 || k >= phob_nvol(p)) ? 0 : ((void**)((uint8_t*)p + 0x14))[k];
}

struct Box { float mn[3], mx[3]; int idx; bool bounded; };
static std::vector<Box> g_boxes;
static std::vector<uint64_t> g_pairs;                             // (i << 32) | j, i < j
static volatile LONG64 g_pair_tests, g_pair_ticks;

static bool phob_box(void* p, Box& b) {
    b.bounded = true;
    for (int k = 0; k < 3; k++) { b.mn[k] = 3.0e38f; b.mx[k] = -3.0e38f; }
    for (int k = 0; k < phob_nvol(p); k++) {
        void* v = phob_vol(p, k);
        if (!v || VSLOT(v, 0x18) == (void*)G.getextents_stub) { b.bounded = false; return false; }
        float mn[3], mx[3];
        ((VExtents_t)VSLOT(v, 0x18))(v, 0, mn, mx);
        for (int a = 0; a < 3; a++) {
            if (!(mn[a] <= mx[a])) { b.bounded = false; return false; }   // NaN or inverted: trust nothing
            if (mn[a] < b.mn[a]) b.mn[a] = mn[a];
            if (mx[a] > b.mx[a]) b.mx[a] = mx[a];
        }
    }
    const float m = 0.05f;                                         // a hair of slack for rounding
    for (int a = 0; a < 3; a++) { b.mn[a] -= m; b.mx[a] += m; }
    return true;
}

static void build_pairs(void** ph, int n) {
    g_boxes.clear();
    g_pairs.clear();
    std::vector<int> unbounded;
    for (int i = 0; i < n; i++) {
        void* p = ph[i];
        if (!p || phob_nvol(p) == 0) continue;                     // can never take part in a pair
        Box b; b.idx = i;
        if (phob_box(p, b)) g_boxes.push_back(b); else unbounded.push_back(i);
    }
    std::sort(g_boxes.begin(), g_boxes.end(), [](const Box& a, const Box& b) { return a.mn[0] < b.mn[0]; });
    for (size_t a = 0; a < g_boxes.size(); a++) {                  // sort and sweep along x
        const Box& A = g_boxes[a];
        for (size_t c = a + 1; c < g_boxes.size() && g_boxes[c].mn[0] <= A.mx[0]; c++) {
            const Box& C = g_boxes[c];
            if (C.mn[1] > A.mx[1] || C.mx[1] < A.mn[1] || C.mn[2] > A.mx[2] || C.mx[2] < A.mn[2]) continue;
            uint32_t i = (uint32_t)(A.idx < C.idx ? A.idx : C.idx), j = (uint32_t)(A.idx < C.idx ? C.idx : A.idx);
            g_pairs.push_back(((uint64_t)i << 32) | j);
        }
    }
    for (int u : unbounded)                                        // unbounded: paired with everyone
        for (int k = 0; k < n; k++)
            if (k != u && ph[k] && phob_nvol(ph[k]) != 0) {
                bool seen_u = false;                               // two unbounded objects: add the pair once
                for (int w : unbounded) if (w == k) { seen_u = true; break; }
                if (seen_u && k < u) continue;
                uint32_t i = (uint32_t)(u < k ? u : k), j = (uint32_t)(u < k ? k : u);
                g_pairs.push_back(((uint64_t)i << 32) | j);
            }
    std::sort(g_pairs.begin(), g_pairs.end());
}

static void __cdecl collide_phobs(void) {
    void** ph = *(void***)G.phobs;
    int n = *(int*)G.nphobs;
    const bool collisions = *(uint8_t*)G.collisions != 0, walls = *(uint8_t*)G.walls != 0;
    // 1. every dynamic object's volumes move to where their object now is
    for (int i = 0; i < n; i++) {
        void* p = ph[i];
        if (p && phob_dynamic(p))
            for (int k = 0; k < phob_nvol(p); k++) ((VVoid_t)VSLOT(phob_vol(p, k), 0x04))(phob_vol(p, k), 0);
    }
    // 2. pairs (only the ones that can touch), then walls, object by object in the original order
    if (collisions) build_pairs(ph, n); else g_pairs.clear();
    size_t at = 0;
    LONG64 tests = 0;
    for (int i = 0; i < n; i++) {
        size_t from = at;
        while (at < g_pairs.size() && (int)(g_pairs[at] >> 32) == i) at++;
        void* p = ph[i];
        if (!p || !phob_dynamic(p) || phob_nvol(p) == 0) continue;
        if (collisions && phob_solid(p)) {
            for (size_t e = from; e < at; e++) {
                int j = (int)(uint32_t)g_pairs[e];
                void* q = ph[j];
                if (!q || phob_nvol(q) == 0 || !phob_dynamic(q) || !phob_solid(q)) continue;
                for (int kq = 0; kq < phob_nvol(q); kq++) {
                    void* vq = phob_vol(q, kq);
                    for (int kp = 0; kp < phob_nvol(p); kp++) {
                        ((VCollide_t)VSLOT(phob_vol(p, kp), 0x08))(phob_vol(p, kp), 0, vq);
                        tests++;
                    }
                }
            }
        }
        if (walls) collide_object(p);
    }
    g_pair_tests += tests;
    g_pair_ticks++;
}

static void speed_up_collisions() {
    // sub esp,14h; push ebx; push esi; push edi; push ebp; xor esi,esi (the race.bin builds have no
    // profiler calls in it, so theirs starts sub esp,10h -- the loops are the same)
    static const uint8_t pro[] = {0x83, 0xEC, 0x14, 0x53, 0x56, 0x57, 0x55, 0x33, 0xF6};
    jmp_hook(0x00427120, pro, sizeof pro, (void*)collide_phobs, "collide_phobs (broad-phase)");
}

// the most of each seen during the session, for the exit line
static volatile LONG g_peak_phobs, g_peak_wobs, g_peak_gobs;
static void note_peaks() {
    LONG p = *(LONG*)G.nphobs, w = *(LONG*)G.nwobs, g = *(LONG*)G.ngobs;
    if (p > g_peak_phobs) g_peak_phobs = p;
    if (w > g_peak_wobs) g_peak_wobs = w;
    if (g > g_peak_gobs) g_peak_gobs = g;
}

static void resolve() {
    PhysicsGetTime = (PhysicsGetTime_t)A(0x0042bc80);
    Obstacle_Perturb = (Method0_t)A(0x0043d3e0);
    PhobDyno_Update = (Method0_t)A(0x00445210);
    PoolBase_alloc = (PoolAlloc_t)A(0x0041bb20);
    PoolBase_free = (PoolFree_t)A(0x0041bb60);
    dxStateFlush = (Void_t)A(0x0045dfd0);
    dxDPBegin = (IntArg_t)A(0x00458990);
    dxDPEnd = (Void_t)A(0x00458a90);
    TextureHasAlpha = (HasAlpha_t)A(0x0045a590);
    LightSurfacePreLit = (PreLit_t)A(0x0045c250);
    dxDPDraw = (DPDraw_t)A(0x00458a60);
    collide_object = (CollideObject_t)A(0x00427350);
    G.deferred_pool = A(0x00522d80);
    G.deferred_flag = A(0x00522d84);
    G.prelit_buffer = A(0x004f2198);
    G.phobs = A(0x00520bb4);
    G.nphobs = A(0x00521090);
    G.collisions = A(0x004ecce4);
    G.walls = A(0x004ecce8);
    G.getextents_stub = A(0x00436080);                           // CollisionVolume::GetExtents, the stub
    G.nwobs = A(0x005522d0);
    G.ngobs = A(0x00553368);
}

static void install() {
    uint8_t* base = (uint8_t*)GetModuleHandleA(NULL);
    IMAGE_NT_HEADERS* nt = (IMAGE_NT_HEADERS*)(base + ((IMAGE_DOS_HEADER*)base)->e_lfanew);
    for (const Build& b : k_builds)
        if (nt->FileHeader.TimeDateStamp == b.timestamp) g_build = &b;
    if ((uintptr_t)base != 0x400000 || !g_build) {
        logf("host isn't a known build (base %p, timestamp %08lx): nothing hooked", base, nt->FileHeader.TimeDateStamp);
        return;
    }
    logf("host is %s", g_build->name);
    resolve();
    if (g_unresolved) {
        logf("NOT installing anything: %d addresses have no translation for %s", g_unresolved, g_build->name);
        return;
    }
    // push ebx; push esi; fld dword [ecx+23Ch]; fmul dword [ecx+23Ch] (v1.1 and 1.2.x square +238h
    // first: the same sum with the terms the other way round)
    static const uint8_t update_prologue[] = {0x53, 0x56, 0xD9, 0x81, 0x3C, 0x02, 0x00, 0x00, 0xD8, 0x89, 0x3C, 0x02, 0x00, 0x00};
    jmp_hook(0x0043d2e0, update_prologue, sizeof update_prologue, (void*)Obstacle_Update, "Obstacle::Update");
    lift_limits();
    lift_texture_limit();
    relocate_texture_table();
    speed_up_collisions();
    platform_install(g_build->name);            // M2: SDL2 window and input, when viperport.ini asks
}

BOOL WINAPI DllMain(HINSTANCE inst, DWORD reason, LPVOID) {
    if (reason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(inst);
        char path[MAX_PATH];
        GetModuleFileNameA(inst, path, MAX_PATH);
        char* slash = strrchr(path, '\\');
        lstrcpyA(slash ? slash + 1 : path, "viperport.log");
        g_log = fopen(path, "w");
        logf("viperport loaded (M1: object limits, texture limit + table, collision broad-phase, Obstacle::Update)");
        install();
    } else if (reason == DLL_PROCESS_DETACH) {
        logf("exit: new Obstacle::Update ran %ld times, woke obstacles %ld times, put them to sleep %ld times",
             g_calls, g_perturbs, g_sleeps);
        logf("exit: peak physics objects %ld (stock limit 512), world objects %ld and graphics objects %ld (stock 1024 each)",
             g_peak_phobs, g_peak_wobs, g_peak_gobs);
        logf("exit: highest texture number drawn through the deferred buckets %ld (stock crashes past 118); %ld past %d",
             g_peak_tex, g_tex_overflows, TEX_BUCKETS);
        logf("exit: texture table entries in use at the peak %ld (stock table 250)", g_peak_table);
        renderer_report();
        platform_report();
        if (g_pair_ticks)
            logf("exit: collisions: %.0f volume pair tests per tick on average (stock tests every pair)",
                 (double)g_pair_tests / (double)g_pair_ticks);
        if (g_log) fclose(g_log);
    }
    return TRUE;
}
