// w32_table.cpp -- the stand-ins' import table (w32_table.h): race.exe's imports the port implements itself.
// GENERATED by tools/gen_w32_table.py from out/race_v10.exe's import directory and the w32_<Name>
// declarations in hook/w32_*.h -- 186 of race.exe's 190 imports; DDRAW / DSOUND / DINPUT are the port's own
// (renderer_install / audio_install / DirectInputCreateA), not stand-ins.
//
// GCC build: the full table. MSVC build: empty -- viperport.exe then leaves every import as Windows', as before.
#include "w32_table.h"
#include "compiler.h"                                   // VP_GCC
#include "viperport.h"
#include <string.h>
#include "w32_file.h"
#include "w32_kernel.h"
#include "w32_net.h"
#include "w32_user.h"

#ifdef VP_GCC
namespace {
const VpStandIn k_entries[] = {
    {"KERNEL32.dll", "GetSystemInfo", 0, (void*)&w32_GetSystemInfo},
    {"KERNEL32.dll", "CopyFileA", 0, (void*)&w32_CopyFileA},
    {"KERNEL32.dll", "MapViewOfFile", 0, (void*)&w32_MapViewOfFile},
    {"KERNEL32.dll", "CreateFileMappingA", 0, (void*)&w32_CreateFileMappingA},
    {"KERNEL32.dll", "UnmapViewOfFile", 0, (void*)&w32_UnmapViewOfFile},
    {"KERNEL32.dll", "CreateSemaphoreA", 0, (void*)&w32_CreateSemaphoreA},
    {"KERNEL32.dll", "GetCurrentThreadId", 0, (void*)&w32_GetCurrentThreadId},
    {"KERNEL32.dll", "ExitProcess", 0, (void*)&w32_ExitProcess},
    {"KERNEL32.dll", "GetExitCodeProcess", 0, (void*)&w32_GetExitCodeProcess},
    {"KERNEL32.dll", "WaitForSingleObject", 0, (void*)&w32_WaitForSingleObject},
    {"KERNEL32.dll", "CreateProcessA", 0, (void*)&w32_CreateProcessA},
    {"KERNEL32.dll", "QueryPerformanceCounter", 0, (void*)&w32_QueryPerformanceCounter},
    {"KERNEL32.dll", "FindClose", 0, (void*)&w32_FindClose},
    {"KERNEL32.dll", "CreateDirectoryA", 0, (void*)&w32_CreateDirectoryA},
    {"KERNEL32.dll", "HeapCreate", 0, (void*)&w32_HeapCreate},
    {"KERNEL32.dll", "HeapAlloc", 0, (void*)&w32_HeapAlloc},
    {"KERNEL32.dll", "HeapValidate", 0, (void*)&w32_HeapValidate},
    {"KERNEL32.dll", "HeapFree", 0, (void*)&w32_HeapFree},
    {"KERNEL32.dll", "HeapDestroy", 0, (void*)&w32_HeapDestroy},
    {"KERNEL32.dll", "CreateThread", 0, (void*)&w32_CreateThread},
    {"KERNEL32.dll", "SetThreadPriority", 0, (void*)&w32_SetThreadPriority},
    {"KERNEL32.dll", "GetCurrentThread", 0, (void*)&w32_GetCurrentThread},
    {"KERNEL32.dll", "ResumeThread", 0, (void*)&w32_ResumeThread},
    {"KERNEL32.dll", "Sleep", 0, (void*)&w32_Sleep},
    {"KERNEL32.dll", "SuspendThread", 0, (void*)&w32_SuspendThread},
    {"KERNEL32.dll", "ExitThread", 0, (void*)&w32_ExitThread},
    {"KERNEL32.dll", "QueryPerformanceFrequency", 0, (void*)&w32_QueryPerformanceFrequency},
    {"KERNEL32.dll", "FindFirstFileA", 0, (void*)&w32_FindFirstFileA},
    {"KERNEL32.dll", "EnterCriticalSection", 0, (void*)&w32_EnterCriticalSection},
    {"KERNEL32.dll", "LeaveCriticalSection", 0, (void*)&w32_LeaveCriticalSection},
    {"KERNEL32.dll", "DeleteCriticalSection", 0, (void*)&w32_DeleteCriticalSection},
    {"KERNEL32.dll", "DeleteFileA", 0, (void*)&w32_DeleteFileA},
    {"KERNEL32.dll", "FindNextFileA", 0, (void*)&w32_FindNextFileA},
    {"KERNEL32.dll", "SetFileAttributesA", 0, (void*)&w32_SetFileAttributesA},
    {"KERNEL32.dll", "GetModuleFileNameA", 0, (void*)&w32_GetModuleFileNameA},
    {"KERNEL32.dll", "CreateMailslotA", 0, (void*)&w32_CreateMailslotA},
    {"KERNEL32.dll", "DeviceIoControl", 0, (void*)&w32_DeviceIoControl},
    {"KERNEL32.dll", "GetLocaleInfoA", 0, (void*)&w32_GetLocaleInfoA},
    {"KERNEL32.dll", "GetCurrencyFormatA", 0, (void*)&w32_GetCurrencyFormatA},
    {"KERNEL32.dll", "GetDateFormatA", 0, (void*)&w32_GetDateFormatA},
    {"KERNEL32.dll", "ClearCommError", 0, (void*)&w32_ClearCommError},
    {"KERNEL32.dll", "SetCommTimeouts", 0, (void*)&w32_SetCommTimeouts},
    {"KERNEL32.dll", "GetCommModemStatus", 0, (void*)&w32_GetCommModemStatus},
    {"KERNEL32.dll", "GetCommProperties", 0, (void*)&w32_GetCommProperties},
    {"KERNEL32.dll", "SetCommState", 0, (void*)&w32_SetCommState},
    {"KERNEL32.dll", "GetCommState", 0, (void*)&w32_GetCommState},
    {"KERNEL32.dll", "SetConsoleTitleA", 0, (void*)&w32_SetConsoleTitleA},
    {"KERNEL32.dll", "SetConsoleMode", 0, (void*)&w32_SetConsoleMode},
    {"KERNEL32.dll", "GetStdHandle", 0, (void*)&w32_GetStdHandle},
    {"KERNEL32.dll", "AllocConsole", 0, (void*)&w32_AllocConsole},
    {"KERNEL32.dll", "WriteConsoleA", 0, (void*)&w32_WriteConsoleA},
    {"KERNEL32.dll", "FreeConsole", 0, (void*)&w32_FreeConsole},
    {"KERNEL32.dll", "ReadConsoleA", 0, (void*)&w32_ReadConsoleA},
    {"KERNEL32.dll", "GetCurrentProcess", 0, (void*)&w32_GetCurrentProcess},
    {"KERNEL32.dll", "DuplicateHandle", 0, (void*)&w32_DuplicateHandle},
    {"KERNEL32.dll", "WriteFile", 0, (void*)&w32_WriteFile},
    {"KERNEL32.dll", "ReadFile", 0, (void*)&w32_ReadFile},
    {"KERNEL32.dll", "GetLastError", 0, (void*)&w32_GetLastError},
    {"KERNEL32.dll", "GetFileSize", 0, (void*)&w32_GetFileSize},
    {"KERNEL32.dll", "CloseHandle", 0, (void*)&w32_CloseHandle},
    {"KERNEL32.dll", "SetFilePointer", 0, (void*)&w32_SetFilePointer},
    {"KERNEL32.dll", "GetTempFileNameA", 0, (void*)&w32_GetTempFileNameA},
    {"KERNEL32.dll", "CreateFileA", 0, (void*)&w32_CreateFileA},
    {"KERNEL32.dll", "GetVersion", 0, (void*)&w32_GetVersion},
    {"KERNEL32.dll", "GlobalAlloc", 0, (void*)&w32_GlobalAlloc},
    {"KERNEL32.dll", "GlobalLock", 0, (void*)&w32_GlobalLock},
    {"KERNEL32.dll", "CreateEventA", 0, (void*)&w32_CreateEventA},
    {"KERNEL32.dll", "PulseEvent", 0, (void*)&w32_PulseEvent},
    {"KERNEL32.dll", "RaiseException", 0, (void*)&w32_RaiseException},
    {"KERNEL32.dll", "SetUnhandledExceptionFilter", 0, (void*)&w32_SetUnhandledExceptionFilter},
    {"KERNEL32.dll", "GetExitCodeThread", 0, (void*)&w32_GetExitCodeThread},
    {"KERNEL32.dll", "InitializeCriticalSection", 0, (void*)&w32_InitializeCriticalSection},
    {"KERNEL32.dll", "RtlUnwind", 0, (void*)&w32_RtlUnwind},
    {"KERNEL32.dll", "GetStringTypeA", 0, (void*)&w32_GetStringTypeA},
    {"KERNEL32.dll", "LCMapStringW", 0, (void*)&w32_LCMapStringW},
    {"KERNEL32.dll", "HeapReAlloc", 0, (void*)&w32_HeapReAlloc},
    {"KERNEL32.dll", "LoadLibraryA", 0, (void*)&w32_LoadLibraryA},
    {"KERNEL32.dll", "HeapSize", 0, (void*)&w32_HeapSize},
    {"KERNEL32.dll", "GetFullPathNameA", 0, (void*)&w32_GetFullPathNameA},
    {"KERNEL32.dll", "SetCurrentDirectoryA", 0, (void*)&w32_SetCurrentDirectoryA},
    {"KERNEL32.dll", "GlobalUnlock", 0, (void*)&w32_GlobalUnlock},
    {"KERNEL32.dll", "GetProcAddress", 0, (void*)&w32_GetProcAddress},
    {"KERNEL32.dll", "LCMapStringA", 0, (void*)&w32_LCMapStringA},
    {"KERNEL32.dll", "SetEnvironmentVariableA", 0, (void*)&w32_SetEnvironmentVariableA},
    {"KERNEL32.dll", "GetCommandLineA", 0, (void*)&w32_GetCommandLineA},
    {"KERNEL32.dll", "GetCurrentDirectoryA", 0, (void*)&w32_GetCurrentDirectoryA},
    {"KERNEL32.dll", "GetModuleHandleA", 0, (void*)&w32_GetModuleHandleA},
    {"KERNEL32.dll", "GetOEMCP", 0, (void*)&w32_GetOEMCP},
    {"KERNEL32.dll", "UnhandledExceptionFilter", 0, (void*)&w32_UnhandledExceptionFilter},
    {"KERNEL32.dll", "FreeEnvironmentStringsA", 0, (void*)&w32_FreeEnvironmentStringsA},
    {"KERNEL32.dll", "MultiByteToWideChar", 0, (void*)&w32_MultiByteToWideChar},
    {"KERNEL32.dll", "GetEnvironmentStrings", 0, (void*)&w32_GetEnvironmentStrings},
    {"KERNEL32.dll", "FreeEnvironmentStringsW", 0, (void*)&w32_FreeEnvironmentStringsW},
    {"KERNEL32.dll", "GetEnvironmentStringsW", 0, (void*)&w32_GetEnvironmentStringsW},
    {"KERNEL32.dll", "WideCharToMultiByte", 0, (void*)&w32_WideCharToMultiByte},
    {"KERNEL32.dll", "GetCPInfo", 0, (void*)&w32_GetCPInfo},
    {"KERNEL32.dll", "GetACP", 0, (void*)&w32_GetACP},
    {"KERNEL32.dll", "FlushFileBuffers", 0, (void*)&w32_FlushFileBuffers},
    {"KERNEL32.dll", "SetHandleCount", 0, (void*)&w32_SetHandleCount},
    {"KERNEL32.dll", "GetFileType", 0, (void*)&w32_GetFileType},
    {"KERNEL32.dll", "GetDriveTypeA", 0, (void*)&w32_GetDriveTypeA},
    {"KERNEL32.dll", "GetLocalTime", 0, (void*)&w32_GetLocalTime},
    {"KERNEL32.dll", "SetEndOfFile", 0, (void*)&w32_SetEndOfFile},
    {"KERNEL32.dll", "GetStartupInfoA", 0, (void*)&w32_GetStartupInfoA},
    {"KERNEL32.dll", "GetStringTypeW", 0, (void*)&w32_GetStringTypeW},
    {"KERNEL32.dll", "SetStdHandle", 0, (void*)&w32_SetStdHandle},
    {"USER32.dll", "GetSystemMetrics", 0, (void*)&w32_GetSystemMetrics},
    {"USER32.dll", "EndPaint", 0, (void*)&w32_EndPaint},
    {"USER32.dll", "RegisterClassA", 0, (void*)&w32_RegisterClassA},
    {"USER32.dll", "CreateWindowExA", 0, (void*)&w32_CreateWindowExA},
    {"USER32.dll", "SetFocus", 0, (void*)&w32_SetFocus},
    {"USER32.dll", "LoadIconA", 0, (void*)&w32_LoadIconA},
    {"USER32.dll", "LoadCursorA", 0, (void*)&w32_LoadCursorA},
    {"USER32.dll", "UpdateWindow", 0, (void*)&w32_UpdateWindow},
    {"USER32.dll", "FindWindowA", 0, (void*)&w32_FindWindowA},
    {"USER32.dll", "ShowWindow", 0, (void*)&w32_ShowWindow},
    {"USER32.dll", "IsWindow", 0, (void*)&w32_IsWindow},
    {"USER32.dll", "SetCursorPos", 0, (void*)&w32_SetCursorPos},
    {"USER32.dll", "CallNextHookEx", 0, (void*)&w32_CallNextHookEx},
    {"USER32.dll", "DestroyWindow", 0, (void*)&w32_DestroyWindow},
    {"USER32.dll", "MessageBoxA", 0, (void*)&w32_MessageBoxA},
    {"USER32.dll", "OpenClipboard", 0, (void*)&w32_OpenClipboard},
    {"USER32.dll", "CloseClipboard", 0, (void*)&w32_CloseClipboard},
    {"USER32.dll", "SetClipboardData", 0, (void*)&w32_SetClipboardData},
    {"USER32.dll", "EmptyClipboard", 0, (void*)&w32_EmptyClipboard},
    {"USER32.dll", "LoadBitmapA", 0, (void*)&w32_LoadBitmapA},
    {"USER32.dll", "DefWindowProcA", 0, (void*)&w32_DefWindowProcA},
    {"USER32.dll", "TranslateMessage", 0, (void*)&w32_TranslateMessage},
    {"USER32.dll", "MapVirtualKeyA", 0, (void*)&w32_MapVirtualKeyA},
    {"USER32.dll", "GetMessageA", 0, (void*)&w32_GetMessageA},
    {"USER32.dll", "UnhookWindowsHookEx", 0, (void*)&w32_UnhookWindowsHookEx},
    {"USER32.dll", "DispatchMessageA", 0, (void*)&w32_DispatchMessageA},
    {"USER32.dll", "PeekMessageA", 0, (void*)&w32_PeekMessageA},
    {"USER32.dll", "ShowCursor", 0, (void*)&w32_ShowCursor},
    {"USER32.dll", "ClipCursor", 0, (void*)&w32_ClipCursor},
    {"USER32.dll", "SetWindowsHookExA", 0, (void*)&w32_SetWindowsHookExA},
    {"USER32.dll", "GetForegroundWindow", 0, (void*)&w32_GetForegroundWindow},
    {"USER32.dll", "PostQuitMessage", 0, (void*)&w32_PostQuitMessage},
    {"USER32.dll", "SetCursor", 0, (void*)&w32_SetCursor},
    {"USER32.dll", "BeginPaint", 0, (void*)&w32_BeginPaint},
    {"USER32.dll", "SetForegroundWindow", 0, (void*)&w32_SetForegroundWindow},
    {"USER32.dll", "GetClipboardData", 0, (void*)&w32_GetClipboardData},
    {"GDI32.dll", "BitBlt", 0, (void*)&w32_BitBlt},
    {"GDI32.dll", "DeleteObject", 0, (void*)&w32_DeleteObject},
    {"GDI32.dll", "CreateCompatibleDC", 0, (void*)&w32_CreateCompatibleDC},
    {"GDI32.dll", "DeleteDC", 0, (void*)&w32_DeleteDC},
    {"GDI32.dll", "SelectObject", 0, (void*)&w32_SelectObject},
    {"ADVAPI32.dll", "RegFlushKey", 0, (void*)&w32_RegFlushKey},
    {"ADVAPI32.dll", "RegQueryValueExA", 0, (void*)&w32_RegQueryValueExA},
    {"ADVAPI32.dll", "RegOpenKeyExA", 0, (void*)&w32_RegOpenKeyExA},
    {"ADVAPI32.dll", "RegCloseKey", 0, (void*)&w32_RegCloseKey},
    {"ADVAPI32.dll", "RegSetValueExA", 0, (void*)&w32_RegSetValueExA},
    {"WINMM.dll", "timeGetTime", 0, (void*)&w32_timeGetTime},
    {"WINMM.dll", "timeKillEvent", 0, (void*)&w32_timeKillEvent},
    {"WSOCK32.dll", 0, 116, (void*)&w32_WSACleanup},
    {"WSOCK32.dll", 0, 3, (void*)&w32_closesocket},
    {"WSOCK32.dll", 0, 115, (void*)&w32_WSAStartup},
    {"WSOCK32.dll", 0, 23, (void*)&w32_socket},
    {"WSOCK32.dll", 0, 9, (void*)&w32_htons},
    {"WSOCK32.dll", 0, 20, (void*)&w32_sendto},
    {"WSOCK32.dll", 0, 17, (void*)&w32_recvfrom},
    {"WSOCK32.dll", 0, 15, (void*)&w32_ntohs},
    {"WSOCK32.dll", 0, 12, (void*)&w32_ioctlsocket},
    {"WSOCK32.dll", 0, 57, (void*)&w32_gethostname},
    {"WSOCK32.dll", 0, 52, (void*)&w32_gethostbyname},
    {"WSOCK32.dll", 0, 111, (void*)&w32_WSAGetLastError},
    {"WSOCK32.dll", 0, 10, (void*)&w32_inet_addr},
    {"WSOCK32.dll", 0, 103, (void*)&w32_WSAAsyncGetHostByName},
    {"WSOCK32.dll", 0, 108, (void*)&w32_WSACancelAsyncRequest},
    {"WSOCK32.dll", 0, 7, (void*)&w32_getsockopt},
    {"WSOCK32.dll", 0, 2, (void*)&w32_bind},
    {"WSOCK32.dll", 0, 21, (void*)&w32_setsockopt},
    {"TAPI32.dll", "lineGetDevCaps", 0, (void*)&w32_lineGetDevCaps},
    {"TAPI32.dll", "lineShutdown", 0, (void*)&w32_lineShutdown},
    {"TAPI32.dll", "lineInitialize", 0, (void*)&w32_lineInitialize},
    {"TAPI32.dll", "lineNegotiateAPIVersion", 0, (void*)&w32_lineNegotiateAPIVersion},
    {"TAPI32.dll", "lineAnswer", 0, (void*)&w32_lineAnswer},
    {"TAPI32.dll", "lineMakeCall", 0, (void*)&w32_lineMakeCall},
    {"TAPI32.dll", "lineGetCallInfo", 0, (void*)&w32_lineGetCallInfo},
    {"TAPI32.dll", "lineSetDevConfig", 0, (void*)&w32_lineSetDevConfig},
    {"TAPI32.dll", "lineGetDevConfig", 0, (void*)&w32_lineGetDevConfig},
    {"TAPI32.dll", "lineGetID", 0, (void*)&w32_lineGetID},
    {"TAPI32.dll", "lineDrop", 0, (void*)&w32_lineDrop},
    {"TAPI32.dll", "lineDeallocateCall", 0, (void*)&w32_lineDeallocateCall},
    {"TAPI32.dll", "lineClose", 0, (void*)&w32_lineClose},
    {"TAPI32.dll", "lineOpen", 0, (void*)&w32_lineOpen},
};
const uint32_t N_ENTRIES = sizeof k_entries / sizeof k_entries[0];

// stand-ins the game finds through GetProcAddress but doesn't import (the C runtime's fatal-error message box)
const VpStandIn k_extra[] = {
    {"USER32.dll", "GetActiveWindow", 0, (void*)&w32_GetActiveWindow},
    {"USER32.dll", "GetLastActivePopup", 0, (void*)&w32_GetLastActivePopup},
};

bool same_dll(const char* a, const char* b) {     // "USER32" matches "USER32.dll", any case
    for (; *a && *b; a++, b++)
        if ((*a | 0x20) != (*b | 0x20)) return false;
    return (!*a || !strcmp(a, ".dll") || !strcmp(a, ".DLL")) && (!*b || !strcmp(b, ".dll") || !strcmp(b, ".DLL"));
}
// the kernel stand-ins' GetProcAddress asks here first (w32_kernel.h, w32_set_proc_lookup)
void* lookup(const char* dll, const char* name) {
    for (const VpStandIn& e : k_entries)
        if (e.name && !strcmp(e.name, name) && same_dll(e.dll, dll)) return e.fn;
    for (const VpStandIn& e : k_extra)
        if (!strcmp(e.name, name) && same_dll(e.dll, dll)) return e.fn;
    return 0;
}
struct Register { Register() { w32_set_proc_lookup(lookup); } } g_register;   // (a plain pointer: set at load)

void __cdecl log_line(const char* line) { logf("%s", line); }
void __cdecl set_image(uint32_t base, const char* path, const char* command_line) {
    w32_set_process_image(base, path, command_line);
}
}  // namespace
extern "C" VP_STAND_INS_API const VpStandIns viperport_stand_ins = {
    sizeof(VpStandIns), VP_STAND_INS_VERSION, N_ENTRIES, k_entries, log_line, set_image};
#else
extern "C" VP_STAND_INS_API const VpStandIns viperport_stand_ins = {sizeof(VpStandIns), VP_STAND_INS_VERSION, 0, 0, 0, 0};
#endif
