// w32_kernel.h -- the stand-ins for race.exe's KERNEL32 imports of memory, threads, synchronisation, time, process,
// environment, modules, locale/strings and exceptions, and WINMM's timeGetTime / timeKillEvent (relink stage R2a;
// w32_handle.h says what a stand-in is). Agent C's import table (w32_table.cpp) puts these in race.exe's import slots
// in the GCC standalone; nothing else calls them in the MSVC build.
//
// Each is the Win32 function of the same name with the same ABI (__stdcall, 32-bit arguments), and returns what
// Windows returns for the game's use: values, out parameters, GetLastError codes. HANDLE / DWORD / BOOL / UINT are
// uint32_t, int / LONG int32_t. The files:
//   w32_mem.cpp     Heap*, Global*, GetSystemInfo, GetVersion
//   w32_thread.cpp  threads, critical sections, events, semaphores, WaitForSingleObject, Sleep, the current
//                   process/thread, ExitProcess, CreateProcessA (not available), affinity masks
//                   (GetLastError / SetLastError are agent A's, w32_file.cpp: w32::last_error)
//   w32_time.cpp    QueryPerformanceCounter/Frequency, GetLocalTime, timeGetTime, timeKillEvent
//   w32_proc.cpp    the command line, the environment, GetStartupInfoA, SetHandleCount, modules, LoadLibraryA,
//                   GetProcAddress
//   w32_locale.cpp  code pages, MultiByteToWideChar / WideCharToMultiByte, LCMapString, GetStringType,
//                   GetLocaleInfoA, GetCurrencyFormatA, GetDateFormatA (this machine's en-US answers:
//                   w32_locale_tables.inc, generated by test/w32_locale_gen.cpp)
//   w32_seh.cpp     SetUnhandledExceptionFilter, UnhandledExceptionFilter, RaiseException, RtlUnwind: still Windows'
// test/w32_kernel_test.cpp runs each against the real API.
#pragma once
#include <stdint.h>
#include "w32_handle.h"

#if defined(_WIN32)
#define W32K_CALL __stdcall
#else
#define W32K_CALL __attribute__((stdcall))
#endif

// ---- the structures the game passes (32-bit Windows layouts) -------------------------------------------------------
struct W32CriticalSection {        // CRITICAL_SECTION (0x18 bytes; the game's cs_tags keep a flag right after it)
    uint32_t debug_info;           // +0x00 as Windows leaves it
    int32_t lock_count;            // +0x04 -1 free
    int32_t recursion_count;       // +0x08 the owner's depth
    uint32_t owning_thread;        // +0x0c the owner's thread id
    uint32_t lock_semaphore;       // +0x10 the stand-in's lock object
    uint32_t spin_count;           // +0x14 as Windows leaves it
};
struct W32SystemTime {             // SYSTEMTIME
    uint16_t year, month, day_of_week, day, hour, minute, second, ms;
};
struct W32SystemInfo {             // SYSTEM_INFO (0x24 bytes)
    uint16_t processor_architecture, reserved;
    uint32_t page_size, min_app_address, max_app_address, active_processor_mask, number_of_processors, processor_type,
        allocation_granularity;
    uint16_t processor_level, processor_revision;
};
struct W32StartupInfoA {           // STARTUPINFOA (0x44 bytes)
    uint32_t cb, reserved, desktop, title, x, y, x_size, y_size, x_count_chars, y_count_chars, fill_attribute, flags;
    uint16_t show_window, cb_reserved2;
    uint32_t reserved2, std_input, std_output, std_error;
};
struct W32CpInfo {                 // CPINFO (18 bytes used)
    uint32_t max_char_size;
    uint8_t default_char[2];
    uint8_t lead_byte[12];
};
typedef uint32_t(W32K_CALL* W32ThreadProc)(void* param);

// ---- memory (w32_mem.cpp) ------------------------------------------------------------------------------------------
uint32_t W32K_CALL w32_HeapCreate(uint32_t options, uint32_t initial_size, uint32_t maximum_size);
int32_t W32K_CALL w32_HeapDestroy(uint32_t heap);
void* W32K_CALL w32_HeapAlloc(uint32_t heap, uint32_t flags, uint32_t bytes);
void* W32K_CALL w32_HeapReAlloc(uint32_t heap, uint32_t flags, void* mem, uint32_t bytes);
int32_t W32K_CALL w32_HeapFree(uint32_t heap, uint32_t flags, void* mem);
uint32_t W32K_CALL w32_HeapSize(uint32_t heap, uint32_t flags, const void* mem);
int32_t W32K_CALL w32_HeapValidate(uint32_t heap, uint32_t flags, const void* mem);
uint32_t W32K_CALL w32_GlobalAlloc(uint32_t flags, uint32_t bytes);
void* W32K_CALL w32_GlobalLock(uint32_t mem);
int32_t W32K_CALL w32_GlobalUnlock(uint32_t mem);
uint32_t W32K_CALL w32_GlobalFree(uint32_t mem);           // (not imported by the game: for the clipboard's owner)
uint32_t W32K_CALL w32_GlobalSize(uint32_t mem);           // (likewise)
void W32K_CALL w32_GetSystemInfo(W32SystemInfo* si);
uint32_t W32K_CALL w32_GetVersion();

// ---- threads, synchronisation, process (w32_thread.cpp) ------------------------------------------------------------
uint32_t W32K_CALL w32_CreateThread(void* security, uint32_t stack_size, W32ThreadProc start, void* param,
                                    uint32_t flags, uint32_t* thread_id);
void W32K_CALL w32_ExitThread(uint32_t code);
int32_t W32K_CALL w32_GetExitCodeThread(uint32_t thread, uint32_t* code);
uint32_t W32K_CALL w32_SuspendThread(uint32_t thread);
uint32_t W32K_CALL w32_ResumeThread(uint32_t thread);
int32_t W32K_CALL w32_SetThreadPriority(uint32_t thread, int32_t priority);
uint32_t W32K_CALL w32_GetCurrentThread();
uint32_t W32K_CALL w32_GetCurrentThreadId();
uint32_t W32K_CALL w32_GetCurrentProcess();
void W32K_CALL w32_ExitProcess(uint32_t code);
int32_t W32K_CALL w32_CreateProcessA(const char* app, char* cmdline, void* proc_sa, void* thread_sa, int32_t inherit,
                                     uint32_t flags, void* env, const char* dir, void* startup, void* proc_info);
int32_t W32K_CALL w32_GetExitCodeProcess(uint32_t process, uint32_t* code);
void W32K_CALL w32_Sleep(uint32_t ms);
void W32K_CALL w32_InitializeCriticalSection(W32CriticalSection* cs);
void W32K_CALL w32_EnterCriticalSection(W32CriticalSection* cs);
void W32K_CALL w32_LeaveCriticalSection(W32CriticalSection* cs);
void W32K_CALL w32_DeleteCriticalSection(W32CriticalSection* cs);
uint32_t W32K_CALL w32_CreateEventA(void* security, int32_t manual_reset, int32_t initial_state, const char* name);
int32_t W32K_CALL w32_PulseEvent(uint32_t event);
int32_t W32K_CALL w32_SetEvent(uint32_t event);            // (not imported by the game: for the port's own events)
int32_t W32K_CALL w32_ResetEvent(uint32_t event);          // (likewise)
uint32_t W32K_CALL w32_CreateSemaphoreA(void* security, int32_t initial, int32_t maximum, const char* name);
int32_t W32K_CALL w32_ReleaseSemaphore(uint32_t sem, int32_t count, int32_t* previous);   // (likewise)
uint32_t W32K_CALL w32_WaitForSingleObject(uint32_t handle, uint32_t ms);
uint32_t W32K_CALL w32_GetLastError();                     // (defined in w32_file.cpp, agent A's: w32::last_error)
void W32K_CALL w32_SetLastError(uint32_t error);           // (likewise)
// reached through GetProcAddress (the C runtime's FDIV check), not imported
int32_t W32K_CALL w32_GetProcessAffinityMask(uint32_t process, uint32_t* process_mask, uint32_t* system_mask);
uint32_t W32K_CALL w32_SetThreadAffinityMask(uint32_t thread, uint32_t mask);

// ---- time (w32_time.cpp) --------------------------------------------------------------------------------------------
int32_t W32K_CALL w32_QueryPerformanceCounter(int64_t* count);
int32_t W32K_CALL w32_QueryPerformanceFrequency(int64_t* freq);
void W32K_CALL w32_GetLocalTime(W32SystemTime* st);
uint32_t W32K_CALL w32_timeGetTime();
uint32_t W32K_CALL w32_timeKillEvent(uint32_t id);

// ---- process image, environment, modules (w32_proc.cpp) -------------------------------------------------------------
char* W32K_CALL w32_GetCommandLineA();
char* W32K_CALL w32_GetEnvironmentStrings();               // (the import's name: KERNEL32's ANSI GetEnvironmentStrings)
uint16_t* W32K_CALL w32_GetEnvironmentStringsW();
int32_t W32K_CALL w32_FreeEnvironmentStringsA(char* block);
int32_t W32K_CALL w32_FreeEnvironmentStringsW(uint16_t* block);
int32_t W32K_CALL w32_SetEnvironmentVariableA(const char* name, const char* value);
void W32K_CALL w32_GetStartupInfoA(W32StartupInfoA* si);
uint32_t W32K_CALL w32_SetHandleCount(uint32_t count);
uint32_t W32K_CALL w32_GetModuleHandleA(const char* name);
uint32_t W32K_CALL w32_GetModuleFileNameA(uint32_t module, char* buf, uint32_t size);
uint32_t W32K_CALL w32_LoadLibraryA(const char* name);
void* W32K_CALL w32_GetProcAddress(uint32_t module, const char* name);

// The loader tells the stand-ins who the game is, as Windows would have started race.exe (loader/viperport_main.cpp's
// race_GetModuleHandleA / race_GetModuleFileNameA / race_GetCommandLineA): its image base (GetModuleHandleA(NULL)),
// its path (GetModuleFileNameA of NULL or that base) and its command line (GetCommandLineA). Until then (and in the
// MSVC build, where nothing calls them) these answer for the process.
void w32_set_process_image(uint32_t base, const char* path, const char* command_line);
// GetProcAddress's table: lookup(dll, name) -> a stand-in or null (agent C's import table registers its own; dll is
// the module's file name without folder or ".dll", any case). Without one, or when it says null, the stand-ins below
// (w32_kernel_proc) answer for KERNEL32 and WINMM; anything else is Windows' (on Linux: not found).
typedef void* (*W32ProcLookup)(const char* dll, const char* name);
void w32_set_proc_lookup(W32ProcLookup lookup);
// this file's stand-ins by DLL ("KERNEL32" / "WINMM", any case) and name: the function, or null
void* w32_kernel_proc(const char* dll, const char* name);

// ---- locale and strings (w32_locale.cpp) ----------------------------------------------------------------------------
uint32_t W32K_CALL w32_GetACP();
uint32_t W32K_CALL w32_GetOEMCP();
int32_t W32K_CALL w32_GetCPInfo(uint32_t code_page, W32CpInfo* info);
int32_t W32K_CALL w32_MultiByteToWideChar(uint32_t code_page, uint32_t flags, const char* src, int32_t src_len,
                                          uint16_t* dst, int32_t dst_len);
int32_t W32K_CALL w32_WideCharToMultiByte(uint32_t code_page, uint32_t flags, const uint16_t* src, int32_t src_len,
                                          char* dst, int32_t dst_len, const char* default_char, int32_t* used_default);
int32_t W32K_CALL w32_LCMapStringA(uint32_t lcid, uint32_t flags, const char* src, int32_t src_len, char* dst,
                                   int32_t dst_len);
int32_t W32K_CALL w32_LCMapStringW(uint32_t lcid, uint32_t flags, const uint16_t* src, int32_t src_len, uint16_t* dst,
                                   int32_t dst_len);
int32_t W32K_CALL w32_GetStringTypeA(uint32_t lcid, uint32_t info_type, const char* src, int32_t src_len,
                                     uint16_t* types);
int32_t W32K_CALL w32_GetStringTypeW(uint32_t info_type, const uint16_t* src, int32_t src_len, uint16_t* types);
int32_t W32K_CALL w32_GetLocaleInfoA(uint32_t lcid, uint32_t type, char* buf, int32_t size);
int32_t W32K_CALL w32_GetCurrencyFormatA(uint32_t lcid, uint32_t flags, const char* value, const void* format,
                                         char* out, int32_t size);
int32_t W32K_CALL w32_GetDateFormatA(uint32_t lcid, uint32_t flags, const W32SystemTime* date, const char* format,
                                     char* out, int32_t size);

// ---- exceptions (w32_seh.cpp): Windows' own, behind the stand-in (see there for R2b) ---------------------------------
void* W32K_CALL w32_SetUnhandledExceptionFilter(void* filter);
int32_t W32K_CALL w32_UnhandledExceptionFilter(void* exception_pointers);
void W32K_CALL w32_RaiseException(uint32_t code, uint32_t flags, uint32_t nargs, const uint32_t* args);
void W32K_CALL w32_RtlUnwind(void* target_frame, void* target_ip, void* exception_record, void* return_value);

// ---- shared with the other stand-ins ----------------------------------------------------------------------------------
namespace w32 {
// a w32_GlobalAlloc block's memory and size (for a Linux clipboard's SetClipboardData): null if it isn't one. On
// Windows the blocks are Windows' own HGLOBALs (the real clipboard takes them), so this is GlobalLock's pointer.
void* global_memory(uint32_t mem, uint32_t* size);
}  // namespace w32
