#!/bin/bash
# build_linux.sh -- the native Linux build (relink stage R2b), in WSL Ubuntu (or any i386-multilib Linux with
# gcc/g++-multilib and libsdl2-dev:i386): every hook/*.cpp of hook\build_gcc.bat's list compiled with Linux GCC into
# out-linux/obj/, in parallel, then linked.
#
#   tools/build_linux.sh            compile (only what changed) + link out-linux/viperport-link-test
#   tools/build_linux.sh clean      remove out-linux/
#   VP_JOBS=n                       compilers at a time (default: nproc)
#
# The flags are build_gcc.bat's (the x87 rules of hook/compiler.h: -m32 -O2 -march=i686 -mfpmath=387
# -fexcess-precision=standard -fno-strict-aliasing -masm=intel -std=c++17 -fms-extensions), plus what makes Ubuntu's GCC
# generate the code mingw's does: no PIE/PIC (the GNU asm blocks address globals absolutely, as MSVC's do), no stack
# protector, no stack-clash probes, no CET endbr32, no _FORTIFY_SOURCE -- Ubuntu turns all of those on by default,
# mingw none.
#
# -DVP_R2B_STUBS: w32_user.cpp's loading-window stand-ins succeed doing nothing until agent D's SDL splash replaces them.
#
# Linux has no <windows.h>: hook/linux_inc/ (on the include path here only) has windows.h, mmsystem.h, intrin.h,
# winsock.h, ddraw.h, d3d.h and dsound.h, which bring in hook/win32_compat.h (Windows' types, constants and functions at
# their exact 32-bit layouts) and hook/dx_compat.h (DirectX 5's) -- no source changes its #include, and the Windows
# builds never see them. hook/msvc_compat.h, force-included (-include), is what MSVC / mingw give every file without an
# #include: __stdcall & co., __declspec, the intrinsics, the MSVC C runtime names.
#
# The link test (out-linux/viperport-link-test): every object of the port plus a main() that references the stand-ins'
# table, proving everything resolves. What agents B/C/D of R2b will provide is a stub in hook/linux_todo.cpp
# (vp_r2b_todo: prints its name and aborts) -- running the test stops at the first one (standalone.cpp's static
# initialiser reads the environment). The real executable (out-linux/viperport, with the ELF loader) is agent B's.
set -u
cd "$(dirname "$0")/.." || exit 1
ROOT=$(pwd)
OUT=$ROOT/out-linux
if [ "${1:-}" = clean ]; then rm -rf "$OUT"; exit 0; fi
mkdir -p "$OUT/obj"

CXX=${CXX:-g++}
SDL_CFLAGS=$(sdl2-config --cflags) || { echo "build_linux: no sdl2-config (apt install libsdl2-dev:i386)"; exit 1; }
CFLAGS="-m32 -O2 -march=i686 -mfpmath=387 -fexcess-precision=standard -fno-strict-aliasing -masm=intel -std=c++17 \
-fms-extensions -Wno-invalid-offsetof -fno-pie -fno-pic -fno-stack-protector -fno-stack-clash-protection \
-fcf-protection=none -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 $SDL_CFLAGS \
-I$ROOT/hook/linux_inc -include $ROOT/hook/msvc_compat.h -DVP_R2B_STUBS"
LDFLAGS="-m32 -no-pie"
LIBS="-lSDL2 -lGL -lpthread -ldl -lrt"

# build_gcc.bat's VP_SOURCES, in its order, plus the Linux-only files
PATTERNS="viperport.cpp port.cpp replay.cpp session.cpp standalone.cpp net_*.cpp crt_*.cpp edit_*.cpp phys_*.cpp \
wld_*.cpp krn_*.cpp gx_*.cpp snd_*.cpp ui_*.cpp menu_*.cpp root_*.cpp career_*.cpp paint_*.cpp w32_*.cpp vp_os.cpp \
platform.cpp gl_table.cpp gl_core.cpp gl_dxgi.cpp ddraw_gl.cpp dsound_sdl.cpp linux_todo.cpp"
SOURCES=()
cd hook
for p in $PATTERNS; do
    for f in $(ls $p 2>/dev/null | LC_ALL=C sort); do SOURCES+=("$f"); done
done
cd ..

# compile: a source is rebuilt when it, or any header it read (gcc -MMD), is newer than its object
compile_one() {
    local s=$1 o="$OUT/obj/${1%.cpp}.o"
    if [ -f "$o" ] && [ -f "${o%.o}.d" ]; then
        local stale=0 dep
        for dep in $(sed -e 's/^[^:]*://' -e 's/\\$//' "${o%.o}.d"); do
            case $dep in /*) ;; *) dep=$ROOT/hook/$dep ;; esac        # (gcc ran in hook/)
            if [ "$dep" -nt "$o" ] || [ ! -e "$dep" ]; then stale=1; break; fi
        done
        [ $stale = 0 ] && return 0
    fi
    if (cd "$ROOT/hook" && $CXX $CFLAGS -MMD -MF "${o%.o}.d" -c "$s" -o "$o") >"$o.log" 2>&1; then
        [ -s "$o.log" ] && { echo "== $s"; cat "$o.log"; }
        return 0
    fi
    echo "== $s FAILED"; cat "$o.log"; rm -f "$o"
    return 1
}
export -f compile_one
export CXX CFLAGS OUT ROOT
JOBS=${VP_JOBS:-$(nproc)}
printf '%s\n' "${SOURCES[@]}" | xargs -P "$JOBS" -I{} bash -c 'compile_one "$@"' _ {}
failed=0
OBJS=()
for s in "${SOURCES[@]}"; do
    o="$OUT/obj/${s%.cpp}.o"
    if [ -f "$o" ]; then OBJS+=("$o"); else failed=$((failed + 1)); fi
done
if [ $failed != 0 ]; then echo "build_linux: $failed of ${#SOURCES[@]} sources failed"; exit 1; fi
echo "build_linux: ${#SOURCES[@]} sources compiled"

# the link test: everything the port is, plus a main that reaches it
cat >"$OUT/link_test.cpp" <<'EOF'
// generated by tools/build_linux.sh: references the port, so every object of it must resolve
#include <stdio.h>
#include "w32_table.h"
int main() {
    printf("viperport-link-test: %u stand-ins\n", (unsigned)viperport_stand_ins.count);
    return 0;
}
EOF
$CXX $CFLAGS -I"$ROOT/hook" -c "$OUT/link_test.cpp" -o "$OUT/link_test.o" || exit 1
$CXX $LDFLAGS -o "$OUT/viperport-link-test" "$OUT/link_test.o" "${OBJS[@]}" -Wl,-Map,"$OUT/viperport-link-test.map" $LIBS \
    || { echo "build_linux: link failed"; exit 1; }
echo "build_linux: out-linux/viperport-link-test linked"
