"""Generate the M3 harness's tables from the v1.0 race.exe, the map and the recovered types.

    python tools/gen_port_tables.py

Writes three files into hook/ (derived only from addresses, instruction bytes and names -- no game code
beyond each hooked function's first few instructions, which the trampolines must reproduce):

  prologues.inc     for every address hook/*.cpp hooks with PORT_FN / PORT_FN_BUILDS / detour: its first
                    whole instructions (at least the 5 bytes a jmp overwrites), so a trampoline can run
                    the original. A call/jmp rel32 among them is marked for relocation; a short branch, or
                    a jump from inside the function back into those bytes, is refused.
  state_layout.inc  every physics-object class (PhobRoot and what derives from it): vtable, size, name;
                    and the named fields of each, flattened through bases and embedded parts ("wheels[2].
                    load"), so logs can name the byte where two runs part.
  globals_phys.inc  the .data owned by the physics and AI modules (and the random-number generator), by
                    symbol: what a shadow check saves, restores and compares besides the footprint.

Needs out/race_v10.exe, out/symbols.csv, out/inventory.csv, out/types.json.
"""
from __future__ import annotations

import csv
import json
import re
import struct
import sys
from pathlib import Path

from capstone import CS_ARCH_X86, CS_MODE_32, Cs

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "out"
HOOK = ROOT / "hook"
BASE = 0x400000
DATA_END = 0x4E1000 + 0xF5F2C              # .data's virtual end (bss included)


def sections(exe: bytes):
    pe = struct.unpack_from("<I", exe, 0x3C)[0]
    n = struct.unpack_from("<H", exe, pe + 6)[0]
    opt = struct.unpack_from("<H", exe, pe + 20)[0]
    return [struct.unpack_from("<8sIIII", exe, pe + 24 + opt + i * 40) for i in range(n)]


def file_off(secs, va: int) -> int:
    for _name, vs, vaddr, _rs, ro in secs:
        if vaddr <= va - BASE < vaddr + vs:
            return va - BASE - vaddr + ro
    raise ValueError(f"{va:08x} is in no section")


# ---- prologues ------------------------------------------------------------------------------------------
def hooked_addresses() -> list[int]:
    pat = re.compile(r"\b(?:PORT_FN|PORT_FN_BUILDS|detour)\(\s*(0x[0-9a-fA-F]+)")
    found = set()
    for f in sorted(HOOK.glob("*.cpp")):
        for m in pat.finditer(f.read_text(encoding="utf-8")):
            found.add(int(m.group(1), 16))
    return sorted(found)


def prologue(exe, secs, md, va: int, size: int) -> tuple[bytes, int]:
    """The first whole instructions covering 5 bytes, and the offset of a rel32 to relocate (-1: none)."""
    off = file_off(secs, va)
    code, rel = b"", -1
    for ins in md.disasm(exe[off:off + 32], va):
        b = bytes(ins.bytes)
        if b[0] in (0xE8, 0xE9) and len(b) == 5:
            rel = len(code) + 1
        elif b[0] in (0xEB, 0xE3) or 0x70 <= b[0] <= 0x7F or (b[0] == 0x0F and 0x80 <= b[1] <= 0x8F):
            raise SystemExit(f"{va:08x}: a short or conditional branch in the first 5 bytes ({ins.mnemonic} {ins.op_str})")
        elif ins.mnemonic in ("ret", "retn") and len(code) + len(b) < 5:
            raise SystemExit(f"{va:08x}: returns within its first 5 bytes -- too short to hook")
        code += b
        if len(code) >= 5:
            break
    # nothing in the function may jump back into the bytes being moved
    body = exe[off:off + size]
    for ins in md.disasm(body, va):
        if ins.mnemonic.startswith("j") or ins.mnemonic in ("loop", "call"):
            try:
                t = int(ins.op_str, 16)
            except ValueError:
                continue
            if va < t < va + len(code):
                raise SystemExit(f"{va:08x}: {ins.address:08x} jumps into the first {len(code)} bytes")
    return code, rel


def write_prologues(exe, secs, sizes):
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    rows = []
    for va in hooked_addresses():
        code, rel = prologue(exe, secs, md, va, sizes.get(va, 64))
        rows.append(f"    {{0x{va:08x}, {len(code)}, {rel}, {{{', '.join(f'0x{b:02x}' for b in code)}}}}},")
    (HOOK / "prologues.inc").write_text(
        "// generated by tools/gen_port_tables.py: v1.0's first instructions at every hooked address\n"
        "// {address, bytes, offset of a rel32 to relocate (-1 none), the bytes}\n" + "\n".join(rows) + "\n",
        encoding="utf-8")
    return len(rows)


# ---- class layouts and field names ---------------------------------------------------------------------
KNOWN_SIZE = {"P3DBase": 12, "P3D": 12, "Point": 12, "Frame": 48, "Matrix": 36, "Quat": 16}


def type_size(types, tname: str | None) -> int:
    if not tname:
        return 4
    if tname.startswith("ptr") or tname in ("float", "int", "uint"):
        return 4
    if tname in ("bool", "byte", "u1", "char"):
        return 1
    if tname == "u2":
        return 2
    m = re.fullmatch(r"arr:(.+):(\d+)", tname)
    if m:
        return type_size(types, m.group(1)) * int(m.group(2))
    if tname.startswith("struct:"):
        n = tname[7:]
        return KNOWN_SIZE.get(n) or types.get(n, {}).get("size") or 4
    return 4


def flat_fields(types, cls: str, prefix: str = "", base_off: int = 0, depth: int = 0) -> list[tuple[int, int, str]]:
    """(offset, size, name) for every named field of cls: bases first, embedded parts expanded."""
    if depth > 6 or cls not in types:
        return []
    c = types[cls]
    out = []
    if c.get("base"):
        out += flat_fields(types, c["base"], prefix, base_off, depth + 1)
    for f in c.get("fields", []):
        name, t = f.get("name"), f.get("type")
        if not name:
            continue
        off = base_off + f["offset"]
        emb = f.get("embedded")
        m = re.fullmatch(r"arr:struct:([\w:]+):(\d+)", t or "")
        if emb and m and m.group(1) in types and types[m.group(1)].get("size"):
            esz = types[m.group(1)]["size"]
            for i in range(int(m.group(2))):
                out += flat_fields(types, m.group(1), f"{prefix}{name}[{i}].", off + i * esz, depth + 1)
            continue
        if t and t.startswith("struct:") and t[7:] in types and types[t[7:]].get("fields") and t[7:] not in KNOWN_SIZE:
            sub = flat_fields(types, t[7:], f"{prefix}{name}.", off, depth + 1)
            if sub:
                out += sub
                continue
        out.append((off, type_size(types, t), prefix + name))
    return out


def derives_from(types, cls: str, root: str) -> bool:
    seen = 0
    while cls and seen < 12:
        if cls == root:
            return True
        cls = types.get(cls, {}).get("base")
        seen += 1
    return False


def write_layout(types):
    classes = [n for n, c in types.items() if c.get("vtable") and c.get("size") and
               (derives_from(types, n, "PhobRoot") or derives_from(types, n, "CollisionVolume"))]
    classes.sort(key=lambda n: int(types[n]["vtable"]["va"], 16))
    lines = ["// generated by tools/gen_port_tables.py: physics-object and collision-volume classes and their named fields",
             "#ifdef VP_CLASSES", "// {vtable, size, name, first field, field count}"]
    fields, rows = [], []
    for n in classes:
        ff = sorted(set(flat_fields(types, n)))
        rows.append(f'    {{0x{int(types[n]["vtable"]["va"], 16):08x}, {types[n]["size"]}, "{n}", {len(fields)}, {len(ff)}}},')
        fields += ff
    lines += rows + ["#endif", "#ifdef VP_FIELDS", "// {offset, size, name}"]
    lines += [f'    {{{o}, {s}, "{nm}"}},' for o, s, nm in fields]
    lines += ["#endif"]
    (HOOK / "state_layout.inc").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(classes), len(fields)


# ---- physics and AI globals --------------------------------------------------------------------------------
# What a shadow check saves, restores and compares besides a function's footprint: the statics of the
# physics and AI object files. The map names only public data, so a symbol's "size up to the next name"
# can swallow other files' statics; instead every .data address the code references is attributed to the
# object file(s) that reference it. The linker lays each file's statics out together, so a run of
# addresses used by one file is that file's block, up to where the next file's begins.
SIM_LIBS = ("physics", "ai")
SIM_OBJECTS = ()           # (random.obj is left out: random numbers are a check's inputs, fed to the rewrite)
# Physics-library files that are the player's input, run on the MAIN thread: not simulation state. The
# physics reads the controls only through DriverGet* (inputs, which the recorder records) and writes them
# only through DriverSetGear / DriverSetForce (outputs); a check on the physics thread would see the main
# thread's writes land mid-check, and restoring would undo them.
INPUT_OBJECTS = (("physics", "control.obj"), ("physics", "driver.obj"))
# and single buffers the main thread writes inside simulation files
MAIN_THREAD = [
    (0x004ECF8C, 4, "PhysicsReadControls: the physics time it last read the controls"),
    (0x005215D8, 0x00521608 - 0x005215D8, "PhysicsTimeString's text buffer (the HUD clock)"),
    (0x00521608, 1, "physics_paused: set by the pause menu; an input, which the recorder records"),
]


def data_owners(exe, secs, inv) -> dict[int, set[tuple[str, str]]]:
    """.data address -> the (library, object) of every function that references it."""
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    owners: dict[int, set[tuple[str, str]]] = {}
    for r in inv:
        va, size = int(r["va"], 16), int(r["size"])
        if size < 2:
            continue
        off = file_off(secs, va)
        for ins in md.disasm(exe[off:off + size], va):
            for m in re.findall(r"0x([0-9a-f]{6,8})\b", ins.op_str):
                x = int(m, 16)
                if 0x4E1000 <= x < DATA_END:
                    owners.setdefault(x, set()).add((r["library"], r["object"]))
    return owners


def carve(va: int, end: int) -> list[tuple[int, int]]:
    """[va, end) with the main-thread ranges cut out."""
    spans = [(va, end)]
    for x, n, _why in MAIN_THREAD:
        out = []
        for a, b in spans:
            if x + n <= a or x >= b:
                out.append((a, b))
                continue
            if a < x:
                out.append((a, x))
            if x + n < b:
                out.append((x + n, b))
        spans = out
    return spans


def write_globals(exe, secs):
    inv = list(csv.DictReader(open(OUT / "inventory.csv", encoding="utf-8")))
    owners = data_owners(exe, secs, inv)
    syms = [r for r in csv.DictReader(open(OUT / "symbols.csv", encoding="utf-8")) if r["section"] == ".data"]
    named = {int(r["va"], 16): r["demangled"].split("(")[0].split()[-1].replace('"', "'")[:48] for r in syms}
    # a public symbol belongs to the file that defines it (the map says which), whoever else uses it
    for r in syms:
        va = int(r["va"], 16)
        lib = next((l for l, o in owners.get(va, ()) if o == r["object"]), r["library"])
        owners[va] = {(lib, r["object"])}
    addrs = sorted(owners)

    def sim(o: set) -> bool:
        return bool(o) and all((lib in SIM_LIBS or (lib, obj) in SIM_OBJECTS) and (lib, obj) not in INPUT_OBJECTS
                               for lib, obj in o)

    # runs of addresses owned by one simulation file; a run ends where another file's addresses begin
    blocks = []
    i = 0
    while i < len(addrs):
        o = owners[addrs[i]]
        j = i
        while j + 1 < len(addrs) and owners[addrs[j + 1]] == o:
            j += 1
        end = addrs[j + 1] if j + 1 < len(addrs) else DATA_END
        if sim(o) and len(o) == 1:
            lib, obj = next(iter(o))
            blocks.append((addrs[i], end, f"{obj} statics"))
        i = j + 1
    out, total = [], 0
    for va, end, what in blocks:
        cuts = sorted({va, end} | {n for n in named if va < n < end})
        for a0, a1 in zip(cuts, cuts[1:]):
            name = named.get(a0) or f"{what}"
            for a, b in carve(a0, a1):
                out.append(f'    {{0x{a:08x}, {b - a}, "{name}"}},')
                total += b - a
    (HOOK / "globals_phys.inc").write_text(
        "// generated by tools/gen_port_tables.py: the statics of the physics and AI object files\n"
        "// (the input files and main-thread buffers left out); {address, bytes, name}\n" + "\n".join(out) + "\n",
        encoding="utf-8")
    return len(out), total


def main():
    exe = (OUT / "race_v10.exe").read_bytes()
    secs = sections(exe)
    sizes = {int(r["va"], 16): int(r["size"]) for r in csv.DictReader(open(OUT / "inventory.csv", encoding="utf-8"))}
    types = json.loads((OUT / "types.json").read_text(encoding="utf-8"))
    n = write_prologues(exe, secs, sizes)
    c, f = write_layout(types)
    g, gb = write_globals(exe, secs)
    print(f"prologues.inc: {n} hooked addresses; state_layout.inc: {c} classes, {f} named fields; "
          f"globals_phys.inc: {g} spans, {gb} bytes")


if __name__ == "__main__":
    sys.exit(main())
