"""Generate hook/texture_table_fields.inc from out/texture_table_refs.txt (tools/xrefs-style scan).

Every instruction in the texture functions that addresses the 250-entry texture table (0x522fa0, 40-byte
entries, end 0x5256b0) becomes one entry: {address, field offset, old value, kind}, where kind 0 is an
address inside the table (moves with its base) and kind 1 is a loop's end marker (moves with its end).
The $E static initialisers are skipped: the variables they set sit just after the table and aren't part
of it. The generated file isn't game code -- only addresses and the values found there.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE, END = 0x522fa0, 0x5256b0
lines = []
for row in (ROOT / "out" / "texture_table_refs.txt").read_text().splitlines():
    at, off, val, *rest = row.split()
    func = rest[-1]
    if func.startswith("$E"):
        continue
    at, off, val = int(at, 16), int(off.lstrip("+")), int(val, 16)
    kind = 0 if BASE <= val < END else 1
    lines.append(f"    {{0x{at:06x}, {off}, 0x{val:06x}, {kind}}},   // {func}")
out = ROOT / "hook" / "texture_table_fields.inc"
out.write_text("// generated by tools/gen_texture_table.py -- {address, field offset, v1.0 value, 0=in table / 1=end marker}\n"
               + "\n".join(lines) + "\n")
print(f"{len(lines)} fields -> {out}")
