"""Generate hook/w32_table.cpp: the stand-ins' import table (relink stage R2a; hook/w32_table.h).

    python tools/gen_w32_table.py            (needs out/race_v10.exe)

Every import of v1.0 race.exe that has a stand-in -- a w32_<Name> declared in a hook/w32_*.h header (WSOCK32's
ordinals by their winsock names) -- becomes an entry; the imports without one are listed in the file's header comment
and printed (they stay Windows', and viperport.exe logs them). DDRAW / DSOUND / DINPUT are the port's own, not
stand-ins. Run it again whenever a stand-in is added.
"""
import os, re, struct

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HOOK = os.path.join(REPO, 'hook')
WSOCK = {116: 'WSACleanup', 3: 'closesocket', 115: 'WSAStartup', 23: 'socket', 9: 'htons', 20: 'sendto', 17: 'recvfrom',
         15: 'ntohs', 12: 'ioctlsocket', 57: 'gethostname', 52: 'gethostbyname', 111: 'WSAGetLastError', 10: 'inet_addr',
         103: 'WSAAsyncGetHostByName', 108: 'WSACancelAsyncRequest', 7: 'getsockopt', 2: 'bind', 21: 'setsockopt'}
# replaced by the port itself (DirectX on OpenGL / SDL; DINPUT is the DLL's own export) -- not stand-ins
PORT_OWN = {'DDRAW.dll', 'DSOUND.dll', 'DINPUT.dll'}


def imports():
    d = open(os.path.join(REPO, 'out', 'race_v10.exe'), 'rb').read()
    pe = struct.unpack_from('<I', d, 0x3c)[0]
    nsec = struct.unpack_from('<H', d, pe + 6)[0]
    sz = struct.unpack_from('<H', d, pe + 20)[0]
    opt = pe + 24
    secs = []
    for i in range(nsec):
        vs, va, rs, ra = struct.unpack_from('<IIII', d, opt + sz + 40 * i + 8)
        secs.append((va, max(vs, rs), ra))

    def off(rva):
        for va, s, ra in secs:
            if va <= rva < va + s:
                return rva - va + ra

    def cstr(rva):
        o = off(rva)
        return d[o:d.index(b'\0', o)].decode()

    out = []
    i = struct.unpack_from('<I', d, opt + 96 + 8)[0]
    while True:
        oft, _, _, name, ft = struct.unpack_from('<IIIII', d, off(i))
        if not name:
            break
        dll = cstr(name)
        k = 0
        while True:
            v = struct.unpack_from('<I', d, off(oft or ft) + 4 * k)[0]
            if not v:
                break
            if v & 0x80000000:
                out.append((0x400000 + ft + 4 * k, dll, None, v & 0xffff))
            else:
                out.append((0x400000 + ft + 4 * k, dll, cstr(v + 2), 0))
            k += 1
        i += 20
    return out


def declared():
    found = {}
    for f in sorted(os.listdir(HOOK)):
        if not (f.startswith('w32_') and f.endswith('.h')) or f in ('w32_table.h',):
            continue
        text = open(os.path.join(HOOK, f), encoding='utf-8', errors='replace').read()
        text = re.sub(r'//[^\n]*', '', text)
        text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
        for m in re.finditer(r'\bw32_([A-Za-z_][A-Za-z0-9_]*)\s*\(', text):
            found.setdefault(m.group(1), f)
    return found


def main():
    imps = imports()
    decl = declared()
    headers = sorted(set(decl.values()))
    rows, missing = [], []
    for slot, dll, name, ordinal in imps:
        if dll in PORT_OWN:
            continue
        fn = name or WSOCK.get(ordinal)
        what = '%s!%s' % (dll, name) if name else '%s #%d (%s)' % (dll, ordinal, fn)
        if fn in decl:
            rows.append((slot, dll, name, ordinal, fn, decl[fn]))
        else:
            missing.append((slot, what))
    lines = []
    w = lines.append
    w('// w32_table.cpp -- the stand-ins\' import table (w32_table.h): race.exe\'s imports the port implements itself.')
    w('// GENERATED by tools/gen_w32_table.py from out/race_v10.exe\'s import directory and the w32_<Name>')
    w('// declarations in hook/w32_*.h -- %d of race.exe\'s %d imports; DDRAW / DSOUND / DINPUT are the port\'s own' % (len(rows), len(imps)))
    w('// (renderer_install / audio_install / DirectInputCreateA), not stand-ins.')
    if missing:
        w('// Imports with no stand-in yet (they stay Windows\', and the loader logs them):')
        for slot, what in missing:
            w('//   %08x %s' % (slot, what))
    w('//')
    w('// GCC build: the full table. MSVC build: empty -- viperport.exe then leaves every import as Windows\', as before.')
    w('#include "w32_table.h"')
    w('#include "compiler.h"                                   // VP_GCC')
    w('#include "viperport.h"')
    w('#include <string.h>')
    for h in headers:
        w('#include "%s"' % h)
    w('')
    w('#ifdef VP_GCC')
    w('namespace {')
    w('const VpStandIn k_entries[] = {')
    for slot, dll, name, ordinal, fn, hdr in rows:
        if name:
            w('    {"%s", "%s", 0, (void*)&w32_%s},' % (dll, name, fn))
        else:
            w('    {"%s", 0, %d, (void*)&w32_%s},' % (dll, ordinal, fn))
    w('};')
    w('const uint32_t N_ENTRIES = sizeof k_entries / sizeof k_entries[0];')
    w('')
    w('// stand-ins the game finds through GetProcAddress but doesn\'t import (the C runtime\'s fatal-error message box)')
    w('const VpStandIn k_extra[] = {')
    w('    {"USER32.dll", "GetActiveWindow", 0, (void*)&w32_GetActiveWindow},')
    w('    {"USER32.dll", "GetLastActivePopup", 0, (void*)&w32_GetLastActivePopup},')
    w('};')
    w('')
    w('bool same_dll(const char* a, const char* b) {     // "USER32" matches "USER32.dll", any case')
    w('    for (; *a && *b; a++, b++)')
    w('        if ((*a | 0x20) != (*b | 0x20)) return false;')
    w('    return (!*a || !strcmp(a, ".dll") || !strcmp(a, ".DLL")) && (!*b || !strcmp(b, ".dll") || !strcmp(b, ".DLL"));')
    w('}')
    w('// the kernel stand-ins\' GetProcAddress asks here first (w32_kernel.h, w32_set_proc_lookup)')
    w('void* lookup(const char* dll, const char* name) {')
    w('    for (const VpStandIn& e : k_entries)')
    w('        if (e.name && !strcmp(e.name, name) && same_dll(e.dll, dll)) return e.fn;')
    w('    for (const VpStandIn& e : k_extra)')
    w('        if (!strcmp(e.name, name) && same_dll(e.dll, dll)) return e.fn;')
    w('    return 0;')
    w('}')
    w('struct Register { Register() { w32_set_proc_lookup(lookup); } } g_register;   // (a plain pointer: set at load)')
    w('')
    w('void __cdecl log_line(const char* line) { logf("%s", line); }')
    w('void __cdecl set_image(uint32_t base, const char* path, const char* command_line) {')
    w('    w32_set_process_image(base, path, command_line);')
    w('}')
    w('}  // namespace')
    w('extern "C" VP_STAND_INS_API const VpStandIns viperport_stand_ins = {')
    w('    sizeof(VpStandIns), VP_STAND_INS_VERSION, N_ENTRIES, k_entries, log_line, set_image};')
    w('#else')
    w('extern "C" VP_STAND_INS_API const VpStandIns viperport_stand_ins = {sizeof(VpStandIns), VP_STAND_INS_VERSION, 0, 0, 0, 0};')
    w('#endif')
    open(os.path.join(HOOK, 'w32_table.cpp'), 'w', newline='\n').write('\n'.join(lines) + '\n')
    print('%d stand-ins, %d imports without one' % (len(rows), len(missing)))
    for slot, what in missing:
        print('  missing %08x %s' % (slot, what))


main()
