"""Generate hook/com_base.h: a C++ base class for each DirectX interface the emulation implements, with
every method present (exact signatures, from the Windows SDK's own ddraw.h / d3d.h) returning "not
supported" and logging the first call. The emulation (hook/ddraw_gl.cpp) derives from these and
overrides only what the game calls, so a method it didn't expect shows up in viperport.log instead of
corrupting the stack.

    python tools/gen_com_base.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SDK = Path(r"C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um")
TARGETS = [   # (headers, header to include, interfaces, output)
    (["ddraw.h", "d3d.h"], "dx5.h",
     ["IDirectDraw", "IDirectDraw2", "IDirectDrawSurface3", "IDirect3D2", "IDirect3DDevice2",
      "IDirect3DViewport2", "IDirect3DMaterial2", "IDirect3DTexture2"], "com_base.h"),
    (["dsound.h"], "ds5.h",
     ["IDirectSound", "IDirectSoundBuffer", "IDirectSound3DBuffer", "IDirectSound3DListener", "IKsPropertySet"],
     "com_dsound.h"),
]


def strip_version_blocks(text):
    """Drop #if(DIRECT3D_VERSION >= 0x0600/0x0700) ... #endif blocks, as a DX5 build would."""
    out, skip = [], 0
    for line in text.splitlines():
        m = re.match(r"\s*#if\s*\(?\s*DIRECT(3D|DRAW|SOUND)_VERSION\s*>=\s*0x0([0-9a-fA-F]{3})", line)
        if skip:
            if re.match(r"\s*#if", line):
                skip += 1
            elif re.match(r"\s*#endif", line):
                skip -= 1
            continue
        if m and int(m.group(2), 16) > 0x500:
            skip = 1
            continue
        out.append(line)
    return "\n".join(out)


def interfaces(text):
    found = {}
    for m in re.finditer(r"DECLARE_INTERFACE_\(\s*(\w+)\s*,\s*(\w+)\s*\)\s*\{(.*?)\n\};", text, re.S):
        name, base, body = m.groups()
        methods = []
        for decl in re.findall(r"STDMETHOD_?\((.*?)\)\s*\((.*?)\)\s*PURE\s*;", body, re.S):
            head, params = decl
            head = [h.strip() for h in head.split(",")]
            ret, meth = (head[0], head[1]) if len(head) == 2 else ("HRESULT", head[0])
            params = " ".join(params.split())
            params = re.sub(r"^THIS_\s*", "", params)
            params = "" if params == "THIS" else params
            methods.append((ret, meth, params))
        found[name] = (base, methods)
    return found


def main():
    for headers, include, want, outname in TARGETS:
        text = strip_version_blocks("\n".join((SDK / h).read_text(errors="replace") for h in headers))
        ifs = interfaces(text)
        lines = [f"// generated by tools/gen_com_base.py from the Windows SDK's {', '.join(headers)} -- do not edit",
                 "#pragma once", f'#include "{include}"', "",
                 "void com_unsupported(const char* method);   // logs the first call to each", ""]
        for name in want:
            base, methods = ifs[name]
            chain = []
            b = base
            while b != "IUnknown" and b in ifs:          # methods inherited from a non-IUnknown base
                chain = ifs[b][1] + chain
                b = ifs[b][0]
            lines.append(f"struct Base_{name} : {name} {{")
            seen = set()
            for ret, meth, params in chain + methods:
                if meth in seen:
                    continue
                seen.add(meth)
                if meth == "QueryInterface":
                    body = "{ *ppvObj = 0; return E_NOINTERFACE; }"
                    params = "REFIID riid, LPVOID * ppvObj"
                elif meth in ("AddRef", "Release"):
                    body = "{ return 1; }"
                else:
                    val = "0" if ret != "HRESULT" else "E_NOTIMPL"
                    body = f'{{ com_unsupported("{name}::{meth}"); return {val}; }}'
                lines.append(f"    {ret} STDMETHODCALLTYPE {meth}({params}) override {body}")
            lines.append("};")
            lines.append("")
        out = ROOT / "hook" / outname
        out.write_text("\n".join(lines) + "\n")
        print(f"{out}: {', '.join(f'{n} ({len(ifs[n][1])})' for n in want)}")


if __name__ == "__main__":
    main()
